export type BlogCategory = {
  slug: string; name: string; parent?: string; description: string; intro: string;
  catalogue: { href: string; label: string }[];
};
export const blogCategories: BlogCategory[] = [
  { slug: "inspection-material-quality", name: "Inspection & Material Quality", description: "Oil and gas inspection and material quality guides: define acceptance evidence, inspection scope, certificates and equipment traceability.", intro: "Specify the evidence your project needs.", catalogue: [{href:"/quality",label:"Quality and compliance enquiries"}] },
  { slug: "maintenance-repair", parent: "oil-and-gas-services", name: "Equipment Maintenance & Repair", description: "Scope industrial equipment maintenance and repair enquiries using condition reports, OEM identification, work boundaries and acceptance requirements.", intro: "Define the repair before authorizing work.", catalogue: [{href:"/oil-and-gas/services/inspection-engineering",label:"Equipment repair and maintenance service enquiries"}] },
  { slug: "valves-actuation", parent: "oil-and-gas-equipment", name: "Valves & Actuation", description: "Oil and gas valve selection guidance covering isolation, control duties, actuator sizing, interfaces and enquiry requirements.", intro: "Specify the valve and its actuation.", catalogue: [{href:"/oil-and-gas/equipment/valves",label:"Valve and actuation equipment requirements"}] },
  { slug: "gaskets-sealing", parent: "oil-and-gas-equipment", name: "Gaskets & Sealing Products", description: "Specify industrial gaskets and sealing products by joint geometry, materials, service conditions and traceability requirements.", intro: "Select sealing for the actual joint.", catalogue: [{href:"/oil-and-gas/equipment/gaskets-seals",label:"Gasket and sealing product requirements"}] },
  { slug: "oil-and-gas-equipment", name: "Oil & Gas Equipment", description: "Oil and gas equipment selection guides: compare duties, interfaces, materials and project requirements before requesting a quotation.", intro: "Specify the right equipment.", catalogue: [{href:"/oil-and-gas/equipment",label:"Oil and gas equipment catalogue"}] },
  { slug: "pumps-rotating-equipment", parent: "oil-and-gas-equipment", name: "Pumps & Rotating Equipment", description: "Understand pump duties, curves, seals, couplings and acceptance testing to prepare a complete rotating equipment enquiry.", intro: "Match the machine to the duty.", catalogue: [{href:"/oil-and-gas/equipment/pumps",label:"Pump requirements and applications"},{href:"/oil-and-gas/services/inspection-engineering",label:"Inspection and engineering service enquiries"}] },
  { slug: "piping-flanges-fittings", parent: "oil-and-gas-equipment", name: "Piping, Flanges & Fittings", description: "Specify oil and gas piping, flanges, fittings and bolting using dimensions, materials, connection standards and project documentation.", intro: "Build compatible pressure boundaries.", catalogue: [{href:"/oil-and-gas/equipment/valves",label:"Valve and actuation requirements"},{href:"/oil-and-gas/equipment/flanges-fittings-bolting",label:"Flanges, fittings and bolting catalogue"}] },
  { slug: "pressure-vessels-tanks", parent: "oil-and-gas-equipment", name: "Pressure Vessels, Tanks & Heat Exchangers", description: "Specify pressure vessels, storage tanks and heat exchangers with clear process conditions, fabrication scope and inspection requirements.", intro: "Connect process duty and measurement.", catalogue: [{href:"/oil-and-gas/equipment/pressure-vessels-tanks",label:"Vessels and tank equipment"},{href:"/oil-and-gas/equipment/instrumentation-control",label:"Instrumentation and control catalogue"}] },
  { slug: "wellhead-production-equipment", parent: "oil-and-gas-equipment", name: "Wellhead & Production Equipment", description: "Prepare wellhead and production equipment enquiries with pressure, temperature, materials, interfaces and traceability requirements.", intro: "Define the well equipment boundary.", catalogue: [{href:"/oil-and-gas/equipment/wellhead-production-equipment",label:"Wellhead and production equipment"},{href:"/oil-and-gas/services/well-construction-intervention",label:"Well construction and intervention service scopes"}] },
  { slug: "oil-and-gas-services", name: "Oil & Gas Services", description: "Scope oil and gas field services, pipeline interventions, inspections and maintenance with clear responsibilities and acceptance evidence.", intro: "Scope the work before mobilization.", catalogue: [{href:"/oil-and-gas/services",label:"Specialist oil and gas service requirements"}] },
  { slug: "pipeline-intervention", parent: "oil-and-gas-services", name: "Pipeline Intervention", description: "Understand hot tapping and line stopping scope, equipment interfaces and project information needed for specialist pipeline enquiries.", intro: "Plan a specialist pipeline enquiry.", catalogue: [{href:"/oil-and-gas/equipment/pipeline-intervention",label:"Pipeline intervention equipment"},{href:"/oil-and-gas/services/pipeline-process",label:"Pipeline and process service requirements"}] },
  { slug: "inspection-testing", parent: "inspection-material-quality", name: "Inspection & Testing", description: "Define industrial inspection, testing and calibration scopes, witness points, competence requirements and acceptance records.", intro: "Agree what acceptance will prove.", catalogue: [{href:"/oil-and-gas/services/inspection-engineering",label:"Inspection, calibration and repair services"},{href:"/oil-and-gas/services/asset-integrity-surveys",label:"Asset integrity and survey enquiries"}] },
  { slug: "oil-and-gas-procurement", name: "Oil & Gas Procurement", description: "Practical oil and gas procurement guidance covering RFQs, supplier selection, shipment coordination and material documentation.", intro: "Turn requirements into comparable offers.", catalogue: [{href:"/services",label:"Oillinko sourcing and procurement services"}] },
  { slug: "supplier-selection-rfq", parent: "oil-and-gas-procurement", name: "Supplier Selection & RFQs", description: "Prepare equipment RFQs, evaluate supplier fit and compare quotations with a clear scope, exceptions and commercial responsibilities.", intro: "Ask the right supplier the right questions.", catalogue: [{href:"/services",label:"Sourcing and RFQ coordination"},{href:"/oil-and-gas/companies",label:"Independent global company directory"}] },
  { slug: "logistics-delivery", parent: "oil-and-gas-procurement", name: "Logistics & Delivery", description: "Plan multi-vendor shipments, packing, delivery terms and handover records around actual equipment readiness and project deadlines.", intro: "Coordinate equipment through to delivery.", catalogue: [{href:"/oil-and-gas/services/freight-expediting-and-project-logistics",label:"Freight, expediting and project logistics enquiries"}] },
  { slug: "materials-documentation", parent: "inspection-material-quality", name: "Materials & Documentation", description: "Specify material records, EN 10204 inspection documents and traceability evidence that match the purchased equipment and project scope.", intro: "Connect each item to its evidence.", catalogue: [{href:"/quality",label:"Quality and documentation enquiries"},{href:"/oil-and-gas/equipment/flanges-fittings-bolting",label:"Pressure component requirements"}] },
];
export function getBlogCategory(slug: string) { return blogCategories.find(c => c.slug === slug); }
export function categoryUrl(category: BlogCategory) { return `/blog/category/${category.parent ? `${category.parent}/` : ""}${category.slug}`; }
export function categoryName(slug: string) { return getBlogCategory(slug)?.name ?? slug; }
export function categoryChildren(slug: string) { return blogCategories.filter(c => c.parent === slug); }
export function categoryAncestors(category: BlogCategory) { return category.parent ? [getBlogCategory(category.parent)!, category] : [category]; }
