type GuidanceSection = { title: string; paragraphs: string[] };

export const hydraulicSpecificationGuidance: Record<string, Record<string, string>> = {
  "hydraulic-power-units": {
    "Required flow and pressure": "Give the required flow and pressure together for each documented consumer demand case. Identify which actuators operate simultaneously and which demands occur separately, with units and the reference location shown on the hydraulic schematic. Ask the offer to identify the proposed pump arrangement and the demand cases it addresses. A maximum flow stated separately from a maximum pressure does not establish that both are available together. Keep unresolved load data visible rather than treating a motor rating as a complete hydraulic output specification.",
    "Duty cycle and fluid": "Describe the sequence, frequency and duration of the machine's hydraulic demands, including documented idle periods. Identify the specified hydraulic fluid and available viscosity and temperature information; a general oil description is insufficient for reviewing the complete package. Ask the technical response to identify fluid compatibility assumptions for pumps, seals and accessories. For a replacement, disclose any changed consumer duty or fluid specification. The enquiry should provide the design basis for assessment, without prescribing operating adjustments or assuming a previous power pack remains suitable.",
    "Reservoir and cooling": "State the available installation space, reservoir arrangement and cooling utilities, including confirmed utility conditions where a water-cooled package is contemplated. Ask whether the quoted assembly includes the cooler, circulation circuit, filtration and level or temperature indication. These can be separate modules within a power unit package. Request the offered tank dimensions and the engineering basis used for the cooling proposal. Comparing reservoir capacity alone can miss exclusions, utility requirements and access constraints that affect whether the complete package fits the installation.",
    "Electrical and control interfaces": "Identify the available electrical supply, motor starting arrangement and the controls boundary between the power unit and the machine. Provide the required signals, communication interfaces and approved functional documents for review. Ask whether the quotation includes the starter or drive, control enclosure, internal wiring and interface drawings, or expects these from another package. Include the specified installation environment and location approvals. A matching motor voltage does not establish that the supplied controls will integrate with the existing system or perform the documented functions."
  }
};

export const hydraulicTopicGuidance: Record<string, GuidanceSection[]> = {
  "hydraulic-power-units": [
    { title: "Define the package boundary on the hydraulic schematic", paragraphs: [
      "Mark the boundary of the requested power unit on the current schematic and list the assemblies crossing that boundary. A buyer seeking a replacement pump-and-tank assembly may already own the distribution manifold, whereas a new installation may need that manifold included. Use an inclusion schedule so each proposal addresses the same package and identifies equipment retained from the existing installation.",
      "Separate the complete power unit from optional accumulator assemblies, external piping, hoses and consumer-side valves. Where these are requested, identify their design references and the party responsible for reviewing their integration. Obtain a bill of materials and interface drawing for the offered arrangement. The phrase complete hydraulic package should be explained through that equipment list rather than relied on as an acceptance description."
    ] },
    { title: "Compare utilities, access and maintenance provisions", paragraphs: [
      "Give the installation layout enough detail to review connections and service access. Record the footprint limit, available clearance and interfaces with existing containment or supports. Ask where filter elements, pump assemblies and cooler connections are accessed in the offered layout. A skid that fits its allocated footprint may still require additional space for the maintenance tasks identified in its documentation.",
      "List the required spare parts and consumables separately from the assembled unit. Request identifiable filter-element and seal-kit references, together with the documentation delivered for future purchasing. If standby pumps or additional cooling circuits are specified, ask how they appear in the equipment list and controls scope. Treat redundancy as a defined project requirement; do not infer it from the number of components visible in a photograph."
    ] },
    { title: "Agree the documentation and acceptance scope", paragraphs: [
      "Identify the drawings, component schedule, electrical documents and operating documentation needed for technical review and handover. Ask the offer to show the revision and approval stage for each deliverable. A preliminary layout supports an enquiry comparison, while the final package should be assessed against the agreed project documents. Include responsibility for reviewing interfaces with existing machinery in the purchasing scope.",
      "State the required inspection and test documentation and distinguish workshop verification from site integration or commissioning services. Ask which work is included in the price, which needs separate attendance and which remains with the buyer. Record deviations against individual requirements, along with manufacturing origin and delivery location. Oillinko receives this package information for manual sourcing review; the listing itself confirms neither an available assembly nor an accepted hydraulic design."
    ] }
  ]
};
