type GuidanceSection = { title: string; paragraphs: string[] };

// Original instrument-enquiry copy. Research boundaries are documented in
// docs/measurement-content-2026-10-02.md; no supplier identity or setpoint is public.
export const measurementSpecificationGuidance: Record<string, Record<string, string>> = {
  "instrument-calibration-equipment": {
    "Variables and ranges": "List the quantities to be measured or generated, with ranges, units and the instrument types being checked. Separate pressure generation, pressure measurement, electrical sourcing and electrical measurement rather than assuming a multifunction label covers every task. For temperature work, identify whether the enquiry concerns an electrical sensor signal or a complete temperature reference arrangement. Ask the offer to identify the functions and accessories included for each requested task. A wide headline range does not show which functions are available in the delivered kit.",
    "Required uncertainty": "Specify the measurement uncertainty needed for the intended comparison, with the relevant points or range and the project's acceptance basis. Request the offered performance information and its stated conditions, rather than equating display resolution with measurement uncertainty. The uncertainty associated with a calibration and the conditions of subsequent measurements both matter to interpreting results. Have the responsible technical reviewer assess the complete intended measurement arrangement. Where the target is still provisional, identify that gap so a quotation is not mistaken for a confirmed suitability assessment.",
    "Reference traceability": "Request calibration records identifying the actual reference instruments, measured results, associated uncertainties and the reference basis. Metrological traceability concerns a measurement result supported through a documented calibration chain; a logo or a general traceable statement is insufficient evidence for the enquiry. Ask which serial-numbered equipment receives a certificate and whether accessories or separate modules are covered. Specify any required laboratory accreditation scope for review. Traceability alone does not establish that the proposed equipment meets the uncertainty needed for the buyer's task.",
    "Field or bench use": "Describe the intended work location, available power, transport arrangements and the instrument connection interfaces. A bench reference, a portable indicator and a complete field kit can have different accessory requirements. Ask whether the offer includes connection adapters, test leads, carrying case, power accessories and any required software entitlement. Identify the specified location approvals for review where field use requires them. Keep equipment suitability, the site's authorization to perform work and any contracted calibration service as separate parts of the purchasing requirement."
  },
  "pressure-gauges-and-transmitters": {
    "Range and overload pressure": "Specify the required pressure reference as gauge, absolute or differential, with explicit units and the intended measurement range. Include normal operating cases and the design information needed to assess pressure exposure outside that range. For differential measurement, identify the pressure conditions on both connections, not only the expected difference. Ask the response to distinguish the offered measuring range, configured output range and documented overload limits. A matching number on a dial or quotation does not establish that the instrument measures the required pressure reference.",
    "Process connection": "Identify the connection and mounting arrangement using the current instrument schedule or a controlled drawing. Record the thread or flange reference, connection location and any manifold, adaptor or remote interface included in the package. For a replacement, provide the installed assembly reference and available dimensions rather than a photograph alone. Ask which accessories and interface components are supplied with the instrument. A transmitter, its process connection and the required mounting package may appear as separate quotation items and should be compared on the same boundary.",
    "Wetted materials": "Describe the process medium and its relevant properties, together with the specified materials for parts exposed to it. Include cleaning or other service exposures identified by the project. A case material description does not establish the materials of the sensing element, diaphragm, seals or process fittings. Ask the offer to identify the wetted construction of the actual assembly and any limitations requiring technical review. Where a diaphragm seal or remote arrangement is proposed, keep its compatibility and complete measurement configuration visible in the response.",
    "Output signal and approvals": "State whether local indication, an electrical signal or both are required. Identify the receiving system's approved input, power arrangements and communication requirements, including the configured engineering units. List any location or project approvals needed for the offered assembly. Ask for the relevant documentation and any configuration, calibration or installation services included in the price. Signal compatibility does not by itself establish approval for a protective function; the assigned system design must define that duty and its evidence."
  },
  "temperature-sensors-and-thermowells": {
    "Sensor type and range": "Identify the sensing element or thermocouple designation required by the installed system and the measurement range. Include the receiving input or transmitter arrangement, wiring requirements and any specified accuracy basis. Distinguish a bare element, a replaceable insert and a complete assembled instrument. Ask the response to identify the offered configuration and its applicable limits. An apparently similar temperature probe may use a different element or connection arrangement, so a shared outer diameter is insufficient to confirm compatibility with the existing measurement channel.",
    "Insertion length and drawing": "Provide the approved assembly drawing and define the length references used for the sensor, extension and thermowell. Identify the process connection, bore, tip arrangement and other dimensions required for the actual interface. A sensor insertion length and a thermowell process insertion length can describe different parts of the assembly. Ask for confirmation that the proposed components fit together against the drawing. Critical dimensions should be checked from controlled records rather than estimated from a photograph or copied from a similar instrument.",
    "Thermowell material": "Specify the thermowell's material and construction against the approved process and mechanical design. Include the fluid, pressure, temperature and flow information required for the responsible review. A thermowell protects a compatible sensor and also forms part of the process interface; its assessment is separate from the sensing element's temperature range. Ask which material records and design checks are included in the proposal. Do not treat a general stainless-steel description or an acceptable sensor range as proof of suitability for the complete thermowell assembly.",
    "Connection and head arrangement": "Identify the process and instrument connections, extension arrangement, terminal head and any transmitter included in the package. State cable-entry and enclosure requirements for the intended location, with mounting constraints and maintenance access available for review. Ask whether the quotation covers the complete assembly or separately supplied parts. Record the required wiring and receiving-system interface without sharing live-system credentials. For replacements, match the actual installed arrangement and approved drawings rather than assume that every probe with the same nominal thread has identical dimensions."
  },
  "radar-and-ultrasonic-level-instruments": {
    "Tank dimensions and measuring range": "Provide a drawing showing vessel dimensions, measurement reference, nozzle position and relevant internal features. State the required measuring range and the level information the receiving system needs. Tank height and usable instrument range are different descriptions, so identify the actual limits and any areas requiring separate review. Ask the technical response to state the installation assumptions used in its assessment. A nominal range alone does not establish that the proposed instrument can measure the required surfaces through the actual vessel arrangement.",
    "Product properties": "Describe the material being measured and the process conditions that affect its surface and measurement path. Identify liquids, solids or any required interface between materials, with available property data and known variation. Include foam, vapour, buildup or other conditions documented for the vessel where relevant. Ask the response to explain suitability for the actual duty rather than selecting a technology solely by its name. A capability advertised for one application should not be assumed to apply to every product or installation.",
    "Process pressure and temperature": "State the vessel's documented pressure and temperature conditions, including the operating cases relevant to the instrument. Identify external ambient conditions separately from exposure at the process connection. Ask for the applicable limits of the complete offered arrangement, including its process interface and enclosure. A measuring principle's broad application range does not define the limits of every product configuration. Keep assumptions and exceptions visible so the responsible reviewer can evaluate the instrument against the specified location and service.",
    "Nozzle and output requirements": "Describe the nozzle dimensions, connection and position, together with any chamber or probe arrangement included in the design. Identify the required output, power supply and receiving-system interface. State whether the enquiry includes mounting accessories, configuration or commissioning services. Ask the offer to identify the exact assembly and the installation information needed for review. A compatible signal output cannot resolve an unsuitable mechanical interface, and a matching flange does not establish that the complete measurement requirement is covered."
  },
  "flow-meters": {
    "Fluid and flow range": "Identify the actual fluid and whether the required result is volume flow, mass flow or another defined quantity. Give normal, minimum and maximum flow cases with units, and describe intermittent or changing duties. Include composition and relevant fluid properties from current records, distinguishing measured information from estimates. Ask the response to identify the offered measuring principle and the basis of its assessment. A line-size match alone does not establish performance across the required range or suitability for the actual liquid, gas or steam service.",
    "Line size": "Provide the pipe size, internal dimensions where needed, material and connection reference. Include the available layout and nearby components relevant to the proposed measuring arrangement. State whether the instrument is an inline assembly, an insertion device or another approved configuration. Ask which installation dimensions, accessories and site checks the proposal requires. A nominal line size does not describe every physical interface or the available space, so the technical response should identify dimensional assumptions and any changes needed for the actual installation.",
    "Operating conditions": "Describe the pressure, temperature and fluid state for the intended operating cases. Identify available information about solids, entrained gas, conductivity or other properties relevant to the proposed technology. Include the external environment and any specified location approvals. Ask for the limits and requirements of the offered configuration, rather than assuming one measuring principle addresses every service. If process information is incomplete, mark it as an unresolved input so the response can explain its effect on selection and performance assessment.",
    "Accuracy and output": "State the required measurement performance over the intended range and the purpose for which the result will be used. Ask how the offered accuracy is expressed and what conditions it assumes. Identify calibration evidence, measurement units, signal output, totalization and any required communication functions. The receiving-system interface and configuration scope should be explicit. Where transfer accounting or a regulated measurement use is involved, list the actual approval requirements for review; a general accuracy statement does not establish suitability for every commercial measurement."
  }
};

export const measurementTopicGuidance: Record<string, GuidanceSection[]> = {
  "instrument-calibration-equipment": [
    { title: "Turn the instrument list into a kit schedule", paragraphs: [
      "Prepare a task schedule showing the instrument tag, measured quantity, range and connection for each planned use. For a pressure transmitter, list the pressure interface and electrical signal separately. For a temperature instrument, identify the sensor type and what part of the measurement chain is included in the task. This gives a reviewer a clearer enquiry than a request for one general-purpose calibrator.",
      "Map each task to the quoted main instrument, module and accessory. If the response offers only part of the requested functions, record the uncovered tasks instead of treating a supplied adapter as a new measurement capability. Identify quantities for shared and dedicated accessories, and ask which items are included as standard or priced separately. Keep alternative kit arrangements comparable through the same task schedule."
    ] },
    { title: "Keep calibration evidence tied to the delivered references", paragraphs: [
      "Define the certificate deliverables in the enquiry and request confirmation against the actual equipment list. The purchasing record should distinguish a sample certificate used during quotation from records supplied for the delivered serial numbers. If a kit contains several measurement modules, ask which records relate to each one. File the documents with the asset reference so later users can identify the evidence for the instrument they hold.",
      "Ask how the calibration service is purchased initially and how later support can be arranged, including shipment location, quoted turnaround and any separate charges. Leave the ongoing recalibration interval to the owner's measurement programme and technical assessment. A quotation should not silently create that programme or substitute a generic interval for it. Identify who will review any reported limitations before the reference is assigned to a task."
    ] },
    { title: "Separate equipment supply from records and software services", paragraphs: [
      "Some purchasing enquiries include automatic record generation or transfer to a maintenance system. Specify the required export format, receiving application and ownership of the records. Ask whether the quoted price covers only hardware or also the necessary software entitlement, configuration and support. A communication port alone does not demonstrate that the intended reporting workflow is included or compatible with the buyer's current systems.",
      "Compare training, initial calibration, repair support and replacement accessories as explicit commercial lines. Record manufacturing origin for the offered instruments separately from the laboratory location or delivery address. Submit the equipment list and outstanding questions to Oillinko for manual review and sourcing coordination. Availability, documented performance and the scope of supporting services are confirmed through the actual offer; inclusion in this catalogue does not certify a calibration capability."
    ] }
  ],
  "pressure-gauges-and-transmitters": [
    { title: "Keep the pressure reference in every comparison", paragraphs: [
      "Use the same pressure reference, units and range when preparing the enquiry and comparing responses. Gauge, absolute and differential measurements refer to different baselines. A similar numerical range can therefore describe a different measurement. Ask each response to show the specified reference and identify any proposed alternative, so a purchasing comparison does not overlook a mismatch hidden behind a familiar unit or product description.",
      "Separate the range available from the instrument from the range required at its output or indication. Identify the process cases the technical reviewer must assess and the conditions relevant to calibration. The offered configuration should be recorded against the equipment tag. A catalogue capability or configurable range is not proof that the delivered instrument will already have the project's required units and measurement configuration."
    ] },
    { title: "Compare the complete process-interface package", paragraphs: [
      "List process fittings, manifolds, seals, mounting accessories and documentation that belong to the requested assembly. Ask which items are included, optional or provided by the site. A standalone instrument quotation may exclude components needed for the approved installation. Keep these boundaries visible in the comparison rather than selecting an apparently cheaper offer that assumes an existing interface which has not been identified or checked.",
      "For a replacement, confirm the current tag, configuration and interface records through the owner. A new instrument may fit mechanically while presenting a different output or requiring a different receiving-system arrangement. Ask who provides configuration and the agreed acceptance checks. This purchasing review establishes the required package; actual system changes and installation remain subject to the site's authorized design and work process."
    ] },
    { title: "Request records for the delivered configuration", paragraphs: [
      "Specify the identification, material, calibration and approval records required for the purchase. Link them to the actual instrument and any separately documented interface components. Ask the offer to describe its calibration scope and the proposed configuration at delivery. The handover should allow the receiving team to reconcile the equipment tag, reference pressure, range and output with the accepted proposal without treating a general product datasheet as evidence for every delivered setting."
    ] }
  ],
  "temperature-sensors-and-thermowells": [
    { title: "Separate sensor compatibility from mechanical suitability", paragraphs: [
      "A temperature assembly has both a measurement interface and a mechanical process interface. The sensor and receiving input must match the specified sensing arrangement, while the thermowell and connection need review against their actual design duty. Ask the proposal to address these separately. A satisfactory sensor datasheet does not establish that its protective assembly has the required material, geometry or supporting design evidence.",
      "For existing installations, identify which parts are being retained and which are being replaced. A new insert may be intended for an existing thermowell, while a complete replacement can involve additional mechanical and electrical interfaces. Ask for an assembly drawing or confirmed compatibility record appropriate to the scope. Keep unknown dimensions visible rather than assuming that a familiar probe length describes all the parts needed at the measurement location."
    ] },
    { title: "Define what the acceptance evidence actually measures", paragraphs: [
      "State whether calibration evidence is required for the sensing element, a transmitter or the assembled measurement chain. Identify the range and conditions relevant to that request, with any uncertainty requirement supplied by the project. Different records can describe different parts of the assembly. Ask the response to name the item covered and the evidence delivered, so an element certificate is not mistaken for verification of every component in the installed channel.",
      "Document any required mechanical review separately from calibration. The thermowell's specified design basis, material records and dimensions relate to its role at the process connection. These should be reviewed by the assigned technical team using the actual process information. The enquiry can request that evidence without prescribing a universal insertion length, material or calculation outcome for unrelated installations."
    ] },
    { title: "Make later replacement enquiries traceable", paragraphs: [
      "Request a handover schedule linking the equipment tag to the delivered sensor, thermowell, extension, head and transmitter where included. Record their configuration and the accepted drawing revision. This helps distinguish a later insert replacement from a complete assembly purchase. Oillinko receives the enquiry for manual review; an existing catalogue entry does not confirm stock, an appointed manufacturer or compatibility with an unidentified installed temperature assembly."
    ] }
  ],
  "radar-and-ultrasonic-level-instruments": [
    { title: "Describe the required level result before choosing technology", paragraphs: [
      "Identify whether the requirement is continuous level, a point indication, interface information or inventory-related data. Define the result the receiving system needs and the role it plays in the approved installation. Different measurement arrangements address different conditions and outputs. Ask for a technical assessment against the documented duty, rather than treating radar, ultrasonic or guided-wave descriptions as interchangeable product labels for every vessel.",
      "Keep measurement and protective functions explicit. If a separate alarm or protective duty is required, its design and approval basis should be stated in the enquiry. An instrument suitable for routine level information is not automatically accepted for every protective function. The proposal should identify the evidence and responsibilities for the actual requirement without assuming that an advertised feature completes the design of the surrounding system."
    ] },
    { title: "Provide a vessel sketch that supports the assessment", paragraphs: [
      "Show the measurement location, internals, inlets and other features relevant to the proposed arrangement. Record any chamber or probe interfaces and identify unconfirmed dimensions. Ask which survey or further information is needed before a final configuration is proposed. A useful vessel sketch supports an assessment of the actual installation, while a tank-volume figure or a single exterior photograph can leave essential interfaces undefined.",
      "For a replacement, identify changes in the stored product, nozzle arrangement or operating conditions since the existing instrument was selected. A former configuration may have been assessed for a different duty. Ask the technical response to distinguish retained assumptions from those requiring a new review. The final offer should make limitations visible, especially if part of the required measurement range or process conditions remains unverified."
    ] },
    { title: "Agree configuration and commissioning boundaries", paragraphs: [
      "Specify the delivered output, reference and configuration information required for the equipment tag. Ask whether site assessment, setup, integration and commissioning are included or provided separately. Request the agreed acceptance records for the actual assignment. The handover should identify outstanding checks and limitations, so a delivered instrument is not treated as a fully accepted level measurement merely because it powers up or communicates with the receiving system."
    ] }
  ],
  "flow-meters": [
    { title: "Use one measurement basis for the enquiry", paragraphs: [
      "Keep the required quantity and units consistent across the data sheet, quotation and receiving-system description. Volume flow and mass flow are different results, and any reference conditions or additional calculation needed should be identified. Ask what the proposed instrument measures directly and what the offered package derives from other information. This helps the technical reviewer compare configurations without assuming that similar displayed values describe the same measurement basis.",
      "State whether the assignment needs instantaneous flow, accumulated totals or both, with the intended use of each result. Identify any required data connection or report interface. Ask which functions are included in the proposed hardware and configuration. A measuring sensor, its transmitter and an external totalizer can have different scope boundaries; the commercial comparison should show the complete arrangement needed for the requested information."
    ] },
    { title: "Review performance over the actual duty range", paragraphs: [
      "Ask for performance information applicable to the fluid and operating cases in the enquiry. The way accuracy is stated, its reference basis and any conditions attached to it matter when comparing offers. Identify the calibration evidence required by the project and the part of the package that record covers. A headline accuracy figure without its range and assumptions is insufficient to assess the complete measurement requirement.",
      "Review installation requirements against the available pipe arrangement. Ask which dimensions, flow conditions and supporting components the proposed configuration depends on, and identify any unresolved survey information. The technical response should state differences between the requested and offered installation. An instrument that covers the nominal line size can still require additional engineering or site work that belongs in the scope and cost comparison."
    ] },
    { title: "Link the delivered meter to its measurement records", paragraphs: [
      "Request the delivered configuration, identification, calibration and required approval documents against the equipment tag. Reconcile units, outputs and included accessories with the accepted offer, including any external functions needed for totals or data transfer. Manufacturing country, delivery location and commercial source remain separate facts to confirm for the actual supplied item. The handover should preserve enough information for a later replacement or recalibration enquiry without relying only on the nominal meter size."
    ] }
  ]
};
