type GuidanceSection = { title: string; paragraphs: string[] };

// Original service-enquiry copy. Primary research and scope limitations are
// recorded in docs/service-scope-content-2026-10-02.md.
export const serviceSpecificationGuidance: Record<string, Record<string, string>> = {
  "tank-cleaning-and-sludge-removal": {
    "Tank drawings and previous contents": "Identify the tank and provide current drawings showing its geometry, internal features and connections relevant to the work. Describe previous products, known contaminants and any available residue analyses. State whether drawings reflect the present installation or require confirmation. A capacity figure alone does not describe the surfaces, obstructions or access arrangements involved in cleaning. The initial information should support a competent scope and site assessment, with operational preparation and authorization remaining under the asset owner's approved arrangements.",
    "Residue estimate and condition": "Give the available estimate of liquid, sludge and other residues, separating measured information from assumptions. Describe the basis of the estimate and any known variation between tank locations. Samples or previous reports can support characterization where the responsible team considers them appropriate. Ask the proposal to identify the residue quantities and properties on which equipment, handling and cost assumptions depend. A preliminary sludge-volume estimate should not be presented as a confirmed waste quantity or classification before the relevant assessment.",
    "Access and cleaning objectives": "Define the condition required at handover and the activity it must support, such as inspection, maintenance or a change of stored product. Identify access constraints and the site arrangements that require review before work. Cleaning and authorization for entry are separate matters; a cleaning quotation does not establish that a tank is safe to enter or return to service. Ask for the proposed service boundaries and acceptance evidence against the owner's approved objective, with any survey or additional preparation clearly identified.",
    "Waste responsibilities and schedule": "List residue collection, temporary storage, transport and final treatment or disposal as separate responsibilities. Identify who owns the waste and which records the project requires. Ask the proposal to explain quantity assumptions and the basis of any provisional handling charges. Include the shutdown window, available work areas and interfaces with inspection or repair teams. Waste arrangements and the execution schedule should be reviewed for the actual location; a broad cleaning scope should not imply that every downstream waste service and approval is included."
  },
  "heat-exchanger-cleaning-and-retubing": {
    "Exchanger data and drawings": "Provide the equipment identification, exchanger arrangement and current drawings for the assembly being maintained. Include the relevant tube, tubesheet, baffle and connection details when retubing or bundle work is proposed. Record material specifications and drawing revisions, with missing information marked for confirmation. Nominal exchanger size alone is insufficient to define replacement components or handling requirements. Ask the response to identify which dimensions and design records it relies on and which must be checked before a final repair scope is agreed.",
    "Fouling or damage assessment": "Describe the reported problem and the evidence available, such as inspection findings, leakage records or comparable operating data. Distinguish suspected fouling from confirmed mechanical damage and identify the affected side or components where known. Performance changes can involve conditions beyond the exchanger, so a cleaning proposal should not be treated as a diagnosis by itself. Ask which assessment is included and how its findings will influence the scope. The responsible engineering team should review unresolved causes and any proposed change to the existing design.",
    "Cleaning or repair scope": "Separate cleaning, inspection, bundle handling, tube replacement and other mechanical repair activities in the enquiry. Identify work performed on site and work proposed at a workshop, together with transport and supporting services. For retubing, state the approved replacement requirements and the responsibility for reviewing compatibility with the retained assembly. Ask which scope is firm and which depends on inspection after access or dismantling. A complete offer should identify exclusions and additional work that would require a further decision.",
    "Inspection and acceptance tests": "State the required inspection and acceptance basis from the approved maintenance or repair package. Identify the records, witnesses and responsible reviewers for each stage. Dimensional checks, material records, integrity tests and operating-performance evaluation answer different questions and should not be grouped under an undefined final test. Ask how findings and deviations will be documented. The proposed method and conditions need project approval; neither a cleaning completion note nor one workshop test establishes every aspect of the exchanger's suitability for service."
  },
  "hydrostatic-testing-services": {
    "Test pack and system volume": "Provide the approved test package, equipment or line references and drawings defining the test boundaries. Identify the system volume and the basis of any estimate, since temporary equipment and water-handling requirements depend on the actual scope. Record excluded components and interfaces that need the project's review. Ask the service proposal to identify what it assumes is prepared by others. A list of pipe sizes or vessel capacities should not replace the controlled package that identifies the assembly to be tested.",
    "Approved test conditions": "Supply the test conditions and acceptance requirements specified by the responsible design and approved project documents. Identify the governing document and revision rather than asking a service provider to infer test conditions from a nominal equipment rating. Clarify the review and authorization responsibilities, including how proposed deviations are handled. The enquiry should request execution against the approved basis and the necessary planning deliverables. It should not substitute a general service description for an engineered test procedure or the site's required controls.",
    "Water supply and disposal": "Describe the available water source, required water characteristics and the handling scope defined by the test package. Identify the responsibilities for supply, transport, storage, removal and any required treatment or disposal. Record available utilities and the location constraints affecting these services. Ask which quantities and conditions the proposal uses for pricing, especially if the system volume remains provisional. Water used for a test may need assessment before release or disposal; the appropriate arrangements depend on the actual fluid, system and location.",
    "Instrumentation and report scope": "Identify the measurements and records required by the approved test package, with instrument ranges and calibration evidence suitable for that assignment. State who reviews the instruments and witnesses the agreed stages. Ask for the report format and traceability between the tested assembly, instrument identification and recorded result. The scope should address how deviations, interruptions or incomplete tests are documented. A general statement that equipment is calibrated does not establish that the offered instrumentation and records meet the particular test requirement."
  },
  "equipment-repair-and-overhaul": {
    "OEM model and serial": "Identify the equipment, assembly and serial number, with current drawings, configuration and available maintenance records. Include the installed manufacturer's reference where the buyer has it, without assuming that similar external dimensions establish the same internal arrangement. State whether the unit has previously been modified. Ask the repair response to identify the configuration it has assessed and any information needed before parts can be selected. A familiar equipment family name is insufficient to confirm the repair scope for a particular asset.",
    "Fault or condition report": "Describe observed symptoms and the evidence supporting them, distinguishing confirmed findings from suspected causes. Include relevant inspection records and operating history through the project's approved information process. State whether the equipment is assembled, dismantled or awaiting assessment. A quoted replacement part may address a symptom without establishing why it occurred. Ask which diagnostic or inspection work is included, what findings will be reported and which decisions require the owner's technical review before a repair recommendation is accepted.",
    "Repair scope": "Define the initial work requested and the limits of authorization. Separate inspection, dismantling, refurbishment, replacement parts, upgrades and final assembly where they involve different decisions. Identify any parts supplied by the owner and the responsibility for reviewing alternatives. An overhaul may reveal additional work that cannot be priced confidently in advance. Ask the offer to distinguish a firm scope from provisional items and to explain how findings, cost changes and schedule consequences will be submitted for review before proceeding.",
    "Acceptance testing": "Specify the evidence required to accept the repaired equipment against its approved scope. Identify the relevant dimensions, functions and performance conditions to be checked, along with the applicable records and witnesses. Workshop tests and site acceptance may cover different conditions, so their responsibilities should be stated separately. Ask what cannot be demonstrated within the offered test arrangement. A repaired unit's release should be supported by the agreed dossier and review process, rather than inferred solely from a statement that it runs."
  }
};

export const serviceTopicGuidance: Record<string, GuidanceSection[]> = {
  "tank-cleaning-and-sludge-removal": [
    { title: "Write a measurable cleaning handover objective", paragraphs: [
      "Describe what the receiving team needs to do after cleaning and the evidence it will review. An inspection team, a repair crew and an operator preparing a product change may require different handover conditions. Identify the areas covered, the records needed and any limitations on access or observation. Avoid comparing proposals on the word clean alone when they describe different endpoints or leave part of the tank outside their scope.",
      "Keep the cleaning outcome distinct from structural condition and operational release. Removing residues can make surfaces available for an agreed inspection without establishing that corrosion, leaks or other defects have been resolved. Record who assesses the exposed condition and who authorizes the next activity. This separation helps prevent a completed cleaning service from being mistaken for acceptance of the tank's mechanical integrity or readiness for operation."
    ] },
    { title: "Make variable residue costs visible in the offer", paragraphs: [
      "Ask for the basis used to estimate recoverable liquids, solid residues and waste needing separate handling. If quantities remain uncertain, identify how the actual work will be measured and reconciled for review. Separate mobilization and defined activities from charges linked to residue quantity or condition. The commercial comparison should show which uncertainty each offer carries instead of treating every preliminary total as a fixed price for an identical task.",
      "Request the proposed responsibility boundaries for recovered material, waste containers and transport documents. Confirm which arrangements must be provided or approved by the owner before mobilization. Where a further analysis or site assessment is required, include it as an explicit dependency. An offer that stops at recovering sludge from the tank cannot be compared directly with one that also includes agreed transport and final waste services."
    ] },
    { title: "Coordinate cleaning with the next maintenance package", paragraphs: [
      "Identify the interfaces between cleaning, inspection and any subsequent repair work. Agree the information passed to each team and the person receiving the handover records. Include photographs or area references where the approved reporting scope requires them, while documenting areas that were not assessed. Oillinko receives the enquiry for manual review; the actual execution arrangement, location coverage and specialist suitability are confirmed against the project's requirements."
    ] }
  ],
  "heat-exchanger-cleaning-and-retubing": [
    { title: "Separate fouling removal from a mechanical repair decision", paragraphs: [
      "A maintenance enquiry should state whether the immediate objective is access for inspection, removal of deposits, investigation of leakage or replacement of damaged components. These activities may be connected, but they do not have the same scope or acceptance evidence. Ask the proposal to explain the sequence of decisions and the information required at each stage. Retubing should follow an approved repair basis, rather than be assumed necessary from a reported reduction in performance.",
      "Record the condition of retained parts and the responsibilities for assessing them. New tubes do not by themselves establish the condition of tubesheets, baffles, channels or the shell. Identify any inspection needed to review the retained assembly before approving the final work. Where a design change is proposed, require its differences and engineering-review responsibility to remain visible instead of treating the change as a routine replacement."
    ] },
    { title: "Describe the workshop and site interfaces separately", paragraphs: [
      "List bundle handling, transportation, temporary storage and site preparation as distinct scope elements when they apply. State which drawings, equipment references and handling information are available for review. Ask the offer to identify what the workshop receives and what it returns, including loose components or owner-supplied parts. An apparently complete repair quotation may depend on another contractor providing access, dismantling or reinstatement at the plant.",
      "Define the required handover dossier for the repaired assembly. It may include the agreed material identification, inspection findings, approved deviations, dimensional records and test results, according to the project scope. Identify the documents needed before shipment and those completed at the site. Keep these requirements connected to the actual equipment reference so receiving personnel can reconcile the repaired bundle and its records without relying only on a transport description."
    ] },
    { title: "Compare performance evidence using a common basis", paragraphs: [
      "If post-maintenance performance is part of acceptance, agree the relevant operating data and comparison basis with the responsible engineering team. Changes in flow, temperatures or process conditions can affect interpretation. A workshop integrity result and an operating-performance review address different objectives. Ask what evidence the offered service will provide and which evaluation remains with the owner, rather than promising a universal efficiency recovery from cleaning or tube replacement alone."
    ] }
  ],
  "hydrostatic-testing-services": [
    { title: "Agree what is supplied and what is prepared by the site", paragraphs: [
      "Create a responsibility schedule for the approved test package. Identify temporary equipment, fittings, water services, instrumentation and reporting that belong to the service, and the preparation assigned to the site or another contractor. Record the required readiness evidence and the person authorized to review it. These boundaries belong in the enquiry so a provider can assess the assignment without assuming that every connection and supporting service is already available.",
      "Testing involves stored energy and requires competent planning and site authorization. A catalogue listing is an invitation to define a service requirement, not approval to start work. Ask for the planning and review deliverables required by the project, including the responsibility for resolving changes in the test scope. The actual method, controls and execution conditions must remain within the approved process for the location and equipment concerned."
    ] },
    { title: "Make the report traceable to the approved test package", paragraphs: [
      "Specify how each result will be linked to the equipment or line reference, test-package revision and instrument records. Agree the required witnesses, dates and supporting observations. If a test is incomplete or an approved condition was not met, its status should be documented explicitly. A report title such as pressure tested does not show the boundaries checked or establish that the entire installation was included in one assignment.",
      "Ask how findings and deviations are referred back to the responsible project team. A test report records evidence against the agreed acceptance basis; it does not automatically establish the absence of every possible defect or replace other specified inspections. Identify the separate reviews needed before the asset is released for its next activity. Keep unresolved matters visible in the dossier and distinguish completed tests from work still awaiting authorization or acceptance."
    ] },
    { title: "Include water removal and completion records in the scope", paragraphs: [
      "Define the agreed responsibilities after the test, including water handling, removal of temporary items and completion documentation where these are part of the package. State which reinstatement or subsequent preparation is provided by others. Ask for an explicit handover boundary and the records the receiving team requires. A quotation limited to test equipment and personnel may leave important completion activities outside its price, even when the test itself is successfully documented."
    ] }
  ],
  "equipment-repair-and-overhaul": [
    { title: "Use staged approval when the internal condition is unknown", paragraphs: [
      "Consider defining an initial inspection and assessment package before authorizing the full repair, where the condition is uncertain. Ask for a findings report identifying damaged parts, measurements, proposed work and unresolved questions. The owner can then review the recommended scope and commercial implications against the equipment's required duty. A staged arrangement should make the approval boundary clear instead of treating an open-ended overhaul description as authority for every additional activity.",
      "Require the proposal to explain how work outside the agreed scope is handled. Record which changes affect parts, testing, warranty terms or the delivery programme. Identify who can approve them and what supporting evidence is needed. This helps distinguish an initial budget estimate from a defined repair commitment, and gives the purchasing team a consistent basis for comparing recommendations received after the equipment has been examined."
    ] },
    { title: "Keep replacements and modifications identifiable", paragraphs: [
      "Ask the repair dossier to identify parts replaced, retained or modified, with the traceability required by the project. Alternative materials, components or configurations should be described against the approved requirement. A proposed improvement may need an engineering review beyond the original maintenance scope. Keep that decision separate from routine repair so the owner can assess interfaces, future spares and the effect on the asset's configuration records.",
      "Reconcile the returned assembly with its identification and the agreed test evidence. Include the documented configuration, outstanding limitations and any site work needed before acceptance. Repair recommendations for one equipment family should not be treated as universal requirements for every pump, valve or machine. The governing documents and evidence should match the actual asset and scope, with workshop capabilities reviewed for the work being proposed."
    ] },
    { title: "Define the return condition and continuing support", paragraphs: [
      "State the packing, preservation, transport and documentation requirements for the repaired unit. Ask the offer to identify any warranty terms, support arrangements and exclusions rather than assume that all repairs carry the same coverage. Record the agreed handover and site-acceptance responsibilities. The final purchasing comparison should include assessment work, approved parts, testing and logistics so a low initial workshop price is not mistaken for the complete cost of returning the asset to its required condition."
    ] }
  ]
};
