type TopicGuidanceSection = { title: string; paragraphs: string[] };

// Topic-specific purchasing guidance. Research basis is recorded in
// docs/content-expansion-2026-10-02.md; supplier identities stay in the directory.
export const catalogueTopicGuidance: Record<string, TopicGuidanceSection[]> = {
  "cathodic-protection-equipment": [
    { title: "Separate the protection design from the equipment order", paragraphs: [
      "A cathodic protection enquiry should identify whether the requirement is for replacement components, a new equipment package or a protection design with associated supply. Galvanic anodes and impressed-current equipment need different schedules and supporting information. For a new system, provide the approved design basis, protected asset geometry, coating condition, exposure environment and intended service life. For replacement anodes, identify the original drawing and alloy specification, together with any survey findings that prompted the replacement. An equipment quotation alone does not establish that the proposed arrangement will protect the complete asset.",
      "List the boundaries of the package. An anode supply may include cast alloy and an insert but exclude attachment hardware, welding, installation and electrical continuity checks. An impressed-current package may involve a power supply, anode assembly, reference electrodes, monitoring and connecting cables. Identify which components already exist and who will check their compatibility. Where design information is incomplete, ask for the missing input or a separately defined engineering scope instead of treating a familiar anode shape as a verified substitute."
    ] },
    { title: "Describe anode mass, inserts and connection details", paragraphs: [
      "Distinguish net anode alloy mass from gross assembly mass, which can include the steel insert or mounting arrangement. Give the required dimensions, insert material, attachment drawing and quantity per asset. Request confirmation of alloy designation and the specified chemical and electrochemical test evidence; appearance and weight cannot establish these characteristics. For cables and reference electrodes, state the installed environment, required length, termination and mounting interface. Keep allowable tolerances and acceptance values tied to the approved project specification rather than inventing a universal limit for every installation."
    ] },
    { title: "Plan receipt evidence and commissioning responsibilities", paragraphs: [
      "A useful delivery dossier connects the supplied batch to its identification, material records, dimensional checks and specified test results. State whether witnessing is required and how marking must remain legible after packing or installation. Ask the proposal to separate manufacturing checks from installation and commissioning measurements. The responsible engineer should define the survey method, acceptance criteria and future monitoring plan for the asset. Packaging should protect connection surfaces, cables and delicate sensing elements; confirm storage instructions and any limits on preservation before an extended period between receipt and installation."
    ] }
  ],
  "casing-and-production-tubing": [
    { title: "Order a defined tubular, not just a nominal size", paragraphs: [
      "A casing or tubing line item needs a complete identity: nominal outside diameter, mass designation, material grade and grade variant, end connection, length range and quantity unit. State whether the order is measured in joints, metres or tonnes, and define how the final tally will be accepted. A familiar grade name does not identify every applicable material condition or service qualification. Provide the governing product specification and project requirements, including any restrictions related to the well environment, without assuming that all products with the same grade label are interchangeable.",
      "For a replacement string or short completion section, record the installed connection and its exact designation. Nominal diameter does not confirm thread compatibility, seal geometry or interchangeability between connection families. State whether couplings are included and whether the request covers plain-end pipe for later processing or fully finished and inspected connections. Any proposed alternative needs review against the well design and mating equipment. Keep material suitability for corrosive or sour service as an explicit engineering decision supported by the specified evidence."
    ] },
    { title: "Keep accessory quantities and connection processing visible", paragraphs: [
      "Separate pup joints, crossovers, couplings, handling accessories and spare components from the main tubular quantity. Give each crossover's two connection ends and its required length instead of describing it only by the string size. Clarify whether thread inspection, gauging, coating, cleaning and protective compounds are included in the supply scope. If products will be cut or rethreaded, identify who performs that work and how the resulting pieces retain traceability. These boundaries help explain why two offers for apparently identical pipe can cover different finished products."
    ] },
    { title: "Match the material dossier to the physical tally", paragraphs: [
      "Request a packing list and tally that can be reconciled with markings on the delivered joints and the applicable material and inspection records. Define the required certificate type, traceability level, inspection scope and release process in the enquiry. A general company certificate is not a substitute for records covering the offered batch. State preservation, thread-protector and transport requirements, particularly where storage or several handling stages are expected. Ask for the manufacturing country separately from the dispatch location, and make commercial tolerances on delivered length or quantity visible before comparing totals."
    ] }
  ],
  "wellheads-and-christmas-trees": [
    { title: "Identify the complete pressure and interface schedule", paragraphs: [
      "A wellhead or tree enquiry should describe the assembly arrangement rather than a single bore dimension. Include a schematic or approved general arrangement identifying casing and tubing interfaces, pressure ratings, outlets, valves and connection details. Distinguish the wellhead housing, spools, hangers, tubing-head adapter and tree components that are included in the package. Where the design specifies material, temperature, product specification or performance requirements, reproduce the exact project designations and governing edition. Avoid assigning an assembly rating from the most visible valve or the nominal tubing size.",
      "For an installed asset, provide the original equipment identification and controlled drawings. Replacement seals, adapters and hangers can have critical geometry that is not established by a photograph or nominal flange size. Clarify whether the scope is a complete new assembly, replacement parts, refurbishment or integration with existing equipment. A proposal for an alternative should describe every affected interface and its qualification basis. The responsible well engineer must review compatibility with the well programme and existing pressure-containing equipment before the alternative is accepted."
    ] },
    { title: "Separate valve actuation and control from the mechanical assembly", paragraphs: [
      "State which valves are manual, remotely actuated or part of a specified safety function. Identify the required actuator arrangement, control interface, available utilities and environmental constraints without assuming that actuation is included with every tree valve. List any control panel, hydraulic equipment, instruments, connectors and interconnecting lines as distinct deliverables where appropriate. Define responsibility for integration and functional acceptance. A mechanical assembly quotation can be technically useful while still excluding the controls, field connections or services needed for the complete installation."
    ] },
    { title: "Define the release dossier and preservation scope", paragraphs: [
      "Ask for a component list tied to the assembly drawing, serial identification and the project-required material, inspection and test records. Specify the witnessing or review points and who authorises release; do not treat a broad product-family statement as evidence for the offered assembly. The quotation should identify testing boundaries, any exclusions and the documentation supplied with spare parts. Confirm protection of sealing surfaces, cleanliness, transport supports and storage instructions. Installation, pressure testing at site and commissioning require separately agreed procedures and qualified responsibilities, not assumptions carried over from a supply-only price."
    ] }
  ],
  "completion-packers-and-downhole-valves": [
    { title: "Check the complete dimensional envelope of the string", paragraphs: [
      "A packer or downhole valve must be evaluated within the complete completion string. Give the casing size, mass designation and relevant internal dimensions, the tubing size and exact connection, and the setting location. Nominal tubing and casing sizes alone do not establish clearance through restrictions or compatibility with adjacent tools. Include the approved completion schematic and any drift or minimum-bore requirements. Separate a tool's outside diameter, through-bore and connection dimensions so the technical reviewer can identify which limitation affects installation, intervention or production.",
      "For a retrievable packer, identify the required setting and retrieval arrangement, together with the project-defined load and differential-pressure cases. For a downhole valve, describe its function and whether control lines, shifting tools or other interfaces are involved. Temperature, fluid composition and expected exposure affect the proposed materials and seals. These conditions should come from the approved well basis. A supplier's ability to manufacture a tool for the nominal string size does not by itself demonstrate suitability for the intended duty."
    ] },
    { title: "Make qualification and accessory boundaries explicit", paragraphs: [
      "State the required product specification, validation basis and project acceptance requirements for each tool. Packers and safety valves have different functions and qualification scopes; a certificate covering one product family cannot establish the other. Ask for a line-by-line response identifying offered model, qualification evidence and deviations. List setting tools, seal assemblies, control-line connections, plugs and retrieval accessories separately where needed. Define whether these are included, rented, supplied by the operator or covered by a separate service package. This prevents an apparently complete tool price from concealing missing deployment interfaces."
    ] },
    { title: "Request a usable handover package", paragraphs: [
      "The delivery records should identify the actual tools, assembly revision, materials and specified tests, with documentation that can be reconciled to their markings. Confirm storage and preservation conditions for elastomers and exposed connection surfaces. Ask what technical support, approved operating documentation and installation services are included, and identify the parties responsible for the final completion design and operational procedures. Keep any proposed substitution subject to engineering approval. Sourcing information is useful for comparing scope, but it should not be used as a field setting or retrieval instruction."
    ] }
  ],
  "inspection-ndt-and-material-testing": [
    { title: "Turn an inspection request into a defined examination scope", paragraphs: [
      "Identify what the inspection must establish: receipt condition, weld discontinuities, material identity, thickness, mechanical properties or another specified characteristic. These objectives call for different methods and can require different preparation and access. Provide the component drawing, material, dimensions, inspection stage and the acceptance document. Define coverage by locations, weld references, surfaces or sample quantities instead of asking only for an NDT certificate. Where a method is prescribed, state it; where method selection is required, ask for a technically justified proposal for review.",
      "Separate non-destructive examination from destructive material tests and identify who authorises sample removal. An inspection result applies to the examined locations or samples and the method's stated limitations. It does not automatically establish that every part of a batch has the same condition. For receiving work, define how the sample or inspection plan relates to the delivery quantity. For fabrication, connect examination records to the weld map and drawing revision so the report remains useful after assembly, coating or installation hides the examined surface."
    ] },
    { title: "Confirm qualifications, access and acceptance responsibility", paragraphs: [
      "Ask for personnel qualification and authorisation appropriate to the method and governing scheme, together with the laboratory scope when laboratory testing is required. A company-level accreditation or a technician's general experience is not enough to establish coverage of a particular assignment. Confirm access, surface condition, lighting, utilities and any site arrangements the work requires. State who supplies preparation, scaffolding or handling. The owner of the acceptance criteria should be identified before work starts; reporting an indication and deciding whether the component is acceptable are different responsibilities."
    ] },
    { title: "Specify evidence that can be reviewed later", paragraphs: [
      "A usable report identifies the item, examination locations, procedure or method reference, equipment, relevant settings, results and applicable limitations. Request photographs, maps or retained data where the project requires them, with a clear link to the component identification. State the required report format, review timing and handling of nonconforming findings. If re-examination after repair is likely, define whether it is included or separately priced. Compare proposals against the same coverage and reporting scope; a lower visit price may exclude preparation, interpretation, repeat attendance or the evidence needed for final release."
    ] }
  ],
  "calibration-and-instrument-repair": [
    { title: "Separate calibration, adjustment and repair", paragraphs: [
      "Calibration establishes a relationship between an instrument's indication and reference values under stated conditions. Adjustment changes the instrument response, while repair addresses a fault or damaged component. An enquiry should identify which activities are authorised and whether the instrument must be assessed before any adjustment. Request as-found results when the previous condition matters, and as-left results after an authorised intervention. This distinction is especially useful when measurements already taken with the instrument may need review; a final passing result alone cannot show its earlier condition.",
      "Provide the instrument identification, measuring range, required points, output type and accessories needed to use it. For a transmitter, distinguish sensor measurement from the electrical output or a complete installed loop. For a portable instrument, identify probes, leads or modules that form part of the measurement system. State whether work takes place in a laboratory or at site, and define removal, isolation, reinstatement and configuration responsibilities. Keep passwords and other credentials out of the enquiry while describing the interface or access arrangements that the authorised team will need."
    ] },
    { title: "Request uncertainty and conformity on the intended basis", paragraphs: [
      "Ask for the calibration results and measurement uncertainty appropriate to the intended use, with traceability and accreditation scope where the project requires them. A badge or certificate heading does not establish that the required quantity and range are covered. If a pass or fail statement is needed, specify the tolerance and agree the decision rule used to account for uncertainty. Keep resolution, accuracy specifications and reported uncertainty distinct. A certificate without a conformity statement can still provide useful measurement results, but the buyer must know who evaluates those results against the application requirements."
    ] },
    { title: "Set repair approval and return conditions", paragraphs: [
      "Request a diagnosis and separately priced repair proposal when the condition is unknown. Define whether parts replacement, firmware changes or adjustment require approval, and how any configuration is recorded. Confirm turnaround assumptions, packaging, transport and the documentation returned with the instrument. Ask for limitations if the required performance cannot be restored. The next calibration interval should be determined through the equipment programme using its duty, history and risk; an arbitrary annual interval is not a conclusion established by every calibration certificate."
    ] }
  ],
  "piping-spools-and-skid-fabrication": [
    { title: "Issue a controlled fabrication package", paragraphs: [
      "A piping spool enquiry should include the approved isometric or fabrication drawing, revision, material schedule and connection details. For a skid, add the layout, equipment interfaces, battery limits and the responsibilities for structural, piping, electrical and instrument work. Separate free-issued components from contractor-supplied material. Identify which drawings are approved for fabrication and which still require engineering. A workshop should not be expected to infer design pressure, weld details or nozzle orientation from a general arrangement alone; unresolved design information needs a defined review step before manufacture.",
      "Give the reference dimensions and the acceptance basis for the assembled package. Tie fit-up, flange orientation, support locations and equipment mounting interfaces to the controlled drawings. State whether site measurement or a fit check is required and who supplies the mating-interface information. Welding sequence and restraint can affect distortion, so the proposal should explain how dimensional requirements will be managed where they are important. The enquiry should define the required result and inspection evidence without prescribing an unreviewed workshop procedure."
    ] },
    { title: "Keep welding, testing and finishing as visible work items", paragraphs: [
      "Specify the governing construction basis and the required welding procedures, qualifications, examination coverage and inspection plan. Identify responsibility for any pressure test, including the approved test basis, witnessing, temporary components and restoration after the test. State cleaning, coating, insulation and preservation boundaries, and clarify whether these occur before or after particular examinations. A quoted skid may be a mechanically fabricated frame with piping, or a fully integrated and tested package. Describe the required level of completion so proposals cover the same deliverables."
    ] },
    { title: "Link material traceability to the finished assembly", paragraphs: [
      "Request a material register, weld map and fabrication dossier that connect the finished spool or skid to its drawings, material records and inspection results. Define how identification is retained when stock is cut, assembled or coated. Ask for the final bill of materials and drawings reflecting approved changes, with deviations recorded before release. Confirm lifting, packing and transport engineering responsibilities rather than assuming that a fabricated skid is automatically ready to lift. Delivery dimensions, mass and preservation details should be available in time for the buyer to plan handling and installation."
    ] }
  ],
  "structural-steel-and-equipment-supports": [
    { title: "Separate engineering from fabrication of supports", paragraphs: [
      "Identify whether the enquiry covers fabrication to an approved design, verification of an existing support or design and supply of a new arrangement. Provide drawings, member and plate schedules, connection details and the governing structural basis. Equipment loads, operating effects and relevant environmental actions belong in the design information supplied or agreed with the responsible engineer. A fabricator's workshop drawing does not automatically establish that the complete structure has been checked for the installation. Make the design approval and fabrication release responsibilities clear before requesting a fixed scope.",
      "For replacement supports, record interfaces with the existing structure, equipment and foundations. Include access limits, bolt patterns, elevations and any survey required to confirm these dimensions. Photographs can explain the location but cannot establish a hidden connection or a load path. Clarify whether anchor bolts, base plates, grout interfaces and installation hardware are included. If existing equipment will be moved or temporarily supported, that activity needs a separately reviewed site plan and qualified responsibility; it should not be assumed from a price for steelwork."
    ] },
    { title: "Define the material, weld and surface protection package", paragraphs: [
      "Give the specified steel grades, applicable product forms and required material records. Specify welding and inspection requirements for the actual connection details, together with the dimensional acceptance basis. Surface protection should identify the required system, preparation, inspection and repair arrangements. Galvanizing, painting and other finishes are different scopes and may affect fabrication details or the order of work. Ask the proposal to identify exclusions around preparation, finishing and site touch-up. Do not treat a generic coated description as evidence that the project protection system is included."
    ] },
    { title: "Plan assembly evidence and site fit", paragraphs: [
      "Request clear identification of members or assemblies, fabrication drawings, material traceability and the specified inspection records. Define whether trial assembly, dimensional surveys or fit checks are required before dispatch. For bolted equipment supports, agree which mating dimensions will be checked and how unresolved site dimensions affect release. Confirm packing, transport dimensions and handling instructions, with lifting provisions addressed by the appropriate engineer. Installation supervision, alignment, final bolting and inspection at site should appear as separate inclusions or exclusions so the buyer can assemble a complete work package."
    ] }
  ],
};
