type GuidanceSection = { title: string; paragraphs: string[] };

export const valveSpecificationGuidance: Record<string, Record<string, string>> = {
  "globe-and-control-valves": {
    "Flow cases and pressure drop": "Provide a row for each required operating case, linking flow, upstream pressure, downstream pressure and temperature rather than listing unrelated maxima. Identify the units and pressure references, and distinguish measured values from design assumptions. Include minimum and normal duty alongside the maximum case when they apply. State pipe size, connection rating and any approved noise limit. Ask for a sizing response against the supplied cases, with proposed valve and trim details. Matching the line size or quoting a single flow coefficient does not establish suitability across the required operating range.",
    "Fluid properties": "Identify the fluid and its phase at the valve inlet, together with the properties needed for the applicable sizing assessment. For a liquid, provide available density, viscosity and vapour-pressure information with its temperature basis; for a gas or vapour, identify the composition and relevant property basis. Record solids or other constituents that the material and trim review must consider. Ask the engineering response to identify missing inputs and assumptions. Use the project's confirmed data rather than treating a general fluid name as a complete specification.",
    "Required shutoff": "Define the requested closure performance separately from flow-regulating duty. Identify the applicable test standard and edition, leakage requirement, test conditions and direction specified by the project. State the differential pressure to be considered when reviewing closure and actuator requirements. Ask the offer to confirm the proposed seat and trim arrangement against that basis and to list deviations. An unqualified tight-shutoff description is insufficient for comparison, and a control-valve closure test should not be interpreted as evidence that the valve fulfills a separate safety-isolation requirement.",
    "Control signal and fail position": "Provide the control-interface schedule, actuator utility conditions, required feedback and accessory scope. Distinguish the operating command from position feedback and diagnostic communications. Describe the approved response required for each relevant loss condition, such as loss of control signal, actuator supply or electrical power; do not reduce several different cases to an unexplained fail-open or fail-closed label. Request the offered assembly's stated response and verification scope. Any safety function needs its own project requirements and review; an actuator or digital positioner does not alone establish that capability."
  },
  "ball-gate-and-plug-valves": {
    "Bore size and pressure class": "State the nominal size, required flow passage and the project's valve rating designation separately. Where full bore or passage for an inspection tool is required, attach the dimensional requirement rather than rely on the valve size alone. Give the governing design standard and edition specified by the project. Ask the offered valve's pressure-temperature basis to be identified for its actual construction and materials. A class or nominal-pressure label should not be treated as a pressure limit valid at every temperature or as proof of an unrestricted internal bore.",
    "Body and trim materials": "Identify the specified body, closure element, stem, seating surfaces and other wetted materials, including their grade or approved designation. Request a materials schedule for the proposed valve instead of accepting a single body-material description as the complete specification. Seat inserts, packing and body seals also need review against the fluid and temperature basis. For a replacement, record the installed configuration and any change in duty. Proposed substitutions should identify the affected components and evidence for review before they are accepted as equivalent.",
    "End connections": "Provide the mating flange, thread or welding-end details from the controlled piping documents. For flanged valves, include the specified standard, facing, rating and connection dimensions; for threaded or welded arrangements, retain the exact thread or weld preparation requirement. State the face-to-face or end-to-end dimension needed for a replacement and the available installation space. Ask the proposed drawing to identify differences from the existing valve. Matching nominal size does not establish a suitable joint, compatible sealing surface or a replacement that fits the existing spool.",
    "Operating medium and temperature": "Describe the process medium and available composition or contamination information, with the operating cases and temperature range established by the project. Identify conditions relevant to seats, packing and other wetted components instead of describing the valve only as suitable for oil or gas. Keep design limits distinct from routine duty and identify any required special service qualification. Ask the technical response to state assumptions and exceptions. A valve family or material name alone cannot establish suitability for a changed fluid, cleaning exposure or temperature requirement."
  },
  "butterfly-and-check-valves": {
    "Line size": "State the line size and identify whether the item is a butterfly valve or a check valve; these functions should occupy separate lines in the enquiry. Provide the mating pipe and flange details, required face-to-face dimension and available passage around adjacent equipment. For a replacement, attach the existing drawing rather than rely on an abbreviated size designation. Request the proposed valve's connection and envelope drawing. Internal geometry and the moving element's clearance require review even when the nominal line size matches the installed arrangement.",
    "Pressure and temperature": "Give the documented operating and design conditions with their units and identify the project's rating and acceptance basis. Ask the offered assembly to be reviewed against the complete pressure-temperature envelope, including the selected seat or liner and other materials. For a check valve, provide the normal and minimum flow cases and relevant pressure information for its automatic response assessment. For a butterfly valve, specify the required shutoff duty and differential-pressure cases. The same body rating does not demonstrate identical seating performance or suitable behavior in both valve families.",
    "Installation orientation": "Provide the intended pipe orientation, permitted flow direction and a layout showing access and adjacent components. Check-valve suitability can depend on the closure design and gravity effects, so request confirmation for the actual offered construction and position. For butterfly valves, identify actuator or gearbox space and the interface dimensions that need review. Refer installation and clearance decisions to the selected valve's approved documentation and project personnel. Do not assume that a generic arrow or a photograph establishes every permitted position, clearance or flow arrangement.",
    "Disc, seat and seal materials": "Specify the disc or closure element, seat or liner, stem and seal materials using the project requirements and known fluid conditions. Ask the offer to distinguish wetted parts from non-wetted body components and to identify the complete material configuration. Butterfly-valve liner construction and check-valve seating arrangements are different details, even when their quotation uses similar material names. Include restrictions for the actual application and request proposed alternatives explicitly. A general elastomer or stainless-steel description does not define a complete, reviewable material selection."
  }
};

export const valveTopicGuidance: Record<string, GuidanceSection[]> = {
  "globe-and-control-valves": [
    { title: "Specify the regulating assembly behind each valve tag", paragraphs: [
      "State whether the enquiry is for a manually operated globe valve, a complete actuated control valve or a replacement part for an existing assembly. A globe body describes construction, while a control-valve enquiry must also describe the regulating function and its interfaces. Use a tag-specific datasheet so offers for a body alone are not compared with offers including an actuator, positioner and accessories. Identify which parts will be retained and who is responsible for integrating them.",
      "For a replacement, provide the existing body, trim, actuator and instrument identification together with a controlled drawing and current operating cases. Clarify whether the replacement is intended to reproduce the installed configuration or resolve a changed process requirement. A matching model description or face-to-face dimension does not confirm equivalent regulating performance. Ask a proposed alternative to state its assumptions, interface differences and review evidence without treating a lower price as approval to change the assembly."
    ] },
    { title: "Review the proposal against a common operating-case register", paragraphs: [
      "Give every operating case a reference that can be carried into the sizing response and technical comparison. Ask the response to identify the proposed body and trim, the calculation basis and the case-specific findings that the project needs reviewed. Keep unresolved input data visible. If bidders use different assumed pressures or fluid properties, reconcile those assumptions before comparing the results; a neatly presented calculation is still conditional on the data used.",
      "Where the documented duty requires review of noise, cavitation, flashing or other limiting behavior, ask for the applicable assessment and the conditions it covers. Separate a selected trim arrangement from evidence that it addresses the actual cases. The responsible engineering reviewer should identify any additional system information or specialist study required. This enquiry guidance does not prescribe a valve size, trim selection, acceptable travel band or adjustment procedure, and it does not guarantee stable control from a catalogue description."
    ] },
    { title: "Separate factory evidence from installed control-loop acceptance", paragraphs: [
      "List the required factory inspection, pressure-boundary, closure and assembly-function records with their acceptance basis. Ask each record to identify the configuration and tag examined. A workshop demonstration of valve movement is different from verification of the installed loop's performance, so show site configuration and commissioning responsibilities as separate scope items. Identify who supplies the process inputs, interface checks and approved test arrangements needed at each stage, including any items excluded from an equipment-only offer.",
      "Request the final datasheet, assembly drawing, materials schedule, accessory register and configuration information needed for the owner's maintenance records. Identify spares by the offered construction and record manufacturing origin separately from the dispatch location. Keep outstanding tests, deviations and field work visible at handover. Send the controlled enquiry documents to Oillinko for manual sourcing coordination; quotations remain subject to technical review, and this page does not confirm stock, product approval or completed commissioning."
    ] }
  ],
  "ball-gate-and-plug-valves": [
    { title: "Describe the isolation function before choosing the construction", paragraphs: [
      "Use the valve tag and piping schedule to identify the required function. Gate valves provide an opening or closing function through a moving gate, while ball and plug valves use rotating closure elements. These construction differences do not make every design suitable for the same service. Record whether the requirement is routine isolation, a specified shutdown function or another approved duty, and ask the proposal to address that function explicitly.",
      "Keep continuous flow regulation separate from an isolation enquiry unless the selected design and project basis expressly require it. Ask which valve construction is offered, how it addresses the defined duty and which limitations remain. Where the enquiry permits several families, compare the proposed bore, seats, operating arrangement and maintenance access against the same requirements. A familiar family name should not replace a technical response for the actual installation."
    ] },
    { title: "Define actuation and accessories as a complete assembly", paragraphs: [
      "Identify manual operation, gearing or an actuator as part of the purchase scope. For an actuated valve, provide the approved functional requirements, available utilities, mounting interface and required signals. Ask the proposal to distinguish valve hardware, actuator, brackets, couplings, switches and control accessories. An actuator supplied separately needs an agreed integration and verification responsibility; matching a mounting pattern alone does not establish a complete working valve assembly.",
      "For replacements, record the installed valve and drive identification and the controlled assembly drawing. Ask who reviews the operating loads and offered actuator selection for the documented duty. Keep any shutdown or safety function subject to the project's responsible engineering review. Request assembly documentation and the specified functional acceptance evidence. Do not infer a fail position, operating time or safety capability from the presence of an actuator or a generic control-box description."
    ] },
    { title: "Agree the valve test and release records", paragraphs: [
      "Define the required inspection and testing standard, edition and acceptance criteria in the purchasing specification. Distinguish pressure-boundary testing from seat or closure testing, and state the requested test medium and direction where the approved basis requires them. Ask the offer to identify which requirements are included and where witnessing or additional records cost extra. Terms such as tested or tight shutoff need a documented acceptance basis rather than an assumed universal meaning.",
      "Request records linked to valve tags or serial identification, together with the specified material documentation, final drawing and accessory list. Treat product-family qualification and tests on the actual supplied valve as different evidence. List special-service requirements separately and ask for their applicable scope, without assuming that one certificate covers every construction. Oillinko reviews this enquiry information and coordinates sourcing manually; the catalogue does not confirm available stock, an accepted alternative or a completed valve qualification."
    ] }
  ],
  "butterfly-and-check-valves": [
    { title: "Separate commanded operation from automatic reverse-flow response", paragraphs: [
      "A butterfly valve changes the flow passage through movement of its disc and may be supplied with manual or powered operation. A check valve responds to flow and pressure conditions to oppose reverse flow. State the required function for each tag before comparing alternatives. A check valve does not provide the same commanded isolation arrangement as an operated valve, and a butterfly valve alone should not be assumed to perform automatic non-return duty.",
      "For a check-valve enquiry, describe the installed system, normal and reduced flow cases, and the conditions surrounding equipment starting or stopping that the project needs assessed. Request a proposal stating the construction and its suitability basis, with any additional data needed. If the project requires transient analysis, identify that engineering scope separately. Do not accept a generic non-slam description as evidence that all system pressure transients or reverse-flow conditions have been evaluated."
    ] },
    { title: "Review body arrangement and access against the piping layout", paragraphs: [
      "For a butterfly valve, identify the required wafer, lugged or flanged arrangement from the piping specification and request the offered connection drawing. Confirm the face-to-face dimension, mating flange details and the moving disc's required clearance with the responsible reviewer. Identify any required end-of-line duty explicitly; it should be confirmed for the actual construction and documented conditions. A compact body arrangement does not by itself establish suitability for every flange or adjacent fitting.",
      "For a check valve, ask the offer to identify the closure arrangement and the required orientation and access conditions. Provide the location of adjoining equipment and the space available for inspection or replacement. Compare the complete installed envelope, not only the body length. The layout review should also identify what supports, connecting parts and installation work are outside the valve supply. Use approved drawings and selected-product documentation to resolve these interfaces before treating a substitution as interchangeable."
    ] },
    { title: "Compare flow evidence and acceptance documentation", paragraphs: [
      "Request the flow and pressure-loss information needed for the project review, with the configuration and conditions to which it applies. For a check valve, ask for the stated opening and operating characteristics relevant to the documented duty. For a butterfly valve, distinguish the requested shutoff evidence from any flow-control information. Do not compare isolated coefficients or marketing descriptions without their basis, or assume that a workshop closure test demonstrates suitable behavior throughout an operating system's changing flow conditions.",
      "Identify the required material records, inspection reports, valve tests and final drawings, linking them to the supplied tags or serial references. For powered butterfly valves, include the agreed assembly and functional records for the drive and accessories. List spares, preservation and supplied instructions separately from field services. State manufacturing origin independently of dispatch location. Submit the valve schedule and piping details to Oillinko for manual enquiry coordination, with unconfirmed data and proposed deviations kept visible for technical review."
    ] }
  ]
};
