type GuidanceSection = { title: string; paragraphs: string[] };

// Original procurement copy; primary editorial basis is recorded in
// docs/digital-content-2026-10-02.md. No supplier identities or access secrets.
export const digitalSpecificationGuidance: Record<string, Record<string, string>> = {
  "reservoir-software-and-data-services": {
    "Technical objective": "Identify the subsurface question and the decision the work should support. Distinguish interpretation, geological modelling, simulation input preparation and a software purchase, because each has different inputs and acceptance records. Describe the asset or study area through the approved project brief and state which assumptions the technical team has already established. Ask the response to separate data preparation, specialist interpretation and application configuration. A software license supplies defined usage rights; it does not automatically include a reservoir study or validate its conclusions. Where the objective remains exploratory, request a bounded assessment phase with identified outputs before commissioning a larger modelling scope.",
    "Available datasets": "Provide a dataset inventory that identifies source, coverage, revision, format and the rights available for the proposed use. Include the relevant well, log, seismic, geological and production inputs only where they apply to the study. State units, coordinate references and known quality limitations. A file being available does not establish that its content is complete or suitable for the intended modelling task. Use representative anonymized samples for an initial compatibility review when authorized. Keep confidential field data within the agreed access arrangements, and ask the proposal to distinguish cleaning or conversion work from interpretation of the underlying measurements.",
    "Software environment": "List the applications and versions that create, process and receive the study data. State the required import and export formats and any exchange-standard version specified by the project. Support for a format family does not prove that every object or version needed by the workflow is handled. Ask for a compatibility statement against the actual source and destination applications and a representative exchange check. Identify computing, storage and deployment assumptions separately from software rights. Account credentials, activation files and unrestricted project databases are not required in a general enquiry; approved access is arranged through the owner's controlled project process.",
    "Deliverables and license scope": "Describe the outputs the owner must receive: source or edited datasets, model files, interpretation reports, assumptions, quality findings and any reproducibility records appropriate to the assignment. State which editable files are required and who will review the study. For software, identify edition, modules, user quantities, term, deployment and support coverage. For a service, define review stages, included revisions and the handover format independently of the license quotation. Ask how developed material and third-party data may be used after completion under the proposed agreement. Technical conclusions, usage rights and a successful file exchange are separate matters that require their own evidence."
  },
  "industrial-software-licensing-and-support": {
    "Product and version": "Identify the exact software product, edition, required modules and installed version. Include the workflow the team needs to perform, because a familiar product name can cover several editions with different functions. Separate a new license from an upgrade, renewal or additional module. State the versions of connected applications and the required file formats. Ask the proposal to identify the offered entitlement and compatibility assumptions; an upgrade right does not by itself establish that existing projects or integrations will work without testing.",
    "Users and license model": "Describe how the software will be used: individual workstations, shared engineering teams, servers or another approved deployment. State the number of intended users and any simultaneous-use requirement. Licensing metrics can differ between products, so ask which metric the proposal uses and how it applies to the requested deployment. Identify sites, devices or computing resources when they affect the terms. Keep the permitted use, term and quantity explicit rather than comparing quotations solely by an apparently similar seat count.",
    "Existing entitlements": "Provide a controlled inventory of existing editions, quantities, contract references and renewal dates, with confidential documents handled through the agreed review channel. Identify which rights are being retained, renewed or expanded. An installed application is not proof that every user, module or deployment is licensed. Ask for the documents that establish the offered usage rights and support coverage. Do not include passwords, activation codes, license files or account recovery details in a general enquiry. Uncertain entitlement records should be reconciled before relying on an upgrade or renewal proposal.",
    "Deployment and support requirements": "Explain whether the application will run on workstations, a local server, virtual infrastructure or an approved hosted environment. List compatibility and connectivity restrictions, including any offline operation needed. Backup, disaster recovery and test environments should be identified for review under the offered terms. Define support hours, contact arrangements, response expectations and covered versions separately from configuration or engineering work. Ask the proposal to state the dependencies and exclusions, including which installation, migration, training and integration services must be purchased separately."
  },
  "asset-data-monitoring-and-digital-integration": {
    "Asset and data sources": "List the assets and data sources to be included, with sample tag registers or anonymized examples where appropriate. Record signal names, units, timestamps, update frequency and available quality indicators. Distinguish live measurements, manually entered values, calculated signals and historical records. Identify who can explain the source and approve its interpretation. A project may need to reconcile duplicated asset identifiers or inconsistent units before connecting a dashboard; receiving a readable value does not prove that it describes the intended equipment or condition.",
    "Use case and deliverables": "Define the operational question the integration should answer and who will use the result. An asset register, condition dashboard, historian connection and maintenance-system interface have different deliverables. Specify the required views, reports, data exports and update behavior. Record whether the work includes cleaning historical data, configuring an application or developing an analytical model. Avoid treating a dashboard demonstration as evidence of validated fault prediction or a safety function. The acceptance scope should match the stated use case and the evidence available from the actual data.",
    "Existing platforms": "Identify the source and destination platforms, relevant versions, approved interfaces and any existing connectors. State which application owners will provide documentation and test access through their normal controls. Ask whether the proposed interface requires additional software rights, gateways, subscriptions or changes to the existing environment. Distinguish communication compatibility from agreement on the meaning of the data. Include retention and export requirements so the proposal can address storage, historical access and transfer to another approved system without assuming that every connector includes those capabilities.",
    "Security and data ownership": "State the owner's rules for permitted data use, access, hosting and retention. Define which party owns source records, transformed datasets, configurations and any developed models. Identify the approved arrangements for external personnel and for returning or removing project copies. Operational data can reveal sensitive plant information, so an initial enquiry should describe interfaces without sharing credentials or unrestricted system exports. Security review and authorization remain with the asset owner; purchasing a monitoring service does not authorize an unapproved connection to the control environment."
  },
  "automation-integration-and-commissioning": {
    "Existing architecture and versions": "Provide the approved architecture and a controlled inventory of controllers, I/O, operator interfaces and connected applications. Identify versions and the current configuration baseline through project records. Describe the modification and the parts of the system affected. A new module or software release may involve dependencies beyond its physical connection, so ask the technical response to identify compatibility assumptions. Keep the scope of configuration review explicit and use the owner's approved process for access; a general enquiry does not require passwords or a complete live-system backup.",
    "Functional requirements": "List the approved functions to be integrated and the documents that define them. These may include I/O schedules, operating descriptions, alarm requirements, interface registers and cause-and-effect documents. Identify which functions are already designed and which require a separately assigned engineering review. Control, monitoring and protective functions need their respective responsibilities stated clearly. The request should ask for implementation and verification against the approved basis, rather than invite an integrator to infer a safety design from a short equipment list or an undocumented existing program.",
    "Interfaces and migration window": "Describe each connection between the modified package and existing equipment, with signal types, communication requirements and responsible parties. Identify available work windows and restrictions imposed by operations. State which site preparations, hardware installation and application changes are provided by others. Ask for an agreed migration and recovery plan to be reviewed by the owner, including the conditions that require postponement or additional work. These are planning deliverables; the actual execution remains subject to the site's authorization and approved procedures.",
    "Testing and handover scope": "Define the tests and acceptance records required for the changed functions. Workshop demonstrations, interface tests, site checks and commissioning address different conditions, so identify the scope and responsible witnesses for each stage. Ask how requirements will be traced to test results and how unresolved findings will be recorded. Include drawings, configuration records, version information and operator or maintenance training where required. A successful software demonstration cannot establish that every field connection, device response and project operating case has been checked at the installation."
  },
  "industrial-networking-and-telecoms": {
    "Protocol and bandwidth": "State the applications and communication protocols the network must support, together with the required physical interfaces. Identify endpoint quantities, expected traffic and timing or availability constraints defined by the responsible design. Ethernet port counts alone do not describe protocol functions, management features or compatibility. For optical links, specify the approved fiber and transceiver interfaces; for radio links, identify the required technology and the applicable site frequency arrangements. Ask the response to distinguish supported features from additional licenses or equipment needed to enable them.",
    "Network topology": "Provide the approved network arrangement showing the role of each device and the interfaces with existing systems. Distinguish new equipment from replacements and identify any project redundancy or separation requirements. A ring, star or remote link description should be accompanied by the functions expected from the selected hardware. Configuration, addressing and security changes belong to the owner's controlled design and approval process. Request compatibility and implementation evidence without assuming that installing an additional switch automatically provides resilient or secure communication across the complete plant.",
    "Range and environment": "Describe installation locations, cable routes, link distances and the exposure conditions that affect the equipment choice. Radio enquiries need the available site survey and the intended locations of antennas or endpoints; an advertised range is not a verified result for every terrain or building arrangement. Optical and copper connections need their specified interface and route information. Identify outdoor, corrosive or classified-area requirements from project documents. Ask which installation, survey and testing services are included, and keep assumptions visible where the route or field conditions remain unconfirmed.",
    "Power and enclosure rating": "Specify the available power supply, mounting arrangement, cabinet conditions and required environmental ratings. Identify whether power accessories, backup supply or the enclosure are included in the equipment request. Devices within a cabinet and exposed field units can face different temperatures and protection requirements. Ask the offer to identify the exact assembly and supporting documentation for the required location. Power-over-network functions, grounding interfaces and surge-protection provisions should be reviewed as part of the approved design, rather than inferred from a general industrial product label."
  }
};

export const digitalTopicGuidance: Record<string, GuidanceSection[]> = {
  "reservoir-software-and-data-services": [
    { title: "Keep the data baseline separate from the interpretation", paragraphs: [
      "Start with a controlled input register so the reviewer can identify which records underlie each model or report. Mark missing coverage, uncertain units and revisions that have not been reconciled. Ask for changes made during preparation to be recorded rather than silently replacing the original inputs. This gives the owner a practical way to compare a returned dataset with the material supplied and to decide whether unresolved gaps need additional work.",
      "Set review stages for the study's assumptions and outputs. An interpretable model can still depend on limited data or choices that need project approval. Ask the proposal to explain how those limitations will be presented and who accepts them. Avoid treating the purchase of a recognised application, or a visually persuasive model, as confirmation of reservoir performance or a reserve estimate. Those conclusions belong to the defined technical study and its responsible reviewers."
    ] },
    { title: "Test the required model exchange rather than a format name", paragraphs: [
      "An exchange standard such as RESQML addresses earth and reservoir modelling data between applications. The enquiry should still name the required version, objects and receiving workflow. Ask which parts of the project model can be transferred and what is omitted or converted. Version-specific documentation and a representative sample are more useful than a general statement that an application supports an industry standard.",
      "Agree the checks for the exchanged result before work starts. Examples may include the expected geometry, property units, object identifiers and links to the supporting data relevant to the assignment. The buyer's technical team should determine which checks are appropriate; successful import alone does not demonstrate complete preservation of the intended model. Record warnings and unsupported content, and keep any approved simplifications visible in the delivered exchange report."
    ] },
    { title: "Make the final study usable beyond the initial demonstration", paragraphs: [
      "Specify the delivery folder structure, file formats, version register and explanatory notes needed for the owner's next workflow. Distinguish editable project files from read-only reports and exports. Identify continuing access or support dependencies and the terms governing reuse of developed material. Training or later model updates should be separately described when they are outside the initial assignment. Send the defined scope to Oillinko for manual review and coordination, with confidential datasets shared only through the agreed project channel."
    ] }
  ],
  "industrial-software-licensing-and-support": [
    { title: "Separate renewal from a new implementation", paragraphs: [
      "A renewal request should identify the coverage being continued and its dates. A new implementation needs a separate list of installation, configuration and acceptance tasks. Expanding the user population or moving the application to a different environment can introduce additional questions about permitted use and compatibility. Ask for those changes to be described individually in the proposal so the existing baseline is not lost inside a single renewal total.",
      "Compare proposals on the same period and scope. Record the product edition, modules, licensing metric, support coverage and any implementation work as separate items. Ask what happens at the end of the offered term and which charges or conditions apply to continuing the service. Do not assume that a subscription, maintenance renewal and perpetual license provide the same rights merely because their annual prices are similar."
    ] },
    { title: "Describe the assistance the team actually needs", paragraphs: [
      "Support can mean access to product assistance, update rights, application configuration or specialist help with an engineering workflow. Name the expected assistance and the responsible provider in the actual proposal. Identify whether requests are handled remotely, on site or through the software owner's service channel. Training and engineering deliverables should be listed separately when they go beyond the offered support arrangement.",
      "For a critical workflow, identify required versions and the planned test before changing the production environment. Ask for compatibility information and a defined implementation scope if these are needed. A support entitlement does not establish that a particular project model has been validated or that a software update can be installed during any work window. The application owner should approve the deployment and acceptance arrangements."
    ] },
    { title: "Keep an entitlement record at handover", paragraphs: [
      "Request a handover schedule identifying the delivered products, quantities, usage metrics, dates and support references. Reconcile it with the organization's entitlement inventory and the documents provided with the purchase. Keep protected activation information in the authorized licensing process. The purchasing record should allow a later renewal or audit to identify what was bought without publishing credentials or relying only on screenshots of a running application."
    ] }
  ],
  "asset-data-monitoring-and-digital-integration": [
    { title: "Agree the meaning of each exchanged value", paragraphs: [
      "An interface agreement should cover more than the ability to read a tag. Record units, naming, timestamps, status indicators and the asset to which each value belongs. A protocol can carry information while the two applications interpret it differently. Identify the approved data model and any mapping or conversion required, with examples that let the receiving team review the expected meaning before the full integration is commissioned.",
      "Keep lineage visible for calculated or transformed values. The deliverable should explain the source, transformation and update behavior, including how missing or invalid records are represented. Time zones and clock alignment matter when combining events from different systems. Agree the treatment of unavailable information rather than allowing a blank, zero or stale reading to be presented as a current measurement without context."
    ] },
    { title: "Use acceptance examples that expose data problems", paragraphs: [
      "Prepare representative cases for normal updates, missing records, changes in asset identifiers and interrupted connections. Define the expected output for each case and who approves it. Where historical data are migrated, agree reconciliation checks and the treatment of gaps. A visually complete dashboard can still contain duplicate assets, incorrect units or delayed values, so acceptance should examine the underlying records as well as the display.",
      "Assign responsibility for correcting source data separately from building the interface. Some discrepancies need an asset owner or instrument specialist to resolve them. Record known limitations in the handover and identify which use cases remain unsupported. The integration should not turn an unverified dataset into an apparent engineering conclusion merely by presenting it in a new application."
    ] },
    { title: "Identify who maintains the connection after delivery", paragraphs: [
      "Specify the owner of tag mappings, connectors, platform updates and ongoing monitoring. Ask for configuration records, export arrangements and instructions appropriate to the approved support scope. List licenses and recurring services needed after handover. If another team must maintain the integration, include the agreed training and documentation so a change to a source system can be assessed without losing the history or meaning of the data."
    ] }
  ],
  "automation-integration-and-commissioning": [
    { title: "Establish the limits of an integration package", paragraphs: [
      "Define the boundary between hardware supply, programming, system design and field execution. Identify who installs cables and instruments, supplies software entitlements and approves the functional documents. For a modification, explain how the existing system baseline will be recorded before the work. Include responsibilities for temporary facilities and coordination with operations when they affect the agreed scope or work window.",
      "Operational technology has reliability and safety constraints alongside information-security needs. The owner should review the proposed access, changes and test arrangements in that context. Ask for a project-specific plan rather than assume that a general office-system deployment process suits an operating plant. The procurement scope can request this review and its deliverables without prescribing unapproved changes to the installation."
    ] },
    { title: "Trace each required function to its acceptance evidence", paragraphs: [
      "Use a controlled requirement and test register to connect the approved functions with their verification records. Identify test prerequisites, the configuration examined and the person responsible for accepting the result. Record changes and retest requirements when findings are corrected. This helps the reviewer distinguish a function demonstrated in a workshop from one verified with the installed interfaces and equipment.",
      "Agree how incomplete tests and outstanding work will be recorded at handover. Separate technical acceptance, completion of documentation and readiness for the next project stage. Where an interface is supplied by another contractor, define who provides the simulation, field signal or witness needed for the test. A single statement that commissioning is complete can hide boundaries unless its scope and remaining limitations are explicit."
    ] },
    { title: "Deliver a configuration that the owner can maintain", paragraphs: [
      "Specify updated drawings, version records, approved configuration files and the relevant maintenance information as handover deliverables. Confirm ownership and permitted use of developed application material in the actual agreement. Include training and support periods when required. Backups and access information should pass through the owner's controlled process; a public catalogue enquiry should never be used to transfer a live control-system credential."
    ] }
  ],
  "industrial-networking-and-telecoms": [
    { title: "Count the accessories that make each link complete", paragraphs: [
      "A device schedule should distinguish installed ports from the links to be equipped at delivery. Identify transceivers, antennas, cables, connectors, mounting parts and power accessories as applicable. State which are existing and which must be supplied. Compatible-looking connectors do not establish a match for the complete link, so use the approved interface schedule and ask the offer to identify the exact included configuration.",
      "Keep spare requirements separate from operational quantities. A spare switch, optical module or radio may need a particular version or configuration to replace the installed item. State whether configuration and labeling are included before dispatch. Packing should identify the individual accessories so they can be checked against the link schedule rather than arriving as an undocumented collection of small parts."
    ] },
    { title: "Separate equipment features from licensed services", paragraphs: [
      "Management functions, remote services or software features may have commercial conditions beyond the hardware price. Ask the proposal to identify what is enabled at delivery, the applicable term and any recurring service needed for the requested function. Where no additional entitlement is required, ask for that boundary to be clear. Compare the offered capability and lifecycle support instead of assuming that similarly named devices include the same functions.",
      "A network device can include security features while still depending on correct system design, configuration and maintenance. Ask for the capabilities needed by the approved architecture, not a blanket promise of a secure plant network. Define the responsibility for updates, access administration and monitoring. Field installation and engineering support should appear separately when the purchase is for equipment only."
    ] },
    { title: "Require configuration and link-test records", paragraphs: [
      "Agree the verification records needed for the supplied links and devices, including the configuration baseline and identification of the equipment tested. Workshop checks and field link tests cover different conditions. Request the appropriate drawings, port or asset labels and handover records for the owner's maintenance team. Keep system access and configuration transfer within approved channels, and identify any link that could not be verified under the available site conditions."
    ] }
  ]
};
