type GuidanceSection = { title: string; paragraphs: string[] };

// Original requirement-specific copy, reviewed against the public primary
// sources recorded in docs/maintenance-content-2026-10-02.md.
export const maintenanceSpecificationGuidance: Record<string, Record<string, string>> = {
  "freight-expediting-and-project-logistics": {
    "Packing list and dimensions": "Provide a package-level packing list with gross and net weights, external dimensions and the number of pieces. Identify whether measurements are confirmed after packing or estimated from an equipment drawing. List handling restrictions, lifting points and any cargo that requires a separate review, with the relevant supporting documents. A pump's catalogue weight is not a reliable substitute for the weight of its packed skid and accessories. Ask the transport proposal to state which cargo information its price and routing assumptions depend on.",
    "Collection and delivery points": "Identify the actual collection premises and the intended delivery location, including access restrictions and the party receiving the cargo. A country or port name alone may leave inland movement, terminal handling and unloading outside the quoted scope. State the agreed delivery rule, named place and edition when these form part of the purchase. The freight request should then identify the services required between those points. Keep the manufacturing country separate from the collection location; cargo collected in one country may have been manufactured elsewhere.",
    "Required dates": "Separate the goods-ready date, latest collection date and required arrival date. Identify which dates are confirmed and which depend on fabrication, inspection release or document approval. Include the receiving site's working hours and any fixed project window. Ask whether the proposed transit period starts at collection, departure or another milestone, and how intermediate storage is treated. An equipment production estimate and a freight transit estimate describe different stages; neither should be presented as a confirmed door-to-door delivery commitment without reviewing the complete sequence.",
    "Handling and customs-document scope": "List loading, unloading, lifting, storage, insurance and document services individually, with the party responsible for each. Identify the commercial invoice, packing list and project-specific records available for review, while leaving customs classification and clearance to the authorized parties. Ask which terminal charges, inspection costs or local services are included and which remain provisional. Document support does not necessarily include acting as importer, exporter or customs representative. A complete logistics proposal should make these boundaries visible before its total is compared with another offer."
  },
  "welding-cutting-and-machining-tools": {
    "Process and material": "Describe the intended process and the material to be worked, with the approved production or repair requirement where available. Arc welding, plasma cutting, mechanical cutting and portable machining involve different equipment packages. Identify whether the enquiry is for a power source, a complete station or a specialist service. Ask for the offered equipment's documented process capabilities and limitations. Supplying a tool does not establish that a welding procedure, operator qualification or repair design has been approved for the particular component.",
    "Size range": "Give the workpiece dimensions and the required range of joints, cuts or machined features. For pipe preparation, distinguish outside diameter, wall thickness, access around the pipe and the specified end geometry. For machining, identify the drawing revision, tolerances and surface requirements that the proposed equipment must address. A nominal capacity in a brochure may describe only one configuration or condition. Ask the technical response to identify the accessories, workholding and setup assumptions needed to cover the actual range in the enquiry.",
    "Power and portability": "State the available electrical supply and any other utilities required by the proposed process, using confirmed site information. Identify whether the equipment will remain in a workshop or move between field locations, with weight, access and transport constraints. Ask for the input requirements, documented output characteristics and environmental limitations of the offered configuration. Portable equipment may still need supporting utilities and handling arrangements. Site authorization and safe work planning remain separate from purchasing an apparently suitable power source or machine.",
    "Consumables and accessories": "List the components needed for a complete working package, such as specified torches, cables, feeders, cutting tools, fixtures or process accessories. Identify consumables against the approved material and procedure requirements rather than a broad description such as welding wire. State initial quantities and the expected replacement demand. Ask what is included with the offered machine and which items are optional or supplied separately. Equivalent consumables and accessories require review for the actual process, equipment compatibility and project documentation."
  },
  "protective-coatings-and-insulation": {
    "Substrate and environment": "Identify the substrate material, existing surface condition and the exposure to be addressed. Separate outdoor atmospheric exposure, immersion, buried service and process contact when they occur on different parts of an assembly. For insulation, describe the thermal objective and the surrounding weather or washdown conditions. Supply the project's approved environmental classification or design basis where available. A generic marine or industrial label does not define a complete protective system; the proposed materials should be assessed against the actual substrate and exposure.",
    "Surface preparation": "Provide the preparation requirements from the approved coating or lining specification and identify the present condition of the surface. New fabrication, maintenance over an existing coating and removal of a damaged system involve different scopes. State whether material supply includes application, preparation or inspection services. Ask the proposal to identify the condition assumed at the start of work and any compatibility review needed for retained layers. The purchasing description should establish responsibilities and evidence, without substituting for the application's approved method and safety controls.",
    "Temperature range": "Describe the temperatures relevant to the coating or insulation system, including the project's operating cases and external conditions. Identify whether the requirement concerns the substrate, process fluid or surrounding air, and distinguish continuous exposure from temporary cases. Thermal insulation enquiries should state the intended performance requirement and the approved basis for assessing it. Ask for supporting product information applicable to the offered system. A material's advertised maximum temperature alone does not establish that a complete multilayer assembly will meet the project's protective or thermal objective.",
    "System thickness and specification": "Provide the complete approved system, including layers, specified thicknesses and the inspection or acceptance basis. Separate coating thickness from insulation thickness, and identify any cladding, sealing or attachment components included in the package. State the required area or quantity with its measurement basis, including how allowances will be handled. Ask the offer to identify substitutions and excluded components clearly. A price per litre, kilogram or square metre cannot be compared fairly when proposals use different systems or assume different preparation and application scopes."
  },
  "industrial-hoses-and-expansion-joints": {
    "Medium and temperature": "Identify the conveyed medium, concentration where relevant, and the temperatures applicable to the complete connection. Include cleaning media or other exposures that the approved design requires the assembly to tolerate. Hose liners, reinforcement, seals, joint materials and end connections can have different compatibility limits. Ask the technical response to identify the offered construction and the evidence supporting its intended duty. A broad chemical family or rubber description is insufficient to establish compatibility, particularly when the actual composition or operating conditions remain uncertain.",
    "Size and pressure": "State the required flow passage, nominal size and pressure conditions from the design documents. Distinguish the working conditions from any specified test or temporary operating case, with clear units and references. Request a rating for the complete assembly in the stated service rather than relying only on the hose material or one end fitting. Hoses and expansion joints perform different mechanical functions, so a matching size and pressure label does not make them interchangeable. Proposed alternatives should identify the conditions and limitations used in their assessment.",
    "End fittings": "Describe both mating interfaces using an approved drawing or precise dimensional reference. Record the connection type, material and required orientation, including any swivel, adaptor or accessory specified for the installation. Similar-looking threads or flanges may not provide the same interface. For a replacement, include the existing assembly reference and photographs as supporting identification, while marking uncertain dimensions for confirmation. Ask whether the offered connections and assembly method are included in the documented rating and inspection scope of the complete supplied item.",
    "Movement and length": "Provide the installation geometry and the movements defined by the responsible design. Identify the required hose length and how it is measured, or the expansion joint's installation length and specified movement directions. Include the relevant supports, access constraints and associated equipment interfaces for technical review. An expansion joint is not a substitute for an undefined piping movement analysis, and a longer hose is not automatically a suitable replacement. Ask the proposal to state which geometry and movement assumptions must be confirmed before the assembly is accepted."
  }
};

export const maintenanceTopicGuidance: Record<string, GuidanceSection[]> = {
  "freight-expediting-and-project-logistics": [
    { title: "Distinguish production progress from released cargo", paragraphs: [
      "Expediting reports should identify agreed milestones and the evidence behind each status. Material receipt, fabrication completion, inspection release and packing completion describe different events. Ask which documents or observations support the report and who can resolve an outstanding issue. A progress percentage without a defined basis may be less useful than a clear list of completed steps, dependencies and decisions affecting shipment.",
      "Keep the release-to-ship requirement explicit. Cargo can be physically ready while inspection records, payment conditions or export documents remain unresolved. The logistics schedule should identify these dependencies and the party responsible for clearing them. Oillinko can receive the requirement and coordinate clarification, but a catalogue service description does not establish that cargo has been released or that a transport booking is confirmed."
    ] },
    { title: "Compare freight quotations by their boundaries", paragraphs: [
      "Build a comparison using the same cargo details, route endpoints and requested services. Separate main carriage from collection, terminal handling, storage, delivery and unloading. Ask how the proposal treats changes in weight, dimensions or readiness dates. List assumptions about access and handling equipment so an apparently lower freight price is not accepted on a scope that omits a required stage of movement.",
      "Insurance arrangements need their own review, including the party arranging cover and the offered documents. A delivery rule can allocate particular responsibilities without resolving every issue in the purchase or service agreement. Record exclusions, additional charges and the conditions attached to the quotation. Keep these terms distinct from the cost of the goods, inspection services and other project expenses when preparing a purchasing comparison."
    ] },
    { title: "Maintain a traceable shipment handover", paragraphs: [
      "Agree the shipment references and records that connect each packed piece to the purchase and packing list. Request collection and delivery evidence appropriate to the scope, with a process for recording visible damage or discrepancies at receipt. Identify who receives documents and reports exceptions. When several equipment packages are consolidated, preserve their individual identification and document status so the receiving team can reconcile cargo without treating one transport reference as proof that every item is complete."
    ] }
  ],
  "welding-cutting-and-machining-tools": [
    { title: "Define the complete station around the main machine", paragraphs: [
      "An equipment list should distinguish the main machine from the supporting package. Depending on the specified process, this may include workholding, cables, cooling, extraction interfaces or other approved accessories. Identify what the workshop already provides and what must arrive with the purchase. Compare the offered configuration by these boundaries, rather than assuming that a power-source price includes every component needed for the intended work.",
      "Name the person or discipline responsible for reviewing process suitability. Equipment capability, procedure approval and personnel competence address different questions. Ask for the documents required by the purchase specification and the proposed training scope, if included. A machine demonstration may confirm particular functions while leaving the project procedure and the completed component's acceptance requirements to their assigned reviewers."
    ] },
    { title: "Use representative workpieces for acceptance", paragraphs: [
      "Define the agreed acceptance demonstration using a representative material, size and feature from the actual requirement. Record what the demonstration is intended to show, its setup assumptions and the result to be documented. For portable machining, dimensional access may be as important as the nominal capacity. The acceptance plan should explain which conditions are checked and which remain subject to a separate site or process assessment.",
      "Specify the documentation needed to maintain the offered equipment, including identification, manuals, required inspection records and the supplied accessory list. Ask for any product conformity evidence required for the destination and application. An equipment standard covering a welding power source does not certify an entire fabrication process or every tool in a mixed workshop package. The evidence should be matched to the actual item and purchasing requirement."
    ] },
    { title: "Plan the replenishment list before delivery", paragraphs: [
      "Record wear items and consumables using unambiguous descriptions and the offered equipment's compatible references. Separate routine replenishment from major spare assemblies, and state quantities and units. Ask which replacement items require configuration-specific selection. The handover should give the purchasing team enough information to request the correct item later, without treating a similar trade description as proof that a substitute will fit or perform the approved process."
    ] }
  ],
  "protective-coatings-and-insulation": [
    { title: "Purchase an identified system rather than a color", paragraphs: [
      "A coating request should identify the approved protective system and the parts of the asset to which it applies. Color may be one finish requirement, but it does not describe compatibility, layer sequence or the exposure basis. Ask for current product documentation for the proposed materials and a clear list of deviations. Maintenance enquiries should identify retained layers and the review required before a new system is applied over them.",
      "Keep thermal insulation and corrosion protection responsibilities distinct where both are required. An insulation package can include material, attachments, cladding, seals and removable sections around maintenance points. State which components are supplied and who reviews their interfaces with the coated substrate. The specification should address the complete assembly rather than assume that a suitable insulation material alone establishes a suitable protection package."
    ] },
    { title: "Separate material quantities from application work", paragraphs: [
      "Give the measured areas and geometry used for the enquiry, including equipment features that affect the scope. Ask how material quantities and allowances have been calculated and which assumptions remain provisional. If a service is included, identify access, preparation, containment and inspection responsibilities separately. Comparing only a unit material price can hide different area assumptions, excluded accessories or a service boundary that stops before the asset is ready for acceptance.",
      "Set out the required records for delivery and application. Material identification, batch information and storage requirements belong to the supplied products; preparation and application evidence belong to the assigned work scope. State which inspections require witnessing and who reviews deviations from the approved system. These requirements should follow the project documents and current product information, without applying a universal thickness or acceptance value to unrelated duties."
    ] },
    { title: "Check shelf life and storage against the work schedule", paragraphs: [
      "Ask for the offered material's shelf life, packaging and specified storage conditions, with the relevant dates available at delivery. Compare these with the expected application schedule and the site's storage arrangements. Identify whether part quantities or staged deliveries are needed. The handover should reconcile product and batch references with the approved system so remaining material can be reviewed for later use without relying only on a container's appearance or an earlier purchase description."
    ] }
  ],
  "industrial-hoses-and-expansion-joints": [
    { title: "Identify the flexible component's intended function", paragraphs: [
      "Start with the reason flexibility is required: equipment connection, transfer, vibration accommodation or movement identified by the design. Record the actual function and installation boundaries. Hose assemblies and expansion joints can differ in construction, loading and support needs. The technical request should allow the responsible reviewer to assess the proposed component in its system, rather than treat every flexible connection as a general-purpose interchangeable accessory.",
      "For a replacement, record the installed assembly and the reason it is being changed. A previous leak, damaged end connection or changed operating condition may require a fresh review rather than copying the former size and length. Mark missing identification and uncertain operating data explicitly. Ask for a proposed configuration with its assumptions stated, while leaving diagnosis and system design decisions with the assigned technical team."
    ] },
    { title: "Request evidence for the complete supplied assembly", paragraphs: [
      "Identify the required construction, inspection and test records for the actual service. Ask whether the quoted item is a finished assembly or material that still requires fabrication and verification. A certificate relating to a length of hose does not necessarily establish the documented condition of its fitted connections. Trace the offered assembly reference to the records required by the purchase specification, including any required identification marking.",
      "The governing document should match the component and application. Guidance written for hydraulic hose assemblies has a defined scope and should not be treated as a universal specification for every process hose or expansion joint. State the project's applicable requirements and request clarification where the offered evidence covers a different construction or duty. A technical exception should remain visible rather than being removed from the commercial comparison because the nominal dimensions agree."
    ] },
    { title: "Make the delivered length and configuration unambiguous", paragraphs: [
      "Use a drawing or agreed assembly schedule showing end references, orientation and the defined length measurement. Identify how the item will be protected and labelled for storage and receipt. Where several similar assemblies are ordered, give each a distinct reference linked to its intended location. The receiving record should reconcile those references and required documents before release for installation; a count of identical-looking pieces cannot confirm that every configuration matches its assigned interface."
    ] }
  ]
};
