import type { CatalogueGroup, CatalogueType } from "./catalogue";
import { coreOverviews } from "./catalogue-overviews-core";
import { processOverviews } from "./catalogue-overviews-process";
import { wellOverviews } from "./catalogue-overviews-wells";
import { operationsOverviews } from "./catalogue-overviews-operations";
import { specialistOverviews } from "./catalogue-overviews-specialist";
import { serviceOverviews } from "./catalogue-overviews-services";

export const topicOverviews = { ...coreOverviews, ...processOverviews, ...wellOverviews, ...operationsOverviews, ...specialistOverviews, ...serviceOverviews };
export type ContentSection = { title: string; paragraphs: string[] };

const guidance: [RegExp, string][] = [
 [/composition|fluid|medium|chemical|sample|contaminant|water matrix|feed|crude|analytes/i, "The properties of the handled or measured material affect compatibility and performance. A name such as oil, gas or water can cover very different compositions, temperatures and contamination levels. Use the available analysis or approved material specification to describe the actual duty. Identify expected variation and distinguish measured data from estimates. For replacements, record whether the medium or operating conditions have changed since the existing equipment was selected. These details help a reviewer assess a proposed material or configuration against the intended application."],
 [/flow|capacity|rate|duty|load|power|torque|force|throughput|heat|demand|autonomy/i, "Performance requirements should describe the intended operating cases rather than a single headline rating. State the units and distinguish normal demand from minimum, maximum and temporary conditions where they apply. Include the duration or frequency of intermittent duties, because a continuously operating assembly and an occasionally used one may need different configurations. Record which loads or consumers operate together. This provides a consistent basis for comparing proposals and helps identify whether an offer includes the full performance range required by the application."],
 [/pressure|temperature|depth|operating|envelope|ambient|climate/i, "Operating conditions establish the environment in which the selected equipment or service must perform. Distinguish routine conditions from the design limits stated in the project documentation, and include startup or shutdown cases where the responsible design requires them. Use explicit units and identify the measurement reference. For an existing installation, check current records rather than copying an old nameplate without review. A proposed configuration should be assessed against the complete documented envelope, with any exceptions made visible in the technical response."],
 [/drawing|dimension|geometry|size|diameter|stroke|length|layout|connection|mount|interface|schematic|bore|port|thread|nozzle|casing|tubing/i, "Physical interfaces determine whether an item can be integrated into the installation. Drawings should identify the relevant dimensions, mating connections, access limits and drawing revision. Nominal sizes do not always describe actual clearances or connection geometry, so include the governing dimensional reference where available. For replacements, photographs can help identify the assembly, but an approved drawing or exact part reference is preferable for critical interfaces. Record any installation constraints that could affect assembly, maintenance access or the scope of associated fittings and supports."],
 [/material|grade|coating|lining|insulation|corrosion|compound|hardness|cleanliness|finish/i, "Material selection relates to the complete service environment, including the process medium, temperature and external exposure. Give the specified grade or approved material system rather than relying on a general description such as stainless steel or rubber. Identify any project restrictions and required evidence of conformity. Replacement materials should be reviewed for compatibility with the existing assembly and the actual duty. Coatings, seals and other secondary materials can be as important as the main body material when assessing a proposed product."],
 [/signal|output|protocol|control|software|version|license|data|firmware|system architecture|network|communication|security/i, "Functional and digital interfaces determine how the requirement connects to the existing system. Identify the installed platform, relevant versions and required signals or data formats. Separate hardware compatibility from software entitlement and engineering work; an available connection does not establish that the complete function is included. Document ownership of configuration, integration and acceptance testing. Share interface requirements through appropriate project documents without disclosing passwords, activation keys or other account credentials. This makes the proposed scope easier to assess and reduces ambiguity during implementation."],
 [/model|manufacturer|serial|part number|oem|revision|existing|equipment details/i, "Identification is especially important when the request concerns an installed asset. Manufacturer, model, serial number and the exact part reference can distinguish assemblies that have similar names or dimensions. Include the drawing or bill-of-materials revision where available, together with a description of the component's function. If the original reference is incomplete, mark the uncertainty for technical review rather than treating a guessed match as confirmed. Alternatives should be evaluated against the required interfaces, materials and performance before they are accepted for the installation."],
 [/method|accuracy|uncertainty|measurement|range|detection|test|calibration|acceptance|qualification|inspection|standard|certif|approval|traceab/i, "The required evidence should relate to the actual purpose of the item or assignment. Identify the method, acceptance basis and documents required by the project, including the relevant edition or revision where specified. A certificate title alone may not establish that the required scope or measurement range is covered. Distinguish manufacturer records, calibration results, inspection reports and specialist qualifications. State whether witnessing or independent review is required, and make the responsibility for evaluating the results clear before comparing technical and commercial proposals."],
 [/site|location|access|vessel|workface|terrain|water depth|route|installation/i, "The work location and installation conditions affect access, equipment arrangement and the resources needed to complete the scope. Include known restrictions, available utilities and interfaces with existing operations. For a service, identify what the site provides and what the contractor must mobilize. For equipment, record space, handling and connection constraints that could affect installation or maintenance. If a survey is still required, distinguish confirmed information from assumptions so that the proposal can identify the conditions on which its price and programme depend."],
 [/deliverable|scope|responsib|programme|program|objective|design|plan|report|study|assessment/i, "A clear scope describes the intended result and the responsibilities of the parties involved. List the required deliverables and identify which design or operating decisions have already been made. Separate investigation, engineering, supply, installation and acceptance activities where they are different work packages. State the review process and the information that will be provided by the buyer or operator. This allows proposals to address the same work and makes omissions or additional services visible before a commitment is made."],
 [/date|schedule|duration|window|timing|rental|hours|cycle|experience|count|quantity|volume|packing|packaging|storage|handling|logistic/i, "Quantities, timing and handling requirements influence the practical scope of supply or service. State units clearly and distinguish complete assemblies, individual components and sets. Identify the required delivery or work date separately from the requested quotation date. Packaging, preservation, storage and site access may affect the proposed arrangement. For temporary services or rental, include the expected duration and define standby or extension assumptions. These details help compare the complete requirement rather than only a unit price or an estimated mobilization period."],
];

function specificationText(label: string, used: Set<string>): string {
  const matching = guidance.filter(([pattern]) => pattern.test(label));
  const text = matching.find(([,text])=>!used.has(text))?.[1];
  if (text) { used.add(text); return text; }
  const alternatives = [
    "The specification should establish a clear baseline for technical review. Record the required characteristics using the current design documents and identify any mandatory limits. If an input is provisional, label it as an assumption so the reviewer can explain its effect on the proposed solution. For existing assets, compare the current duty with the original design basis. Changes in conditions, interfaces or project requirements can mean that a previously accepted configuration needs a fresh compatibility assessment before it is purchased or used again.",
    "Document how this requirement connects to the rest of the installation or work package. A component may meet its own description while still needing additional equipment, a different interface or specialist integration to perform the intended function. Identify who will verify the proposed arrangement and which records are required for that review. Where a supplier suggests an alternative, its differences should be explained against the specified basis. This supports a technical comparison before commercial approval and makes the final scope easier to understand.",
    "Clarify the intended result and the evidence needed to establish that the requirement has been met. Different projects can use similar terminology for different levels of scope, so supporting drawings, schedules or method references are useful. Define what is supplied by the buyer and what is expected from the proposed provider. Include any relevant limitations in the initial information rather than leaving them to be discovered during delivery or mobilization. The resulting technical response should identify assumptions, exclusions and matters requiring project approval.",
  ];
  const fallback = alternatives.find(text=>!used.has(text));
  if (!fallback) throw new Error(`No distinct specification guidance for ${label}`);
  used.add(fallback); return fallback;
}

export function productSections(group: CatalogueGroup, item: CatalogueType): ContentSection[] {
  const overview = topicOverviews[item.id];
  if (!overview) throw new Error(`Missing product overview: ${item.id}`);
  const service = item.kind === "Service";
  const software = item.kind === "Software";
  const used = new Set<string>();
  const sections: ContentSection[] = [
    { title: `About ${item.name.toLowerCase()}`, paragraphs: [overview[0]] },
    { title: service ? "Where the service is used" : "Typical applications", paragraphs: [overview[1]] },
    { title: service ? "Service options and scope" : software ? "Licensing and deployment options" : "Types and configuration choices", paragraphs: [overview[2]] },
    ...item.requirements.map(label => ({ title: label, paragraphs: [specificationText(label, used)] })),
    { title: "How related requirements differ", paragraphs: group.types.filter(t => t.id !== item.id).slice(0, 3).map(t => `${t.name}: ${topicOverviews[t.id]?.[0] ?? t.description} ${topicOverviews[t.id]?.[2] ?? ""}`) },
    { title: service ? "Compare the complete service proposal" : software ? "Compare licensing and support terms" : "Compare the complete supply scope", paragraphs: [
      service
        ? `For ${item.name.toLowerCase()}, compare the stated work, personnel, equipment and deliverables before comparing the headline price. A proposal may exclude preparation, access equipment, consumables, standby time or completion documentation. Identify these boundaries in the same way for each offer. The project location and work window should be explicit, together with the required qualifications for the particular assignment. Oillinko receives the enquiry and coordinates clarification with you; the actual service arrangement and the suitability of the proposed specialist are reviewed for the project.`
        : software
          ? `For ${item.name.toLowerCase()}, compare the product edition, number of users, permitted deployment and support period. A license quotation may not include configuration, data migration, training or implementation services. Identify existing entitlements and the required renewal terms without sharing activation keys or account credentials. Software usage rights and support arrangements should be confirmed in the proposed license terms. Oillinko reviews the requirement and coordinates the enquiry; inclusion in the catalogue does not imply a software partnership or reseller appointment.`
          : `For ${item.name.toLowerCase()}, compare the complete assembly and documented scope of supply. An offer for a component may exclude the drive, controls, fittings, accessories or inspection services needed for the installation. List exclusions and proposed alternatives so each quotation can be assessed against the same requirement. Manufacturing origin, delivery location and the supplier's business address are separate facts. If a particular origin is required, request confirmation for the actual offered item and the supporting documentation specified by your project.`,
    ] },
    { title: "Questions before requesting a quotation", paragraphs: [
      `What information should be available first? Start with the intended application and the current technical specification for ${item.name.toLowerCase()}. In this category, the initial review includes ${item.requirements.map(r=>r.toLowerCase()).join(", ")}. Attach the relevant drawings or scope documents and identify any information still awaiting confirmation. This makes it possible to distinguish a preliminary enquiry from a fully defined purchasing or service requirement.`,
      service
        ? "Does a service listing confirm that a contractor is already appointed? No. The listing describes a scope that can be submitted to Oillinko for review. The proposed specialist, location coverage, qualifications, work boundaries and commercial terms are checked for the actual enquiry. Equipment rental, personnel and complete execution should not be assumed to be included together unless the proposal expressly states that scope."
        : software
          ? "Can a similar software name be treated as the same product? No. Edition, version, licensing model and permitted deployment can change the functionality or usage rights. An alternative should be evaluated against the required workflow and interfaces, with its commercial terms made explicit. Support and implementation responsibilities should be agreed separately where they are not included in the license proposal."
          : "Can an alternative be accepted on size or price alone? A proposed alternative needs review against the required function, materials, interfaces and documented performance. Similar dimensions or a familiar brand name do not establish compatibility. State which requirements are mandatory and where an equivalent may be considered. Availability, lead time and supporting documents are confirmed for the actual offer rather than assumed from this catalogue.",
    ] },
  ];
  return sections;
}
export function contentWordCount(sections: ContentSection[]) {
  return sections.flatMap(s => s.paragraphs).join(" ").split(/\s+/).filter(Boolean).length;
}
