type GuidanceSection = { title: string; paragraphs: string[] };

// Primary research and the limits of this procurement guidance are recorded in
// docs/filtration-content-2026-10-03.md. Selection requires application review.
export const filtrationSpecificationGuidance: Record<string, Record<string, string>> = {
  "filtration-and-coalescing": {
    "Medium and contaminants": "Describe the continuous process phase and the contamination to be removed separately. For a gas stream, distinguish solid particles, liquid aerosols and bulk liquid carryover; a single description such as dirty gas hides different duties. Include available composition, contaminant identity and loading information, with sampling dates and known uncertainty. For liquid filtration or liquid-liquid separation, identify the relevant fluid properties and phases. Do not transfer a gas coalescer performance claim to a different process simply because both products use replaceable cartridges.",
    "Flow and removal target": "Provide minimum, normal and maximum flow cases, identifying whether gas volumes are actual or referenced to stated standard conditions. Express the outlet target with units and a defined measurement basis. A particle size, capture percentage and downstream liquid concentration describe different aspects of performance and should not be compared as interchangeable ratings. Request the test method and conditions behind the proposed result, together with clean and service-condition pressure drop for the documented duty. Keep unverified inlet loading or flow assumptions visible in the offer.",
    "Pressure and temperature": "State operating pressure and temperature for each relevant flow case, then identify design limits separately. Include the allowable pressure loss across the complete assembly and distinguish it from an element-only figure. For gas duties, density and volumetric flow depend on the stated conditions; a capacity claim without its pressure and temperature basis is incomplete. Ask the proposal to identify its selection assumptions and applicable limits. The responsible project team should assess housing, element and seal suitability against the full process envelope.",
    "Element compatibility": "For replacements, provide the installed housing reference, element part number and drawing revision where available. Identify cartridge dimensions, end connections, seal arrangement, flow direction and the approved media requirements. Similar external dimensions do not establish equal removal performance or material compatibility. Ask an alternative proposal to show which interfaces and service conditions it has checked and which remain unresolved. Separate the initial element set, replacement sets, seals and installation accessories in the quoted quantity so a complete housing is not confused with a consumable-only offer."
  }
};

export const filtrationTopicGuidance: Record<string, GuidanceSection[]> = {
  "filtration-and-coalescing": [
    { title: "Separate the contaminant duty from the package boundary", paragraphs: [
      "Start the enquiry with the downstream function that needs protection and the available inlet analysis. A filter intended to retain solids and a coalescer intended to collect fine liquid droplets are not equivalent requirements. In gas coalescing service, captured droplets combine and drain from the gas stream; selection also depends on the assembly that accommodates that drainage. Identify existing upstream separation and known carryover events so the proposal can state whether additional preparation or separation is assumed. Avoid treating a cartridge specification as proof that the complete process package will meet its outlet objective.",
      "List the supply boundary explicitly: housing or vessel, internals, initial elements, differential-pressure indication, drainage interfaces, supports and documentation. Identify what the project already provides and what needs separate review. A quotation for replacement cartridges may exclude all housing and instrumentation work, whereas a skid proposal can include several treatment stages. Ask the offer to label these boundaries and its battery-limit connections. Access for element removal, existing orientation and available layout drawings belong in the enquiry because a technically suitable element may still require a different installation arrangement."
    ] },
    { title: "Compare removal evidence under stated service conditions", paragraphs: [
      "Use one comparison sheet for the required contaminant, inlet loading, flow cases, outlet objective and allowable pressure loss. Record each proposed performance claim with its test basis and the configuration to which it applies. A dry element pressure-drop result should not be presented as the pressure loss of a liquid-loaded coalescing assembly without supporting evidence. Request the applicable service-condition result and identify whether housing losses are included. Likewise, an efficiency figure measured for a particular challenge material does not independently establish the same outlet quality for an uncharacterized process mixture.",
      "Ask the technical response to explain coverage of the specified operating range and any limitations associated with liquid loading or the installed arrangement. Coalescer sizing considers flow through the media and space for separated liquid to disengage and drain; selecting only by nozzle diameter can miss these constraints. Keep the response at the level of documented application assessment, rather than prescribe a generic sizing factor. If the offer relies on estimated data, identify what must be confirmed before selection and which quoted performance statements remain conditional. No universal removal rating or operating limit is established by this catalogue page."
    ] },
    { title: "Make replacement and handover assumptions traceable", paragraphs: [
      "For an installed housing, compare the proposed cartridge against the controlled reference rather than only a photograph or nominal length. Request a compatibility statement covering the identified interfaces, media, seals and documented service. Keep any substituted material or changed performance basis in the deviation register for project review. A statement that an element fits is narrower than confirmation that it meets the process requirement. Where the original reference cannot be established, record the identification task separately and avoid accepting an undocumented interchange as a verified equivalent.",
      "At handover, reconcile the approved element references and quantities with the delivered assembly, drawings and technical documents. Request the applicable inspection and material records for the actual supply scope, distinguishing vessel documentation from consumable information. Identify the proposed replacement reference and any storage or handling information supplied with it. Ask the offer to state lead time, manufacturing country and commercial exclusions without assuming stock or a guaranteed service life. Inspection findings, sampling results and maintenance history can support later review, but element-change criteria and work on a pressurized assembly must follow the owner's approved arrangements and the applicable product documentation."
    ] }
  ]
};
