import { blogPosts, postUrl } from "./blog";
import { catalogue, typeUrl } from "./catalogue";
import type { ContentSection } from "./catalogue-content";

// Research scope and source limitations: docs/engineered-equipment-content-2026-10-04.md.
function articleLink(slug: string, label: string) {
  const post = blogPosts.find(post => post.slug === slug);
  if (!post) throw new Error(`Missing related article: ${slug}`);
  return { label, href: postUrl(post) };
}
function equipmentLink(id: string, label: string) {
  const group = catalogue.find(group => group.types.some(item => item.id === id));
  const item = group?.types.find(item => item.id === id);
  if (!group || !item) throw new Error(`Missing related equipment: ${id}`);
  return { label, href: typeUrl(group, item) };
}

export const engineeredEquipmentSpecificationGuidance: Record<string, Record<string, string>> = {
  "reciprocating-compressors": {
    "Gas analysis": "Provide the gas composition and its measurement basis, including the sampling date, units and expected variation between operating cases. Identify water, liquids, particles and constituents requiring a materials or emissions review. A description such as natural gas is insufficient for a package selection. Separate measured values from assumed values and explain whether an upstream treatment package forms part of the enquiry. Request a documented application review for the offered configuration; a previous selection for a similar stream does not establish suitability for this gas.",
    "Stage pressures and temperatures": "Identify suction and required delivery pressure for each operating case, stating whether pressure is absolute or gauge. Give inlet temperature and available cooling conditions alongside the gas analysis. Distinguish the process requirement from the proposed number of stages and the resulting interstage conditions, which should be explained in the technical offer. Keep design limits separate from normal operation. Ask for a case-by-case performance schedule with assumptions, limitations and the package boundary used in the calculation, rather than comparing a single discharge pressure printed in a brochure.",
    "Capacity and duty cycle": "State gas flow with units and its reference conditions; a standard volume and an actual inlet volume are different quantities. Describe normal, minimum, maximum and future cases, including which cases occur together and the expected hours of service. Identify the required capacity-control range and the site's electrical or driver constraints without prescribing an unreviewed control method. Request power and performance information for the same cases from every bidder. Keep continuous duty, standby provision and intermittent operation separate in the enquiry so an attractive rated capacity does not conceal a different service basis.",
    "Cylinder and packing requirements": "Record process cleanliness limits, permitted lubricant carryover, service constituents and project restrictions affecting cylinders, seals and rod packing. For an existing machine, supply its cylinder, packing and drawing references as well as the frame identity. Ask the technical proposal to describe the selected arrangement, required cooling and vent interfaces, and the application assumptions behind it. A non-lubricated cylinder description does not automatically describe every lubrication system in a complete package. Material and sealing compatibility remain matters for documented application review, with alternatives and unresolved inputs clearly identified."
  },
  "shell-and-tube-heat-exchangers": {
    "Heat duty and temperatures": "Provide paired hot-side and cold-side cases, with inlet temperatures, required outlet conditions and heat duty where established by the process design. State whether each fluid stays in one phase or includes boiling, condensation or another phase change. Distinguish an agreed process requirement from a preliminary estimate, and identify which values the thermal designer may calculate. Describe seasonal utility temperatures and relevant operating variation. Ask bidders to state their thermal basis and exceptions explicitly; quoting a heat-transfer area without the conditions used to select it does not establish the requested duty.",
    "Flow on both sides": "Give the mass or volumetric flow on each side with units, reference conditions and the fluid property information used by the process designer. Include composition and phase information where they affect the calculation. Pair the flows with their respective temperatures and pressures instead of assembling unrelated maxima into a fictional operating case. Identify minimum and maximum duties, startup cases requiring evaluation and any proposed future capacity. If a flow or property is uncertain, show its source and status so the proposal can identify what remains provisional.",
    "Allowable pressure drop": "Specify the allowable pressure loss separately for the shell side and tube side, and define the boundaries of those allowances. Clarify whether connecting pipework or other equipment is outside the exchanger calculation. Request calculated pressure drops at the same operating cases used for thermal selection, together with the assumptions behind them. A larger heat-transfer surface is not automatically an acceptable solution if the hydraulic limits, available space or maintenance arrangement differ. Keep a bidder's proposed allowance separate from the limit approved by the process team.",
    "Tube and shell materials": "Identify the specified material grades for tubes, shell, channels, tubesheets and other relevant wetted parts, along with gaskets and any approved corrosion allowance or lining. Provide fluid composition and relevant external exposure for materials review. An expression such as stainless steel does not define every component of an exchanger. Request the offered material schedule, traceability requirements and any substitutions against the enquiry. The material certificate requirement and its acceptance process should be explicit, with unresolved compatibility questions retained for the responsible project team."
  }
};

export const engineeredEquipmentSupplyGuidance: Record<string, string> = {
  "reciprocating-compressors": "For reciprocating compressors, distinguish an assembly quotation from a complete gas compression package. Compare the driver, cooling, process auxiliaries, controls, engineering studies and agreed tests using the same boundary. Identify field connections, utilities and commissioning work supplied by others. Request a list of departures from the case schedule and scope matrix, with their effect on the proposed selection. Keep manufacturing origin, dispatch location and delivery terms as separate entries. A preliminary assembly price should remain visibly preliminary until the required interfaces and included work have been reviewed.",
  "shell-and-tube-heat-exchangers": "For shell-and-tube heat exchangers, compare complete exchanger supply separately from a bundle-only replacement. Identify channels, covers, supports, connections, insulation or other specified accessories, inspection activities and the final document package as included or excluded. For retained equipment, define responsibility for checking its condition and interfaces. Compare the offered thermal and hydraulic cases against the same datasheet revision, with deviations clearly listed. Manufacturing origin and dispatch location are separate from the named delivery point. Do not treat two prices as comparable until their equipment boundaries and evidence requirements are aligned."
};

export const engineeredEquipmentTopicGuidance: Record<string, ContentSection[]> = {
  "reciprocating-compressors": [
    { title: "What should a reciprocating compressor RFQ contain?", paragraphs: [
      "A useful reciprocating compressor RFQ combines a gas analysis, a schedule of operating cases and a defined package boundary. Begin with the intended service: for example, an existing gathering installation, a process compression duty or a replacement package. Explain the result the plant needs rather than choosing a frame solely from a headline power rating. Give each duty case a reference that can also appear in the supplier's performance schedule. Record who owns the process data, who will review the proposed selection and which inputs are still awaiting confirmation. This creates an enquiry that can be revised without losing the basis on which the initial quotation was prepared.",
      "Separate requirements into process, mechanical, electrical, control and documentation schedules where the project already uses those disciplines. A first enquiry can be preliminary, but it should say so and list the missing inputs. Request the calculation basis, equipment arrangement and deviations with the commercial response. For a replacement, include the installed equipment references, current operating conditions and the reason for replacement. Photographs are useful for identification and access planning; they should not substitute for a reviewed interface drawing. A concise cover note plus controlled attachments is easier to compare than specifications scattered across emails with conflicting revisions."
    ] },
    { title: "How do operating cases affect package selection?", paragraphs: [
      "Compare proposals using a common case schedule. The schedule should pair gas flow, composition, suction conditions and required delivery conditions for each real operating state. Label normal duty, minimum throughput, peak demand and any future case that is genuinely required. Do not combine the highest flow from one case with the lowest suction pressure from another unless the process team intends that combination to be evaluated. Ask the bidder to identify the proposed configuration and power demand for each case, together with any case it cannot cover. This makes a limitation visible before it becomes a disagreement over a nominal capacity figure.",
      "An illustrative comparison is two proposals that both state the requested maximum flow. One evaluates that flow at the normal suction condition, while the other evaluates it at the specified low-suction case. Their headline capacities look comparable, but their calculation bases differ. Resolve the case mismatch before considering the price difference. Require the technical review to address the offered machine's loading and operating limits, and retain the supporting application calculation with the proposal. A purchasing comparison should not attempt to establish those limits through a generic online formula or turn an unverified sales statement into a project performance guarantee."
    ] },
    { title: "Which auxiliaries belong in the compressor package?", paragraphs: [
      "Define the boundary between the compressor assembly and the complete compression package. Ask the quotation to identify the driver, coupling, base or skid, cooling arrangements, lubrication systems, instrumentation, controls and required process auxiliaries as included, excluded or supplied by others. Describe the interface with upstream gas conditioning and downstream equipment. If separators, interstage coolers, pulsation-control equipment or associated piping are required by the package design, make their design and supply responsibilities explicit. The enquiry should also identify who prepares the relevant engineering studies and who approves their findings. A list of component names alone does not establish an integrated package scope.",
      "Site information should include the available utilities, location conditions, electrical requirements, space limits and the project documents governing installation interfaces. Ask for a general arrangement drawing showing connection locations and the access needed for maintenance and component removal. Separate shop assembly from field assembly, commissioning support and any site acceptance work. These boundaries are particularly useful when one offer includes a skid while another includes only the compressor assembly. Record the agreed responsibility matrix with the selected proposal so later accessories are assessed against a documented boundary rather than assumed to be free additions."
    ] },
    { title: "How should lubrication and gas cleanliness be specified?", paragraphs: [
      "Describe the permitted process contamination and the downstream equipment's cleanliness requirements before comparing lubricated and non-lubricated cylinder arrangements. Ask which parts of the offered package use lubricant and what carryover assumptions underlie the proposal. Gas composition, contamination and operating conditions require an application-specific lubrication review. Do not select lubricant type or quantity from a general procurement guide. State whether any downstream oil-removal scope is included and which party must demonstrate the required outlet quality. If a bidder uses an expression such as oil-free, request a precise explanation of the package boundary and the conditions to which the statement applies.",
      "For a replacement or modification, distinguish the historic gas basis from today's measured composition and duty. Provide records of changed service conditions to the responsible reviewer, together with the installed cylinder and packing references where available. Ask for any resulting changes in materials, cooling, vent interfaces or auxiliary requirements to be listed as part of the offer. This review also helps distinguish an equivalent replacement from a proposed reconfiguration. Treat recommendations affecting operation as controlled technical deliverables requiring the appropriate approval; the quotation exercise should collect the evidence and responsibilities rather than instruct site personnel to alter lubrication or protective settings."
    ] },
    { title: "Which inspections and documents should be requested?", paragraphs: [
      "Request a project-specific inspection and documentation schedule with the proposal. Identify the technical datasheet, performance calculations, general arrangement, utility requirements, material records, electrical and control documents, manuals and the agreed test reports. Where a project standard applies, state its required edition and scope in the enquiry and ask for a clear compliance or deviation response. Separate a component certificate from evidence covering the complete assembled package. An organizational certificate, a catalogue statement and a witnessed package test are different records; the purchasing file should show which evidence actually supports each acceptance requirement.",
      "Agree the proposed shop tests and acceptance criteria before comparing claims about a tested package. Identify the test boundary, medium or method, conditions, measurements, witnessing arrangements and report deliverables through the approved test plan. Record what must be checked at site and who supplies the resources for it. For replacements, link the documentation to the exact equipment identity and drawing revision. Request a final document index and explain which records are needed before dispatch or acceptance. This keeps reviewable deliverables separate from an unspecific promise that certificates will be supplied later."
    ] },
    { title: "How can buyers compare compressor quotations fairly?", paragraphs: [
      "Build the comparison around the same case schedule and scope matrix. For each offer, record the selected arrangement, covered duties, driver and auxiliary scope, interfaces, required evidence, deviations and information still needed from the buyer. Keep technical acceptance separate from the commercial comparison. Record the currency, price basis, named delivery location, quotation validity, proposed lead time and the event from which that lead time starts. Manufacturing origin means the country in which the offered equipment is manufactured; it is not established by the quotation sender's address. Request origin information at the appropriate assembly or component level where the project requires it.",
      "A lower assembly price may require separate purchases or engineering work to produce the same package boundary. Show those gaps explicitly instead of inventing an estimated complete price. Likewise, distinguish a budget quotation from an offer with reviewed process inputs and an agreed scope. Submit your datasheet and case schedule to Oillinko for manual review and clarification; this page does not establish stock, an appointed manufacturer or an accepted design. The related equipment and inspection guides below help define connected scopes without treating those items as automatically included in a compressor offer."
    ], links: [equipmentLink("shell-and-tube-heat-exchangers", "Specify cooling equipment using paired thermal and hydraulic cases"), articleLink("inspection-test-plans-hold-vs-witness-points", "Define inspection hold points and witness points in the package test plan")] }
  ],
  "shell-and-tube-heat-exchangers": [
    { title: "What should a shell-and-tube heat exchanger RFQ contain?", paragraphs: [
      "A shell-and-tube heat exchanger RFQ needs a thermal duty schedule, separate hydraulic limits for both sides and a mechanical design basis. Identify whether the purchase is a new exchanger, a complete replacement or a replacement bundle. These are different scopes even when they refer to the same plant tag. Provide the fluid identities and paired operating cases, then describe the required materials, interfaces, inspection and documentation. Mark unresolved process data as provisional. The thermal proposal should explain how it addresses the stated cases; a drawing that fits the available space is not by itself evidence that the exchanger will meet the process requirement.",
      "For an installed exchanger, include the current datasheet, nameplate information, general arrangement and relevant drawings with their revisions. Explain whether the process duty has changed and whether the existing equipment suffered a service problem that needs investigation. Keep the replacement boundary explicit: a new bundle inside the retained shell has different interface and condition questions from a completely new vessel assembly. If the first RFQ is for budgeting, request a list of assumptions and the information required to firm up the proposal. That makes the next revision a controlled improvement rather than an unexplained change in specification or price."
    ] },
    { title: "Why must thermal duty and pressure drop be reviewed together?", paragraphs: [
      "The required heat transfer and the available pressure-drop allowances belong in the same comparison. Ask each bidder for a case schedule identifying the inlet and outlet conditions, flows, stated duty and calculated pressure drop on both sides. Specify the agreed basis for fouling and any margin through the project design documents, and ask the proposal to distinguish clean and specified service conditions where relevant. Do not treat an added surface area, a fouling assumption and a performance margin as interchangeable quantities. A bare statement of area cannot show whether a proposal meets the required outlets within the hydraulic limits.",
      "An illustrative comparison is two offers for the same stated duty. One uses the buyer's summer cooling-water condition; the other assumes colder water and provides no summer case. Resolve that difference before deciding that one smaller unit is the better purchase. Similarly, keep the shell-side allowance separate from the tube-side allowance and make the calculation boundaries clear. Ask the responsible thermal reviewer to assess the offered cases and exceptions. The buyer's role in the RFQ is to supply consistent inputs and obtain comparable results, rather than infer a design from a general sizing rule or accept a calculation whose assumptions remain hidden."
    ] },
    { title: "How do mechanical arrangement and maintenance access affect selection?", paragraphs: [
      "The exchanger arrangement determines interfaces and the access required for inspection, cleaning and replacement. Request a general arrangement with nozzle locations, supports, overall dimensions and the spaces required by the proposed maintenance approach. State restrictions on bundle removal, channel access, lifting and installation orientation where they are known. Ask the proposal to identify the offered construction and how it addresses the project's access constraints. A removable part may still need a clear withdrawal path and handling resources; its name alone does not demonstrate that the installed location can accommodate the planned work.",
      "For a replacement, compare mating connections, support positions and retained interfaces against the approved drawings. Record differences requiring changes to pipework, supports or insulation as part of the scope review. Distinguish design information provided by the buyer from a survey or verification service that is being requested. Photographs can help explain a restricted location, but critical geometry needs a documented dimensional basis. If access information is incomplete, ask bidders to identify their assumptions rather than declare the replacement interchangeable. The final purchasing comparison should include the agreed interface drawings and the work excluded from supply."
    ] },
    { title: "What do TEMA class and pressure-vessel code requirements establish?", paragraphs: [
      "TEMA class and a pressure-vessel construction code describe different aspects of the specification. The public TEMA guidance distinguishes Class R for severe petroleum duties, Class B for chemical process duties and Class C for general commercial duties. A class designation should come from the project's requirements and does not establish an individual exchanger's suitability by itself. State the applicable class and edition explicitly and request deviations against that basis. TEMA now uses a year-based edition designation; confirm the edition required by the project instead of assuming that a previous numbered edition is the current purchasing basis.",
      "Where ASME Section VIII or another construction code is required, identify the applicable division, edition, certification requirements and governing project or jurisdictional basis. The public ASME description addresses pressure-vessel construction, inspection, testing and certification; it is not a thermal performance guarantee. Ask the offered scope to distinguish construction-code requirements from thermal acceptance, materials restrictions and any additional project specifications. Do not infer an authorized certification or an acceptable completed vessel from the presence of a standard's name in a sales description. The responsible reviewer should confirm the required evidence and any proposed exceptions before technical acceptance."
    ] },
    { title: "Which material and inspection records should accompany the offer?", paragraphs: [
      "Request a component material schedule and a proposed inspection and test plan alongside the technical response. The schedule should identify the specified and offered materials for the relevant pressure-retaining and wetted components, as well as seals, linings or other specified systems. Define material certificate and traceability requirements through the enquiry. Record alternatives as deviations rather than replacing the original specification silently. A certificate for one tube batch does not identify every material in the completed exchanger; the documentation should connect the required records to the actual component and equipment references.",
      "Agree the required fabrication inspections, tests, acceptance references, witness or hold points and final reports in the project plan. Separate the purpose of a mechanical pressure test from the evidence needed for a thermal guarantee. Identify any third-party review, special cleaning or preservation requirements and ask whether those activities are included in the quotation. Request the final drawing and document index, including the records required at dispatch and those required for handover. Do not assume a catalogue listing establishes a particular test, certificate or manufacturing capability. Those facts must be confirmed for the equipment and scope actually offered."
    ] },
    { title: "How can buyers compare complete exchanger offers?", paragraphs: [
      "Compare the same equipment boundary, thermal cases, hydraulic limits, material schedule and mechanical requirements before comparing price. Record offered construction, maintenance access, design and test responsibilities, documentation, spare parts and deviations in a common matrix. Keep the proposed lead time tied to a stated starting event, such as approved drawings or another agreed milestone, without assuming those events have already occurred. Identify currency, delivery terms, named delivery location, packaging and quotation validity. Manufacturing country, dispatch location and the supplier's registered address are separate facts; ask for the origin evidence required by the project rather than treating them as interchangeable.",
      "If one offer excludes engineering, a retained-shell condition assessment or installation changes, show those boundaries clearly. Avoid declaring a complete replacement and a bundle-only quotation commercially equivalent. Send the current datasheet, case schedule and interface drawings to Oillinko for manual review; availability, design suitability and commercial terms require confirmation for the actual enquiry. For further detail, use the bundle guide when retaining the existing shell, the pressure-vessel records guide when identifying an installed unit, and the compressor page when the cooling equipment is part of a compression package. These connected requirements can be coordinated without assuming that every item is supplied together."
    ], links: [articleLink("replacement-heat-exchanger-tube-bundles-rfq", "Prepare a replacement tube-bundle RFQ for an existing exchanger"), articleLink("pressure-vessel-nameplates-data-reports-replacement-rfq", "Identify installed pressure equipment using nameplates and data reports"), equipmentLink("reciprocating-compressors", "Define the cooling and auxiliary boundary of a reciprocating compressor package")] }
  ]
};
