import { blogPosts, postUrl } from "./blog";
import { catalogue, typeUrl } from "./catalogue";
import type { ContentSection } from "./catalogue-content";

// Research scope and source limitations: docs/engineered-equipment-content-2026-10-04.md.
function articleLink(slug: string, label: string) {
  const post = blogPosts.find(post => post.slug === slug);
  if (!post) throw new Error(`Missing related article: ${slug}`);
  return { label, href: postUrl(post) };
}
function equipmentLink(id: string, label: string) {
  const group = catalogue.find(group => group.types.some(item => item.id === id));
  const item = group?.types.find(item => item.id === id);
  if (!group || !item) throw new Error(`Missing related equipment: ${id}`);
  return { label, href: typeUrl(group, item) };
}

export const engineeredEquipmentSpecificationGuidance: Record<string, Record<string, string>> = {
  "safety-and-relief-valves": {
  "Set pressure": "Provide the set pressure from the approved relief specification, with its units and pressure reference. Keep the equipment operating pressure, design information and proposed valve setting in separate fields so a bidder does not have to infer which value governs the enquiry. Include the protected equipment tag and the revision of the relief data sheet. For a replacement, supply a readable nameplate photograph alongside the current approved record and identify any discrepancy for engineering review. This purchasing information does not authorize a change to the installed setting.",
  "Relieving medium and capacity basis": "Identify the relieving case and required capacity established by the responsible design team. State the fluid, phase, relevant composition, relieving temperature and the units and reference conditions used for flow. Keep each case together rather than combining a flow from one scenario with a temperature from another. Ask the technical proposal to identify the sizing basis and offered configuration against the supplied cases. An inlet connection size or an old model number cannot substitute for the relief duty. Where the calculation remains incomplete, describe the quotation as preliminary and identify the missing design input.",
  "Back pressure": "Provide the outlet-system information and back-pressure cases from the approved relief study, including any distinction between pressure already present and pressure developing during discharge. State the destination of the discharge connection and supply relevant interface drawings. Ask the bidder to explain the assumptions used for its offered valve construction and any limitations requiring further review. Do not infer an allowable back pressure from a generic product-family description. Changes to a shared discharge system or an existing installation should be referred to the responsible engineer before a replacement is treated as equivalent.",
  "Required certification": "List the code, jurisdictional and project documentation requirements that apply to the purchase. Ask for identification of the offered device and the evidence supporting each required certification or capacity claim. A general company certificate, product brochure and record for the actual supplied valve serve different purposes. The quotation should state which material, test and identification records are included and which require a separate request. Match the proposed documentation to the specified service and configuration; a familiar certification mark alone does not complete the application review."
},
  "o-rings-and-packing": {
  "Dimensions or part number": "Separate an O-ring enquiry from a packing-set enquiry even when both appear on the same maintenance list. For an O-ring, provide the approved part reference or drawing, nominal inside diameter and cross-section, dimensional units and required tolerance basis. For packing, identify the shaft or stem and stuffing-box dimensions from the approved equipment record, together with the specified ring or set arrangement. A photograph is useful for orientation but should not become the controlling dimensional specification. Mark measurements from removed parts as observations for review.",
  "Compound or packing material": "Request identification of the actual offered compound or packing construction, rather than only a broad material family. For an elastomer seal, retain the specified compound reference and hardness where available and ask how any proposed substitute differs. For packing, identify the specified material, construction and complete set contents. Keep an original part quotation separate from a proposed alternative. Neither a matching colour nor a similar catalogue description establishes that the replacement meets the approved requirement.",
  "Service conditions": "Describe the medium, relevant composition and the normal and exceptional pressure and temperature cases known to the project. State whether the sealing interface is stationary, rotating or reciprocating and provide applicable movement or speed information for technical selection. Include cleaning or flushing exposure when it forms part of the approved service description. Ask the supplier to identify the conditions used in its assessment and any unanswered inputs. The enquiry should support specialist selection without turning preliminary service data into a seal rating.",
  "Equipment model": "Connect every seal line to the relevant equipment tag, assembly drawing and parts-list revision. Identify whether the request concerns one loose component, a matched packing set or a maintenance kit covering several sealing positions. If equipment has been modified, provide the current approved configuration instead of relying only on the original model. Ask the offer to map its references to the requested positions, quantities and revisions, and to identify omitted kit items explicitly."
},
  "cooling-towers-and-utility-air-dryers": {
  "Utility medium and duty": "Identify whether the enquiry covers cooling-water heat rejection, compressed-air moisture removal or two separately tagged packages. For a cooling tower, describe the connected water circuit and list the required operating cases. For a dryer, identify the air users, demand profile and required outlet air-quality specification. Mark existing equipment that remains within the installation. A shared purchase schedule can contain both packages, but each needs its own duty sheet, supply boundary and technical acceptance record. Do not compare a tower capacity with a dryer flow rating.",
  "Inlet and target conditions": "For the tower, supply water flow, entering and required leaving water temperatures, and the design entering-air wet-bulb condition. Keep all values tied to the same case. For the dryer, state airflow with reference conditions, inlet temperature, pressure and required pressure dew point at that pressure. Include the relevant ambient conditions. Ask the bidder to identify the rating basis and confirm the offered performance at the specified conditions. A nominal catalogue capacity does not establish performance for a different inlet or ambient case.",
  "Available utilities": "Provide the available electrical supply and identify other utility connections included in the enquiry. Ask tower bidders to state the proposed fan-drive scope and the water-system interfaces requiring separate provision. Ask dryer bidders to identify power, regeneration-air or other utility requirements for their offered technology. Have each proposal separate equipment consumption from auxiliary loads excluded from supply. Use the same project operating cases when requesting these figures. Record the source and status of estimated utility data so commercial comparisons do not present assumptions as confirmed site capacity.",
  "Space and environmental limits": "Include a dimensioned installation layout, connection locations, access route and maintenance clearances. For a tower, identify surrounding structures and the available air paths for specialist review; also state applicable site noise and environmental requirements. For a dryer, describe the installation environment and the space available for filter, desiccant or refrigeration-system service as applicable. Request an offered layout showing the actual service envelope. For replacements, list the supports, connections and control interfaces that must remain, and record any proposed change as a deviation rather than assuming a matching footprint proves compatibility."
},
  "plate-exchangers-and-air-coolers": {
  "Thermal duty": "Identify the process heat load together with the inlet and required outlet conditions used to establish it. For a plate exchanger, provide the paired flow and temperature data for both streams and the allowable pressure loss on each side. For an air cooler, include the approved inlet-air design condition with the process case. Separate normal, peak and minimum cases, and ask the bidder to show which cases the proposed unit covers. A heat-duty number alone does not establish the available cooling conditions or the required equipment arrangement.",
  "Fluids and design conditions": "Provide composition, phase and relevant properties for each process stream, identifying uncertainty, solids and known fouling concerns. Distinguish operating pressures and temperatures from the project design limits. Request the material and sealing schedule for the offered construction rather than assuming one metal grade defines the whole assembly. For plate units, include the proposed gasket compound where applicable. For air coolers, distinguish process-side materials from fins and external protection. Keep suitability decisions subject to the actual service and responsible technical review.",
  "Space limits": "Supply a dimensioned layout showing connections, supports, access routes and the equipment removal boundary. A plate exchanger enquiry should allow the bidder to state the space required for opening the frame and handling plates, where that construction applies. An air cooler enquiry should identify the available arrangement and surrounding obstructions for review of air access and discharge. Ask for maintenance and lifting clearances on the offered drawing. A unit fitting the available footprint does not establish that its service space or installation interfaces are acceptable.",
  "Existing model for replacements": "Send the complete equipment reference, serial number, nameplate photograph and available drawing revision. State exactly what is being replaced: a whole exchanger, a plate pack, individual plates and gaskets, an air-cooler bundle or a fan-related component. Identify which parts remain in service and who verifies their condition and compatibility. Require an exact replacement or a clearly identified alternative against the retained interfaces. Matching overall dimensions, plate count or nominal fan diameter alone is not sufficient evidence of interchangeability."
},
  "reciprocating-compressors": {
    "Gas analysis": "Provide the gas composition and its measurement basis, including the sampling date, units and expected variation between operating cases. Identify water, liquids, particles and constituents requiring a materials or emissions review. A description such as natural gas is insufficient for a package selection. Separate measured values from assumed values and explain whether an upstream treatment package forms part of the enquiry. Request a documented application review for the offered configuration; a previous selection for a similar stream does not establish suitability for this gas.",
    "Stage pressures and temperatures": "Identify suction and required delivery pressure for each operating case, stating whether pressure is absolute or gauge. Give inlet temperature and available cooling conditions alongside the gas analysis. Distinguish the process requirement from the proposed number of stages and the resulting interstage conditions, which should be explained in the technical offer. Keep design limits separate from normal operation. Ask for a case-by-case performance schedule with assumptions, limitations and the package boundary used in the calculation, rather than comparing a single discharge pressure printed in a brochure.",
    "Capacity and duty cycle": "State gas flow with units and its reference conditions; a standard volume and an actual inlet volume are different quantities. Describe normal, minimum, maximum and future cases, including which cases occur together and the expected hours of service. Identify the required capacity-control range and the site's electrical or driver constraints without prescribing an unreviewed control method. Request power and performance information for the same cases from every bidder. Keep continuous duty, standby provision and intermittent operation separate in the enquiry so an attractive rated capacity does not conceal a different service basis.",
    "Cylinder and packing requirements": "Record process cleanliness limits, permitted lubricant carryover, service constituents and project restrictions affecting cylinders, seals and rod packing. For an existing machine, supply its cylinder, packing and drawing references as well as the frame identity. Ask the technical proposal to describe the selected arrangement, required cooling and vent interfaces, and the application assumptions behind it. A non-lubricated cylinder description does not automatically describe every lubrication system in a complete package. Material and sealing compatibility remain matters for documented application review, with alternatives and unresolved inputs clearly identified."
  },
  "shell-and-tube-heat-exchangers": {
    "Heat duty and temperatures": "Provide paired hot-side and cold-side cases, with inlet temperatures, required outlet conditions and heat duty where established by the process design. State whether each fluid stays in one phase or includes boiling, condensation or another phase change. Distinguish an agreed process requirement from a preliminary estimate, and identify which values the thermal designer may calculate. Describe seasonal utility temperatures and relevant operating variation. Ask bidders to state their thermal basis and exceptions explicitly; quoting a heat-transfer area without the conditions used to select it does not establish the requested duty.",
    "Flow on both sides": "Give the mass or volumetric flow on each side with units, reference conditions and the fluid property information used by the process designer. Include composition and phase information where they affect the calculation. Pair the flows with their respective temperatures and pressures instead of assembling unrelated maxima into a fictional operating case. Identify minimum and maximum duties, startup cases requiring evaluation and any proposed future capacity. If a flow or property is uncertain, show its source and status so the proposal can identify what remains provisional.",
    "Allowable pressure drop": "Specify the allowable pressure loss separately for the shell side and tube side, and define the boundaries of those allowances. Clarify whether connecting pipework or other equipment is outside the exchanger calculation. Request calculated pressure drops at the same operating cases used for thermal selection, together with the assumptions behind them. A larger heat-transfer surface is not automatically an acceptable solution if the hydraulic limits, available space or maintenance arrangement differ. Keep a bidder's proposed allowance separate from the limit approved by the process team.",
    "Tube and shell materials": "Identify the specified material grades for tubes, shell, channels, tubesheets and other relevant wetted parts, along with gaskets and any approved corrosion allowance or lining. Provide fluid composition and relevant external exposure for materials review. An expression such as stainless steel does not define every component of an exchanger. Request the offered material schedule, traceability requirements and any substitutions against the enquiry. The material certificate requirement and its acceptance process should be explicit, with unresolved compatibility questions retained for the responsible project team."
  }
};

export const engineeredEquipmentSupplyGuidance: Record<string, string> = {
  "safety-and-relief-valves": "Compare the valve assembly together with its stated accessories, connections, materials and documentation. Ask whether the quotation covers a complete new device, a replacement component or a separately defined inspection or repair service. Identify any omitted accessory and any proposed change to the specified construction. Keep the technical deviation register alongside the price comparison, with unresolved relief inputs clearly marked. Confirm manufacturing country, dispatch location, delivery terms, quotation validity and the event starting the lead time. Route the enquiry through Oillinko for manual review and supplier coordination; the catalogue entry does not establish stock, certified capacity or acceptance of a particular valve.",
  "o-rings-and-packing": "Compare an individual seal, a defined packing set and a complete maintenance kit on their stated contents. Record the quantity and unit of supply, offered part reference, material identification, packaging and required documents for each line. Ask whether any accessories or specialist support are included, optional or excluded. Keep proposed alternatives separate from the approved part requirement until technical review is complete. Confirm manufacturing country independently of dispatch location, together with quotation validity, delivery terms and the assumptions behind the lead time. A low unit price does not resolve an incomplete kit or an unidentified compound.",
  "cooling-towers-and-utility-air-dryers": "Compare a complete package with a complete package. For a cooling tower, identify the structure, heat-transfer internals, fan equipment, water-distribution components, instruments and controls included in the offer. For a dryer, identify the drying unit, associated filters, drains, instruments and connection accessories. State which civil, piping, electrical and commissioning services are separate. Request manufacturing origin independently of dispatch location, and record the named delivery place, documentation, inspection scope and exclusions. Oillinko receives enquiries for manual coordination; catalogue inclusion does not establish stock, delivery time or confirmed application suitability.",
  "plate-exchangers-and-air-coolers": "Compare the quoted equipment boundary line by line. For a plate unit, identify the frame, plates, seals, connections, insulation and any separately priced spares. For an air cooler, identify bundles, fans, drives, supports, guards, access provisions and control interfaces. Record inspection, documentation and site attendance as included or excluded. Ask for manufacturing origin separately from the dispatch location and named delivery place. A replacement-only price should not be compared directly with a complete package quotation that includes new supports, controls and installation work.",
  "reciprocating-compressors": "For reciprocating compressors, distinguish an assembly quotation from a complete gas compression package. Compare the driver, cooling, process auxiliaries, controls, engineering studies and agreed tests using the same boundary. Identify field connections, utilities and commissioning work supplied by others. Request a list of departures from the case schedule and scope matrix, with their effect on the proposed selection. Keep manufacturing origin, dispatch location and delivery terms as separate entries. A preliminary assembly price should remain visibly preliminary until the required interfaces and included work have been reviewed.",
  "shell-and-tube-heat-exchangers": "For shell-and-tube heat exchangers, compare complete exchanger supply separately from a bundle-only replacement. Identify channels, covers, supports, connections, insulation or other specified accessories, inspection activities and the final document package as included or excluded. For retained equipment, define responsibility for checking its condition and interfaces. Compare the offered thermal and hydraulic cases against the same datasheet revision, with deviations clearly listed. Manufacturing origin and dispatch location are separate from the named delivery point. Do not treat two prices as comparable until their equipment boundaries and evidence requirements are aligned."
};

export const engineeredEquipmentTopicGuidance: Record<string, ContentSection[]> = {
  "safety-and-relief-valves": [
  {
    "title": "Separate a replacement enquiry from a revised relief duty",
    "paragraphs": [
      "For a replacement, assemble a record that connects the installed valve to the protected equipment. Include the equipment tag, valve identification, current approved data sheet and the available inlet and outlet connection drawings. Describe whether the request is for an identical documented configuration or for an alternative requiring review. A nameplate photograph helps identify the existing device, but it does not demonstrate that the current process and discharge conditions are unchanged.",
      "Keep the original requirement and each proposed difference visible in the offer comparison. The reviewer should be able to trace a change in construction, material, connection or documentation without reconstructing the enquiry from several email attachments. If the relief study is being revised, identify that dependency explicitly and distinguish a budget estimate from a technically released purchase description. Do not let a short delivery promise silently become approval of an unresolved alternative."
    ]
  },
  {
    "title": "Request evidence that identifies the actual offered device",
    "paragraphs": [
      "Ask the supplier to link its technical selection, drawing and certification references to one identifiable offered configuration. Separate the required relieving duty from the capacity evidence presented for the device. Record the units and applicable conditions for both, and have the responsible technical reviewer resolve any difference in basis. Where a certification listing is required, check the relevant listing for the offered design rather than relying only on a company name appearing in a directory.",
      "At order review, agree which records must accompany the eventual delivery and how they will identify each valve. A schedule can associate the equipment tag, offered reference, serial identification when assigned, required documents and open points. This is a document-control aid, not a replacement for the applicable acceptance specification. A delivery should not be described as technically accepted merely because the packing list and quantity match the commercial order."
    ]
  },
  {
    "title": "Keep supply and specialist service responsibilities explicit",
    "paragraphs": [
      "An enquiry may require goods only, a workshop service, engineering selection support or a combination of these scopes. Ask each response to distinguish them and identify the documents expected from each activity. Where an existing device is to be inspected or repaired, describe its known condition and available history, while leaving assessment and authorized work to the competent service provider. A new-valve quotation should not be assumed to include removal, installation, testing at site or a revision of the relief study.",
      "Make the release sequence clear in the commercial comparison. Record which technical questions must be answered before a firm selection can be accepted and which documents are needed before shipment. Preserve the difference between a quoted manufacturing lead time and the overall project delivery schedule. Required site dates, freight and documentation review time should be stated independently. Installation, adjustment and operating decisions remain governed by the approved equipment instructions and the responsible site and engineering teams."
    ]
  }
],
  "o-rings-and-packing": [
  {
    "title": "How should a replacement list distinguish individual seals from complete kits?",
    "paragraphs": [
      "A shutdown list often describes several different purchasing units as a seal kit. Before requesting prices, define what one unit means for each line. An individual O-ring, a bag of identical rings, a set for one valve and a kit for a complete pump assembly cannot be compared by unit price without this distinction. Use a simple schedule showing the equipment reference, sealing position, quantity per assembly and number of assemblies to be serviced. Keep contingency spares visible as a separate quantity so they are not confused with the content of each kit.",
      "Ask for a proposed kit-content list where the original contents cannot be confirmed. That list should identify each supplied component and the equipment position it is intended to serve. Record whether accessories or retained components are included, excluded or supplied by the owner. A commercial description such as complete does not resolve an uncertain assembly boundary. The responsible maintenance or engineering team should review the mapping before the quotation is treated as a replacement for the requested kit."
    ]
  },
  {
    "title": "What evidence makes a material substitution reviewable?",
    "paragraphs": [
      "A useful alternative proposal explains what changes and gives the reviewer enough information to decide whether further assessment is needed. Ask the offer to retain the original requirement beside the proposed compound or packing construction, with the relevant product data and stated service assumptions. The review should remain specific to the sealing position. Acceptance of a material in one item does not automatically approve its use in another item exposed to different conditions or movement.",
      "Keep the technical response tied to a dated document or identified data-sheet revision. If the supplier cannot establish a requested property or traceable material identity, record that as an open point. Do not resolve the gap by copying a property from another product in the same family. The purchasing comparison can still show the quoted price and delivery estimate, provided the alternative is clearly described as awaiting technical acceptance. No general promise of interchangeability should replace that review."
    ]
  },
  {
    "title": "How should receiving records support maintenance without implying installation approval?",
    "paragraphs": [
      "Agree the information that must accompany the goods before comparing offers. Depending on the approved purchasing specification, this may include the supplied part reference, compound or material identification, quantity, batch reference, dimensional records and the required certificate. Ask which records are standard, which require an additional request and which cannot be supplied. A generic brochure describes a product range; it is not a record identifying the particular items received for the maintenance job.",
      "Arrange packaging and labelling so different sizes, materials and equipment allocations can be distinguished during receipt and storage. Request the product-specific storage instructions and any required shelf-life information instead of assigning one storage life to every elastomer or packing material. If a delivery is split, retain the link between each consignment and the remaining quantities. Receiving checks establish what arrived against the purchase description; they do not authorize installation or establish that an unreviewed substitution is suitable.",
      "Send the requirement to Oillinko with the available drawings, parts schedule and unresolved questions. Oillinko reviews the enquiry and coordinates supplier responses manually. The eventual offer should separate goods, documentation and any optional specialist support, while identifying manufacturing origin, delivery terms and validity. Installation methods, gland adjustments and operating acceptance remain with the approved equipment instructions and the responsible site team. This page supports preparation of the purchase enquiry and does not prescribe a sealing arrangement."
    ],
    "links": [
      {
        "label": "Distinguish sheet gaskets from ring and packing requirements",
        "href": "/oil-and-gas/equipment/gaskets-seals/sheet-and-non-metallic-gaskets"
      }
    ]
  }
],
  "cooling-towers-and-utility-air-dryers": [
  {
    "title": "How should a cooling-tower thermal case be compared?",
    "paragraphs": [
      "Keep the water-temperature change and the approach distinct. The approach for an evaporative tower is the difference between the leaving cold-water temperature and the entering air wet-bulb temperature. It is not the temperature reduction across the water circuit. Require a proposal to repeat the complete water and air design case, including the flow basis, rather than quoting a single temperature difference without its definition. Where the project has several seasonal or load cases, identify them individually for assessment.",
      "Build the comparison around the project documents. Give each thermal case a reference and revision, then ask bidders to mark accepted inputs, proposed alternatives and unresolved assumptions. Identify the party responsible for checking the proposed arrangement against the connected process. If a bidder changes the water flow or target temperature, retain that change visibly in the comparison instead of presenting the option as an equivalent offer. Agree the required performance evidence and its acceptance conditions before selecting the commercial proposal."
    ]
  },
  {
    "title": "What does the dryer moisture target actually mean?",
    "paragraphs": [
      "Pressure dew point describes the condensation temperature at the stated compressed-air pressure. It differs from atmospheric dew point, so a moisture target without its pressure basis is incomplete. Ask for confirmation of the required pressure dew point at the specified flow and inlet conditions. Keep the end-user requirement separate from the bidder's proposed dryer technology. A refrigerated or desiccant label alone does not document the operating envelope or establish that the offered unit meets every project case.",
      "Record moisture, particle and oil requirements as separate entries where the project specifies them. Require the proposal to identify which part of the offered treatment package addresses each entry and what supporting documents will be supplied. This avoids interpreting a dryer-only offer as evidence for the complete air-quality specification. Identify the location at which acceptance is required, the applicable project specification and who will review the evidence. Do not silently move an acceptance requirement from a user connection to a different point in the package."
    ]
  },
  {
    "title": "Which replacement and handover boundaries need a written answer?",
    "paragraphs": [
      "For a replacement enquiry, attach the verified equipment tag, model reference, available drawings and a list of retained components. State whether the request is for a complete tower or dryer, a defined assembly, or separately identified spare parts. A quotation for an internal component cannot establish the condition or performance of an entire installed system. Ask the bidder to identify any checks needed before confirming compatibility and keep those checks visible in the procurement schedule. Separate a preliminary budget from a technically reviewed replacement proposal.",
      "Before comparing final offers, agree the drawing list, inspection records, operating documentation and handover responsibilities. Identify whether site attendance, functional checks and performance verification are included, optional or by others. Keep the equipment supply obligation distinct from ongoing water-management or compressed-air-system responsibilities. Assign each open interface to the project reviewer who can close it. Use the related utility and heat-exchanger pages when defining adjacent equipment, while retaining separate specifications and acceptance boundaries for the tower and the air dryer."
    ],
    "links": [
      {
        "label": "Define the wider plant utility package",
        "href": "/oil-and-gas/equipment/water-environment-utilities/boilers-cooling-and-compressed-air-utilities"
      },
      {
        "label": "Separate plate-exchanger and air-cooler duties",
        "href": "/oil-and-gas/equipment/pressure-vessels-tanks/plate-exchangers-and-air-coolers"
      }
    ]
  }
],
  "plate-exchangers-and-air-coolers": [
  {
    "title": "Which cooling arrangement is actually being requested?",
    "paragraphs": [
      "Begin the enquiry with the available cooling resource and the approved process objective. A plate exchanger connects two specified fluid streams; an air cooler transfers heat to the air around its heat-transfer assembly. They are not interchangeable purchases merely because both are described as coolers. If the project is comparing technologies, label the enquiry as an options review and give each bidder the same process basis. Ask the reviewer to identify what utility, electrical and installation changes belong to each option before comparing purchase prices.",
      "Keep a preliminary selection separate from a replacement order. A new package may permit changes to the arrangement, while an installed unit usually has retained connections and support constraints. State whether the responsible engineer allows alternatives and which interfaces must remain fixed. Use a short boundary list to distinguish equipment supply from layout engineering, piping changes, electrical work and site installation. Oillinko can coordinate the enquiry for manual review, but catalogue coverage alone does not confirm availability or the suitability of a proposed design."
    ]
  },
  {
    "title": "What makes plate and gasket replacements traceable?",
    "paragraphs": [
      "For a plate exchanger, ask the proposal to identify the plate design, material, channel arrangement and applicable sealing system against the installed records. A gasketed construction, a welded arrangement and a brazed unit have different replacement boundaries. State the required spare quantity and whether it means individual components or an assembled pack. Provide existing part references and the purpose of the work without instructing a bidder to infer compatibility from a photograph alone. Any proposed substitute should be listed as a technical deviation for review.",
      "Connect the delivery documents to the actual supplied components. Request the agreed material identification and inspection records, the applicable configuration drawing and the instructions needed by the qualified service team. If an existing pack has been modified, provide the latest verified arrangement rather than an obsolete original bill of materials. Do not prescribe a tightening dimension, cleaning chemical or assembly sequence from a generic enquiry guide. Such instructions depend on the actual equipment and the approved maintenance procedure."
    ]
  },
  {
    "title": "Which air-cooler auxiliaries and acceptance records belong in the offer?",
    "paragraphs": [
      "An air-cooler package may contain more than its heat-transfer bundle. Ask the bidder to identify the proposed fan and drive arrangement, electrical inputs, controls and access provisions. Where the project requires cold-weather accessories or special handling of discharged air, state the requirement and request a defined scope rather than assuming these features are standard. Record site noise constraints and the conditions under which any quoted noise or power figure applies. Keep those figures attached to the offered configuration and operating case.",
      "Agree what the supplier will demonstrate before shipment and which checks remain part of installation or commissioning. Tie the approved drawing, inspection schedule and final records to the equipment tag. Record deviations from the process case, hydraulic allowance or interface drawing before commercial acceptance. For a bundle replacement, identify whether retained fans, structure and controls are part of the assessment or outside the order. A successful component test does not by itself demonstrate performance of the complete installed cooling system. Use the related exchanger and maintenance guides to define connected work without merging their separate responsibilities."
    ],
    "links": [
      {
        "label": "Define a complete shell-and-tube exchanger enquiry",
        "href": "/oil-and-gas/equipment/pressure-vessels-tanks/shell-and-tube-heat-exchangers"
      },
      {
        "label": "Scope exchanger cleaning and retubing separately",
        "href": "/oil-and-gas/services/heat-exchanger-cleaning-and-retubing"
      }
    ]
  }
],
  "reciprocating-compressors": [
    { title: "What should a reciprocating compressor RFQ contain?", paragraphs: [
      "A useful reciprocating compressor RFQ combines a gas analysis, a schedule of operating cases and a defined package boundary. Begin with the intended service: for example, an existing gathering installation, a process compression duty or a replacement package. Explain the result the plant needs rather than choosing a frame solely from a headline power rating. Give each duty case a reference that can also appear in the supplier's performance schedule. Record who owns the process data, who will review the proposed selection and which inputs are still awaiting confirmation. This creates an enquiry that can be revised without losing the basis on which the initial quotation was prepared.",
      "Separate requirements into process, mechanical, electrical, control and documentation schedules where the project already uses those disciplines. A first enquiry can be preliminary, but it should say so and list the missing inputs. Request the calculation basis, equipment arrangement and deviations with the commercial response. For a replacement, include the installed equipment references, current operating conditions and the reason for replacement. Photographs are useful for identification and access planning; they should not substitute for a reviewed interface drawing. A concise cover note plus controlled attachments is easier to compare than specifications scattered across emails with conflicting revisions."
    ] },
    { title: "How do operating cases affect package selection?", paragraphs: [
      "Compare proposals using a common case schedule. The schedule should pair gas flow, composition, suction conditions and required delivery conditions for each real operating state. Label normal duty, minimum throughput, peak demand and any future case that is genuinely required. Do not combine the highest flow from one case with the lowest suction pressure from another unless the process team intends that combination to be evaluated. Ask the bidder to identify the proposed configuration and power demand for each case, together with any case it cannot cover. This makes a limitation visible before it becomes a disagreement over a nominal capacity figure.",
      "An illustrative comparison is two proposals that both state the requested maximum flow. One evaluates that flow at the normal suction condition, while the other evaluates it at the specified low-suction case. Their headline capacities look comparable, but their calculation bases differ. Resolve the case mismatch before considering the price difference. Require the technical review to address the offered machine's loading and operating limits, and retain the supporting application calculation with the proposal. A purchasing comparison should not attempt to establish those limits through a generic online formula or turn an unverified sales statement into a project performance guarantee."
    ] },
    { title: "Which auxiliaries belong in the compressor package?", paragraphs: [
      "Define the boundary between the compressor assembly and the complete compression package. Ask the quotation to identify the driver, coupling, base or skid, cooling arrangements, lubrication systems, instrumentation, controls and required process auxiliaries as included, excluded or supplied by others. Describe the interface with upstream gas conditioning and downstream equipment. If separators, interstage coolers, pulsation-control equipment or associated piping are required by the package design, make their design and supply responsibilities explicit. The enquiry should also identify who prepares the relevant engineering studies and who approves their findings. A list of component names alone does not establish an integrated package scope.",
      "Site information should include the available utilities, location conditions, electrical requirements, space limits and the project documents governing installation interfaces. Ask for a general arrangement drawing showing connection locations and the access needed for maintenance and component removal. Separate shop assembly from field assembly, commissioning support and any site acceptance work. These boundaries are particularly useful when one offer includes a skid while another includes only the compressor assembly. Record the agreed responsibility matrix with the selected proposal so later accessories are assessed against a documented boundary rather than assumed to be free additions."
    ] },
    { title: "How should lubrication and gas cleanliness be specified?", paragraphs: [
      "Describe the permitted process contamination and the downstream equipment's cleanliness requirements before comparing lubricated and non-lubricated cylinder arrangements. Ask which parts of the offered package use lubricant and what carryover assumptions underlie the proposal. Gas composition, contamination and operating conditions require an application-specific lubrication review. Do not select lubricant type or quantity from a general procurement guide. State whether any downstream oil-removal scope is included and which party must demonstrate the required outlet quality. If a bidder uses an expression such as oil-free, request a precise explanation of the package boundary and the conditions to which the statement applies.",
      "For a replacement or modification, distinguish the historic gas basis from today's measured composition and duty. Provide records of changed service conditions to the responsible reviewer, together with the installed cylinder and packing references where available. Ask for any resulting changes in materials, cooling, vent interfaces or auxiliary requirements to be listed as part of the offer. This review also helps distinguish an equivalent replacement from a proposed reconfiguration. Treat recommendations affecting operation as controlled technical deliverables requiring the appropriate approval; the quotation exercise should collect the evidence and responsibilities rather than instruct site personnel to alter lubrication or protective settings."
    ] },
    { title: "Which inspections and documents should be requested?", paragraphs: [
      "Request a project-specific inspection and documentation schedule with the proposal. Identify the technical datasheet, performance calculations, general arrangement, utility requirements, material records, electrical and control documents, manuals and the agreed test reports. Where a project standard applies, state its required edition and scope in the enquiry and ask for a clear compliance or deviation response. Separate a component certificate from evidence covering the complete assembled package. An organizational certificate, a catalogue statement and a witnessed package test are different records; the purchasing file should show which evidence actually supports each acceptance requirement.",
      "Agree the proposed shop tests and acceptance criteria before comparing claims about a tested package. Identify the test boundary, medium or method, conditions, measurements, witnessing arrangements and report deliverables through the approved test plan. Record what must be checked at site and who supplies the resources for it. For replacements, link the documentation to the exact equipment identity and drawing revision. Request a final document index and explain which records are needed before dispatch or acceptance. This keeps reviewable deliverables separate from an unspecific promise that certificates will be supplied later."
    ] },
    { title: "How can buyers compare compressor quotations fairly?", paragraphs: [
      "Build the comparison around the same case schedule and scope matrix. For each offer, record the selected arrangement, covered duties, driver and auxiliary scope, interfaces, required evidence, deviations and information still needed from the buyer. Keep technical acceptance separate from the commercial comparison. Record the currency, price basis, named delivery location, quotation validity, proposed lead time and the event from which that lead time starts. Manufacturing origin means the country in which the offered equipment is manufactured; it is not established by the quotation sender's address. Request origin information at the appropriate assembly or component level where the project requires it.",
      "A lower assembly price may require separate purchases or engineering work to produce the same package boundary. Show those gaps explicitly instead of inventing an estimated complete price. Likewise, distinguish a budget quotation from an offer with reviewed process inputs and an agreed scope. Submit your datasheet and case schedule to Oillinko for manual review and clarification; this page does not establish stock, an appointed manufacturer or an accepted design. The related equipment and inspection guides below help define connected scopes without treating those items as automatically included in a compressor offer."
    ], links: [equipmentLink("shell-and-tube-heat-exchangers", "Specify cooling equipment using paired thermal and hydraulic cases"), articleLink("inspection-test-plans-hold-vs-witness-points", "Define inspection hold points and witness points in the package test plan")] }
  ],
  "shell-and-tube-heat-exchangers": [
    { title: "What should a shell-and-tube heat exchanger RFQ contain?", paragraphs: [
      "A shell-and-tube heat exchanger RFQ needs a thermal duty schedule, separate hydraulic limits for both sides and a mechanical design basis. Identify whether the purchase is a new exchanger, a complete replacement or a replacement bundle. These are different scopes even when they refer to the same plant tag. Provide the fluid identities and paired operating cases, then describe the required materials, interfaces, inspection and documentation. Mark unresolved process data as provisional. The thermal proposal should explain how it addresses the stated cases; a drawing that fits the available space is not by itself evidence that the exchanger will meet the process requirement.",
      "For an installed exchanger, include the current datasheet, nameplate information, general arrangement and relevant drawings with their revisions. Explain whether the process duty has changed and whether the existing equipment suffered a service problem that needs investigation. Keep the replacement boundary explicit: a new bundle inside the retained shell has different interface and condition questions from a completely new vessel assembly. If the first RFQ is for budgeting, request a list of assumptions and the information required to firm up the proposal. That makes the next revision a controlled improvement rather than an unexplained change in specification or price."
    ] },
    { title: "Why must thermal duty and pressure drop be reviewed together?", paragraphs: [
      "The required heat transfer and the available pressure-drop allowances belong in the same comparison. Ask each bidder for a case schedule identifying the inlet and outlet conditions, flows, stated duty and calculated pressure drop on both sides. Specify the agreed basis for fouling and any margin through the project design documents, and ask the proposal to distinguish clean and specified service conditions where relevant. Do not treat an added surface area, a fouling assumption and a performance margin as interchangeable quantities. A bare statement of area cannot show whether a proposal meets the required outlets within the hydraulic limits.",
      "An illustrative comparison is two offers for the same stated duty. One uses the buyer's summer cooling-water condition; the other assumes colder water and provides no summer case. Resolve that difference before deciding that one smaller unit is the better purchase. Similarly, keep the shell-side allowance separate from the tube-side allowance and make the calculation boundaries clear. Ask the responsible thermal reviewer to assess the offered cases and exceptions. The buyer's role in the RFQ is to supply consistent inputs and obtain comparable results, rather than infer a design from a general sizing rule or accept a calculation whose assumptions remain hidden."
    ] },
    { title: "How do mechanical arrangement and maintenance access affect selection?", paragraphs: [
      "The exchanger arrangement determines interfaces and the access required for inspection, cleaning and replacement. Request a general arrangement with nozzle locations, supports, overall dimensions and the spaces required by the proposed maintenance approach. State restrictions on bundle removal, channel access, lifting and installation orientation where they are known. Ask the proposal to identify the offered construction and how it addresses the project's access constraints. A removable part may still need a clear withdrawal path and handling resources; its name alone does not demonstrate that the installed location can accommodate the planned work.",
      "For a replacement, compare mating connections, support positions and retained interfaces against the approved drawings. Record differences requiring changes to pipework, supports or insulation as part of the scope review. Distinguish design information provided by the buyer from a survey or verification service that is being requested. Photographs can help explain a restricted location, but critical geometry needs a documented dimensional basis. If access information is incomplete, ask bidders to identify their assumptions rather than declare the replacement interchangeable. The final purchasing comparison should include the agreed interface drawings and the work excluded from supply."
    ] },
    { title: "What do TEMA class and pressure-vessel code requirements establish?", paragraphs: [
      "TEMA class and a pressure-vessel construction code describe different aspects of the specification. The public TEMA guidance distinguishes Class R for severe petroleum duties, Class B for chemical process duties and Class C for general commercial duties. A class designation should come from the project's requirements and does not establish an individual exchanger's suitability by itself. State the applicable class and edition explicitly and request deviations against that basis. TEMA now uses a year-based edition designation; confirm the edition required by the project instead of assuming that a previous numbered edition is the current purchasing basis.",
      "Where ASME Section VIII or another construction code is required, identify the applicable division, edition, certification requirements and governing project or jurisdictional basis. The public ASME description addresses pressure-vessel construction, inspection, testing and certification; it is not a thermal performance guarantee. Ask the offered scope to distinguish construction-code requirements from thermal acceptance, materials restrictions and any additional project specifications. Do not infer an authorized certification or an acceptable completed vessel from the presence of a standard's name in a sales description. The responsible reviewer should confirm the required evidence and any proposed exceptions before technical acceptance."
    ] },
    { title: "Which material and inspection records should accompany the offer?", paragraphs: [
      "Request a component material schedule and a proposed inspection and test plan alongside the technical response. The schedule should identify the specified and offered materials for the relevant pressure-retaining and wetted components, as well as seals, linings or other specified systems. Define material certificate and traceability requirements through the enquiry. Record alternatives as deviations rather than replacing the original specification silently. A certificate for one tube batch does not identify every material in the completed exchanger; the documentation should connect the required records to the actual component and equipment references.",
      "Agree the required fabrication inspections, tests, acceptance references, witness or hold points and final reports in the project plan. Separate the purpose of a mechanical pressure test from the evidence needed for a thermal guarantee. Identify any third-party review, special cleaning or preservation requirements and ask whether those activities are included in the quotation. Request the final drawing and document index, including the records required at dispatch and those required for handover. Do not assume a catalogue listing establishes a particular test, certificate or manufacturing capability. Those facts must be confirmed for the equipment and scope actually offered."
    ] },
    { title: "How can buyers compare complete exchanger offers?", paragraphs: [
      "Compare the same equipment boundary, thermal cases, hydraulic limits, material schedule and mechanical requirements before comparing price. Record offered construction, maintenance access, design and test responsibilities, documentation, spare parts and deviations in a common matrix. Keep the proposed lead time tied to a stated starting event, such as approved drawings or another agreed milestone, without assuming those events have already occurred. Identify currency, delivery terms, named delivery location, packaging and quotation validity. Manufacturing country, dispatch location and the supplier's registered address are separate facts; ask for the origin evidence required by the project rather than treating them as interchangeable.",
      "If one offer excludes engineering, a retained-shell condition assessment or installation changes, show those boundaries clearly. Avoid declaring a complete replacement and a bundle-only quotation commercially equivalent. Send the current datasheet, case schedule and interface drawings to Oillinko for manual review; availability, design suitability and commercial terms require confirmation for the actual enquiry. For further detail, use the bundle guide when retaining the existing shell, the pressure-vessel records guide when identifying an installed unit, and the compressor page when the cooling equipment is part of a compression package. These connected requirements can be coordinated without assuming that every item is supplied together."
    ], links: [articleLink("replacement-heat-exchanger-tube-bundles-rfq", "Prepare a replacement tube-bundle RFQ for an existing exchanger"), articleLink("pressure-vessel-nameplates-data-reports-replacement-rfq", "Identify installed pressure equipment using nameplates and data reports"), equipmentLink("reciprocating-compressors", "Define the cooling and auxiliary boundary of a reciprocating compressor package")] }
  ]
};
