type GuidanceSection = { title: string; paragraphs: string[] };

// Primary basis and procurement boundaries: docs/application-content-2026-10-03.md.
export const electricalSpecificationGuidance: Record<string, Record<string, string>> = {
  "motors-and-variable-speed-drives": {
    "Power, voltage and frequency": "State the available electrical supply and the required mechanical output separately. Include phase, voltage and frequency from the approved electrical schedule, together with the driven machine's load information. A motor's shaft-power rating is not its electrical input demand. For a replacement, supply a readable nameplate and the existing motor and drive references, but identify any change in duty since installation. Ask the proposal to state the offered motor rating and the basis for matching the drive to it. Required efficiency evidence should identify the actual configuration and test basis; a general efficiency claim does not establish the performance of the complete machine system.",
    "Speed and duty": "Describe the required speed range and the machine's torque demand across that range. Give normal operation, starting and intermittent demands, with the duration and frequency of each case where known. Distinguish continuous service from repeated starts or a short-duty application. The motor and drive need assessment as a combination: slowing a machine can affect available torque, cooling and the process result. A kilowatt value and maximum speed alone leave those questions unresolved. If the load information is provisional, request a separately identified engineering assessment rather than allowing an assumed duty to become an unqualified equipment selection.",
    "Mounting and enclosure": "Provide the mounting drawing, shaft dimensions, coupling interface and permitted installation envelope. Identify horizontal or vertical arrangement and any terminal-box orientation that affects the existing installation. State the ambient conditions, altitude where relevant, ventilation constraints and required enclosure protection from the project specification. Distinguish a motor installed in the field from a drive inside a cabinet; they may face different conditions. For a classified location, include the approved area requirements and request evidence for the actual offered arrangement. Do not infer suitability from the word industrial, an enclosure rating alone or the external appearance of a replacement motor.",
    "Drive interface": "List the required control signals, feedback devices and communication interfaces, with the relevant controller and drive versions. Identify whether the enquiry covers a bare drive, a cabinet assembly or a coordinated motor-drive package. Give the intended motor-to-drive cable arrangement for technical review, without prescribing a cable or filter from a catalogue description. Ask which accessories, protection provisions, configuration work and interface tests are included. Record the responsibility for integration with the approved control and electrical design. Any protective or safety function requires its own specified scope and acceptance basis; an available communication port does not establish that function."
  }
};

export const electricalTopicGuidance: Record<string, GuidanceSection[]> = {
  "motors-and-variable-speed-drives": [
    { title: "Compare a motor-drive package against the driven machine", paragraphs: [
      "A pump, fan and conveyor can require different load behavior even when their motors have the same rated power. Prepare a duty schedule showing the intended output, operating speeds and time spent in each condition. For a new installation, use the approved machine requirements. For a retrofit, include current operating information and identify what the change is intended to achieve. Ask the technical response to state which conditions it has assessed and which still depend on missing data.",
      "Keep a proposed energy assessment separate from the supply price. It should identify the operating baseline, expected duty profile and the complete system being compared. Installing a variable speed drive does not by itself establish a particular saving or payback. A machine that must remain at one speed and a system with frequent reduced demand present different questions. Procurement should request the assumptions and evidence rather than attach a general percentage benefit to every drive purchase."
    ] },
    { title: "Identify retrofit interfaces and excluded equipment", paragraphs: [
      "For an existing motor, request review of its suitability for the proposed drive and operating range. Keep the mechanical coupling, driven equipment limitations, cooling arrangement and electrical connection information together. State whether surveys or measurements are available, and distinguish confirmed records from observations still needing verification. The equipment enquiry should identify the assessment responsibility; it is not an instruction to connect a new drive to an unreviewed machine.",
      "An offer may include a motor and drive while excluding the cabinet, local controls, feedback device, connection accessories or site integration. Use a line-by-line supply schedule to make those boundaries visible. Record which parts are retained from the existing installation and which must be provided anew. If an alternative changes mounting or interfaces, request the associated drawings and additional scope before comparing the final package cost."
    ] },
    { title: "Request identification and acceptance records for the supplied assembly", paragraphs: [
      "Agree the motor and drive identification, configuration baseline, dimensional drawings and project-required test records that accompany delivery. Distinguish component factory evidence from verification of the installed machine and controls. Include manuals, declared limitations, preservation requirements and any separately purchased commissioning support. Ask for manufacturing origin for the actual supplied equipment, with components identified separately where the project requires it. Oillinko receives the enquiry for manual review and coordination; equipment acceptance and authorization to operate remain with the responsible project parties."
    ] }
  ]
};
