import type { SectorId } from "./catalogue";

type IndustryGuide = {
  title: string;
  description: string;
  reviewedOn: string;
  sections: { title: string; paragraphs: string[] }[];
  topicIds: string[];
};

export const industryGuides: Partial<Record<SectorId, IndustryGuide>> = {
  power: {
    title: "Defining an industrial power and utilities package",
    description: "Prepare power and utility enquiries with distinct load cases, electrical and process interfaces, package boundaries and acceptance evidence.",
    reviewedOn: "2026-10-02",
    topicIds: ["transformers-and-switchgear", "boilers-and-waste-heat-recovery", "steam-traps-and-condensate-systems", "centrifugal-pumps"],
    sections: [
      { title: "Create a utility schedule before combining equipment prices", paragraphs: [
        "Industrial power and utility enquiries can cover electricity, steam, cooling water, compressed air and the machines that serve them. These systems support related activities but have different performance measures and physical interfaces. Prepare a utility schedule showing each source, consumer and required connection. Identify whether the purchase concerns a complete new system, an additional consumer, a replacement machine or a maintenance service. This distinction helps establish whether the enquiry needs a design study, an equipment quotation or both, instead of assuming that every equipment package includes responsibility for the whole plant network.",
        "Record the approved demand cases for each utility, with units, required conditions and the source of the information. Separate normal consumption, peak demand and any standby case defined by the project. Identify seasonal or production changes and mark estimates that still require confirmation. Ask proposals to explain their assumptions and included capacity against those cases. Adding nominal equipment capacities together can conceal different duty descriptions, so the purchasing comparison should retain the load schedule and the responsible team's design basis alongside the commercial total."
      ] },
      { title: "Provide the electrical design and machine interfaces", paragraphs: [
        "For electrical equipment, supply the current single-line diagram, voltage and frequency requirements, load information and installation environment. The assigned electrical design should define protection, fault ratings, earthing arrangements and any location approvals. Ask the proposal to identify its scope against that design, including enclosures, controls, cables and accessories where specified. A motor power rating, transformer capacity or familiar switchgear description cannot establish that the offered assembly meets every interface of the existing distribution system. Keep unresolved design inputs visible rather than treating them as supplier-confirmed facts.",
        "For machines, distinguish the process load from the electrical supply and control interface. Identify starting or changing-duty information required by the responsible reviewer, along with mounting, drive and receiving-control arrangements. For standby or uninterrupted supplies, provide the loads covered and the project's autonomy and availability requirements. Ask which functions, batteries, fuel-related equipment or external connections belong to the offered package. A quotation for a principal machine can exclude the supporting equipment needed to connect it, and a replacement may require review beyond its nameplate power."
      ] },
      { title: "Draw the steam, heat and condensate boundary", paragraphs: [
        "A steam system includes generation, distribution, the equipment using steam and the handling or return of condensate. Identify the part of this network covered by the purchase. For a boiler or heat-recovery package, provide the required steam conditions and demand cases, available fuel or heat-source data, feedwater specification and existing interfaces. Ask where responsibility for process design, water treatment, controls and connections begins and ends. A boiler-only offer and a complete utility package should not be compared as though they deliver the same installed scope.",
        "For steam distribution accessories or condensate equipment, provide the approved layout, connection details and the operating information relevant to the actual location. Identify whether the assignment supplies individual components, assesses the network or performs maintenance. Request a technical response against the project's design conditions and material requirements without assuming that a nominal connection size selects every component. Keep any performance assessment separate from the purchase price. General energy-improvement guidance does not establish a guaranteed saving or prescribe a suitable arrangement for an unidentified industrial steam system."
      ] },
      { title: "Keep cooling and compressed-air requirements separate", paragraphs: [
        "For cooling duties, identify the medium, heat load, temperature cases, available utilities and the points where the offered system connects to the plant. Include the environmental and water information needed for review when relevant. State which pumps, heat exchangers, controls, treatment interfaces and connecting pipework are included. A circulation-flow figure and a cooling-duty figure describe different requirements. Ask the technical response to address both against the actual installation rather than compare cooling equipment solely by its footprint or a headline capacity.",
        "For compressed air, provide the required delivery conditions, demand profile and specified air quality at the relevant consumption points. Identify the existing compressor, receiver, dryer, filtration and distribution boundaries where those records are available. Ask whether the offer covers a complete train or selected components and which performance conditions apply to the proposed configuration. Record measurement, drain, control and maintenance interfaces for review. The description of a compressor or dryer alone does not define the quality delivered through every existing downstream connection."
      ] },
      { title: "Compare installed scope and the evidence at handover", paragraphs: [
        "Use a responsibility schedule to identify supply, transport, installation, integration, commissioning and continuing support. Request the drawings, equipment identification and acceptance records specified for each package. Distinguish workshop checks from site acceptance against the actual connected system. List outstanding inputs and who must resolve them before manufacture or installation proceeds. If a proposed package changes the installed arrangement, keep the required engineering review and approvals separate from routine equipment delivery; a delivered component is not automatically an accepted plant modification.",
        "Compare exclusions, delivery milestones, spares and documentation before assessing the overall commercial offer. Confirm manufacturing country for the supplied equipment separately from dispatch location and project destination. A multi-utility enquiry can be submitted to Oillinko as a controlled equipment list with drawings and the load schedule attached. Our team reviews the requirement and coordinates clarification. The sector catalogue helps identify relevant equipment and service families; it does not establish a reserved stock position, an appointed contractor or a guaranteed outcome for the combined utility network."
      ] }
    ]
  },
  refining: {
    title: "Preparing refinery equipment and turnaround enquiries",
    description: "Organize refinery enquiries by unit and equipment tag, separating replacement and revamp duties, installation interfaces and turnaround handover records.",
    reviewedOn: "2026-10-02",
    topicIds: ["shell-and-tube-heat-exchangers", "trays-structured-packing-and-distributors", "shutdown-planning-and-mechanical-support", "inspection-ndt-and-material-testing"],
    sections: [
      { title: "Identify the process unit and the reason for the purchase", paragraphs: [
        "Refining includes separation, conversion and treatment activities, with different equipment and service requirements across the plant. Name the actual process unit, system and equipment tag before describing a requested product family. Explain whether the assignment replaces an existing item, restores its condition or changes the process duty. A new exchanger, replacement column internals and inspection during a shutdown can belong to the same project while requiring different technical inputs. Unit capacity alone does not define the specification of every item within that project.",
        "Prepare a controlled equipment and task schedule with identifiable line items. Reference the current drawings and data sheets, and distinguish confirmed quantities from provisional allowances. Separate materials supply, fabrication, examination, field work and commissioning support where their boundaries differ. Ask responses to retain the item references so technical exceptions and commercial exclusions can be reconciled. A single package price can be useful, but it still needs enough detail to show which work and equipment it covers and what remains with the owner or another contractor."
      ] },
      { title: "Keep current service and mechanical records together", paragraphs: [
        "For replacement equipment, provide the installed identification and available design records alongside the current process duty. Identify changes in fluid composition, operating cases or approved material requirements that need assessment. Photographs help describe access and condition, but controlled drawings are needed for critical interfaces. Ask whether an offered item reproduces the accepted arrangement or proposes an alternative requiring review. Similar dimensions, a matching nominal size or an old purchase description cannot demonstrate that every process and mechanical requirement is still covered.",
        "For heat-transfer equipment, define both process sides, the required thermal result and the mechanical connection information. State whether the scope is cleaning, inspection, tube replacement or a complete equipment purchase. Ask which assessment and acceptance records support the proposed work. A restored mechanical condition and a demonstrated thermal result are different questions. Where internal condition is unknown, separate the initial examination from later repair approval, so an indicative allowance is not mistaken for a fixed scope supported by an inspection that has not yet occurred."
      ] },
      { title: "Distinguish column replacement from a process revamp", paragraphs: [
        "For trays, packing, distributors and supports, provide the vessel and internal arrangement drawings, material requirements and relevant process information. Identify the existing components to be retained and the proposed replacement boundary. Ask for the dimensions and installation assumptions of the actual offered assembly. An internal component must be reviewed against its supporting interfaces as well as its intended function; a column diameter or a material name alone leaves important parts of the enquiry undefined. Record any survey needed before manufacturing dimensions can be accepted.",
        "If the objective changes separation performance or throughput, identify the approved performance basis and the engineering assessment requested. A like-for-like replacement quotation and a process revamp proposal can involve different studies, guarantees and site work. Ask the response to explain those boundaries and the data needed to assess them. Keep process design, mechanical design, fabrication and installation responsibilities visible. The procurement enquiry can request an assessment without inventing a guaranteed capacity increase or assuming that new internals resolve every constraint in the surrounding process unit."
      ] },
      { title: "Link turnaround work to a defined readiness and handover", paragraphs: [
        "A turnaround enquiry should identify the equipment list, planned work window and tasks covered by the proposed team. Describe the required readiness conditions and the party responsible for making the worksite available under the site's authorized process. State access, utilities, handling, supervision and other interfaces needed to price the service. Ask the response to distinguish preparation, mobilisation, execution and completion milestones. A duration for hands-on work is not necessarily the elapsed shutdown period, especially when other packages or unresolved condition assessments affect the sequence.",
        "Identify how additional findings will be documented, priced and approved before the scope changes. A planned service can expose condition information that was unavailable during quotation, but this should not create an undefined authorization to perform extra work. Request an agreed reporting and decision process, with separately stated allowances where appropriate. Keep the responsible technical acceptance separate from commercial approval. The enquiry should define responsibilities and evidence; it should not substitute a generic purchasing guide for the site's work controls or prescribe an operating procedure."
      ] },
      { title: "Use a traceable completion dossier in the comparison", paragraphs: [
        "Define the material records, examination coverage, test documentation and dimensional or functional evidence required for each line item. Identify witnessing points and the authority responsible for acceptance. Ask for a dossier linked to the actual equipment tags and delivered parts, including limitations and approved deviations. An examination report, material certificate and performance demonstration address different questions. Specify what the project needs rather than accepting a general reference to certificates as proof of every required inspection or the fitness of the complete process installation.",
        "Confirm the dispatch point, delivery destination and manufacturing origin of supplied items separately. Include preservation, spare parts, site attendance and document delivery in the commercial comparison where required. Mark information still awaiting an owner decision and identify its effect on the offer. Send the equipment schedule or turnaround scope to Oillinko for manual review and coordination, using the available records rather than an assumed final specification. Catalogue coverage describes requirement families; availability, appointments, acceptance and delivery commitments require confirmation for the actual proposal."
      ] }
    ]
  },
  offshore: {
    title: "Preparing an offshore or marine equipment enquiry",
    description: "Plan offshore and marine equipment enquiries with clear seawater duty, installation interfaces, inspection records and delivery boundaries.",
    reviewedOn: "2026-10-02",
    topicIds: ["cathodic-protection-equipment", "wellheads-and-christmas-trees", "inspection-ndt-and-material-testing"],
    sections: [
      { title: "Begin with the asset and the work package", paragraphs: [
        "Offshore and marine purchasing covers several different installations: production platforms, subsea equipment, support vessels and the shore-based facilities that serve them. Identify the asset and the system before selecting a catalogue category. A seawater utility valve, a pressure-containing production component and a vessel treatment package can all appear in a marine enquiry while having different design, inspection and approval requirements. Explain whether the work is a new installation, a replacement, maintenance or a specialist service. This gives a reviewer the context needed to interpret the technical schedule.",
        "Break a mixed request into identifiable line items and work packages. Separate equipment supply, fabrication, inspection, installation support and commissioning when different parties perform them. Provide a controlled bill of quantities and the available drawings, with each clarification linked to an item number. Mark information that is still provisional. A complete package may be convenient commercially, but the proposal still needs to identify its boundaries and the interfaces supplied by the buyer, shipyard, operator or another contractor."
      ] },
      { title: "Describe seawater and external exposure separately", paragraphs: [
        "State which parts contact seawater or another process fluid and which parts face only the external marine environment. Give the relevant fluid analysis, operating and design conditions, and any approved material or coating requirements. Salinity, suspended matter, treatment chemicals and temperature can affect the engineering review. An item described as marine grade is not a complete material specification. Identify the specified body, trim, seals, fasteners and protective system where these are controlled by the project.",
        "For material-sensitive duties, request a documented response to the required grades and supporting records. Distinguish a proposed alternative from a confirmed match. Corrosion protection can involve coatings, cathodic protection, material selection and monitoring, with different responsibilities for design and supply. Provide the approved basis for the relevant system. Do not infer manufacturing origin from a brand, sales office or shipping point; state any origin restriction and ask for confirmation for each offered item."
      ] },
      { title: "Check installation and utility interfaces", paragraphs: [
        "Space, maintenance access, mass and connecting geometry matter on a vessel or offshore installation. Provide the current arrangement drawings and the dimensions needed to evaluate replacement or installation. Record flange or thread references, electrical supply and control interfaces, and any classification or environmental requirements set by the responsible design. Equipment offered with an actuator or control panel should identify the included assembly and the utilities it requires. Similar nominal sizes do not establish compatibility with an existing connection or foundation.",
        "Subsea and topside requirements should be distinguished explicitly. Water depth, access method and intervention interfaces can change the equipment or service scope, but the buyer should use the approved project basis rather than infer operating limits from a general product family. List integration, mounting and site testing as separate responsibilities. Ask how the offered package will be checked against the supplied drawings and what information must be confirmed before release for manufacture."
      ] },
      { title: "Connect approvals and inspection to the actual equipment", paragraphs: [
        "Approval evidence must relate to the particular product and installation. For example, ballast water management systems used for convention compliance require the applicable Administration's type approval under the relevant approval framework. This is a different question from whether a company supplies marine equipment. The project team should identify the vessel, flag, applicable requirements and the survey or commissioning scope. Ask for the offered configuration and its documented approval coverage, and keep installation acceptance separate from a broad catalogue statement.",
        "For other packages, define the inspection and release records appropriate to their function. Material traceability, examination reports, pressure-test records and functional checks are different forms of evidence. Specify the required dossier, witnessing points and acceptance authority before comparing offers. If the work is a service, state the examination coverage, access arrangements and required personnel qualifications. A report should identify the examined asset and any limitations so it can support the intended engineering decision."
      ] },
      { title: "Plan preservation, logistics and handover", paragraphs: [
        "Identify the dispatch point, delivery destination and required arrival date separately. The project schedule may depend on a vessel call, yard period or offshore work window, so distinguish production lead time from transport and mobilisation. Confirm packing dimensions, mass, preservation and storage instructions. Handling or lifting provisions need the appropriate engineering and documentation; inclusion of a fabricated frame does not establish that every offshore lifting requirement is satisfied.",
        "Compare the complete supply or service scope before the final commercial total. Identify spares, accessories, field connections, documentation, training and attendance as inclusions or exclusions. Record deviations for technical review and keep any promised delivery subject to the actual proposal. Submit the specification or whole equipment list to Oillinko when the requirement spans several categories. Our team reviews the enquiry and coordinates clarification; catalogue coverage does not establish reserved inventory, an appointed specialist or project approval."
      ] }
    ]
  },
  water: {
    title: "Defining a water treatment and environmental equipment package",
    description: "Prepare water treatment equipment requests using feed analysis, required outlet quality, utilities, waste streams and acceptance evidence.",
    reviewedOn: "2026-10-02",
    topicIds: ["metering-and-dosing-pumps", "calibration-and-instrument-repair", "inspection-ndt-and-material-testing"],
    sections: [
      { title: "Identify the water stream and the intended result", paragraphs: [
        "Water and environmental equipment enquiries begin with the source and destination of the stream. Produced water, intake water, industrial process water, cooling water and wastewater have different characteristics and treatment objectives. State whether the outlet is intended for reuse, reinjection, further treatment or a permitted discharge. The responsible project team should define the required quality and applicable acceptance basis. A label such as clean water or oily water is not enough to select a treatment process or compare performance proposals.",
        "Describe the current installation and the change required. A new treatment train, replacement filter, dosing skid and monitoring instrument are different packages even when they serve the same water system. Identify what already exists and what the offered equipment must connect to. Where the process has not been selected, request a defined study or treatment proposal rather than assume that equipment supply includes process design. Keep investigation, design, supply, installation and operating support visible as separate work boundaries."
      ] },
      { title: "Supply representative feed data and operating cases", paragraphs: [
        "Provide the available water analysis with sample locations, dates and the operating conditions represented. Relevant information can include suspended and dissolved constituents, hydrocarbons, salinity, temperature and the chemicals already used in the process. Identify which values are measured, estimated or still awaiting analysis. Produced water can contain a mixture of salts, hydrocarbons, solids and residual treatment chemicals; removing one constituent does not establish that the complete outlet quality has been achieved.",
        "Define flow cases and expected variability, including continuous, intermittent and peak conditions where they matter. A single average flow can hide a short-duration load that affects buffer capacity or treatment performance. Describe seasonal changes, cleaning streams or process events that alter the feed. If representative data are unavailable, agree the sampling, laboratory or trial work needed to reduce uncertainty. The proposal should identify the feed envelope on which its performance assessment depends and explain what happens commercially when the actual feed differs."
      ] },
      { title: "Compare a treatment train and its supporting utilities", paragraphs: [
        "Treatment may require several stages with different purposes. Separation, filtration, chemical dosing and monitoring should be considered against the required result and the actual stream, not selected from their names alone. Ask the technical response to explain each included stage, its design basis and the interfaces between stages. Identify tanks, pumps, piping, instruments and controls included with the package. A price for the principal treatment vessel can omit the equipment needed to operate or connect it.",
        "List electrical supply, available pressure, wash water, instrument air and other utilities required by the proposed arrangement. Record space, connection geometry and maintenance access. For dosing, provide chemical identity, concentration, compatibility requirements and the required control interface rather than only a pump flow. Clarify which consumables, initial charges and spare elements are included. Ask for expected consumption and maintenance information on the documented duty, with assumptions stated instead of treating an indicative figure as a guaranteed operating cost."
      ] },
      { title: "Define waste handling and performance acceptance", paragraphs: [
        "A treatment package can create concentrated waste, sludge, spent filters, backwash or cleaning streams. Ask the proposal to identify these outputs, their connection points and the responsibilities for collection, treatment and disposal. The environmental assessment and applicable project requirements should guide these arrangements. General industry guidance is useful context, but it does not replace the site's permits or establish a universal discharge limit for every jurisdiction and water stream.",
        "Agree how performance will be assessed: feed conditions, outlet parameters, measurement methods, sampling points and the duration or operating cases of the acceptance work. Distinguish a workshop function test from a site demonstration with the actual feed. If independent sampling or laboratory analysis is required, state who supplies it and which scope is needed. Define the response to results outside the agreed basis. An outlet-quality statement is useful only when its conditions, measurement evidence and acceptance responsibilities are clear."
      ] },
      { title: "Keep monitoring, service and delivery boundaries clear", paragraphs: [
        "Measurement equipment should be matched to the range, fluid matrix and installation. State sample conditioning, process connections, required outputs and maintenance access where relevant. For calibration or instrument repair, identify whether the scope covers an individual sensor, transmitter output or the complete installed loop. Request results and uncertainty appropriate to the use, and agree any conformity decision rule. A general calibration certificate cannot establish performance for every constituent measured in a water treatment process.",
        "Compare delivery, installation, commissioning and support as distinct items. Confirm the manufacturing origin of equipment separately from the delivery country and service location. Identify documentation, training, spare parts and technical attendance included in the offer. Where the requirement is still developing, send the available analysis, layout and desired result to Oillinko with the uncertainties clearly marked. Our team reviews the information and coordinates the enquiry; a catalogue entry describes a requirement family rather than a preselected process, approved supplier or guaranteed treatment result."
      ] }
    ]
  }
};
