import type { SectorId } from "./catalogue";

type IndustryGuide = {
  title: string;
  description: string;
  reviewedOn: string;
  sections: { title: string; paragraphs: string[] }[];
  topicIds: string[];
};

export const industryGuides: Partial<Record<SectorId, IndustryGuide>> = {
  drilling: {
    title: "Preparing a drilling and well construction purchasing package",
    description: "Scope drilling equipment and services with the approved well programme, rig interfaces, tubular records, fluid duty and inspection deliverables.",
    reviewedOn: "2026-10-04",
    topicIds: ["drill-pipe-and-bottom-hole-assemblies", "mud-pumps-and-solids-control", "cementing-and-well-control-equipment", "mwd-and-lwd-tools", "casing-running-and-cementing-accessories", "inspection-ndt-and-material-testing"],
    sections: [
      { title: "Which part of the well programme does the purchase support?", paragraphs: [
        "A drilling request can concern a complete rig package, replacement wear parts, tubulars, measurement tools or a specialist service for one stage of well construction. Identify the well or project reference, the responsible engineering team and the current programme revision before assembling the purchasing schedule. State whether the requirement supports a new well, an ongoing campaign or maintenance of installed equipment. The depth or general well type alone does not define the equipment configuration, duty or acceptance evidence needed for a useful quotation.",
        "Divide the request into packages with identifiable boundaries: rig and handling equipment, drill-string components, fluid circulation, casing and cementing, well-control equipment, and measurement or specialist support where required. Assign each line an item number, quantity and unit, with the drawing or specification it must satisfy. Identify material supplied by the owner and work performed by the drilling contractor. Keep an equipment-only purchase separate from rental, personnel and execution services so the comparison does not assume that a supplied tool includes a qualified operating crew."
      ] },
      { title: "What has to match the rig and installed equipment?", paragraphs: [
        "For replacements or additions, provide the installed assembly identity, serial number, arrangement drawing and applicable parts revision. Describe mechanical connections, mounting dimensions, electrical supply and control interfaces using controlled records. A matching model family or nominal connection size is a starting point, not evidence that the offered part fits the actual configuration. Ask the proposal to identify its included accessories and the interfaces that need review. Where the original record is incomplete, label the uncertain input rather than fill it with a catalogue assumption.",
        "For a larger package, identify the utilities and supporting systems available at its boundary. Include space, mass, handling, maintenance access and environmental requirements defined by the project. State who supplies connecting pipework, cables, supports, control integration and installation. An equipment description that appears complete may exclude the services or auxiliaries needed to connect it to the rig. Request a boundary drawing or clear scope schedule when these interfaces affect the offer, and keep proposed modifications subject to the responsible project's engineering approval."
      ] },
      { title: "How should drill-string and casing requirements be recorded?", paragraphs: [
        "Specify tubular dimensions, grade, weight designation, length or range, connection and the governing product requirement. Keep drill pipe, casing and production tubing as separate purchasing families. API 5DP identifies a drill-pipe specification, while casing and tubing are addressed by API 5CT; stating only API pipe leaves the required product and evidence unclear. Identify the applicable edition and project amendments through the approved specification. Do not infer the well's mechanical suitability from a familiar grade or connection designation without the design review for that programme.",
        "For existing tubulars or supplied assemblies, link the component identifiers to the inspection history and condition records required by the project. Describe the requested status as new, used or refurbished where that distinction matters, and state the applicable examination and acceptance basis. For bottom-hole assemblies and casing accessories, provide the connection schedule, mating components and relevant dimensional drawings. Separate product documentation from service inspection records. Neither a mill certificate nor an inspection sticker, considered alone, establishes that the entire assembled string meets the well programme and rig interfaces."
      ] },
      { title: "Which circulation and fluid-system inputs belong in the enquiry?", paragraphs: [
        "Describe the required circulation duty as paired flow and pressure cases, with the drilling-fluid properties and programme reference used for selection. A pump's highest advertised flow and highest pressure should not be assumed available together in every configuration. For an installed mud pump, identify the model, fluid-end arrangement and required liners, pistons, valves or other wear parts by the approved parts records. Request the proposed configuration's performance basis and interfaces rather than compare equipment only by a broad power rating or model description.",
        "For solids-control and fluid-processing equipment, define the intended separation duty and the feed conditions provided by the fluid programme. Identify the existing shaker or processing-unit configuration when requesting screens or replacement assemblies. State the installation footprint, utilities, connecting equipment and waste-handling boundary. Consumables need their own quantities, packaging and storage information. Keep fluid formulation, process settings and waste-management decisions with the responsible specialists; the procurement package should capture their requirements and evidence, not prescribe a universal drilling-fluid recipe or operating sequence."
      ] },
      { title: "How are well-control and cementing package boundaries kept clear?", paragraphs: [
        "Cementing equipment and well-control equipment may appear in one drilling schedule, but they serve distinct functions and need their own specifications. Identify each assembly, required bore and connection, pressure and temperature basis, materials and control-system boundary from the approved programme. API 16A concerns drill-through equipment, while API 16D addresses drilling well-control and diverter control systems. A reference to one document does not describe every part of the overall package. Request the actual scope and supporting records applicable to each offered assembly.",
        "The operator and responsible technical team define the well-control arrangement, performance requirements, applicable rules and acceptance activities. A purchasing enquiry should identify those approved requirements and any required technical review, witnessing or qualification evidence. Separate equipment manufacture, inspection, installation and operational readiness responsibilities. For replacement seals, control components or pressure-containing spares, identify the exact assembly and approved part documentation. Similar dimensions or an apparent rating match do not establish compatibility. This guide structures the enquiry; it does not provide well-control procedures, pressure-test settings or instructions for using safety-critical equipment."
      ] },
      { title: "What evidence follows the equipment through inspection and handover?", paragraphs: [
        "Prepare a document schedule alongside the bill of quantities. Identify the material records, dimensional checks, examination reports, specified tests, calibration information and drawings required for each relevant item. State whether a document is submitted for review before manufacture, witnessed at an agreed stage or included at final handover. Connect the evidence to the actual serial, heat, batch or component identity. A general brochure or earlier sample report should remain identifiable as reference material rather than be presented as evidence for the supplied equipment.",
        "Request a clear response to deviations and missing information. An offer may be commercially firm while its technical assumptions still need approval. Define who reviews those assumptions, who accepts inspection findings and how corrected documents are issued. For measurement tools, identify the required outputs, data format and handover responsibility separately from the hardware supply. Preserve configuration and maintenance records for the receiving team. The final dossier should explain what was supplied and assessed, without treating equipment delivery or a test report as automatic authorization to use it in the well."
      ] },
      { title: "What makes the commercial and delivery comparison complete?", paragraphs: [
        "Separate the equipment or service price from optional accessories, initial spares, technical attendance, rental extensions, packing and transport. For rental, identify the start and end milestones, minimum period, standby treatment, condition on return and damage-assessment basis. For purchases, state the delivery rule and named place, document-release assumptions and quoted lead-time starting event. Keep an estimated production period distinct from shipment time and arrival at the rig. A low unit price can represent a materially smaller scope when mobilization, support or acceptance documentation is excluded.",
        "Record the manufacturing country of each offered item separately from the dispatch location, vendor address and worksite. Provide the destination, handling constraints and required dates, identifying which depend on inspection release or other project milestones. Compare every proposal against the same approved schedule and retain a list of unresolved technical and commercial points. Send the enquiry and supporting records to Oillinko for manual review and coordination. Catalogue coverage describes the requirement families that can be discussed; it does not confirm available stock, an appointed contractor or acceptance of the equipment for a particular well."
      ] }
    ]
  },
  pipelines: {
    title: "Coordinating pipeline, station and terminal procurement boundaries",
    description: "Prepare pipeline and terminal enquiries with asset boundaries, inspection objectives, transfer interfaces and traceable acceptance records.",
    reviewedOn: "2026-10-03",
    topicIds: ["line-pipe", "pigging-and-inspection-tools", "pipeline-inline-inspection-services", "custody-transfer-metering-skids", "tank-gauging-and-overfill-prevention"],
    sections: [
      { title: "Divide the asset into connected purchasing scopes", paragraphs: [
        "Start a pipeline or terminal enquiry with a boundary drawing rather than one undifferentiated equipment list. Identify the transmission section, station piping, storage area and loading connection involved. Give each purchase a location and asset reference that can also appear on drawings, inspection records and quotations. State whether the work is a new installation, a replacement or an assessment of an existing asset. A valve at a station, a mainline inspection tool and a terminal measurement package may share a project name while requiring very different technical inputs.",
        "Record which party supplies the connecting pipework, electrical power, communications and civil interfaces. Identify existing equipment that will remain and the approved drawings governing its connections. For a package purchase, ask the proposal to mark its limits and external requirements on the same boundary drawing. Keep equipment supply, installation, inspection and engineering assessment as separate priced activities where their responsibilities differ. This lets the buyer see whether a low package price leaves an essential interface unpriced, without assuming that every offer includes a complete operating system."
      ] },
      { title: "Make the pipe and station records usable across disciplines", paragraphs: [
        "For line pipe, provide the specified outside diameter, wall thickness, grade, manufacturing route, lengths and end preparation. Attach the project material specification and inspection requirements, identifying the controlling revision. Distinguish ordered dimensions from measurements of an installed line. Where the request concerns an existing asset, assemble available construction records, weld information, repairs and coating details by section. Mark uncertain records explicitly. A nominal diameter alone does not establish the internal passage available for equipment or the geometry of a replacement connection.",
        "For pumping or compression stations, describe the handled fluid, relevant flow cases and the inlet and outlet conditions at the proposed package boundary. Include driver supply, installation constraints and the required connection drawings. Separate normal duty from the design conditions used by the responsible engineer. At interfaces with tanks or loading systems, retain a common set of stream and equipment identifiers across documents. If a proposal changes the assumed duty or configuration, record that deviation before comparing price; similar connection sizes do not make two packages technically equivalent."
      ] },
      { title: "Specify the inspection question before selecting a tool", paragraphs: [
        "A request for pipeline inspection should explain what evidence the operator needs. Geometry measurement, metal-loss assessment and crack assessment address different questions, and a cleaning tool does not provide the same information as an instrumented inspection tool. Request a stated inspection capability against the identified concern, including limitations and the conditions on which that capability depends. Provide the available pipe material, thickness and geometry records. Avoid turning a generic tool description into a claim that every relevant defect will be detected and sized in an unidentified line.",
        "Ask the proposed inspection scope to account for bends, restrictions, valves, changes of diameter and available access arrangements using the operator's controlled records. Identify who reviews suitability, supplies preparation work and accepts the inspection data. Request the intended reporting structure, location reference, stated measurement uncertainty or performance basis, and treatment of incomplete coverage. Keep the inspection report distinct from an engineering decision about continued service or repair. Any operating plan, isolation arrangement or pressure-test procedure belongs to qualified project personnel under the operator's approvals, rather than being inferred from the purchasing description."
      ] },
      { title: "Treat terminal transfer and inventory measurement as separate duties", paragraphs: [
        "At a terminal, identify whether a measurement is for commercial transfer, allocation, operational indication or tank inventory. State the reported quantity, product properties, relevant operating range and the receiving system's requirements. A tank-level instrument and a transfer meter belong to different measurement arrangements; one should not be substituted for the other on the basis of a shared accuracy headline. For a metering skid, ask which instruments, computation functions, verification provisions and records are included. The project's measurement specialist should define the acceptance basis appropriate to the stated duty.",
        "Loading equipment needs a defined physical interface and movement envelope as well as product conditions. Supply the connection drawings and identify the shutdown, permissive and communication interfaces already approved by the project. For tank work, distinguish inventory gauging from the specified overfill-protection scope and state the independence requirements established by the design. Ask the offer to identify external components and installation responsibilities. Do not assume that a transfer arm, hose, gauge or controller supplied alone establishes the performance or protection of the complete loading and storage arrangement."
      ] },
      { title: "Close the enquiry with a connected evidence schedule", paragraphs: [
        "Build an acceptance schedule that follows the purchase boundaries: material records for supplied pipe, equipment drawings and tests for station packages, defined results for inspection services, and measurement verification records for terminal systems. Name the receiving reviewer and the asset reference required on each document. Keep workshop acceptance, field verification and final engineering approval distinct. Require unresolved deviations and excluded work to remain visible in the quotation. A single statement that equipment is tested cannot demonstrate that these different deliverables have all been supplied or accepted.",
        "Compare manufacturing lead time, document review, transport and site attendance separately, including the assumptions behind an inspection or installation window. Confirm the manufacturing country of supplied goods independently of the dispatch point or service location. Ask for preservation, storage and handover requirements that suit the actual delivery sequence. Send the boundary drawings, pipe records and requirement schedule to Oillinko for manual review and enquiry coordination. The resulting response should identify priced scope and remaining questions, rather than imply that a sector listing confirms stock, approved inspection coverage or a complete pipeline and terminal solution."
      ] }
    ]
  },
  exploration: {
    title: "Preparing exploration equipment and subsurface data handover enquiries",
    description: "Scope exploration enquiries using survey objectives, equipment interfaces, sample identity, coordinate references and measurable data handover requirements.",
    reviewedOn: "2026-10-03",
    topicIds: ["seismic-and-geophysical-equipment", "formation-evaluation-and-logging-tools", "core-and-fluid-sampling-equipment", "geophysical-geotechnical-and-marine-surveys", "reservoir-software-and-data-services"],
    sections: [
      { title: "State the subsurface question and the purchase boundary", paragraphs: [
        "An exploration enquiry should begin with the question the project needs to investigate and the evidence already available. Identify the survey area, wells or sample programme concerned, and the stage at which the proposed purchase will be used. Distinguish equipment supply or rental from field acquisition, processing and interpretation services. An acquisition system records measurements; a processing assignment and an interpretation study have separate inputs and outputs. Requesting all three under a broad exploration heading can produce quotations that answer different parts of the project while appearing commercially comparable.",
        "Define the expected handover between the field team, laboratory, data processor and subsurface reviewer. List existing equipment and datasets that must be used, together with their known limitations. State which design decisions remain with the project and which specialist proposals are requested. For an early enquiry with an incomplete programme, ask for a defined feasibility or scope review separately from a firm equipment schedule. Do not ask a vendor to infer survey coverage, measurement objectives or a complete evaluation programme solely from the proposed budget or geographic region."
      ] },
      { title: "Describe the acquisition system and its field interfaces", paragraphs: [
        "For seismic or other geophysical equipment, identify the proposed method, land or marine setting, sensor arrangement and recording requirements established by the survey design. Provide the existing system configuration when requesting components, including connection drawings and data interfaces. Ask which sensors, acquisition units, synchronization equipment, cables, power arrangements and handling accessories are included. Channel count or a recording-unit name cannot establish a complete compatible system. Any capability stated in the offer should be related to the specific configuration and the conditions supplied for review.",
        "For a field service, separate survey design, mobilization, acquisition and processing responsibilities. Identify access constraints and the project approvals required before site work, without treating a preliminary enquiry as permission to begin operations. Request the proposed quality-control records, equipment identification and treatment of interrupted or incomplete coverage. Name the deliverables needed during acquisition and at final handover. The responsible survey team should select the measurement programme and operating procedures; the buyer's role is to make scope, assumptions and acceptance evidence clear enough to review and price consistently."
      ] },
      { title: "Preserve location, depth and sample identity", paragraphs: [
        "Subsurface information loses value when its references are unclear. Specify the coordinate reference system, units, survey identifiers and any relevant vertical reference for the proposed data handover. For well records, identify the depth reference and how measurements are associated with the well and run. Request documentation of conversions rather than assume that values with similar labels share a common basis. A plotted image can look plausible even when its underlying position or depth is misunderstood, so reviewers need the reference information alongside the measurement files.",
        "For core or fluid sampling equipment, describe the sample type, intended analysis and preservation requirements determined by the programme. Identify the containers, labels, handling records and accessories included in the purchase. For a sampling service, agree how each sample will be associated with its location, interval and collection record, and how custody will be recorded during transfer. Keep the sampling scope separate from the laboratory analysis. Do not infer representativeness, preservation success or suitability for every test from the fact that a sample was collected or a container supplied."
      ] },
      { title: "Make data delivery testable before the final handover", paragraphs: [
        "List required raw measurements, processed datasets, quality-control records, navigation information and interpretation outputs as separate deliverables. Identify file formats and revisions, units, header conventions and metadata that the receiving team needs. When seismic data are requested in SEG-Y, specify the agreed revision and the header information required for import, rather than naming the format alone. The standard provides structures for trace and coordinate information, but the contract still needs an agreed delivery convention and documented use of relevant fields for the actual dataset.",
        "Request a representative sample delivery for the receiving team to test before the complete dataset is transferred. Check that files can be opened, references understood and expected identifiers reconciled with the delivery inventory. Define how corrupt, missing or inconsistent files will be reported and corrected, and who approves the final package. Keep processing history and the stated limitations with the delivered results. Importing a file successfully is one acceptance step; it does not establish that acquisition coverage is complete or that an interpretation has removed subsurface uncertainty."
      ] },
      { title: "Compare equipment, services and data rights on their own terms", paragraphs: [
        "An equipment quotation should distinguish purchased hardware, rental periods, accessories, software dependencies, maintenance and training. A service quotation should identify personnel scope, deliverable stages, review cycles and excluded processing or interpretation work. State the permissions needed to use existing datasets and the required rights to retain, share and reprocess new deliverables. Data ownership and software licensing are different questions, and neither should be assumed from possession of a file. Request clarification where a proprietary project format would prevent the planned handover to another discipline or application.",
        "Confirm manufacturing country for supplied equipment separately from the location of survey personnel, analysis or dispatch. Compare the schedule for equipment delivery with the time required for field access, sample transfer, processing and review. Submit the objectives, available records and delivery checklist to Oillinko for manual review and enquiry coordination. Mark missing inputs as open items rather than conceal them behind a broad package description. A useful offer identifies what can be supplied or assessed on the stated basis, while leaving geological conclusions, field approvals and unverified compatibility for the responsible project review."
      ] }
    ]
  },
  gas: {
    title: "Preparing gas treatment and compression package enquiries",
    description: "Define gas package enquiries with feed analysis, flow reference conditions, outlet quality, compression duties and clear package interfaces.",
    reviewedOn: "2026-10-03",
    topicIds: ["gas-dehydration-and-sweetening", "centrifugal-compressors", "filtration-and-coalescing", "flow-meters"],
    sections: [
      { title: "Locate the package within the gas supply chain", paragraphs: [
        "A gas-sector enquiry may concern a gathering facility, treatment plant, transmission station, liquefaction facility or receiving terminal. Identify the location of the proposed package in that chain and the stream entering it. Raw gas treatment, gas compression and liquid-product handling answer different process questions. State whether the requirement is a complete process package, replacement equipment, a spare part or an engineering assessment. An enquiry headed gas equipment can otherwise attract offers with different assumptions about the fluid phase and the work included.",
        "Provide a process flow diagram showing the proposed purchase boundary and the connections to existing systems. Mark the equipment to be retained and the changes already approved by the responsible design team. Distinguish sales-gas treatment from liquids separation or recovery, and identify any downstream specification that drives the purchase. Natural gas processing can include separation, water removal and removal of other constituents, but the required stages depend on the actual feed. A complete treatment train should not be assumed from a list of familiar equipment names."
      ] },
      { title: "Put composition and flow on a common reference basis", paragraphs: [
        "Attach the available gas analysis with sample location, date and the operating case represented. Identify its reported composition basis and the constituents relevant to the proposed equipment. Include available information on water, liquids, solids and variability rather than treating one dry-gas composition as a description of every incoming stream. Mark estimated values and missing analyses. The reviewer needs to know whether a sample describes normal production, a different operating period or only part of a blended feed before using it in a package assessment.",
        "Record minimum, normal and maximum flow with units and reference conditions. A normal or standard volumetric rate is not interchangeable with actual volume at the package inlet. State the reference pressure and temperature associated with the reported rate and identify the pressure basis of inlet and outlet figures. Provide the operating and design cases as separate inputs. When proposals use different flow conventions, request a reconciled comparison rather than assume that similar headline capacities describe the same amount of gas or the same equipment duty."
      ] },
      { title: "Separate moisture removal from contaminant treatment", paragraphs: [
        "For dehydration, state the required outlet moisture measure and the conditions attached to it. Water content and water dew point express different information, so retain the units and the project's accepted measurement basis. Explain whether the purchase is a new package, an addition to an existing system or replacement internals. Request the feed envelope, utilities and performance basis of the proposed arrangement. Do not accept a generic description of dry gas as a measurable guarantee or infer the required process from the available skid footprint alone.",
        "For sweetening or other contaminant-removal duties, identify the inlet constituents and the required outlet limits from the approved specification. Ask which treatment stages, regeneration equipment, chemicals and waste-stream interfaces belong to the offered scope. Moisture removal does not establish compliance with a separate contaminant limit. Where the treatment process remains undecided, price a defined study or process proposal separately from equipment supply. Keep handling of removed constituents and any emissions assessment within the responsible project's engineering and environmental review instead of assuming an unspecified disposal route."
      ] },
      { title: "Define compression and auxiliary equipment as one reviewed duty", paragraphs: [
        "A compressor enquiry needs the gas composition, suction and discharge cases, capacity range and required operating pattern. Identify the available driver supply and the limits of the existing installation. Request a technical response against those cases, including the offered package's stated operating envelope. Nominal power and connection size cannot demonstrate performance over every condition. For replacement parts, attach installed equipment identification and controlled records; matching an old part description should not be treated as approval of a changed gas composition or pressure requirement.",
        "List inlet separation or filtration, cooling, lubrication, controls and other auxiliaries required by the project. Ask the proposal to distinguish included components from external systems and identify what is needed to complete the package. State the required control and shutdown interfaces without prescribing their design in the purchasing schedule. Workshop tests, package integration and site acceptance should have separate descriptions. A machine-only price may exclude equipment, wiring, field connections or engineering work that another offer includes, making the apparent price comparison misleading."
      ] },
      { title: "Make the commercial comparison traceable to the technical basis", paragraphs: [
        "Request an itemized response with drawings, assumptions, deviations and the acceptance evidence specified by the project. Identify how performance conditions relate to the feed analysis and which outstanding inputs must be resolved before manufacture. Keep pressure-containing equipment records, material documentation, instrument calibration and package performance results distinct. Each addresses a different part of the requirement. For gas measurement, include the reported quantity, reference conditions and agreed interface so a meter or analyzer quotation can be reviewed against the result the receiving system actually needs.",
        "Separate manufacturing lead time, document review, transport and site attendance in the schedule. Confirm the manufacturing country of each supplied item independently of its dispatch location. Compare preservation, spares, consumables and maintenance documentation alongside the equipment price. Submit the gas analysis, duty cases and package boundary to Oillinko for manual review and enquiry coordination. Unconfirmed data should remain visible in the response; a sector listing does not establish an available package, a selected process or a delivery and performance commitment for an unidentified installation."
      ] }
    ]
  },
  decommissioning: {
    title: "Defining decommissioning and site restoration procurement scopes",
    description: "Prepare retirement enquiries using an asset inventory, approved work boundaries, waste characterization, recovery responsibilities and close-out evidence.",
    reviewedOn: "2026-10-03",
    topicIds: ["plug-and-abandonment-service-coordination", "facility-dismantling-and-materials-recovery", "soil-and-groundwater-remediation", "industrial-waste-treatment-and-disposal-support"],
    sections: [
      { title: "Start with the retirement objective and asset inventory", paragraphs: [
        "Decommissioning procurement can involve a well, selected process equipment, a pipeline, a complete facility or a contaminated site. Describe the retirement boundary and the intended end condition before requesting a package price. Prepare an inventory linking each asset to its location, drawings, available condition records and the proposed disposition. Identify anything that remains in service or is outside the contract. A site name or an approximate steel mass cannot define the work needed to retire all of its systems or restore the surrounding area.",
        "Reference the approved project programme and the applicable local review requirements. Offshore retirement, onshore dismantling and environmental restoration may involve different authorities and acceptance evidence. As one jurisdictional example, the UK offshore framework uses decommissioning programmes that identify infrastructure and its proposed solution. That does not establish the requirements for a Turkish project or another location. The enquiry should name the actual governing basis and identify unresolved approvals so a supplier's commercial proposal is not mistaken for an approved retirement plan."
      ] },
      { title: "Keep well retirement separate from facility removal", paragraphs: [
        "Where wells are included, attach the controlled well information and the approved abandonment scope available for procurement review. Identify whether the enquiry concerns tools, materials, specialist engineering, execution support or a coordination service. Record the required verification and reporting deliverables without inventing a barrier arrangement from a generic equipment category. The well operator's responsible engineering and approval process must establish the programme. A proposal for surface equipment removal does not establish that a well has been permanently abandoned or that the required verification is included.",
        "For facility assets, describe the interfaces between preparation, examination, dismantling, handling and transport. State who supplies the verified readiness information required before a contractor's work begins. Identify surveys or records still needed to assess mass, dimensions, access and structural condition. Request an engineering scope where the necessary handling design is not already established. An estimated tonnage or photograph can support an initial discussion, but it cannot confirm lifting suitability or determine how an unidentified installation should be cut, isolated or dismantled."
      ] },
      { title: "Characterize materials before valuing recovery", paragraphs: [
        "Prepare a materials schedule separating equipment considered for reuse, recyclable material and waste requiring a defined treatment route. Identify the owner of each stream and the party responsible for its characterization. Previous service, coatings, residues and investigation results can affect handling and the proposed destination. Record what has been examined and what remains unknown. A material's metallic appearance or its scrap value does not demonstrate that it is uncontaminated, suitable for unrestricted recycling or accepted by a particular receiving facility.",
        "Ask offers to state the assumptions behind recovery credits, transport quantities and disposal charges. Separate estimated mass from weighed quantities and define the records used for final reconciliation. Identify whether cleaning, testing, sorting, packaging and receiving-facility acceptance are included. Request supporting authorizations where they are required for the actual waste stream and jurisdiction. Recovery income should remain a stated commercial assumption until the material has the necessary assessment and a confirmed destination; it should not conceal a missing waste-treatment allowance in the package total."
      ] },
      { title: "Give restoration work its own measurable end condition", paragraphs: [
        "For soil or groundwater work, attach the available investigation data, sample locations, laboratory results and site history. Identify the contaminants and affected area described by that evidence. Distinguish an investigation enquiry from treatment, monitoring or a complete remediation assignment. Ask the responsible environmental reviewer to establish the objectives and acceptance basis for the site. A proposal to remove a stated volume of soil is not automatically a proposal to achieve every restoration objective, particularly when the extent of contamination remains uncertain.",
        "Define how further findings will affect quantities, treatment scope and approval of additional work. Request a sampling and reporting scope with clear responsibilities and measurement locations. Identify whether waste transport, treatment, imported materials, reinstatement and later monitoring form part of the offer. Keep land condition and groundwater condition separate where they require different evidence. A completion photograph may show visible reinstatement, but laboratory results, survey records or other specified evidence may still be needed to demonstrate the agreed environmental end condition."
      ] },
      { title: "Compare completion evidence and commercial responsibilities", paragraphs: [
        "Use milestones that distinguish surveys, approved preparation, removal, transport, receipt at the destination and final close-out. Identify the information each milestone requires and who accepts it. Ask for a dossier linking asset identifiers to work records, material movements, weighing evidence and any specified environmental results. Record limitations and retained assets explicitly. Removing equipment from its original position and completing every contractual retirement obligation are different milestones, and the quotation should show which evidence supports its proposed definition of completion.",
        "Compare mobilization, site access, temporary facilities, handling equipment and uncertain quantities before the final price. Set out the mechanism for reviewing changes rather than give an undefined authorization for extra work. Send the asset inventory, available surveys and intended end condition to Oillinko for manual requirement review and coordination. Requests for specialist services must remain subject to the actual scope and acceptance arrangements. Catalogue coverage is a way to organize the enquiry; it does not appoint a contractor, certify a disposal destination or approve a retirement method."
      ] }
    ]
  },
  power: {
    title: "Defining an industrial power and utilities package",
    description: "Prepare power and utility enquiries with distinct load cases, electrical and process interfaces, package boundaries and acceptance evidence.",
    reviewedOn: "2026-10-02",
    topicIds: ["transformers-and-switchgear", "boilers-and-waste-heat-recovery", "steam-traps-and-condensate-systems", "centrifugal-pumps"],
    sections: [
      { title: "Create a utility schedule before combining equipment prices", paragraphs: [
        "Industrial power and utility enquiries can cover electricity, steam, cooling water, compressed air and the machines that serve them. These systems support related activities but have different performance measures and physical interfaces. Prepare a utility schedule showing each source, consumer and required connection. Identify whether the purchase concerns a complete new system, an additional consumer, a replacement machine or a maintenance service. This distinction helps establish whether the enquiry needs a design study, an equipment quotation or both, instead of assuming that every equipment package includes responsibility for the whole plant network.",
        "Record the approved demand cases for each utility, with units, required conditions and the source of the information. Separate normal consumption, peak demand and any standby case defined by the project. Identify seasonal or production changes and mark estimates that still require confirmation. Ask proposals to explain their assumptions and included capacity against those cases. Adding nominal equipment capacities together can conceal different duty descriptions, so the purchasing comparison should retain the load schedule and the responsible team's design basis alongside the commercial total."
      ] },
      { title: "Provide the electrical design and machine interfaces", paragraphs: [
        "For electrical equipment, supply the current single-line diagram, voltage and frequency requirements, load information and installation environment. The assigned electrical design should define protection, fault ratings, earthing arrangements and any location approvals. Ask the proposal to identify its scope against that design, including enclosures, controls, cables and accessories where specified. A motor power rating, transformer capacity or familiar switchgear description cannot establish that the offered assembly meets every interface of the existing distribution system. Keep unresolved design inputs visible rather than treating them as supplier-confirmed facts.",
        "For machines, distinguish the process load from the electrical supply and control interface. Identify starting or changing-duty information required by the responsible reviewer, along with mounting, drive and receiving-control arrangements. For standby or uninterrupted supplies, provide the loads covered and the project's autonomy and availability requirements. Ask which functions, batteries, fuel-related equipment or external connections belong to the offered package. A quotation for a principal machine can exclude the supporting equipment needed to connect it, and a replacement may require review beyond its nameplate power."
      ] },
      { title: "Draw the steam, heat and condensate boundary", paragraphs: [
        "A steam system includes generation, distribution, the equipment using steam and the handling or return of condensate. Identify the part of this network covered by the purchase. For a boiler or heat-recovery package, provide the required steam conditions and demand cases, available fuel or heat-source data, feedwater specification and existing interfaces. Ask where responsibility for process design, water treatment, controls and connections begins and ends. A boiler-only offer and a complete utility package should not be compared as though they deliver the same installed scope.",
        "For steam distribution accessories or condensate equipment, provide the approved layout, connection details and the operating information relevant to the actual location. Identify whether the assignment supplies individual components, assesses the network or performs maintenance. Request a technical response against the project's design conditions and material requirements without assuming that a nominal connection size selects every component. Keep any performance assessment separate from the purchase price. General energy-improvement guidance does not establish a guaranteed saving or prescribe a suitable arrangement for an unidentified industrial steam system."
      ] },
      { title: "Keep cooling and compressed-air requirements separate", paragraphs: [
        "For cooling duties, identify the medium, heat load, temperature cases, available utilities and the points where the offered system connects to the plant. Include the environmental and water information needed for review when relevant. State which pumps, heat exchangers, controls, treatment interfaces and connecting pipework are included. A circulation-flow figure and a cooling-duty figure describe different requirements. Ask the technical response to address both against the actual installation rather than compare cooling equipment solely by its footprint or a headline capacity.",
        "For compressed air, provide the required delivery conditions, demand profile and specified air quality at the relevant consumption points. Identify the existing compressor, receiver, dryer, filtration and distribution boundaries where those records are available. Ask whether the offer covers a complete train or selected components and which performance conditions apply to the proposed configuration. Record measurement, drain, control and maintenance interfaces for review. The description of a compressor or dryer alone does not define the quality delivered through every existing downstream connection."
      ] },
      { title: "Compare installed scope and the evidence at handover", paragraphs: [
        "Use a responsibility schedule to identify supply, transport, installation, integration, commissioning and continuing support. Request the drawings, equipment identification and acceptance records specified for each package. Distinguish workshop checks from site acceptance against the actual connected system. List outstanding inputs and who must resolve them before manufacture or installation proceeds. If a proposed package changes the installed arrangement, keep the required engineering review and approvals separate from routine equipment delivery; a delivered component is not automatically an accepted plant modification.",
        "Compare exclusions, delivery milestones, spares and documentation before assessing the overall commercial offer. Confirm manufacturing country for the supplied equipment separately from dispatch location and project destination. A multi-utility enquiry can be submitted to Oillinko as a controlled equipment list with drawings and the load schedule attached. Our team reviews the requirement and coordinates clarification. The sector catalogue helps identify relevant equipment and service families; it does not establish a reserved stock position, an appointed contractor or a guaranteed outcome for the combined utility network."
      ] }
    ]
  },
  refining: {
    title: "Preparing refinery equipment and turnaround enquiries",
    description: "Organize refinery enquiries by unit and equipment tag, separating replacement and revamp duties, installation interfaces and turnaround handover records.",
    reviewedOn: "2026-10-02",
    topicIds: ["shell-and-tube-heat-exchangers", "trays-structured-packing-and-distributors", "shutdown-planning-and-mechanical-support", "inspection-ndt-and-material-testing"],
    sections: [
      { title: "Identify the process unit and the reason for the purchase", paragraphs: [
        "Refining includes separation, conversion and treatment activities, with different equipment and service requirements across the plant. Name the actual process unit, system and equipment tag before describing a requested product family. Explain whether the assignment replaces an existing item, restores its condition or changes the process duty. A new exchanger, replacement column internals and inspection during a shutdown can belong to the same project while requiring different technical inputs. Unit capacity alone does not define the specification of every item within that project.",
        "Prepare a controlled equipment and task schedule with identifiable line items. Reference the current drawings and data sheets, and distinguish confirmed quantities from provisional allowances. Separate materials supply, fabrication, examination, field work and commissioning support where their boundaries differ. Ask responses to retain the item references so technical exceptions and commercial exclusions can be reconciled. A single package price can be useful, but it still needs enough detail to show which work and equipment it covers and what remains with the owner or another contractor."
      ] },
      { title: "Keep current service and mechanical records together", paragraphs: [
        "For replacement equipment, provide the installed identification and available design records alongside the current process duty. Identify changes in fluid composition, operating cases or approved material requirements that need assessment. Photographs help describe access and condition, but controlled drawings are needed for critical interfaces. Ask whether an offered item reproduces the accepted arrangement or proposes an alternative requiring review. Similar dimensions, a matching nominal size or an old purchase description cannot demonstrate that every process and mechanical requirement is still covered.",
        "For heat-transfer equipment, define both process sides, the required thermal result and the mechanical connection information. State whether the scope is cleaning, inspection, tube replacement or a complete equipment purchase. Ask which assessment and acceptance records support the proposed work. A restored mechanical condition and a demonstrated thermal result are different questions. Where internal condition is unknown, separate the initial examination from later repair approval, so an indicative allowance is not mistaken for a fixed scope supported by an inspection that has not yet occurred."
      ] },
      { title: "Distinguish column replacement from a process revamp", paragraphs: [
        "For trays, packing, distributors and supports, provide the vessel and internal arrangement drawings, material requirements and relevant process information. Identify the existing components to be retained and the proposed replacement boundary. Ask for the dimensions and installation assumptions of the actual offered assembly. An internal component must be reviewed against its supporting interfaces as well as its intended function; a column diameter or a material name alone leaves important parts of the enquiry undefined. Record any survey needed before manufacturing dimensions can be accepted.",
        "If the objective changes separation performance or throughput, identify the approved performance basis and the engineering assessment requested. A like-for-like replacement quotation and a process revamp proposal can involve different studies, guarantees and site work. Ask the response to explain those boundaries and the data needed to assess them. Keep process design, mechanical design, fabrication and installation responsibilities visible. The procurement enquiry can request an assessment without inventing a guaranteed capacity increase or assuming that new internals resolve every constraint in the surrounding process unit."
      ] },
      { title: "Link turnaround work to a defined readiness and handover", paragraphs: [
        "A turnaround enquiry should identify the equipment list, planned work window and tasks covered by the proposed team. Describe the required readiness conditions and the party responsible for making the worksite available under the site's authorized process. State access, utilities, handling, supervision and other interfaces needed to price the service. Ask the response to distinguish preparation, mobilisation, execution and completion milestones. A duration for hands-on work is not necessarily the elapsed shutdown period, especially when other packages or unresolved condition assessments affect the sequence.",
        "Identify how additional findings will be documented, priced and approved before the scope changes. A planned service can expose condition information that was unavailable during quotation, but this should not create an undefined authorization to perform extra work. Request an agreed reporting and decision process, with separately stated allowances where appropriate. Keep the responsible technical acceptance separate from commercial approval. The enquiry should define responsibilities and evidence; it should not substitute a generic purchasing guide for the site's work controls or prescribe an operating procedure."
      ] },
      { title: "Use a traceable completion dossier in the comparison", paragraphs: [
        "Define the material records, examination coverage, test documentation and dimensional or functional evidence required for each line item. Identify witnessing points and the authority responsible for acceptance. Ask for a dossier linked to the actual equipment tags and delivered parts, including limitations and approved deviations. An examination report, material certificate and performance demonstration address different questions. Specify what the project needs rather than accepting a general reference to certificates as proof of every required inspection or the fitness of the complete process installation.",
        "Confirm the dispatch point, delivery destination and manufacturing origin of supplied items separately. Include preservation, spare parts, site attendance and document delivery in the commercial comparison where required. Mark information still awaiting an owner decision and identify its effect on the offer. Send the equipment schedule or turnaround scope to Oillinko for manual review and coordination, using the available records rather than an assumed final specification. Catalogue coverage describes requirement families; availability, appointments, acceptance and delivery commitments require confirmation for the actual proposal."
      ] }
    ]
  },
  offshore: {
    title: "Preparing an offshore or marine equipment enquiry",
    description: "Plan offshore and marine equipment enquiries with clear seawater duty, installation interfaces, inspection records and delivery boundaries.",
    reviewedOn: "2026-10-02",
    topicIds: ["cathodic-protection-equipment", "wellheads-and-christmas-trees", "inspection-ndt-and-material-testing"],
    sections: [
      { title: "Begin with the asset and the work package", paragraphs: [
        "Offshore and marine purchasing covers several different installations: production platforms, subsea equipment, support vessels and the shore-based facilities that serve them. Identify the asset and the system before selecting a catalogue category. A seawater utility valve, a pressure-containing production component and a vessel treatment package can all appear in a marine enquiry while having different design, inspection and approval requirements. Explain whether the work is a new installation, a replacement, maintenance or a specialist service. This gives a reviewer the context needed to interpret the technical schedule.",
        "Break a mixed request into identifiable line items and work packages. Separate equipment supply, fabrication, inspection, installation support and commissioning when different parties perform them. Provide a controlled bill of quantities and the available drawings, with each clarification linked to an item number. Mark information that is still provisional. A complete package may be convenient commercially, but the proposal still needs to identify its boundaries and the interfaces supplied by the buyer, shipyard, operator or another contractor."
      ] },
      { title: "Describe seawater and external exposure separately", paragraphs: [
        "State which parts contact seawater or another process fluid and which parts face only the external marine environment. Give the relevant fluid analysis, operating and design conditions, and any approved material or coating requirements. Salinity, suspended matter, treatment chemicals and temperature can affect the engineering review. An item described as marine grade is not a complete material specification. Identify the specified body, trim, seals, fasteners and protective system where these are controlled by the project.",
        "For material-sensitive duties, request a documented response to the required grades and supporting records. Distinguish a proposed alternative from a confirmed match. Corrosion protection can involve coatings, cathodic protection, material selection and monitoring, with different responsibilities for design and supply. Provide the approved basis for the relevant system. Do not infer manufacturing origin from a brand, sales office or shipping point; state any origin restriction and ask for confirmation for each offered item."
      ] },
      { title: "Check installation and utility interfaces", paragraphs: [
        "Space, maintenance access, mass and connecting geometry matter on a vessel or offshore installation. Provide the current arrangement drawings and the dimensions needed to evaluate replacement or installation. Record flange or thread references, electrical supply and control interfaces, and any classification or environmental requirements set by the responsible design. Equipment offered with an actuator or control panel should identify the included assembly and the utilities it requires. Similar nominal sizes do not establish compatibility with an existing connection or foundation.",
        "Subsea and topside requirements should be distinguished explicitly. Water depth, access method and intervention interfaces can change the equipment or service scope, but the buyer should use the approved project basis rather than infer operating limits from a general product family. List integration, mounting and site testing as separate responsibilities. Ask how the offered package will be checked against the supplied drawings and what information must be confirmed before release for manufacture."
      ] },
      { title: "Connect approvals and inspection to the actual equipment", paragraphs: [
        "Approval evidence must relate to the particular product and installation. For example, ballast water management systems used for convention compliance require the applicable Administration's type approval under the relevant approval framework. This is a different question from whether a company supplies marine equipment. The project team should identify the vessel, flag, applicable requirements and the survey or commissioning scope. Ask for the offered configuration and its documented approval coverage, and keep installation acceptance separate from a broad catalogue statement.",
        "For other packages, define the inspection and release records appropriate to their function. Material traceability, examination reports, pressure-test records and functional checks are different forms of evidence. Specify the required dossier, witnessing points and acceptance authority before comparing offers. If the work is a service, state the examination coverage, access arrangements and required personnel qualifications. A report should identify the examined asset and any limitations so it can support the intended engineering decision."
      ] },
      { title: "Plan preservation, logistics and handover", paragraphs: [
        "Identify the dispatch point, delivery destination and required arrival date separately. The project schedule may depend on a vessel call, yard period or offshore work window, so distinguish production lead time from transport and mobilisation. Confirm packing dimensions, mass, preservation and storage instructions. Handling or lifting provisions need the appropriate engineering and documentation; inclusion of a fabricated frame does not establish that every offshore lifting requirement is satisfied.",
        "Compare the complete supply or service scope before the final commercial total. Identify spares, accessories, field connections, documentation, training and attendance as inclusions or exclusions. Record deviations for technical review and keep any promised delivery subject to the actual proposal. Submit the specification or whole equipment list to Oillinko when the requirement spans several categories. Our team reviews the enquiry and coordinates clarification; catalogue coverage does not establish reserved inventory, an appointed specialist or project approval."
      ] }
    ]
  },
  water: {
    title: "Defining a water treatment and environmental equipment package",
    description: "Prepare water treatment equipment requests using feed analysis, required outlet quality, utilities, waste streams and acceptance evidence.",
    reviewedOn: "2026-10-02",
    topicIds: ["metering-and-dosing-pumps", "calibration-and-instrument-repair", "inspection-ndt-and-material-testing"],
    sections: [
      { title: "Identify the water stream and the intended result", paragraphs: [
        "Water and environmental equipment enquiries begin with the source and destination of the stream. Produced water, intake water, industrial process water, cooling water and wastewater have different characteristics and treatment objectives. State whether the outlet is intended for reuse, reinjection, further treatment or a permitted discharge. The responsible project team should define the required quality and applicable acceptance basis. A label such as clean water or oily water is not enough to select a treatment process or compare performance proposals.",
        "Describe the current installation and the change required. A new treatment train, replacement filter, dosing skid and monitoring instrument are different packages even when they serve the same water system. Identify what already exists and what the offered equipment must connect to. Where the process has not been selected, request a defined study or treatment proposal rather than assume that equipment supply includes process design. Keep investigation, design, supply, installation and operating support visible as separate work boundaries."
      ] },
      { title: "Supply representative feed data and operating cases", paragraphs: [
        "Provide the available water analysis with sample locations, dates and the operating conditions represented. Relevant information can include suspended and dissolved constituents, hydrocarbons, salinity, temperature and the chemicals already used in the process. Identify which values are measured, estimated or still awaiting analysis. Produced water can contain a mixture of salts, hydrocarbons, solids and residual treatment chemicals; removing one constituent does not establish that the complete outlet quality has been achieved.",
        "Define flow cases and expected variability, including continuous, intermittent and peak conditions where they matter. A single average flow can hide a short-duration load that affects buffer capacity or treatment performance. Describe seasonal changes, cleaning streams or process events that alter the feed. If representative data are unavailable, agree the sampling, laboratory or trial work needed to reduce uncertainty. The proposal should identify the feed envelope on which its performance assessment depends and explain what happens commercially when the actual feed differs."
      ] },
      { title: "Compare a treatment train and its supporting utilities", paragraphs: [
        "Treatment may require several stages with different purposes. Separation, filtration, chemical dosing and monitoring should be considered against the required result and the actual stream, not selected from their names alone. Ask the technical response to explain each included stage, its design basis and the interfaces between stages. Identify tanks, pumps, piping, instruments and controls included with the package. A price for the principal treatment vessel can omit the equipment needed to operate or connect it.",
        "List electrical supply, available pressure, wash water, instrument air and other utilities required by the proposed arrangement. Record space, connection geometry and maintenance access. For dosing, provide chemical identity, concentration, compatibility requirements and the required control interface rather than only a pump flow. Clarify which consumables, initial charges and spare elements are included. Ask for expected consumption and maintenance information on the documented duty, with assumptions stated instead of treating an indicative figure as a guaranteed operating cost."
      ] },
      { title: "Define waste handling and performance acceptance", paragraphs: [
        "A treatment package can create concentrated waste, sludge, spent filters, backwash or cleaning streams. Ask the proposal to identify these outputs, their connection points and the responsibilities for collection, treatment and disposal. The environmental assessment and applicable project requirements should guide these arrangements. General industry guidance is useful context, but it does not replace the site's permits or establish a universal discharge limit for every jurisdiction and water stream.",
        "Agree how performance will be assessed: feed conditions, outlet parameters, measurement methods, sampling points and the duration or operating cases of the acceptance work. Distinguish a workshop function test from a site demonstration with the actual feed. If independent sampling or laboratory analysis is required, state who supplies it and which scope is needed. Define the response to results outside the agreed basis. An outlet-quality statement is useful only when its conditions, measurement evidence and acceptance responsibilities are clear."
      ] },
      { title: "Keep monitoring, service and delivery boundaries clear", paragraphs: [
        "Measurement equipment should be matched to the range, fluid matrix and installation. State sample conditioning, process connections, required outputs and maintenance access where relevant. For calibration or instrument repair, identify whether the scope covers an individual sensor, transmitter output or the complete installed loop. Request results and uncertainty appropriate to the use, and agree any conformity decision rule. A general calibration certificate cannot establish performance for every constituent measured in a water treatment process.",
        "Compare delivery, installation, commissioning and support as distinct items. Confirm the manufacturing origin of equipment separately from the delivery country and service location. Identify documentation, training, spare parts and technical attendance included in the offer. Where the requirement is still developing, send the available analysis, layout and desired result to Oillinko with the uncertainties clearly marked. Our team reviews the information and coordinates the enquiry; a catalogue entry describes a requirement family rather than a preselected process, approved supplier or guaranteed treatment result."
      ] }
    ]
  }
};
