import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("air-freight-equipment-quotes-gross-volumetric-weight")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>An equipment air-freight quote should begin with the packed cargo, not the net weight on an equipment datasheet. A protective crate, pallet and accessories can change both physical weight and occupied space. A meaningful comparison uses the same package list and asks each forwarder to identify its chargeable-weight calculation. Without that common dataset, different totals may reflect different assumptions rather than a true difference in the price of the same service.</p>
    <p className={paragraph}>This matters for urgent spares, instruments and larger equipment sent by air. The purchaser may know the weight of the main item long before packing is finalized. That early information is useful for an estimate, but it should remain labelled preliminary. Ask what data must be confirmed before booking and when a quoted amount can change. Keep the estimate, revised package list and final freight proposal connected through clear references.</p>
    <h2 id="use-gross-weight-and-external-package-dimensions" className={heading}>Use gross weight and external package dimensions</h2>
    <p className={paragraph}>Prepare a row for every package with its identifier, external length, width and height, units and gross weight. Include the pallet and protective packaging in the cargo description. State whether the figures are measured or estimated, and who supplied them. Distinguish the number of equipment items from the number of packages: one assembly may travel in several cases, while several small items may be packed into a single crate.</p>
    <p className={paragraph}>Record protrusions, irregular shapes and any uncertainty in the declared dimensions for the forwarder to assess. Ask how measurements will be confirmed and how discrepancies will affect the quotation. The <Link className={link} href={postUrl(getPost("export-packing-oil-gas-equipment-rfq")!)}>equipment export-packing RFQ guide</Link> addresses protection and package records. Use that packing scope to produce a reliable cargo list, rather than treating freight dimensions as a reason to reduce protection without approval.</p>
    <h2 id="ask-for-the-chargeable-weight-basis" className={heading}>Ask for the chargeable-weight basis</h2>
    <p className={paragraph}>The <a className={link} href="https://www.dhl.com/us-en/home/global-forwarding/freight-forwarding-education-center/calculating-chargeable-weights.html" target="_blank" rel="noopener noreferrer">DHL chargeable-weight explainer</a> compares gross physical weight, including packaging, with a dimensional weight derived from cargo volume. Its air-freight example uses dimensions in centimetres divided by 6,000, while warning that carrier ratios can differ. Use that relationship to understand a proposal. Confirm the actual factor, measurement units, rounding and rating basis with the forwarder quoting the shipment.</p>
    <p className={paragraph}>Ask whether the comparison is performed per package or across the consignment and how the quoted service applies its rules to the declared cargo. Also identify minimum charges or other rating conditions stated in the offer. A volume calculation alone does not reconstruct the entire freight bill. The buyer needs the applicable calculation and service scope, not an assumption that a familiar divisor governs every express, general cargo or specialist movement.</p>
    <h2 id="use-a-labelled-example-to-check-the-arithmetic" className={heading}>Use a labelled example to check the arithmetic</h2>
    <p className={paragraph}>Consider one illustrative crate measuring 100 by 80 by 75 centimetres externally, with a gross weight of 70 kilograms. Assume, solely for this example, a divisor of 6,000 cubic centimetres per kilogram and no additional rounding. The volume is 600,000 cubic centimetres and the resulting dimensional weight is 100 kilograms. Under an agreed rule that compares these two values for this one package, the higher basis would be 100 kilograms.</p>
    <p className={paragraph}>Now suppose the same illustrative crate weighs 125 kilograms gross. Its calculated dimensional weight remains 100 kilograms, so the higher basis becomes 125 kilograms under the same assumptions. Neither example supplies a rate or a final payable charge. Use the arithmetic to identify which input controls the comparison, then ask the forwarder to confirm its actual rules. If its quoted chargeable weight differs, resolve the factor, dimensions or rounding before assuming an error.</p>
    <h2 id="describe-handling-constraints-before-requesting-a-rate" className={heading}>Describe handling constraints before requesting a rate</h2>
    <p className={paragraph}>Tell the forwarder whether the cargo is non-stackable, has a required orientation or needs special handling review. Supply the available lifting and package drawings where relevant. Ask the provider to confirm acceptance and the quotation assumptions for the actual service and route. A standard price calculated from volume and weight should not be treated as confirmation that a heavy, unusually shaped or restricted package can travel as described.</p>
    <p className={paragraph}>Describe the contents accurately, including relevant information about batteries, liquids or other components that may require classification by qualified parties. Do not omit accessories to make a cargo description appear simpler. The provider should identify documents needed to assess the shipment. This procurement guide does not assign a dangerous-goods classification or prescribe packing instructions. Missing cargo information should lead to a clarification and an appropriately conditional quote, rather than an unsupported declaration of unrestricted carriage.</p>
    <h2 id="compare-the-complete-transport-boundary" className={heading}>Compare the complete transport boundary</h2>
    <p className={paragraph}>Identify collection and delivery locations, the intended airports where established, and whether the request is airport-to-airport or includes inland services. State cargo readiness and the required delivery milestone separately. The <a className={link} href="https://www.iata.org/en/publications/newsletters/iata-knowledge-hub/air-cargo-tariffs-and-rules-what-you-need-to-know/" target="_blank" rel="noopener noreferrer">IATA overview of air-cargo tariffs and rules</a> distinguishes transportation rates from additional services and charges. Ask each offer to show included and excluded handling, screening, pickup, delivery and other applicable charge categories.</p>
    <p className={paragraph}>Request the currency, quote validity and basis for charges that cannot yet be fixed. Ask what happens if the cargo is remeasured, packing changes or the shipment is not ready on the stated date. The <Link className={link} href={postUrl(getPost("quotation-validity-equipment-lead-time-delivery-milestones")!)}>quotation validity and delivery-milestone guide</Link> helps separate those dates. A proposed transit time should have a defined starting event and endpoint; it should not be silently interpreted as a guaranteed site-delivery date.</p>
    <h2 id="control-consolidation-and-package-revisions" className={heading}>Control consolidation and package revisions</h2>
    <p className={paragraph}>For a multi-vendor shipment, prepare a consolidated list that retains each package identifier and its readiness status. Do not simply add equipment net weights from separate offers and call that the shipment gross weight. The <Link className={link} href={postUrl(getPost("consolidated-shipments-and-multi-vendor-orders")!)}>consolidated shipments guide</Link> covers the coordination boundary. Ask the forwarder how a split collection, changed package count or partial dispatch affects the quoted service and calculation.</p>
    <p className={paragraph}>Issue a revised cargo list when packing is finalized, with the previous revision clearly superseded for booking purposes. Preserve a record of what changed and ask whether the freight proposal needs revalidation. If repacking is proposed, obtain the appropriate equipment and logistics review before approving it. A smaller external volume can alter a rating calculation, but that fact does not establish whether a different package provides the protection, handling or documentation the equipment requires.</p>
    <h2 id="build-a-comparison-that-explains-the-total" className={heading}>Build a comparison that explains the total</h2>
    <p className={paragraph}>Compare offers using the same final package list, locations and service boundary. Show gross weight, volume, factor, declared chargeable weight, included charges, exclusions and outstanding acceptance questions in separate fields. Where an offer uses estimated cargo data, mark that status prominently. A low headline rate can be less informative than a complete proposal whose assumptions can be traced to the actual shipment. Avoid assigning fixed costs to unspecified services just to make totals look comparable.</p>
    <p className={paragraph}>Send the package list, readiness information and required transport boundary through Oillinko&apos;s <Link className={link} href="/oil-and-gas/services/freight-expediting-and-project-logistics">freight, expediting and project logistics service page</Link> for manual coordination. Ask for a quotation that identifies its calculation and conditions, then reconcile it with the final cargo before booking. The result should be a reviewable proposal for a defined movement, with remaining uncertainties visible and no invented rate, capacity reservation or delivery commitment.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
