import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post=getPost("api-6a-psl-pr-levels-wellhead-equipment-buyers-guide")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading="mt-12 text-xl font-bold";
const link="text-accent underline underline-offset-4";
const faqs=[
  {q:"Is the highest API 6A PSL automatically the correct purchasing choice?",a:"No. The applicable edition links minimum and additional requirements to the product, pressure rating, material class and service basis. The purchaser should use the governing project specification and qualified engineering review rather than selecting the largest number as a general quality upgrade."},
  {q:"Does a PR designation prove that every delivered item was individually performance tested?",a:"No. Design-validation evidence and routine production acceptance records serve different purposes. The quotation should identify the validated design, its applicable envelope and the item-specific manufacturing, inspection and pressure-test records supplied with the order."},
  {q:"Can ISO 10423 be written as a simple substitute for API 6A?",a:"Do not assume equivalence from the titles alone. Identify the exact editions and project precedence. ISO 10423:2022 states that it supplements API Spec 6A, 21st edition, with specified exceptions."}
];

export default function Page(){return <><BlogPostHeader post={post}/><Prose>
<p className={paragraph}>A wellhead enquiry that says “API 6A, highest PSL and PR” may sound conservative, but it is not a complete technical requirement. API 6A applies to defined wellhead and tree products, and its product specification level and performance-validation requirements must be read in the context of the selected edition, equipment type, rated working pressure, temperature class, material class, service conditions and purchaser supplements. Treating the abbreviations as generic quality grades can produce an offer that is expensive, technically inconsistent or impossible to compare.</p>
<p className={paragraph}>This guide helps buyers organize an RFQ and review supplier evidence. It does not reproduce proprietary tables or select a level for a specific well. Those decisions belong to the applicable standard, operator specification and responsible engineering authority. The practical goal is to make every designation traceable to a product and to distinguish design qualification from the records created for the delivered item.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="API 6A wellhead equipment RFQ workflow separating product identity, service class, PSL requirements, PR validation and item records."/><figcaption className="mt-3 text-sm text-muted">PSL and PR only become useful procurement requirements when connected to the exact product, edition and evidence package.</figcaption></figure>

<h2 id="begin-with-the-product-and-edition" className={heading}>Begin with the product and edition</h2>
<p className={paragraph}>API’s official description of <a className={link} href="https://www.api.org/products-and-services/standards/important-standards-announcements/spec-6a" target="_blank" rel="noopener noreferrer">API Specification 6A, 21st edition</a> identifies it as the specification for wellhead and tree equipment. API’s publication catalogue lists products within scope such as heads and hangers, adapter and spacer spools, connectors, valves, chokes, actuators, safety-valve assemblies and tree assemblies. A request for an “API 6A wellhead” must therefore be broken into the actual components, quantities and interfaces being purchased.</p>
<p className={paragraph}>State the governing edition, addenda and project precedence. API’s current standards plan records the 21st-edition addenda through Addendum 4 and also shows a 22nd edition in development. A draft or planned edition does not automatically govern a purchase. Suppliers should quote against the edition named in the contract and list deviations if their design dossier or licence scope uses a different basis.</p>

<h2 id="understand-what-psl-controls" className={heading}>Understand what PSL controls</h2>
<p className={paragraph}>Product specification level, or PSL, organizes technical quality requirements for manufacturing and acceptance. API’s catalogue states that API 6A establishes four PSL designations, while the 21st-edition announcement explains that the quality requirements were reorganized by activity rather than repeated under separate PSL sections. This matters when reviewing a quotation: the purchaser should not rely on a legacy checklist or assume that one sentence about PSL captures every applicable material, examination, welding, testing, marking and record requirement.</p>
<p className={paragraph}>The required PSL is not selected in isolation. API specifically notes that the 21st edition introduced required minimum PSL values depending on pressure rating and material class, and revised PSL 4 toward critical-service equipment. The buyer should provide the service basis and let the governing standard and project specification establish the minimum requirement. Any requested enhancement should identify the exact clause or deliverable instead of using “higher PSL” as a substitute for engineering.</p>

<h2 id="keep-pr-validation-separate-from-production-acceptance" className={heading}>Keep PR validation separate from production acceptance</h2>
<p className={paragraph}>Performance requirement terminology concerns validation of a product design under the applicable specification. It should not be confused with routine pressure testing, material traceability or inspection of every production item. A design-validation report may support a product family or qualified configuration within a stated envelope; it does not automatically prove that the delivered serial number received every production examination required by the order.</p>
<p className={paragraph}>Edition control is especially important here. API’s 21st-edition announcement says PR1 was removed from the design-validation annex. Buyers working from older datasheets may still see PR1 and PR2 fields, but they should not copy those fields forward without reconciling them to the governing edition. Ask the bidder to identify the applicable validation requirement, the qualified product configuration and limits, the report or certificate reference, and any differences between the offered design and the validated design.</p>

<h2 id="define-service-classes-and-interfaces" className={heading}>Define service classes and interfaces</h2>
<p className={paragraph}>A comparable RFQ identifies rated working pressure, nominal size and bore, temperature class, material class, product-specific class where applicable, retained-fluid composition and project-defined sour-service or other environmental requirements. It also identifies end and outlet connections, ring grooves, flange faces, hanger profiles, sealing interfaces, actuator interfaces and adjacent equipment. The standard designation does not replace an interface schedule or controlled drawings.</p>
<p className={paragraph}>For replacement equipment, include nameplate photographs, original part references, dimensional drawings, assembly sections and the identity of retained components. Do not approve interchangeability from nominal size and pressure alone. The <Link className={link} href={postUrl(getPost("wellhead-and-christmas-tree-equipment-explained")!)}>wellhead and Christmas tree equipment guide</Link> explains the functional boundaries between heads, hangers, spools, valves, chokes and tree assemblies that should be mapped before requesting prices.</p>

<h2 id="connect-validation-to-the-offered-configuration" className={heading}>Connect validation to the offered configuration</h2>
<p className={paragraph}>Ask the supplier for a validation matrix that connects the offered part number to the validated design. Useful fields include product type, size and pressure range, material or temperature envelope, end-connection configuration, sealing system, actuator or operating method, report reference and approved design changes. The responsible reviewer can then determine whether the evidence covers the exact offer or whether additional qualification is required.</p>
<p className={paragraph}>A generic brochure statement is not the same as controlled validation evidence. Likewise, an API Monogram on one product line does not prove that every item a company sells falls within the same licensed scope. If monogram status is contractually required, verify the current facility and product scope through the official API program and require the quotation to identify the manufacturing location. Do not infer authorization or certification from a distributor’s website or a logo copied into a proposal.</p>

<h2 id="specify-item-level-manufacturing-records" className={heading}>Specify item-level manufacturing records</h2>
<p className={paragraph}>The final documentation schedule should connect each delivered item to its purchase order, tag, part number, serial number and manufacturing location. Depending on the product and contractual basis, required records may include material documents, heat-treatment records, examination reports, welding qualifications and maps, dimensional results, pressure-test reports, coating records, marking evidence, nonconformance dispositions and release documents. The exact package must come from the governing specification and approved ITP.</p>
<p className={paragraph}>Keep document purposes separate. A design-validation record addresses qualification of a design. A material certificate records material information under its stated inspection-document basis. A pressure-test report records an item or test lot under defined conditions. A declaration or monogram marking addresses another requirement. The <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>EN 10204 material certificate guide</Link> helps buyers define material-document expectations without treating them as proof of every manufacturing activity.</p>

<h2 id="use-the-itp-to-control-purchaser-participation" className={heading}>Use the ITP to control purchaser participation</h2>
<p className={paragraph}>Agree review, witness and hold points before manufacture. The ITP should define notification periods, submittal timing, responsible parties and release authority for drawings, material verification, examinations, assembly, pressure testing, functional checks and final documentation. A late request to witness a completed activity may require repeat work, delay delivery or provide no reliable way to reconstruct the original condition.</p>
<p className={paragraph}>The <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>hold and witness point guide</Link> explains the difference between mandatory release authority and an opportunity to attend. Quotations should price routine requirements, optional purchaser or third-party attendance, additional reports and any repeat testing separately. This lets the buyer compare complete offers rather than discovering after award that required evidence was excluded.</p>

<h2 id="check-api-and-iso-references-carefully" className={heading}>Check API and ISO references carefully</h2>
<p className={paragraph}><a className={link} href="https://www.iso.org/standard/79588.html" target="_blank" rel="noopener noreferrer">ISO 10423:2022</a> covers performance, interchangeability, design, materials, testing, inspection, welding, marking, handling, storage, shipment and purchasing for wellhead and tree equipment. ISO states that the document supplements API Spec 6A, 21st edition, with specified exceptions. That relationship should be read from the purchased standards and project specification; it is not safe to replace one citation with the other based only on similar titles.</p>
<p className={paragraph}>Record which document takes precedence if requirements differ. Ask bidders to list exceptions clause by clause and identify any qualification evidence based on another edition. If a standard interpretation is disputed, API maintains an official request-for-interpretation process. Commercial urgency should not be resolved by guessing what a proprietary clause means.</p>

<h2 id="build-a-comparable-wellhead-rfq" className={heading}>Build a comparable wellhead RFQ</h2>
<p className={paragraph}>A strong enquiry combines the equipment schedule, datasheets, service conditions, applicable standard and edition, required PSL, applicable validation requirement, interface drawings, inspection plan, document register, marking, preservation and delivery requirements. It asks each bidder to identify manufacturing location, offered part numbers, validation references, exclusions and deviations. The evaluation then compares the same technical boundary across offers.</p>
<p className={paragraph}>Send Oillinko the controlled datasheets, quantities, drawings and project specifications through the <Link className={link} href="/oil-and-gas/equipment/wellhead-production-equipment">wellhead and production equipment enquiry page</Link>. Oillinko reviews the requirement and coordinates it with suitable sources, while the operator and responsible engineering parties approve the final specification, validation basis and acceptance records. This preserves a clear route from the well requirement to the offered configuration without turning PSL or PR into unsupported marketing labels.</p>

<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>}
