import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import SiteImage from "@/components/SiteImage";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("api-5l-line-pipe-rfq-grade-psl-dimensions-records")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A request for “API 5L X52 pipe” leaves several purchasing decisions unresolved. A mill may need to know the applicable edition, product specification level (PSL), manufacturing route, outside diameter, specified wall thickness, end finish, service conditions and document package before it can identify a compliant product. The grade alone does not define a complete pipe or establish that a proposed delivery meets the pipeline design. This guide helps buyers turn an incomplete material list into a comparable enquiry; the pipeline designer and project specification remain responsible for selecting the design basis.</p>
    <p className={paragraph}>API describes Spec 5L as a manufacturing standard for seamless and welded steel line pipe used in pipeline transportation. Its <a className={link} href="https://www.api.org/products-and-services/standards/important-standards-announcements/api-announces-47th-edition-of-foundational-line-pipe-standard-5l" target="_blank" rel="noopener noreferrer">June 2026 announcement of the 47th edition</a> identifies requirements covering material, manufacturing, inspection, testing, marking and traceability. An enquiry should name the edition accepted by the project and ask the bidder to declare the edition offered. A published edition does not, by itself, amend an older contract or make all historic stock unsuitable. Edition differences need a controlled technical review.</p>

    <figure className="mt-8">
      <SiteImage src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Line pipe RFQ diagram connecting standard edition, grade and PSL, dimensions, manufacturing route, inspection records and delivery."/>
      <figcaption className="mt-3 text-sm text-muted">A line-pipe quote becomes comparable when each offer answers the same product and evidence requirements.</figcaption>
    </figure>

    <h2 id="service-basis" className={heading}>Start with the pipeline service and governing documents</h2>
    <p className={paragraph}>State whether the pipe is intended for oil, gas, water, carbon dioxide or another defined service, and provide the relevant project specification and design datasheet. The buyer should identify the design and operating envelope, installation location, external environment and any project-specific coating or corrosion-control requirements supplied by the responsible engineer. Do not ask a seller to infer sour-service, offshore or carbon-dioxide suitability from a grade label. Those applications may call for additional specified requirements and evidence; a routine API 5L quotation should not be represented as automatically qualified for them.</p>
    <p className={paragraph}>Ask whether the requirement covers new manufacture, identified stock or either. For stock, request the original production standard and edition, mill identity, traceable heat and pipe identification, storage condition and records. For new manufacture, distinguish manufacturing lead time from coating, testing, export preparation and transport. State whether the buyer accepts split deliveries or alternative lengths. These commercial facts affect comparison even when two quotes offer the same nominal grade.</p>

    <h2 id="grade-psl" className={heading}>Separate steel grade from product specification level</h2>
    <p className={paragraph}>Give the specified API 5L grade and PSL explicitly. API&apos;s catalogue describes two levels, PSL 1 and PSL 2, for seamless and welded line pipe; the levels are not a substitute for the grade or a generic statement that one quotation is “better.” Specify the project-required level and ask the technical reviewer to check the applicable chemical, mechanical, testing and documentary requirements in the controlled edition. If a bid offers a different grade or level, require it to be listed as a deviation rather than silently substituted.</p>
    <p className={paragraph}>Where a project uses a grade designation such as X52, confirm that the complete grade designation and delivery condition match the governing material schedule. Do not select a grade by comparing its number with the operating pressure alone. Pressure capacity depends on the designed pipe dimensions, material properties, applicable design code, temperature and other project factors. The mill&apos;s manufacturing conformity and the pipeline&apos;s fitness for service are related checks with different owners.</p>

    <h2 id="dimensions-route" className={heading}>Define dimensions and the permitted manufacturing route</h2>
    <p className={paragraph}>List the outside diameter and specified wall thickness for each item, with units and quantities. A nominal pipe size or schedule by itself can be ambiguous when the line-pipe purchase schedule uses outside diameter and wall thickness directly. Request the permitted length range, delivery tolerance, end preparation, straightness and any special dimensional requirements stated by the project. Identify whether bare, coated or lined pipe is required and keep coating details in their own specification rather than burying them in a description of the steel pipe.</p>
    <p className={paragraph}>State whether seamless or a particular welded manufacturing route is required, or whether more than one route may be proposed. Ask each bidder to identify the route it offers and to provide the applicable manufacturing and test evidence. The 47th-edition <a className={link} href="https://www.api.org/products-and-services/standards/important-standards-announcements/api-announces-47th-edition-of-foundational-line-pipe-standard-5l" target="_blank" rel="noopener noreferrer">API notice</a> specifically mentions high-frequency-welded pipe quality among its updates. That is a reason to identify the offered process and edition, not a basis for assuming every welded pipe has the same examination scope or that seamless pipe is always preferable.</p>
    <p className={paragraph}>Connection design deserves its own check. Specify plain or prepared ends, bevel requirements and any approved connection drawing. If the pipe will join fittings, verify the mating bore, material and weld-end compatibility against the line design. The <Link className={link} href={postUrl(getPost("pipeline-fittings-and-schedules")!)}>pipeline fittings and schedules guide</Link> explains fittings and wall matching, but a fitting quotation does not establish that the underlying line pipe has the required grade, PSL or records.</p>

    <h2 id="inspection-records" className={heading}>Ask for inspection and traceability evidence</h2>
    <p className={paragraph}>Set out the required manufacturing records in the RFQ: material test reports, dimensional results, required nondestructive examination and pressure-test records, marking data, release documentation and any project-specific inspection points. The exact tests and acceptance values must come from the cited API edition and purchaser supplements. API notes that its 47th edition updates topics including hydrotest gauge calibration, nondestructive-evaluation personnel certification, records retention, impact toughness and lamination control. A one-line promise of “full certification” does not tell the buyer which of these apply or which reports will be handed over.</p>
    <p className={paragraph}>Request a document index that links each pipe or bundle identification to its heat, production lot and associated reports. The <Link className={link} href={postUrl(getPost("heat-number-traceability-mill-certificates")!)}>heat-number traceability guide</Link> shows why a certificate matters only when it can be linked to the delivered item; the <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>material certificate guide</Link> helps buyers specify the requested inspection-document type where the project uses EN 10204 terminology. Do not claim an EN 10204 document is mandatory for every API 5L purchase. Make the contractual document requirement explicit.</p>

    <h2 id="compare-offers" className={heading}>Compare offers by item, exception and delivery scope</h2>
    <p className={paragraph}>Use one line per diameter, thickness, grade, PSL and finish combination. Ask bidders to repeat the offered standard and edition, manufacturing route, length range, unit of measure, quantity, manufacturing country, document list, inspection scope and delivery basis. Separate coating, end caps, handling protection, packing and freight if they are optional. Ask for a deviations list even when a bidder states “compliant”; an alternative wall, grade, length mix or certificate package can make the apparent lowest price unsuitable for the intended project.</p>
    <p className={paragraph}>A practical RFQ can include a controlled material schedule, project specification, drawing revisions, inspection and test plan, required handover index, desired delivery date and destination. Send those documents to Oillinko through the <Link className={link} href="/oil-and-gas/equipment/pipe-tubing/line-pipe">line pipe enquiry page</Link> for manual review and routing. Oillinko can coordinate sourcing enquiries, but neither a catalogue page nor a preliminary supplier response establishes available stock, manufacturing approval or project acceptance. Compare the eventual quotations against the same controlled requirements and have the responsible engineer resolve technical deviations before award.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
