import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post=getPost("api-598-vs-iso-5208-valve-testing-buyers-guide")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading="mt-12 text-xl font-bold";
const link="text-accent underline underline-offset-4";
const faqs=[
  {q:"Does a statement that a valve was hydrotested identify the acceptance standard?",a:"No. The order should identify the applicable standard and edition, required examinations, test stages, acceptance criteria and report. The word hydrotested does not establish the complete scope."},
  {q:"Can ISO 5208 be substituted for API 598 automatically?",a:"No. Use the product standard and project specification that govern the valve. Any proposed alternative should be compared clause by clause and approved by the responsible purchaser or engineer."},
  {q:"Is a valve pressure-test report the same as a material certificate?",a:"No. A pressure-test report records a defined test and result. Material documents, conformity declarations and other certificates have different purposes and should remain separate deliverables."}
];

export default function Page(){return <><BlogPostHeader post={post}/><Prose>
<p className={paragraph}>A valve quotation that says “tested” or “hydrotested” still leaves the buyer with several unanswered questions. Which document governed the test? Was the pressure boundary tested, was closure leakage checked, and were both flow directions included where relevant? Did the price include an item-specific report or only the manufacturer’s routine production record? API 598 and ISO 5208 are frequently named in industrial valve enquiries, but writing both references beside a valve description does not make their requirements interchangeable or define the evidence the purchaser will receive.</p>
<p className={paragraph}>This guide explains how to specify valve pressure testing as a procurement requirement. It does not reproduce proprietary acceptance tables or prescribe a safe test procedure. Test pressure, medium, duration, leakage limits and safety controls must come from the applicable purchased standard, valve product standard, approved project specification and manufacturer procedure. Buyers can use the questions below to make quotations comparable while leaving execution with competent personnel and controlled factory arrangements.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Valve test evidence workflow from governing standard through test scope, acceptance criteria and traceable report."/><figcaption className="mt-3 text-sm text-muted">A useful valve test requirement connects the governing document to the exact valve and recorded result.</figcaption></figure>

<h2 id="start-with-the-governing-valve-product-standard" className={heading}>Start with the governing valve product standard</h2>
<p className={paragraph}>API’s official catalogue describes <a className={link} href="https://www.api.org/-/media/files/publications/2025-catalog/06_refining_2025.pdf" target="_blank" rel="noopener noreferrer">API Standard 598, Valve Inspection and Testing</a>{" "}as covering inspection, examination, supplementary examinations and pressure-test requirements for gate, globe, plug, ball, check and butterfly valves with several seat constructions. It supplements API product standards that reference it and can be applied to other valve types by agreement between purchaser and manufacturer. That scope makes API 598 a testing reference; it is not a substitute for identifying the product standard, valve design, materials, rating and service requirements.</p>
<p className={paragraph}><a className={link} href="https://www.iso.org/standard/65111.html" target="_blank" rel="noopener noreferrer">ISO 5208:2015</a>{" "}covers examinations and tests used to establish pressure-boundary integrity, closure tightness and structural adequacy of the closure mechanism for industrial metallic valves. ISO states that it is used with the applicable valve product standard and that the product standard prevails where its requirements differ. ISO also shows the 2015 edition was reviewed and confirmed in 2025, while an amendment is under development. An RFQ should therefore name the required edition and avoid assuming that a future amendment already governs the order.</p>

<h2 id="do-not-treat-api-598-and-iso-5208-as-two-labels-for-one-result" className={heading}>Do not treat API 598 and ISO 5208 as two labels for one result</h2>
<p className={paragraph}>Both documents address pressure testing, but the purchaser should not translate test names, leakage designations or acceptance categories by memory. The correct comparison depends on the exact editions, valve type and product standard. Ask a supplier that proposes ISO 5208 instead of API 598, or the reverse, to identify each deviation that affects the ordered valve and its acceptance. The responsible engineer or purchaser then decides whether that proposal meets the project basis.</p>
<p className={paragraph}>Some valves have a more specific purchasing framework. API’s current standards plan identifies API Specification 6D, 25th Edition and its published addenda for pipeline valves. A pipeline valve ordered to API 6D should be reviewed against that specification and the project requirements rather than reduced to a generic API 598 certificate request. Likewise, <a className={link} href="https://www.asme.org/codes-standards/find-codes-standards/b16-34-valves-flanged-threaded-welding-end/2017/pdf" target="_blank" rel="noopener noreferrer">ASME B16.34</a>{" "}covers pressure-temperature ratings, materials, examinations, testing and marking for valves within its scope. Each reference has a role; listing several without defining precedence creates ambiguity instead of added assurance.</p>

<h2 id="separate-shell-closure-and-backseat-requirements" className={heading}>Separate shell, closure and backseat requirements</h2>
<p className={paragraph}>The pressure boundary and the closed valve answer different acceptance questions. A shell test addresses the integrity of the pressure-containing envelope under the specified test conditions. A closure or seat test evaluates leakage past the closed obturator under its stated conditions. A backseat test applies only where the valve construction and governing requirement call for it. The RFQ should list the required stages rather than requesting one unspecified pressure test.</p>
<p className={paragraph}>Valve geometry can also affect the test arrangement. A bidirectional isolation valve, a unidirectional design and a check valve do not necessarily use the same direction, loading or acceptance logic. State the required flow direction and isolation function, then ask the supplier to identify the applicable procedure for the offered construction. For check valves, keep factory closure leakage separate from the operating-system question discussed in the <Link className={link} href={postUrl(getPost("check-valve-cracking-pressure-rfq-guide")!)}>check valve cracking pressure guide</Link>. An opening threshold is not a factory seat-leakage acceptance value.</p>

<h2 id="define-the-acceptance-basis-before-requesting-a-certificate" className={heading}>Define the acceptance basis before requesting a certificate</h2>
<p className={paragraph}>A useful purchase description states the standard and edition, valve type and seat construction, required test stages, and the acceptance class or leakage criterion taken from the governing documents. Do not copy a leakage value from a different valve family or test medium. If the project adds supplementary examinations or a more stringent acceptance requirement, identify it explicitly and request confirmation that it is technically applicable to the proposed design.</p>
<p className={paragraph}>Clarify whether the requirement applies to every supplied valve, a production sample or a qualification test on a representative design. Those are different forms of evidence. A type or qualification record for a valve family does not prove that each delivered serial number received the specified production test. Conversely, a routine production test does not establish every qualification property that may be required by the product specification. The quotation should state which records are lot-specific, item-specific or design-level.</p>

<h2 id="ask-for-a-traceable-valve-test-report" className={heading}>Ask for a traceable valve test report</h2>
<p className={paragraph}>Define the report fields before purchase. Useful records connect the result to the manufacturer, purchase order, valve tag or serial number, valve description, size, pressure designation and relevant material or trim identification. They should state the governing document and edition, test stage, medium, applied pressure, duration, acceptance criterion, observed result, test date and responsible approval. Where measuring equipment identification or calibration status is required by the project, include that requirement in the inspection plan.</p>
<p className={paragraph}>Keep the pressure-test report distinct from material documents, a declaration of conformity, fire-type-test evidence or a general quality certificate. Each supports a different claim. The <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>EN 10204 material certificate guide</Link>{" "}explains the role of inspection documents for materials; it does not turn a material certificate into proof of valve closure performance. Ask suppliers to index the final documentation package so the buyer can connect every required record to the delivered items.</p>

<h2 id="agree-witnessing-and-notification-in-the-itp" className={heading}>Agree witnessing and notification in the ITP</h2>
<p className={paragraph}>If purchaser or third-party attendance matters, place the requirement in the inspection and test plan before the order is released. Define hold, witness and review points, notification periods, document submittals and the consequence of non-attendance. A certificate issued after an unwitnessed routine test should not be described as witnessed evidence. The <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>hold and witness point guide</Link>{" "}shows how to separate mandatory authorization from an opportunity to attend.</p>
<p className={paragraph}>Commercial comparison should show the base production testing, optional witnessing, third-party fees, repeat-test conditions and documentation costs separately. Also confirm where the test will occur and which party coordinates access. These details influence price and schedule, especially for small quantities or valves drawn from finished stock. Do not assume an existing stock valve can be retested, disassembled or remarked without technical review and manufacturer authorization.</p>

<h2 id="build-a-comparable-valve-testing-rfq" className={heading}>Build a comparable valve-testing RFQ</h2>
<p className={paragraph}>Begin with the complete valve description: type, size, pressure designation, end connections, body and trim materials, seat construction, actuation, service conditions and applicable product standard. Then add the pressure-test standard and edition, project supplements, test stages, required acceptance basis, extent of testing, witness points and report format. Ask bidders to list exclusions and deviations against those fields. This produces a technical comparison instead of several certificates carrying similar titles but documenting different work.</p>
<p className={paragraph}>For broader selection context, read the <Link className={link} href={postUrl(getPost("valves-and-actuation-explained")!)}>valves and actuation guide</Link>. Send Oillinko the valve datasheet, quantity, project specifications, required documentation and inspection plan through the <Link className={link} href="/oil-and-gas/equipment/valves">valve and actuation enquiry page</Link>. Oillinko reviews the request and coordinates it with suitable sources while the responsible project parties approve the final technical basis. The offer should identify the exact testing and evidence included, with uncertainties resolved before manufacture or release.</p>

<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>;}
