import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post=getPost("api-526-pressure-relief-valves-rfq-guide")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base",heading="mt-12 text-xl font-bold",link="text-accent underline underline-offset-4";
const faqs=[
  {q:"Does specifying API 526 size a pressure-relief valve?",a:"No. API 526 standardizes defined purchase features for valves within its scope. The required relieving capacity and selected effective area must come from the approved overpressure-protection design basis and applicable code."},
  {q:"Is set pressure the same as allowable accumulation or relieving pressure?",a:"No. These terms serve different functions in an overpressure-protection design. The responsible engineer should provide the approved datasheet values and governing code basis rather than asking a bidder to infer them."},
  {q:"Can a general valve pressure-test certificate replace PRV certification records?",a:"No. A pressure-relief device has performance, capacity, set-pressure and code or jurisdictional evidence requirements that differ from a general isolation-valve shell or seat test."}
];

export default function Page(){return <><BlogPostHeader post={post}/><Prose>
<p className={paragraph}>An API 526 pressure-relief valve enquiry should begin with an approved relief-device datasheet, not a line size and a set pressure copied from a nameplate. The buyer must connect the protected equipment, governing code and credible relieving case to a selected device configuration. API 526 then helps standardize specified purchase features for flanged steel pressure-relief valves within its scope. It does not replace the relief-system study, capacity calculation or engineering approval.</p>
<p className={paragraph}>This guide organizes the data and records needed for a comparable RFQ. It does not provide a sizing formula, field adjustment procedure or permission to change a set pressure. Overpressure protection affects personnel, equipment and the environment. Competent engineers and authorized organizations must perform the design, selection, assembly, testing, installation and maintenance under the applicable code, jurisdiction, manufacturer instructions and site controls.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Pressure-relief valve RFQ chain connecting the approved relief basis to service data, selected API 526 configuration, certification and final records."/><figcaption className="mt-3 text-sm text-muted">Keep the approved relief basis, offered hardware and final evidence connected throughout procurement.</figcaption></figure>

<h2 id="separate-the-design-basis-from-the-purchase-standard" className={heading}>Separate the relief design basis from the purchase standard</h2>
<p className={paragraph}>Name every controlled reference and edition. The <a className={link} href="https://www.api.org/products-and-services/standards/standards-plan" target="_blank" rel="noopener noreferrer">API standards plan</a> identifies API 520 Part I for sizing and selection, API 520 Part II for installation, API 521 for pressure-relieving and depressuring systems, API 526 for flanged steel pressure-relief valves and API 527 for seat tightness. These documents address connected but different questions. The project should identify which apply and how they interact with the governing pressure-equipment code.</p>
<p className={paragraph}><a className={link} href="https://www.asme.org/codes-standards/bpvc-standards" target="_blank" rel="noopener noreferrer">ASME describes the Boiler and Pressure Vessel Code</a> as a source of requirements for the manufacture, construction and operation of boilers and pressure vessels. Modern BPVC editions include Section XIII for overpressure protection. A project may also have national rules, owner specifications or another design code. The RFQ should state the code basis and required certification rather than assuming that the words API 526 automatically satisfy every jurisdiction.</p>

<h2 id="identify-the-protected-equipment-and-relieving-case" className={heading}>Identify the protected equipment and approved relieving case</h2>
<p className={paragraph}>Give the valve tag, protected-equipment tag, service description and relevant process unit. Identify the controlling relieving case from the approved study and provide its required capacity, fluid phase, composition or molecular data, relieving temperature and pressure, and any other properties used by the responsible sizing engineer. If more than one case is relevant, include the case schedule and show which governs capacity and which may govern materials or stability.</p>
<p className={paragraph}>Do not ask vendors to guess the fire, blocked outlet, thermal expansion, utility failure or other scenario from normal operating data. Normal pressure and temperature remain important, but they are not a substitute for the approved relieving conditions. Mark preliminary information clearly and define who will close each technical clarification before award.</p>

<h2 id="state-pressure-terms-with-their-basis" className={heading}>State pressure terms with their basis</h2>
<p className={paragraph}>Record the required set pressure and units, along with the governing code and protected-equipment basis. Keep set pressure distinct from operating pressure, maximum allowable working pressure, overpressure, accumulation and relieving pressure. If the process can operate close to set pressure, identify the operating margin for engineering review. Do not use these terms interchangeably in the commercial comparison.</p>
<p className={paragraph}>Provide atmospheric pressure basis and specify whether values are gauge or absolute wherever ambiguity could affect the review. A quotation should return the offered set pressure, applicable tolerance basis and any assumptions. Changes after order require controlled engineering approval and may affect springs, trim, testing, certification and the protected system.</p>

<h2 id="define-back-pressure-and-discharge-conditions" className={heading}>Define back pressure and discharge conditions</h2>
<p className={paragraph}>State the superimposed back pressure and the built-up back pressure expected during the governing case, including whether either varies. Identify the discharge destination, connected header or atmosphere, and any project requirements for bellows, balancing, venting or pilot operation. Back pressure can affect valve selection, capacity and operating behavior; it should not be left as an unstated piping detail.</p>
<p className={paragraph}>The <a className={link} href="https://www.emerson.com/documents/automation/pressure-relief-valve-engineering-handbook-cs-cz-4262398.pdf" target="_blank" rel="noopener noreferrer">Emerson pressure-relief valve engineering handbook</a> illustrates that manufacturer correction factors and limits can depend on valve design and the relationship between outlet pressure and set pressure. Use current model-specific certified data and the approved calculation. Do not transfer a curve or factor from one design to another merely because both valves have an API orifice letter.</p>

<h2 id="carry-the-approved-orifice-into-the-rfq" className={heading}>Carry the approved area and orifice selection into the RFQ</h2>
<p className={paragraph}>Provide the required calculated effective discharge area and the selected standard orifice designation from the approved sizing review. Ask the bidder to return the offered API designation, effective area, rated capacity for the stated service and the certification basis used. If the manufacturer proposes a different orifice or model, require a revised sizing comparison and engineering approval before acceptance.</p>
<p className={paragraph}>API’s publication catalogue describes API 526 as a purchase specification covering features including orifice designation and area, inlet and outlet size and rating, materials, pressure-temperature limits and center-to-face dimensions. Standardization supports interchangeability and bid comparison within the stated scope, but it does not mean that every manufacturer’s trim, spring, bellows, pilot or capacity data are identical.</p>

<h2 id="define-valve-type-and-construction" className={heading}>Define valve type and construction</h2>
<p className={paragraph}>State whether the approved design requires a conventional direct spring-loaded valve, balanced bellows arrangement, pilot-operated valve or another configuration. Identify gas, vapor, steam, liquid or mixed-service requirements as established by the design basis. Define bonnet and cap arrangement, lifting lever or test gag requirements only where permitted and approved, and list any accessories such as position indication or remote sensing within the project scope.</p>
<p className={paragraph}>Require the supplier to identify the complete model and configuration, not merely “API 526 PSV.” Include inlet and outlet flange size, pressure class, facing and dimensional requirements. Confirm that adjacent piping, flange ratings, inlet losses, discharge loads and support arrangements are reviewed by the responsible piping and relief-system engineers. The valve purchase does not complete the installation design.</p>

<h2 id="specify-materials-for-each-component" className={heading}>Specify materials and service restrictions by component</h2>
<p className={paragraph}>List body, bonnet, nozzle, disc, guide, spindle, spring, bellows, gaskets and other wetted or pressure-containing materials required by the project. Include corrosion, temperature, sour-service and process-compatibility requirements at component level. If NACE MR0175 / ISO 15156 applies, use the <Link className={link} href={postUrl(getPost("nace-mr0175-iso-15156-sour-service-buyers-guide")!)}>sour-service buyer guide</Link> to define the environment, material condition, fabrication controls and evidence rather than writing a broad compliance note.</p>
<p className={paragraph}>Ask for the offered material schedule and identify substitutions. A body grade does not describe the spring or trim, and an optional bellows may introduce its own material and service limits. State coating, painting, preservation and external-environment requirements separately from process compatibility.</p>

<h2 id="define-code-certification-and-nameplate-evidence" className={heading}>Define certification, marking and capacity evidence</h2>
<p className={paragraph}>Specify the required code certification mark, designator, manufacturer authorization and jurisdictional registration where applicable. Do not claim that every API 526 valve is ASME certified. <a className={link} href="https://www.asme.org/certification-accreditation/boiler-and-pressure-vessel-certification" target="_blank" rel="noopener noreferrer">ASME explains that its BPVC certification program covers quality-control systems for organizations manufacturing or assembling pressure equipment and valves</a>. The buyer should verify the certificate holder and scope for the offered device.</p>
<p className={paragraph}>Capacity certification is another defined evidence stream. <a className={link} href="https://www.asme.org/certification-accreditation/pressure-relief-device-testing-laboratories" target="_blank" rel="noopener noreferrer">ASME’s pressure-relief device laboratory accreditation program</a> covers laboratories conducting performance and capacity certification tests under applicable BPVC and performance-test rules. Request the rated capacity and coefficient evidence relevant to the offered model and service, and ensure the final nameplate and data report align with the purchase requirement.</p>

<h2 id="separate-set-pressure-testing-from-seat-tightness" className={heading}>Separate set-pressure testing from seat-tightness evidence</h2>
<p className={paragraph}>Define the required shop tests, media, acceptance basis, witness points and reports. Set-pressure verification addresses valve opening behavior under the stated method. Seat-tightness testing addresses leakage under a separate defined basis. A shell or body pressure test addresses pressure integrity. Keep these records separate so a single “test certificate” does not conceal which examinations were actually performed.</p>
<p className={paragraph}>API’s standards plan lists API 527 specifically for pressure-relief-valve seat tightness. The general <Link className={link} href={postUrl(getPost("api-598-vs-iso-5208-valve-testing-buyers-guide")!)}>valve pressure-testing guide</Link> explains shell and closure evidence for other valve types, but those reports do not replace the performance and certification evidence required for a pressure-relief device. Define sealing-surface condition, test medium and any soft-seat restrictions through the approved standard and manufacturer procedure.</p>

<h2 id="control-documents-and-inspection-points" className={heading}>Control documents and inspection points</h2>
<p className={paragraph}>Create a vendor document register covering the approved datasheet, sizing sheet, outline drawing, material schedule, certificates, welding or repair records where applicable, certified capacity data, test procedures, set-pressure and seat-tightness reports, code data report, nameplate copy, preservation instructions and final dossier index. Mark documents required for approval before manufacture and those required before release.</p>
<p className={paragraph}>Use the <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>hold and witness point guide</Link> to define attendance, notification and release authority. A witness invitation is not a technical approval, and shipment release does not transfer responsibility for the original relief-system design. Record every approved deviation and carry it into the final datasheet.</p>

<h2 id="send-a-complete-pressure-relief-valve-enquiry" className={heading}>Send a complete pressure-relief valve enquiry</h2>
<p className={paragraph}>Before requesting a price, assemble the approved relief case, sizing and selection sheet, governing codes and editions, process data, set pressure, back pressure, required area, selected orifice, valve type, connections, materials, certification, tests, document register and delivery quantity. Ask bidders to return a line-by-line compliance matrix and list assumptions affecting price or lead time.</p>
<p className={paragraph}>Send this package through Oillinko’s <Link className={link} href="/oil-and-gas/equipment/valves/safety-relief-and-pressure-control-valves">safety, relief and pressure-control valve enquiry page</Link>. Oillinko reviews the RFQ and coordinates it manually with suitable sources. The owner, pressure-equipment engineer and responsible overpressure-protection specialists retain approval of the relieving scenario, sizing, selected device, installation and acceptance basis.</p>

<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>}
