import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, CheckList, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";
const post=getPost("asme-b16-5-flange-pressure-classes")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading="mt-12 text-xl font-bold";
const link="text-accent underline underline-offset-4";
const faqs=[
  {q:"Does Class 150 mean a flange is rated for 150 psi?",a:"No. It is a class designation. The applicable pressure-temperature rating depends on the specified material and temperature, with the complete connection assessed against the project requirements."},
  {q:"Can I convert a flange class directly into PN?",a:"Do not use a pressure-unit conversion as proof of dimensional or service compatibility. Confirm the exact standards, materials, facings, dimensions and ratings of the proposed mating components."},
  {q:"Is a higher-class flange an automatic replacement?",a:"No. A different class may change the connection geometry and other requirements. Obtain approval for the complete interface and design basis before accepting a substitute."},
];
export default function Page(){return <>
<BlogPostHeader post={post}/><Prose>
<p className={paragraph}>ASME B16.5 flange pressure classes identify a rating category; they are not a pressure reading in psi. A request for a Class 150 flange therefore says less than many buyers expect. It does not define a single allowable pressure at every temperature, identify the material or establish that the part fits an existing joint. Understanding that distinction helps buyers ask useful questions without attempting to replace the responsible engineer&apos;s selection work.</p>
<p className={paragraph}>The practical purchasing problem usually starts with shorthand. A supplier receives a size and class, returns a price, and later discovers a different material grade, facing or operating condition in the project documents. This guide explains how to keep the rating basis attached to the item description. It covers interpretation and quotation review, not pressure-system design approval. An operating limit must come from the applicable requirements and verified equipment information, rather than from an isolated class number or an unattributed chart.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Flange class, specified material and temperature feed the rating review, followed by a separate complete-joint compatibility check."/><figcaption className="mt-3 text-sm text-muted">A class label starts the review; the final decision needs the rating basis and the complete connection.</figcaption></figure>
<h2 id="class-is-a-designation" className={heading}>Read the class as a designation, not a unit</h2>
<p className={paragraph}>The <a className={link} href="https://www.asme.org/codes-standards/find-codes-standards/b16-5-pipe-flanges-flanged-fittings-nps-1-2-nps-24-metric-inch-standard" target="_blank" rel="noopener noreferrer">official ASME B16.5 scope</a>{" "}covers pressure-temperature ratings alongside materials, dimensions and other product requirements. It lists flange classes 150, 300, 400, 600, 900, 1500 and 2500, with size limits that depend on the class. The public description identifies the standard&apos;s scope; it is not a substitute for the applicable tables and notes. State the required edition and product specification in the purchasing documents.</p>
<p className={paragraph}>When a quotation uses descriptions such as 150 lb or 150#, ask for the formal class designation and governing standard to be stated clearly. Keep pressure values in separate fields with their units. Converting psi to bar changes a pressure value, not a component standard. Likewise, an ASME class and a PN designation should not be treated as interchangeable merely because someone associates them with similar pressures. The proposed connection still needs its own dimensional and rating review.</p>
<h2 id="material-and-temperature" className={heading}>Keep the material and temperature attached to the rating</h2>
<p className={paragraph}>Ask which material specification and grade support the quoted rating. A generic carbon steel or stainless steel description is not a sufficient reference for reviewing a material-dependent table. Provide the approved project conditions and identify the governing temperature cases with the engineer. Normal operating information, design conditions and occasional service conditions should remain distinguishable. A table entry checked for one condition does not explain how the other required cases have been assessed.</p>
<p className={paragraph}>A useful illustration appears in the <a className={link} href="https://www.swagelok.com/downloads/webcatalogs/EN/MS-02-200.pdf" target="_blank" rel="noopener noreferrer">Swagelok flange adapter catalogue, page 3</a>. Its table based on A182 316 stainless steel shows 275 psig for Class 150 at −20 to 100°F, and 140 psig at 600°F. These are entries in that manufacturer&apos;s stated reference table, not universal limits for all Class 150 products. They illustrate both points: the class number is not the pressure value, and temperature matters. Confirm the actual product&apos;s applicable conditions and limitations before using any number.</p>
<h2 id="review-the-complete-connection" className={heading}>Review the complete connection before accepting the part</h2>
<p className={paragraph}>A flange rating is only one part of the information needed for an assembled connection. Identify the mating component, facing, gasket, bolting and any adapter or instrument connected to it. Swagelok&apos;s catalogue specifically notes that an adapter with different end connections is limited by the lower-rated connection. That product example is a useful prompt for the enquiry: ask the supplier to identify the limiting element in the offered assembly instead of describing the whole package only by its flange class.</p>
<p className={paragraph}>An apparent physical fit does not establish suitability for service. Conversely, requesting a higher class as an upgrade can introduce a dimensional mismatch or a different joint arrangement. Obtain a controlled drawing or interface confirmation for replacements. Include the specified bore and pipe connection where relevant, and identify the installed counterpart. The <Link className={link} href={postUrl(getPost("spiral-wound-gasket-identification-rfq")!)}>spiral wound gasket identification guide</Link>{" "}explains the separate information needed for that sealing element. Do not let an abbreviated gasket or fastener description undermine an otherwise detailed flange enquiry.</p>
<h2 id="read-supplier-rating-evidence" className={heading}>Ask for rating evidence that can be reviewed</h2>
<p className={paragraph}>A quotation stating suitable for pressure service leaves important questions unanswered. Ask for the exact offered designation, material, referenced rating basis and declared exceptions. Where the product has additional limitations, obtain the applicable manufacturer document. Have the project&apos;s technical reviewer resolve inconsistent conditions or missing information. A commercial buyer can check that the evidence is complete and corresponds to the requested item without independently approving the engineering calculation.</p>
<p className={paragraph}>Keep chart provenance visible. Record the document title, revision, material basis and units when a supplier sends an extract. A cropped screenshot may omit a heading, footnote or product limitation that changes its meaning. Do not interpolate between entries, extrapolate beyond the published range or apply a simple class ratio without an approved technical basis. If a requested condition is absent, flag it for clarification. Treat an unanswered rating question as an open item in the comparison rather than silently filling the gap.</p>
<h2 id="traceability-and-receiving" className={heading}>Connect the approved specification to delivered items</h2>
<p className={paragraph}>The rating review and material records answer different questions. A material certificate helps establish what was supplied; it does not, by itself, demonstrate that the complete connection was selected correctly for the project. The <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>EN 10204 certificate guide</Link>{" "}explains document types and traceability. Define the required records in the order, then connect the final item identification to the agreed description and supporting documents. Resolve substitutions before shipment instead of relying on receiving personnel to reinterpret an unapproved offer.</p>
<p className={paragraph}>For replacement purchases, retain the original equipment identification and the approved change history. A readable class marking is useful, but it does not explain the present condition of an installed flange or authorize its continued use. Specify the inspection scope relevant to the supplied item and separate it from any assessment of existing plant equipment. Joint preparation, tightening, testing and return to service must follow the approved procedures and competent technical supervision. A procurement guide should not invent a torque or test pressure from the class label.</p>
<h2 id="turn-the-review-into-an-enquiry" className={heading}>Turn the review into a clear purchasing description</h2>
<p className={paragraph}>Build each line item around the actual required component: quantity, nominal size, flange type, governing standard and edition, class, facing, material and relevant connection details. Attach the project conditions and supporting drawing references rather than compressing everything into a short product name. Ask suppliers to return a separate deviation list. This makes a differently rated or dimensioned alternative visible before it becomes an assumed equivalent in a price comparison.</p>
<p className={paragraph}>Submit the specification through the <Link className={link} href="/oil-and-gas/equipment/flanges-fittings-bolting/weld-neck-slip-on-and-blind-flanges">flange equipment enquiry page</Link>. For the wider assembly, use the <Link className={link} href={postUrl(getPost("flanges-gaskets-and-bolting")!)}>flanges, gaskets and bolting overview</Link>{" "}to organize related items. Oillinko reviews the request and coordinates sourcing manually; the relevant manufacturer and project reviewer confirm the offered component and its suitability. Keep the final quotation, approved deviations and inspection requirements together so the ordered product remains tied to the same technical basis throughout purchasing.</p>
<CheckList items={["Standard and edition, nominal size, type, class and facing","Approved material specification and grade","Defined project conditions with explicit units","Mating connection, gasket and bolting requirements","Applicable rating reference and manufacturer limitations","Traceability documents and agreed inspection scope","Written deviations and technical approval responsibilities"]}/>
<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/>
</>;}
