import Image from "@/components/SiteImage";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("centrifugal-pump-spare-parts-rfq-identification")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";
const faqs = [
  { q: "Is the pump model enough to identify a replacement impeller?", a: "Usually not. The installed serial or order reference, assembly drawing and item revision help establish the exact configuration; material, diameter and any approved modification also need confirmation." },
  { q: "Can a supplier quote a dimensionally similar wear ring as an equivalent?", a: "It can be offered as an explicitly identified alternative, but the responsible technical reviewer must assess the complete fit, material, clearances and applicable acceptance requirements before approval." },
  { q: "Should a spare-parts RFQ include the whole pump performance curve?", a: "Include the approved performance and duty information when it affects the component selection, especially an impeller change. The exact document package depends on the repair and engineering scope." },
];

export default function Page() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A request for a centrifugal pump impeller, wear ring or shaft sleeve can be surprisingly ambiguous. Two pumps in the same type series may have different materials, impeller diameters, seal arrangements or production revisions. A quotation for a familiar part name is therefore not yet a quotation for the installed machine. The buyer needs a chain from the equipment identity to the assembly drawing, the item number and the configuration that will actually be supplied. This guide shows how to assemble that chain without claiming that a catalogue family proves interchangeability.</p>
    <p className={paragraph}>Start with the installed pump rather than with a generic shopping list. Record the nameplate type and size, serial or order number, year if available, site tag and any documented modification. Photograph the nameplate clearly and attach the latest approved general-arrangement and sectional drawings. <a className={link} href="https://www.ksb.com/en-gb/spare-parts/find-spareparts-online" target="_blank" rel="noopener noreferrer">KSB spare-parts search guidance</a> uses the product serial number, material number or type series to identify parts. That is an example of why the machine reference matters; another manufacturer may use a different identification system. Include the installed equipment identity in the enquiry so Oillinko can route it appropriately.</p>
    <figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Conceptual checklist connecting a pump nameplate and assembly drawing to identified spare components and acceptance records."/><figcaption className="mt-3 text-sm text-muted">Trace the offered component back to the installed pump and the approved drawing. This is an identification aid, not a pump assembly drawing.</figcaption></figure>
    <h2 id="identify-machine" className={heading}>Identify the actual machine and its revision</h2>
    <p className={paragraph}>The pump tag locates the asset within a plant, but it may not be a manufacturer identifier. Keep the tag alongside the nameplate reference, not in place of it. If the nameplate is missing or unreadable, supply the purchase records, drawing numbers and photographs that remain, and label the identification as provisional. Ask the bidder to state the basis used to identify the part and the information still needed. A quotation that silently assumes a model or revision can be harder to correct after an order is released.</p>
    <p className={paragraph}>Check whether the unit has been repaired or modified since purchase. An impeller may have been trimmed, a seal chamber changed or a casing replaced. The original bill of materials may describe the as-sold unit rather than the installed configuration. Maintenance records and approved as-built drawings can close that gap. Send the current configuration and ask the supplier to highlight any conflict with its records. Where the change affects hydraulic performance or mechanical integrity, the responsible engineer must decide the accepted replacement basis.</p>
    <h2 id="name-components" className={heading}>Name each component and its assembly position</h2>
    <p className={paragraph}>Specify the drawing item number and description for each requested piece. The word “ring” can mean a casing wear ring, an impeller wear ring or another component in the same assembly; “sleeve” can refer to a shaft-protecting sleeve or a different spacer. Quantity may be per pump, per stage or per overhaul kit. <a className={link} href="https://live-resources-e2e-sales.ksb.com/resource/blob/23836/fd081fa7e7da37c77430c18a5540cac0/p2p-sparepartkit-megacpk-210x297-en-190627-data.pdf" target="_blank" rel="noopener noreferrer">The KSB MegaCPK spare-parts kit brochure</a> lists impellers, casing wear rings, shaft-protecting sleeves and seals as different items. Those examples illustrate the need for an itemized RFQ; their part numbers are specific to that product family and must not be copied into another pump enquiry.</p>
    <p className={paragraph}>For each line, show the pump tag, drawing and revision, item number, required quantity and whether mounting hardware, keys, fasteners, gaskets or other associated pieces are included. A “complete impeller” and a bare casting may not be equivalent quoted scopes. If a repair kit is offered, request its itemized contents and quantities. The <Link className={link} href={postUrl(getPost("mechanical-seal-replacement-identification-rfq-guide")!)}>mechanical-seal replacement guide</Link> covers the more specialized task of identifying a seal cartridge or repair kit; keep that scope separate from other internal pump spares.</p>
    <h2 id="check-materials" className={heading}>Separate material identity from physical fit</h2>
    <p className={paragraph}>A component with a matching outside diameter is not necessarily the specified replacement. State the approved material designation, required heat treatment or coating where applicable, and the fluid and temperature conditions that drove the original selection. Ask bidders to show their proposed material for each component, including an alternative, rather than writing “equivalent material” without a comparison. Dimensions, tolerances and mating-part condition still need engineering review; this article does not prescribe service clearances or machining instructions.</p>
    <p className={paragraph}>An impeller enquiry may need the approved diameter or trim, rotation, stage position and balance or inspection requirements from the project documents. A wear-ring enquiry may need both mating components identified because a replacement may be evaluated against the condition of the other surface. A shaft sleeve may depend on the shaft and seal configuration. The manufacturer or qualified technical reviewer should confirm the actual fit and acceptance basis. Our <Link className={link} href={postUrl(getPost("reading-a-pump-curve-explained")!)}>pump-curve guide</Link> explains why an impeller change can matter to the hydraulic duty; do not treat an altered diameter as a purely purchasing substitution.</p>
    <h2 id="compare-offers" className={heading}>Make the quotation scope and evidence comparable</h2>
    <p className={paragraph}>Ask the bidder for its proposed part number and revision, applicable drawing, material, quantities, included accessories, manufacturing origin, delivery basis and lead time. Request a dimensional or interface drawing when the part is proposed as an alternative. State which inspection records and material documents the purchase specification requires, and ask the supplier to identify any exclusions or deviations. The <Link className={link} href={postUrl(getPost("heat-number-traceability-mill-certificates")!)}>heat-number traceability guide</Link> explains how to connect delivered material to its certificate; a certificate heading alone does not prove that a particular spare fits the machine.</p>
    <p className={paragraph}>Compare offers line by line. One proposal might contain an impeller plus its key and nut; another might supply the impeller alone. One might quote a replacement ring set, another a single ring. Show those scope differences before comparing totals. If the supplier proposes reverse-engineered or redesigned parts, record that as an alternative with drawings, material and verification evidence for review. <a className={link} href="https://www.sulzer.com/en/shared/services/centrifugal-pump-spare-parts" target="_blank" rel="noopener noreferrer">The Sulzer centrifugal-pump spare-parts page</a> describes both OEM and reverse-engineering routes; it does not establish that either route is suitable for a specific Oillinko enquiry without technical and commercial evaluation.</p>
    <h2 id="rfq-package" className={heading}>Send one traceable RFQ package</h2>
    <p className={paragraph}>A practical package contains the installed unit identity, approved drawings and revisions, maintenance or modification notes, itemized spare list, materials, quantities, duty context and requested documentation. Note which information is verified and which remains uncertain. Ask each bidder to state its identification basis, proposed scope and deviations in the same format. If an urgent outage leaves little time to recover records, preserve those uncertainties in the RFQ instead of turning assumptions into specifications. A fast but incorrect spare can delay the repair longer than a clear technical clarification.</p>
    <p className={paragraph}>Use the <Link className={link} href="/oil-and-gas/equipment/pumps/centrifugal-pumps">centrifugal pump enquiry page</Link> to send the requirement to Oillinko for manual review and routing. Oillinko can coordinate quotations from relevant sources and organize their stated differences; the project team decides the technical acceptance of a replacement. The useful outcome is a proposal that identifies exactly which installed machine, assembly position and component configuration it addresses, with any uncertainty exposed before purchase.</p>
    <Faq faqs={faqs}/>
  </Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>;
}
