import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("charpy-impact-test-reports-temperature-specimens-acceptance")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A Charpy impact report needs more than an absorbed-energy number and a material grade. A purchaser must connect the result to the ordered material, its condition, the test specimen and the specified acceptance requirement. A seemingly high result may still answer the wrong question if the temperature, orientation or sampling basis differs. Begin with the purchase specification, then review the report as a complete record rather than extracting a single convenient value.</p>
    <p className={paragraph}>This review is useful for steel products, forgings, fabricated items and other metallic material purchases where impact testing is required. It does not establish structural fitness or define a minimum energy for every application. Acceptance limits and testing conditions come from the applicable product, construction and project requirements. Where documents disagree, ask the responsible technical reviewer to resolve the requirement before treating the supplied report as evidence of conformity.</p>
    <h2 id="find-the-purchase-acceptance-requirement" className={heading}>Find the purchase acceptance requirement</h2>
    <p className={paragraph}>Locate the order line, material specification, referenced edition and supplementary requirements that call for testing. Identify the required specimen type, temperature, sampling and evaluation basis. A reference to a test method does not necessarily supply the product acceptance limit. The <a className={link} href="https://store.astm.org/e0023-25.html" target="_blank" rel="noopener noreferrer">ASTM E23-25 public scope</a> covers notched-bar impact methods, specimens, reporting, machines and verification. It identifies the document&apos;s subject without replacing its normative requirements or the purchase specification.</p>
    <p className={paragraph}>Write the applicable requirement beside the report reference in the review record. If a certificate says impact tested but omits the detailed results, request the underlying report where the order requires it. Avoid accepting a generic datasheet value as the result for the delivered material. The <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>EN 10204 inspection-document guide</Link> helps distinguish the requested document type from the actual test information and traceability it must contain.</p>
    <h2 id="connect-the-specimens-to-the-supplied-material" className={heading}>Connect the specimens to the supplied material</h2>
    <p className={paragraph}>Match heat or batch identifiers, product form, dimensions and delivery condition across the order, certificate and test report. Check whether the report identifies the sampling location and the material condition represented by the specimens. If heat treatment is relevant to the purchase, retain its reference and the relation between testing and the final supplied condition. A report for the same nominal grade should not silently stand in for a report representing a different heat or processing condition.</p>
    <p className={paragraph}>Use a line-level link between the delivered item and its supporting records, particularly where several heats or product sizes share one shipment. The <Link className={link} href={postUrl(getPost("heat-number-traceability-mill-certificates")!)}>heat-number traceability guide</Link> explains how that connection can be organized. For a fabricated assembly, distinguish base-material results from any separately required weld or heat-affected-zone testing. Their locations and requirements should be identified in the relevant fabrication and inspection documents.</p>
    <h2 id="retain-the-specimen-details" className={heading}>Retain the specimen details</h2>
    <p className={paragraph}>Check the stated method and edition, notch designation and specimen dimensions. Keep the actual dimensions visible when the tested material cannot provide the specimen assumed by the original requirement. A result from a smaller specimen is not automatically interchangeable with one from another geometry. If a permitted alternative or evaluation rule applies, request its documented basis and approval rather than using an informal proportional conversion to produce an apparently equivalent energy value.</p>
    <p className={paragraph}>Confirm that each specimen or set has an identifiable reference. Where machining was subcontracted, ask for enough information to connect the samples to the laboratory results and source material. A handwritten specimen code that differs from the mill certificate may be valid, but its relationship needs an explanation. Resolve that mapping with the issuing parties. Do not repair an unclear traceability chain by relabelling the buyer&apos;s copy without a controlled clarification.</p>
    <h2 id="read-orientation-and-temperature-with-the-result" className={heading}>Read orientation and temperature with the result</h2>
    <p className={paragraph}>Retain the reported specimen orientation and its relationship to the product and sampling direction. Ask for the drawing or notation needed to interpret abbreviations that are unclear. Keep the stated test temperature, units and applicable test condition with the energy values. An energy number detached from those details is an incomplete comparison. The reviewer should check the actual report condition against the ordered condition, without inferring one from a material description or a project location.</p>
    <p className={paragraph}>A <a className={link} href="https://www.nist.gov/publications/test-temperature-range-nist-certified-charpy-specimens-testing-room-temperature" target="_blank" rel="noopener noreferrer">2023 NIST study of certified verification specimens</a> shows why even a room-temperature label needs a defined temperature basis in that programme. Its subject is machine-verification specimens and their testing range. It does not establish a universal acceptance temperature for purchased materials. For procurement review, the practical lesson is to preserve the actual temperature information and assess it using the applicable requirement.</p>
    <h2 id="review-individual-results-and-the-evaluation-basis" className={heading}>Review individual results and the evaluation basis</h2>
    <p className={paragraph}>Request the individual absorbed-energy results and the reported units, together with any summary required by the specification. Check how the report associates results with specimen references and test sets. An average alone may leave the reviewer unable to apply requirements that also address individual results. Conversely, an isolated low value should not be judged using an invented acceptance rule. Apply the exact approved evaluation basis and record where further technical clarification is needed.</p>
    <p className={paragraph}>Treat retesting and replacement specimens as controlled events. If a report contains additional sets, ask why they were tested and which requirement permits their evaluation. Preserve the original result and the explanation rather than selecting whichever set appears most favourable. A revised laboratory report should identify its revision and relationship to the earlier issue. Commercial urgency does not justify converting unresolved results into a clean pass statement on a comparison sheet.</p>
    <h2 id="separate-machine-evidence-from-material-acceptance" className={heading}>Separate machine evidence from material acceptance</h2>
    <p className={paragraph}>Where required, obtain the relevant test-equipment and verification references supporting the laboratory&apos;s result. These records concern confidence in the testing arrangement; they do not establish that a particular product meets its purchase requirement. Equally, a material result should not be used as a substitute for requested machine-verification evidence. Keep the report, laboratory identity and required supporting records together so the review can distinguish missing test evidence from an actual acceptance failure.</p>
    <p className={paragraph}>If laboratory accreditation is specified, assess the activity and applicable scope rather than relying on a logo. The <Link className={link} href={postUrl(getPost("iso-17025-laboratory-accreditation-scope-test-report")!)}>ISO 17025 laboratory-scope guide</Link> covers that separate check. Ask the laboratory to clarify the status of subcontracted activities where this affects the order. A general accreditation claim should not obscure which party prepared specimens, performed the test or issued the report being used for material acceptance.</p>
    <h2 id="close-evidence-gaps-before-release" className={heading}>Close evidence gaps before release</h2>
    <p className={paragraph}>Record discrepancies by order line and report reference: missing temperature, uncertain specimen dimensions, unexplained orientation, inconsistent identifiers or an absent acceptance basis. Direct the clarification to the party that can issue or approve the relevant record. Distinguish an incomplete report from a result confirmed as nonconforming. Both may prevent acceptance, but they lead to different decisions and should not be merged into an unsupported conclusion about the entire material shipment.</p>
    <p className={paragraph}>Submit the material schedule, purchase requirements and existing reports through Oillinko&apos;s <Link className={link} href="/oil-and-gas/services/inspection-ndt-and-material-testing">inspection, NDT and material testing service page</Link> for manual enquiry coordination. State whether the request concerns new testing, report clarification or document review. The useful deliverable is a traceable set of results that can be evaluated against an identified requirement. Final material release and any engineering fitness assessment belong to the responsible project reviewers.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
