import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";
const post = getPost("check-valve-cracking-pressure-rfq-guide")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading="mt-12 text-xl font-bold";
const link="text-accent underline underline-offset-4";
const faqs=[
  {
    "q": "Is cracking pressure the maximum working pressure?",
    "a": "No. Cracking describes the start of flow under specified conditions. Working pressure is a separate rating for the particular configuration and temperature."
  },
  {
    "q": "Does a lower cracking pressure guarantee enough flow?",
    "a": "No. Obtain the applicable flow data and review the required flow against upstream and downstream conditions for the actual fluid."
  },
  {
    "q": "Can every check valve provide leak-tight isolation?",
    "a": "Do not assume so. Confirm the product-specific reseal and leakage requirements, and have the responsible engineer define any separate isolation function needed."
  }
];
export default function Page(){return <><BlogPostHeader post={post}/><Prose>
<p className={paragraph}>A quotation for a check valve can show a high working pressure and a very small cracking pressure without any contradiction. The two values answer different questions. One concerns the pressure the specified configuration is rated to contain; the other describes the start of opening under defined conditions. Buying from either number alone can leave the valve poorly matched to the available pressure difference, required flow or closing duty. A useful RFQ separates these requirements before asking suppliers to propose a model.</p>
<p className={paragraph}>This guide focuses on inline spring-loaded check valves used in equipment and instrumentation circuits. It explains what buyers should request from the manufacturer, without transferring one product series’ limits to every check valve design. Larger swing, dual-plate and other line check valves need their own selection review. For a wider view of the families involved, start with the <Link className={link} href={postUrl(getPost("valves-and-actuation-explained")!)}>oil and gas valve types guide</Link>{" "}and then identify the particular function your project needs.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Check valve buying questions: opening threshold, required flow, reseal behavior and pressure-temperature rating are separate checks."/><figcaption className="mt-3 text-sm text-muted">Four separate questions belong in the same valve enquiry.</figcaption></figure>
<h2 id="cracking-pressure-is-the-beginning-of-flow" className={heading}>Cracking pressure is the beginning of flow</h2>
<p className={paragraph}>The <a className={link} href="https://www.swagelok.com/downloads/webcatalogs/en/ms-01-176.pdf" target="_blank" rel="noopener noreferrer">Swagelok C, CA, CH, CP and CPA catalogue</a>{" "}defines cracking by the first observed flow and gives separate reseal information. Its flow curves are separate from the opening specification and were developed under stated laboratory conditions. This distinction matters: an opening threshold does not tell a buyer how much fluid will pass at the intended operating point. Obtain the applicable flow data for the exact configuration rather than treating cracking pressure as a capacity rating.</p>
<p className={paragraph}>In the enquiry, identify both upstream and downstream conditions so the reviewer can assess the available pressure difference. A line pressure stated without its location or reference is incomplete. Keep pressure units consistent and distinguish gauge, absolute and differential values wherever they appear. Ask the supplier to explain the basis of any quoted opening value, especially if the catalogue uses upstream pressure under a defined test arrangement. Do not silently substitute a system pressure reading for the manufacturer’s stated test condition.</p>
<h2 id="request-the-opening-range-not-just-the-nominal-value" className={heading}>Request the opening range, not just the nominal value</h2>
<p className={paragraph}>A nominal spring designation is not necessarily a promise that every valve opens at exactly that number. <a className={link} href="https://www.parker.com/content/dam/Parker-com/Literature/Instrumentation-Products-Division/Catalogs/IPD_Check_Valves_Catalog_4135-CV.pdf" target="_blank" rel="noopener noreferrer">Parker catalogue 4135-CV</a>{" "}lists opening ranges and resealing conditions for particular series and notes that initial opening after inactivity can be higher. Treat those statements as product-specific evidence to review, not tolerances to copy across brands. Request the offered nominal setting, permitted range and any conditions relevant to the planned duty.</p>
<p className={paragraph}>If alternatives are allowed, compare their documented ranges against the project requirement instead of matching only the number embedded in a part code. For an adjustable design, state whether a factory setting and recorded verification are required at delivery. Identify who will approve the final selection and any later setting change. This is a procurement requirement, not an instruction to adjust a pressurized valve. Adjustment and commissioning must follow the actual manufacturer documentation and the project’s controlled work arrangements.</p>
<h2 id="resealing-and-reverse-leakage-need-their-own-questions" className={heading}>Resealing and reverse leakage need their own questions</h2>
<p className={paragraph}>Opening and closing are different conditions. The Swagelok catalogue provides reseal values that depend on the selected series and spring, including cases expressed in terms of back pressure. Do not assume a valve closes leak-tight at the same value at which it first opens. Describe the expected reverse-pressure conditions and ask the supplier to confirm the applicable reseal behavior and leakage acceptance basis for the proposed product.</p>
<p className={paragraph}>A manufacturer’s description can make the distinction explicit. Parker identifies its <a className={link} href="https://ipd.parker.com/product/mpi-specialty-valves-and-filters/mac-and-macb-check-valves" target="_blank" rel="noopener noreferrer">MACB ball check valve</a>{" "}for reverse-flow prevention where leak-tight shut-off is not mandatory, while describing a different sealing function for its MAC design. A generic request for a non-return valve therefore leaves an important decision open. State what reverse leakage the project permits, the relevant verification conditions and whether another independently specified isolation function is required. The responsible engineer should determine that protection boundary.</p>
<h2 id="compare-capacity-at-the-required-duty" className={heading}>Compare capacity at the required duty</h2>
<p className={paragraph}>Give minimum, normal and maximum required flow where these are known, with the fluid, operating temperature and pressure conditions associated with each case. For gases, specify the reference conditions used for any standard or normal volumetric flow units. A flow number without its basis can produce an apparently reasonable comparison between different duties. Ask the supplier to identify which published curve or calculation supports the proposed selection and which assumptions still need confirmation.</p>
<p className={paragraph}>For a replacement, attach the existing model and configuration together with the reason for replacement. If the concern is inadequate flow, reverse leakage or unstable operation, describe the observed symptom without declaring an unverified cause. A like-for-like part may restore the original configuration, but it does not by itself resolve a mismatch between that configuration and a changed process. The <Link className={link} href={postUrl(getPost("reading-a-pump-curve-explained")!)}>pump curve reading guide</Link>{" "}provides complementary context when the valve forms part of a pumping circuit; equipment selection still needs a review of the complete duty.</p>
<h2 id="keep-pressure-rating-materials-and-connections-visible" className={heading}>Keep pressure rating, materials and connections visible</h2>
<p className={paragraph}>Write the operating envelope and required design conditions separately from the opening requirement. Ask for the rating applicable to the offered body, seals and end connections at the specified temperature. A headline catalogue maximum is not evidence that every ordering option carries that rating. Record the manufacturer document and revision used to justify the offer. If an alternative needs a different connection or seal arrangement, make it a clearly identified deviation for technical approval.</p>
<p className={paragraph}>Identify the fluid and any relevant composition information needed for compatibility review, rather than writing only oil or gas. Request the materials of the wetted components and seals for the proposed configuration. State connection size, standard, gender and installation orientation, and attach dimensions where a replacement must fit existing space. Manufacturing origin, if required, should be confirmed for the supplied product; a seller’s office address or dispatch country does not establish where the valve was made.</p>
<h2 id="agree-evidence-before-placing-the-order" className={heading}>Agree evidence before placing the order</h2>
<p className={paragraph}>Ask which factory checks are included and what documentation accompanies the supplied items. Where a project needs recorded opening, resealing or leakage results, define the required report and item identification before comparing the commercial offers. Keep a conformity statement, a material record and a functional test result as distinct deliverables. The <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>inspection and test plan guide</Link>{" "}helps when purchaser attendance or approval is part of the order, rather than assuming a certificate automatically includes a witnessed test.</p>
<p className={paragraph}>Send Oillinko the required quantity, available datasheet, existing part identity, operating conditions and acceptance requirements through the <Link className={link} href="/oil-and-gas/equipment/valves/butterfly-and-check-valves">butterfly and check valve enquiry page</Link>. Mark unknown inputs clearly so they become technical clarifications instead of hidden assumptions in the quotation. Oillinko coordinates the sourcing request; the supplier and responsible project reviewer confirm suitability. The aim is an offer that identifies the complete valve configuration, its evidence and any exceptions, with delivery and documentation scope that can be compared fairly.</p>
<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>;}
