import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("check-valve-face-to-face-dimensions-rfq")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";
const faqs = [
  {
    q: "Is a Class 150, two-inch check valve automatically a drop-in replacement?",
    a: "No. The body pattern, installation length, mating connections, materials and duty must also match the approved piping arrangement.",
  },
  {
    q: "Does a reference to API 594 define every dimension needed for purchase?",
    a: "It identifies a product-standard basis, but the buyer should still state the required valve type, applicable edition, end connection and drawing or dimension to be checked.",
  },
  {
    q: "Can a wafer valve be offered instead of a flanged valve?",
    a: "Only as an identified alternative for the responsible engineer to review. The two arrangements have different installation interfaces and must not be treated as interchangeable from nominal size and class alone.",
  },
];

export default function Page() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A check-valve RFQ can look complete when it lists a two-inch size, Class 150 and a standards reference. Yet two quotations with those words can describe different physical installations. A compact wafer body held between mating flanges is not the same purchase as a valve with its own flanged ends. The body may occupy a different length in the line, require a different bolting arrangement and have a different closure mechanism. Before comparing price, the buyer needs to identify the existing or approved connection and the distance available between its connection faces.</p>
    <p className={paragraph}>This guide addresses dimensional interchangeability, especially for replacement and constrained piping work. It complements our <Link className={link} href={postUrl(getPost("check-valve-cracking-pressure-rfq-guide")!)}>check-valve cracking-pressure guide</Link>, which deals with opening, flow and resealing rather than fit. An engineering authority still has to confirm the selected valve for the fluid, installation and operating duty. Oillinko can coordinate enquiries, but a catalogue description or a matching nominal size is not an approval for installation.</p>
    <figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Diagram contrasting the measured installation length of a wafer check valve between flanges with a check valve that has integral flanged ends."/><figcaption className="mt-3 text-sm text-muted">Identify the actual connection faces and installation length before comparing valve patterns. Diagram is conceptual, not a dimensional drawing.</figcaption></figure>
    <h2 id="why-face-to-face-matters" className={heading}>Why face-to-face length matters</h2>
    <p className={paragraph}>Face-to-face is the distance between defined end faces of a straightway valve. The <a className={link} href="https://www.asme.org/codes-standards/find-codes-standards/b16-10-face-face-end-end-dimensions-valves" target="_blank" rel="noopener noreferrer">ASME B16.10-2022 overview</a> explains that standard dimensions support installation interchangeability for a given material, valve type, size, rating class and end connection. That list of qualifiers matters. Merely writing “ASME B16.10” next to a nominal diameter does not tell a bidder which valve construction or length the project expects. The applicable table and any project-specific exception must be checked against the approved drawing or existing installation.</p>
    <p className={paragraph}>For a replacement, record the measured gap and clearly identify its reference faces. An old valve’s overall body length may not be the dimension that governs installation when adapters, gaskets or mating flanges are present. Ask for the manufacturer’s general-arrangement drawing showing its proposed face-to-face or end-to-end dimension and tolerance. Have the responsible piping reviewer compare that drawing with the spool, flange and maintenance-clearance drawings. Do not infer that a short-pattern body will fit merely because its published dimension is smaller; it may require a different bolting or support arrangement.</p>
    <h2 id="name-the-valve-pattern" className={heading}>Name the valve pattern and end arrangement</h2>
    <p className={paragraph}>The <a className={link} href="https://www.api.org/products-and-services/standards/standards-plan" target="_blank" rel="noopener noreferrer">API standards plan</a> identifies API 594 as covering flanged, lug, wafer and butt-welding check valves. Those terms are meaningful RFQ fields, not interchangeable labels. A wafer valve normally fits between mating flanges; a lug pattern uses its own lugged fastening arrangement; and a flanged valve has integral flanged ends. A butt-weld end introduces a different piping interface again. Specify the accepted pattern and whether alternatives are permitted. Where the existing arrangement is uncertain, send photographs and an approved drawing rather than choosing from a sales description.</p>
    <p className={paragraph}>Also identify the internal closure type and any orientation requirement. A swing disc, dual plate and axial or nozzle-style design can differ in envelope, flow behavior and installation restrictions. The manufacturer’s drawing and installation documentation should establish the offered configuration. A <a className={link} href="https://generalmetal.com.tr/en/product/krd-dpc-cekvalf/2/" target="_blank" rel="noopener noreferrer">manufacturer’s dual-plate product page</a> is an example of a series described as wafer type with its own design and face-to-face references; it is not a substitute for checking the offered model against a particular project’s specification. Avoid reading one series’ claims into every product carrying the same generic check-valve name.</p>
    <h2 id="check-the-mating-flanges" className={heading}>Check the mating flanges separately</h2>
    <p className={paragraph}>“RF ends” needs an interface definition. State the flange standard and edition, nominal size, class, facing and any project gasket and bolting requirements. <a className={link} href="https://www.asme.org/codes-standards/find-codes-standards/b16-5-pipe-flanges-flanged-fittings-nps-1-2-nps-24-metric-inch-standard" target="_blank" rel="noopener noreferrer">ASME B16.5-2025</a> covers dimensions and pressure-temperature ratings for the flanges within its scope. That flange reference does not, by itself, establish the check valve’s body pattern or installation length. Request a drawing that shows the interface the offered valve actually provides. For a wafer or lug body, the drawing should make clear which mating flanges and bolting arrangement it assumes.</p>
    <p className={paragraph}>A class designation is not a fixed allowable operating pressure for every material and temperature. Our <Link className={link} href={postUrl(getPost("asme-b16-5-flange-pressure-classes")!)}>flange pressure-class guide</Link> explains how to keep the material group and design temperature visible. The check-valve body, seats, end connections and mating components require their own review. If a bidder offers a different facing, flange series or connection pattern, record it as a deviation; do not hide it under an apparently matching “Class 150” line item.</p>
    <h2 id="specify-duty-and-materials" className={heading}>Keep function, orientation and materials in the same enquiry</h2>
    <p className={paragraph}>Dimensional fit is necessary but not sufficient. State the fluid, expected flow range, pressure and temperature conditions, reverse-flow duty and intended installation orientation. A design that fits the spool still needs an appropriate opening and closing response for the actual system. Ask the manufacturer for the proposed flow data, installation limits and any minimum-flow or pressure-difference assumptions. If water hammer or rapidly changing flow is a concern, provide the system information to the responsible engineer rather than expecting a generic “non-slam” label to resolve it.</p>
    <p className={paragraph}>List required body, disc or plates, hinge or spring, seat and other wetted materials separately. A shorthand such as “stainless check valve” does not identify every wetted component or the seat construction. If the project specification has not yet fixed these materials, mark the gap as a clarification and ask bidders to state their proposed material schedule. Require manufacturing origin for the supplied product when it is commercially relevant; the location of a distributor or shipping warehouse is not proof of the manufacturing country.</p>
    <h2 id="compare-drawings-and-evidence" className={heading}>Compare drawings and evidence, not just line-item prices</h2>
    <p className={paragraph}>For each offer, collect the model and revision, applicable design and dimensional standards, general-arrangement drawing, pressure-temperature rating basis, material schedule and stated test scope. Ask which certificate and test reports will be supplied with the identified valve. Our <Link className={link} href={postUrl(getPost("api-598-vs-iso-5208-valve-testing-buyers-guide")!)}>valve testing guide</Link> helps distinguish a cited test standard from an actual report with an acceptance basis. Verify the exact edition required by the project rather than assuming that all suppliers quote against the same revision.</p>
    <p className={paragraph}>A comparison sheet should show the requested configuration beside each offered configuration. Give separate columns for valve pattern, NPS, class, end connection and facing, face-to-face length, materials, flow direction and installation orientation. Mark an unanswered field as unknown rather than compliant. If the bidder proposes a wafer body against a flanged request, show the dimensional and piping implications and obtain an engineering decision before placing the order. The lowest quoted amount is not comparable if it excludes the work or components needed to make the valve fit.</p>
    <h2 id="send-a-clear-rfq" className={heading}>A compact RFQ package</h2>
    <p className={paragraph}>Send the approved line specification, quantity, latest piping or spool drawing, existing valve identification if available, measured connection faces, mating flange details and required delivery location. Add the operating-duty sheet and document list. Ask bidders to attach their own dimensional drawing and explicitly list deviations. If a field is still being clarified, say so and request a conditional proposal instead of presenting the assumption as an approved requirement. This keeps alternatives visible and lets procurement compare technically reviewable offers.</p>
    <p className={paragraph}>Use Oillinko’s <Link className={link} href="/oil-and-gas/equipment/valves/butterfly-and-check-valves">check-valve enquiry page</Link> to route the requirement for manual sourcing review. Oillinko can request quotations from relevant manufacturers and organize the responses around the approved specification. The project’s responsible technical team confirms compatibility, dimensional fit and any accepted alternative. An RFQ that names the pattern and its actual connection faces gives every bidder a fairer basis for a useful proposal.</p>
    <Faq faqs={faqs}/>
  </Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post), breadcrumbJsonLd(post), faqJsonLd(faqs)]}/><CtaBand/></>;
}
