import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("controlled-bolting-services-rfq-handover-guide")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";
const faqs = [
  { q: "Does a torque record prove a flange is leak-tight?", a: "No. It records the specified assembly activity. Any pressure or leak test, its acceptance criteria and the authority to return the system to service must be agreed separately." },
  { q: "Can a contractor choose the bolt load from flange size alone?", a: "Flange size alone is insufficient. The responsible technical party must approve the joint-specific assembly basis, including gasket, fastener, friction assumptions and relevant component limits." },
  { q: "Is tool rental the same as a complete controlled-bolting service?", a: "No. Rental, trained personnel, engineering, joint preparation, execution, inspection and reporting are distinct scopes unless expressly included in the quotation." },
];

export default function Page() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A controlled bolting services RFQ should identify the joints, the approved assembly requirements and the records expected at handover. A request for a crew with hydraulic tools leaves important questions unanswered: who confirms the loading basis, who supplies replacement fasteners, which joints are ready for work, and what proves completion? These differences can produce quotations that look comparable on a day rate but cover very different responsibilities. Buyers can reduce that uncertainty by defining a work package before asking for prices.</p>
    <p className={paragraph}>This guide addresses procurement and scope control for pressure-boundary flange assembly. It does not provide torque values, hydraulic pressures or a field tightening procedure. The asset owner and responsible technical parties approve those requirements for the actual connection. Equipment supply, onsite execution and engineering support can be purchased separately, so an enquiry should identify the intended combination rather than assume that every service provider includes all three.</p>

    <h2 className={heading}>Build a joint register before counting workdays</h2>
    <p className={paragraph}>Give each joint a stable identifier linked to the piping isometric, equipment nozzle or approved drawing. Record its location, connection standard, nominal size, pressure designation, facing, gasket reference and fastener specification. Include bolt quantity, diameter, thread, length and any coating or approved lubrication information. State whether the work concerns a new assembly, reassembly after maintenance, or investigation of an existing problem. A list of flange sizes alone does not capture these differences.</p>
    <p className={paragraph}>Separate confirmed information from unresolved inputs. If the gasket construction or bolt grade is unknown, identify who will establish it and when. Photographs can help explain restricted access, but they should be tied to the correct joint and drawing revision. For a turnaround with several work fronts, group joints by readiness and location. This lets bidders distinguish practical mobilization and movement time from the actual assembly quantity without inventing a universal productivity rate.</p>

    <h2 className={heading}>Approve the assembly basis and proposed method</h2>
    <p className={paragraph}>The <a className={link} href="https://www.asme.org/codes-standards/find-codes-standards/pressure-boundary-bolted-flange-joint-assembly" target="_blank" rel="noopener noreferrer">ASME PCC-1 product page</a> identifies the 2022 edition and describes guidance for pressure-boundary joints with specified ring-gasket geometry. Name the project-selected edition and verify its applicability. A reference to PCC-1 on a quotation is not a joint-specific procedure or proof that every connection in the work package falls within its scope.</p>
    <p className={paragraph}>Ask the bidder to identify the proposed tightening method and explain the tools and geometry needed for it. Torquing applies a turning moment, while tensioning applies axial loading through a tensioning arrangement. The <a className={link} href="https://blog.enerpac.com/torque-vs-tension-whats-the-difference/" target="_blank" rel="noopener noreferrer">manufacturer explanation of torque and tension</a> also highlights friction in the torque-to-load relationship. Method selection therefore requires review of the complete joint and available access, rather than preference for one tool type in every situation.</p>
    <p className={paragraph}>The scope should identify who develops and approves the loading basis, sequence and verification method. Require any proposed change in lubrication, coating, gasket or fastener condition to be reviewed against that basis. A number copied from a different connection is not an approved target. Where the contractor supplies engineering calculations, specify their inputs, review authority and deliverables separately from the execution price. Where the owner supplies them, include the controlled revision with the enquiry.</p>

    <h2 className={heading}>Define preparation, access and site responsibilities</h2>
    <p className={paragraph}>Joint readiness affects both the scope and the schedule. State who checks flange condition and alignment, provides the specified gasket and fasteners, and resolves damaged threads or unsuitable surfaces. Replacing a gasket, extracting a seized stud, machining a flange face and assembling an accepted joint are different activities. Ask bidders to price conditional repair work separately and identify the approval required before it starts. This prevents an initial assembly quotation from silently becoming an open-ended repair commitment.</p>
    <p className={paragraph}>Include available clearance around the nuts and studs, nearby obstructions, working height and the expected access arrangements. Ask for a feasibility review against the proposed tooling, including required reaction or support arrangements where applicable. Define responsibility for scaffolding, lifting assistance, power, lighting and site induction. Offshore or remote work may also require specific mobilization arrangements and personnel documents; list the requirements that actually apply rather than add generic certificates to every enquiry.</p>
    <p className={paragraph}>The operating organization must define isolation, permits and the conditions for releasing the work area. <a className={link} href="https://www.hse.gov.uk/pubns/books/hsg253.htm" target="_blank" rel="noopener noreferrer">HSE HSG253</a> addresses isolation for intrusive work in oil, gas and associated process operations. Make those responsibilities explicit in the service boundary. A bolting crew’s arrival or completed worksheet does not establish that equipment is isolated or that the system can return to operation. This guide is not a procedure for work on a live pressure boundary.</p>

    <h2 className={heading}>Specify competence, tools and completion evidence</h2>
    <p className={paragraph}>Request competence evidence relevant to the agreed method and joint types, along with the proposed supervision and inspection roles. A company brochure describing controlled bolting does not confirm that the assigned crew meets the project’s requirements. Ask how personnel and tool substitutions will be controlled. For the equipment, define which identification, calibration or verification records are required and connect them to the actual tool package, not only to an unrelated example certificate.</p>
    <p className={paragraph}>Agree the joint record format before mobilization. A useful record identifies the joint, drawing and procedure revisions, specified materials, method, tool references, operator, date and recorded execution results. It also captures abnormalities, substitutions, interrupted work and the associated technical disposition. The required detail follows the approved method. A single summary reading “all flanges complete” provides little traceability when one connection later needs investigation or when work is handed between different shifts.</p>
    <p className={paragraph}>Define review and witness stages in the <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>inspection and test plan</Link>. Distinguish assembly completion from an independent pressure or leak test and from final system acceptance. If testing belongs to another contractor, identify the interface and the records to exchange. Where repeat assembly may follow a test finding, agree how the finding is investigated, who approves corrective work and how the affected joint history is preserved.</p>

    <h2 className={heading}>Compare the complete quotation and handover package</h2>
    <p className={paragraph}>Compare mobilization, crew composition, shift length, tool coverage, consumables and reporting alongside the execution rates. State the planned work window and the expected readiness of each work front. Request explicit standby, extension and demobilization assumptions. A bidder may offer a fixed price for a defined joint register and separate rates for changes, but the change mechanism must identify who authorizes extra work. Do not treat an assumed completion duration as a confirmed site schedule.</p>
    <p className={paragraph}>Review exclusions together with technical deviations. For example, a quote may include assembly personnel and tooling but exclude engineering, replacement materials, machining, access platforms and final testing. Those exclusions may be acceptable if other parties own them and the interfaces are documented. Compare the assembled project scope rather than choosing the lowest isolated line price. The <Link className={link} href={postUrl(getPost("flanges-gaskets-and-bolting")!)}>flange, gasket and bolting guide</Link> and <Link className={link} href={postUrl(getPost("spiral-wound-gasket-identification-rfq")!)}>gasket identification guide</Link> help organize the component information that supports this comparison.</p>
    <p className={paragraph}>Before closing the work order, reconcile the completed joint register with the authorized scope and obtain the agreed records, outstanding-item list and approved dispositions. Send Oillinko the drawings, joint list, site location, work window and reporting requirements through the <Link className={link} href="/oil-and-gas/services/controlled-bolting-and-onsite-machining">controlled bolting and onsite machining enquiry page</Link>. Oillinko reviews and routes the enquiry to suitable service sources; the listing does not establish an appointed contractor or an in-house execution capability.</p>
    <Faq faqs={faqs}/>
  </Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>;
}
