import Link from "next/link";
import SiteImage from "@/components/SiteImage";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("country-of-origin-vs-dispatch-equipment-rfq")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A valve may be manufactured in one country, held by a distributor in another and dispatched from a third. Writing only “origin: Turkey” on an equipment quotation can therefore create a costly misunderstanding: does Turkey mean the factory, the seller, the warehouse or the point of export? Buyers need each fact in its own field. The distinction affects technical approval, customs documents, delivery planning and the credibility of the final handover record.</p>
    <p className={paragraph}>The <a className={link} href="https://www.wcoomd.org/en/topics/origin/overview/faq-origin.aspx" target="_blank" rel="noopener noreferrer">World Customs Organization origin FAQ</a> distinguishes the origin of goods from mere provenance, or the country from which they were shipped. It also explains that origin rules depend on the applicable trade regime and may involve substantial transformation. A purchase document should therefore ask for the factual country of manufacture and, separately, the customs country of origin declared for the intended import. Those answers may need a formal review; neither is established by the seller&apos;s office address.</p>
    <figure className="mt-8"><SiteImage src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Equipment RFQ diagram showing separate fields for manufacturing country, customs origin, dispatch location and supporting evidence."/><figcaption className="mt-3 text-sm text-muted">Four distinct fields prevent a warehouse location from becoming a false manufacturing claim.</figcaption></figure>

    <h2 id="four-fields" className={heading}>Separate four location fields</h2>
    <p className={paragraph}>First, name the actual manufacturing site and country for the offered product. This is where the equipment is made, not where the invoice is issued. For an assembly containing components from several countries, ask what was manufactured and assembled at the named site; do not force a complex assembly into an unsupported single-factory statement. The owner&apos;s equipment records may need the manufacturer, model and serial number as well as the place of manufacture.</p>
    <p className={paragraph}>Second, record the proposed customs country of origin and the rule or certificate basis relevant to the shipment. The customs declaration is a legal classification for a particular destination and trade arrangement, and it may not follow from simple assembly location alone. Third, record where the goods will physically depart from, including the warehouse or port if known. Fourth, identify the contracting seller and invoicing entity. A buyer can then compare these four facts without treating a trading company as the manufacturer.</p>

    <h2 id="why-it-matters" className={heading}>Why the difference changes an RFQ decision</h2>
    <p className={paragraph}>A project may restrict approved manufacturing locations, require a specified country for certain components or demand factory-issued inspection records. A distributor with ready stock may still be a useful source, but the factory documents must match the offered model and serials. A country-of-dispatch answer alone cannot satisfy that approval. Conversely, a product manufactured in the requested country may ship from a regional warehouse elsewhere without changing the fact of its manufacture.</p>
    <p className={paragraph}>The distinction also affects pricing and lead time. A quotation marked EXW at a distributor&apos;s warehouse has a different collection point from EXW at the factory. Export clearance responsibilities, packing, local transport and transit documents must be priced against the actual dispatch point. The <Link className={link} href={postUrl(getPost("exw-vs-fca-oil-gas-equipment-buyers")!)}>EXW versus FCA guide</Link> explains why the named place matters; the <Link className={link} href={postUrl(getPost("dap-vs-ddp-oil-gas-equipment-buyers")!)}>DAP versus DDP guide</Link> addresses later delivery and import responsibilities. Neither Incoterm proves where an item was made.</p>

    <h2 id="evidence" className={heading}>Ask for evidence proportionate to the order</h2>
    <p className={paragraph}>For a preliminary enquiry, request the manufacturer&apos;s name, product series, manufacturing country, proposed dispatch country and any known origin document. At technical bid stage, request the exact model and part number, factory data sheet and the origin statement or certificate that the importer requires. The <a className={link} href="https://www.wcoomd.org/en/topics/origin/instrument-and-tools/origin-certification-tools.aspx?p=1" target="_blank" rel="noopener noreferrer">WCO origin certification material</a> shows that proof of origin is a distinct documentation question. The correct document depends on the importing jurisdiction and any preferential claim; a generic seller declaration should not automatically be treated as sufficient.</p>
    <p className={paragraph}>For serialized equipment, connect the manufacturer record, nameplate or serial list, packing list and shipping documents. Check that the described unit and quantities are consistent across the file. If a supplier proposes several sources for one line item, ask it to identify which source applies to each quantity. If material certificates are required, check that heat or batch references follow the project specification and can be tied to the delivered units. An attractive country label on a brochure has little value if the final shipment cannot be traced back to it.</p>

    <h2 id="comparison" className={heading}>Compare offers without assuming equivalence</h2>
    <p className={paragraph}>A practical bid table has separate columns for manufacturer and factory country, declared customs origin, seller, dispatch point, document offered and uncertainty. Mark missing information explicitly. Two bidders may offer the same nominal valve size but different factories, inspection routes and available records. The comparison should show those differences before any price ranking. If one bid relies on stock already outside the manufacturing country, request a serial-specific confirmation that the stocked items meet the current specification and have not been substituted.</p>
    <p className={paragraph}>Do not use “made in” casually when only the country of shipment is known. Equally, do not tell a customer that a product fails an origin requirement merely because it will leave a different country. Ask the project&apos;s customs adviser or importer to determine the legally applicable origin rule. Procurement can collect the factual supply-chain evidence and flag inconsistencies; it should not issue a customs ruling from a catalogue page.</p>

    <h2 id="rfq" className={heading}>Write the location question into the RFQ</h2>
    <p className={paragraph}>For each offered line, request: actual manufacturer and manufacturing site, country of manufacture, proposed customs country of origin with supporting document, seller and invoice entity, physical dispatch location, Incoterm with named place, export and packing responsibilities, and any permitted substitution. Ask bidders to identify unknowns and provide the date by which they will be resolved. If partial shipments are allowed, collect the same fields by shipment. The <Link className={link} href={postUrl(getPost("export-packing-oil-gas-equipment-rfq")!)}>export packing RFQ guide</Link> helps define a separate packing evidence package.</p>
    <p className={paragraph}>Oillinko can manually route an equipment or logistics enquiry through its <Link className={link} href="/oil-and-gas/services/freight-expediting-and-project-logistics">freight and project logistics page</Link>. Include the destination, required documents and the four location fields above. We do not infer stock, supplier authorization or origin from a public listing. A commercial offer should state confirmed facts, open clarifications and any exceptions before the buyer commits to a delivery promise.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
