import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post=getPost("dap-vs-ddp-oil-gas-equipment-buyers")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading="mt-12 text-xl font-bold";
const link="text-accent underline underline-offset-4";
const faqs=[
  {q:"Does DDP always provide the lowest-risk option for an equipment buyer?",a:"No. DDP places broad delivery and import obligations on the seller, but the seller may be unable to act as importer or recover import taxes in the destination country. The parties must confirm legal feasibility and the actual cost boundary before using it."},
  {q:"Who unloads equipment under DAP and DDP?",a:"Under both rules, delivery is generally made with the goods ready for unloading on the arriving means of transport at the named place. The buyer bears the unloading risk unless the contract deliberately allocates related work or costs differently."},
  {q:"Do Incoterms rules determine payment terms or transfer of ownership?",a:"No. Incoterms rules allocate specified delivery obligations, risk and costs. The sales contract must separately address price, payment, title, warranties, remedies, governing law and other commercial terms."}
];

export default function Page(){return <><BlogPostHeader post={post}/><Prose>
<p className={paragraph}>A quotation marked “delivered” is not complete until the buyer knows who will clear the equipment for import, who will pay duties and taxes, where delivery and risk transfer occur, and which destination charges are included. DAP and DDP are both arrival terms under Incoterms® 2020, but they assign the import boundary differently. That difference can affect customs compliance, cash flow, project schedule and the comparability of competing equipment offers.</p>
<p className={paragraph}>This guide explains how buyers can write and evaluate DAP and DDP quotations for valves, pumps, skids, instruments and other industrial equipment. It is a procurement overview, not customs, tax or legal advice. Import rules vary by country, product and transaction. The buyer and seller should confirm the proposed structure with their customs advisers and incorporate the exact ICC rule, version and named place into the contract.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="DAP versus DDP equipment quotation workflow showing transport, import clearance, duties, delivery and unloading boundaries."/><figcaption className="mt-3 text-sm text-muted">DAP and DDP both bring equipment to a named destination; the import-clearance boundary distinguishes them.</figcaption></figure>

<h2 id="use-the-full-trade-term" className={heading}>Use the full trade term</h2>
<p className={paragraph}>Write the three-letter rule, a precise named place or point, and “Incoterms® 2020.” “DAP Saudi Arabia” or “DDP site” is too broad for pricing and risk allocation. A named place might be a port terminal, freight forwarder’s facility, project warehouse or exact site gate. If the location has several entrances, terminals or unloading areas, name the point that the carrier can reach and state any access restrictions.</p>
<p className={paragraph}>The International Chamber of Commerce explains that the rules allocate obligations, risk and costs; they are not substitutes for the complete sales contract. The <a className={link} href="https://library.iccwbo.org/clp/clp-incoterms-qa-2020.htm?AGENT=ICC_HQ" target="_blank" rel="noopener noreferrer">ICC Incoterms overview</a> also notes that DAP and DDP are among the rules where delivery occurs closest to the buyer. Payment, ownership, warranty, inspection, delay remedies and governing law still need separate clauses.</p>

<h2 id="what-dap-means-for-the-import-boundary" className={heading}>What DAP means for the import boundary</h2>
<p className={paragraph}>Under DAP, the seller arranges and bears the transport risk to the named destination, with the goods placed at the buyer’s disposal on the arriving means of transport ready for unloading. The buyer handles import clearance and the associated import duties and taxes. The buyer should therefore be ready to act as importer or appoint an authorized customs representative and provide the information needed for a timely declaration.</p>
<p className={paragraph}>DAP can be practical when the buyer has an established local import process, duty relief, project exemption or recoverable import-tax structure. The quotation should still identify which charges the seller’s freight price covers. Port storage, demurrage, inspection fees, customs-agent charges, permits, security deposits, inland escorts and waiting time can arise even though the main carriage is included. Allocate them expressly instead of assuming that every destination cost follows the three-letter term.</p>

<h2 id="what-ddp-adds" className={heading}>What DDP adds</h2>
<p className={paragraph}>DDP places responsibility on the seller for both export and import formalities and for the relevant duties required by the rule. The goods are delivered at the named place on the arriving means of transport ready for unloading. The official <a className={link} href="https://www.gov.uk/guidance/customs-valuation/incoterms" target="_blank" rel="noopener noreferrer">UK customs summary of Incoterms</a> describes DDP as requiring the seller to clear the products for export and import and carry out the customs formalities.</p>
<p className={paragraph}>That wider obligation does not mean DDP is always feasible. ICC warns that a foreign seller may face physical or legal difficulty completing import clearance in the buyer’s country and suggests considering DAP or DPU where appropriate. Before accepting DDP, confirm who will be importer of record, whose registration will appear on the declaration, whether the seller can obtain required permits, and how import VAT or similar taxes will be treated. A carrier offering a “DDP service” does not automatically resolve the contractual and regulatory roles.</p>

<h2 id="separate-risk-cost-and-cash-flow" className={heading}>Separate risk, cost and cash flow</h2>
<p className={paragraph}>Risk transfer and cost allocation are related but should not be treated as the same question. Both DAP and DDP place transport risk on the seller until delivery at the named place, yet taxes, customs formalities and some operational charges can follow different paths. The bid tab should separate equipment price, export packing, origin handling, main carriage, destination handling, import brokerage, duties, import taxes, permits, inland delivery and unloading.</p>
<p className={paragraph}>Ask whether duties and taxes are fixed, estimated or excluded. Customs value and tax calculations can include transport, insurance, assists, royalties or other additions depending on local law. Exchange rates and tariff classification can also change the amount. A supplier should not present an uncertain pass-through charge as a guaranteed landed price without explaining the assumptions and adjustment mechanism.</p>

<h2 id="confirm-the-importer-and-customs-data" className={heading}>Confirm the importer and customs data</h2>
<p className={paragraph}>The contract should identify the legal importer, customs representative and party responsible for declaration accuracy. Confirm the commodity classification, country of manufacturing origin, customs value method, product description, permits and any preferential-origin evidence before dispatch. Country of origin is a product attribute; it is not the place from which the trader ships the goods or the market where Oillinko distributes an enquiry.</p>
<p className={paragraph}>Equipment descriptions must be specific enough for both technical review and customs work. “Valve spare parts” or “oilfield equipment” may be inadequate. Provide part numbers, materials, functions, quantities, unit values, net and gross weights, and packing details. If an item contains batteries, pressure vessels, chemicals or controlled technology, check the applicable transport and import rules rather than inferring treatment from the Incoterm.</p>

<h2 id="define-documents-and-timing" className={heading}>Define documents and timing</h2>
<p className={paragraph}>List the required commercial invoice, packing list, transport document, certificate of origin, insurance evidence where separately required, permits and project-specific certificates. State who prepares each document, who approves drafts and the deadline before dispatch. A DDP seller still needs accurate buyer or consignee information, while a DAP buyer needs enough advance data to arrange clearance before the shipment accumulates storage charges.</p>
<p className={paragraph}>Link document review to the shipping plan. Packing lists should identify package numbers, dimensions, weights, lifting points and the equipment contained in each package. The <Link className={link} href={postUrl(getPost("export-packing-oil-gas-equipment-rfq")!)}>export packing RFQ checklist</Link> explains how preservation, handling and package identity should be defined before shipment rather than left to the freight booking.</p>

<h2 id="clarify-unloading-and-site-access" className={heading}>Clarify unloading and site access</h2>
<p className={paragraph}>DAP and DDP delivery is generally ready for unloading, not unloaded by the seller. Define who provides the crane, forklift, rigging crew, permits, induction and unloading area. Also state the maximum vehicle dimensions and weights, road restrictions, gate hours, notice period and site contact. If the seller must unload, consider whether DPU or a carefully drafted additional obligation better reflects the intended scope.</p>
<p className={paragraph}>Avoid casual variants such as “DDP unloaded” without writing the operational responsibilities and risk clearly. ICC cautions against uncontrolled variations because changes can create ambiguity elsewhere in the rule. If the parties add a service, state whether it changes only cost, physical work or also the delivery and risk point.</p>

<h2 id="compare-dap-and-ddp-quotes-on-one-basis" className={heading}>Compare DAP and DDP quotes on one basis</h2>
<p className={paragraph}>Normalize bids to the same named place, shipment configuration, weight, route assumption and delivery window. Record the importer, included duties and taxes, unloading boundary, free-time assumptions, exclusions and validity. One DDP price may include firm duty and local representation while another contains an estimate subject to reimbursement. Those offers are not commercially equivalent until the differences are quantified.</p>
<p className={paragraph}>For upstream comparison, the <Link className={link} href={postUrl(getPost("exw-vs-fca-oil-gas-equipment-buyers")!)}>EXW versus FCA guide</Link> explains the origin-side export boundary. For multi-supplier projects, read the <Link className={link} href={postUrl(getPost("consolidated-shipments-and-multi-vendor-orders")!)}>consolidated shipment guide</Link> before assigning one delivered term across items with different readiness dates.</p>

<h2 id="build-the-delivery-rfq" className={heading}>Build the delivery RFQ</h2>
<p className={paragraph}>A complete delivery request includes the equipment list, manufacturing origin, pickup location, Incoterms rule and version, exact named place, importer details, customs assumptions, required documents, packing standard, package data, schedule, unloading boundary and excluded charges. Ask bidders to identify deviations and distinguish fixed prices from allowances. Customs and tax advisers should approve the import structure before commercial award.</p>
<p className={paragraph}>Send Oillinko the BOQ, delivery location, desired trade term and known import constraints through the <Link className={link} href="/oil-and-gas/services/freight-expediting-and-project-logistics">freight, expediting and project logistics enquiry page</Link>. Oillinko coordinates the sourcing and quotation process, while the buyer retains approval of importer status, customs treatment and destination compliance. A precise DAP or DDP line then becomes a usable commercial boundary instead of a vague promise of delivery.</p>

<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>}
