import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("elastomer-hardness-reports-shore-a-irhd-acceptance")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>An elastomer hardness number is incomplete without the scale, test method and specimen information. A buyer reviewing a seal, gasket or rubber component should first ask whether the submitted measurement matches the purchase specification. A result that appears numerically close can still be the wrong evidence if it was obtained using another method, a different specimen or an untraceable sample. Acceptance requires the agreed limits and a documented connection to the supplied material.</p>
    <p className={paragraph}>The <a className={link} href="https://store.astm.org/d2240-15r21.html" target="_blank" rel="noopener noreferrer">ASTM D2240 durometer hardness scope</a> identifies multiple durometer types and explains that results from different instruments do not have a simple universal relationship. The <a className={link} href="https://store.astm.org/d1415-18r26.html" target="_blank" rel="noopener noreferrer">ASTM D1415 international hardness description</a> concerns IRHD measurement. These are test-method references, not product performance approvals. This guide focuses on the procurement record and the questions a reviewer can resolve before treating a submitted hardness value as acceptable.</p>
    <h2 id="specify-the-method-and-scale-before-requesting-a-certificate" className={heading}>Specify the method and scale before requesting a certificate</h2>
    <p className={paragraph}>The enquiry should identify the required standard and edition, scale, acceptance range and sampling basis approved for the component. Do not send only a nominal hardness followed by a plus or minus tolerance if the measurement method remains undecided. Ask the responsible engineer or material specialist to resolve that gap. Where the design specification already names a method, carry that requirement into the RFQ and purchase documents consistently, including any approved project-specific reporting requirements.</p>
    <p className={paragraph}>For example, an RFQ for an elastomer sealing component may specify a Shore A requirement while a bidder provides an IRHD datasheet value. Record this as a method difference for review rather than rewriting the offered value as Shore A. Ask whether the bidder can provide the specified test or a technically justified alternative for approval. The <a className={link} href="https://www.iso.org/standard/74966.html" target="_blank" rel="noopener noreferrer">ISO guidance on rubber hardness methods</a> is intended to assist method selection; it does not mean that an unidentified measurement automatically meets every hardness specification.</p>
    <h2 id="treat-shore-a-and-irhd-comparability-as-conditional" className={heading}>Treat Shore A and IRHD comparability as conditional</h2>
    <p className={paragraph}>ASTM D1415 describes circumstances in which IRHD readings are comparable with Type A durometer readings on standard specimens, and also identifies limitations involving material behavior, dwell time and curved or irregular shapes. Comparability in a stated test context is different from permission to substitute one acceptance method for another. Ask the reviewer to address the actual compound and specimen, and retain the original scale in the record. Avoid using an internet conversion table to create a certificate value that was never measured.</p>
    <p className={paragraph}>A useful comparison records the method specified, the method offered and the reason for any proposed departure. If a supplier submits two results obtained by different methods, keep them as two measurements rather than averaging them. Explain which result is proposed for acceptance and why. That approach preserves evidence and makes the reviewer’s decision visible. A purchasing comparison should not imply that identical numbers establish identical rubber compounds, sealing performance or behavior under the intended service conditions.</p>
    <h2 id="identify-what-was-actually-tested" className={heading}>Identify what was actually tested</h2>
    <p className={paragraph}>Ask whether the result comes from the finished component, a prepared test specimen or another sample representing the production batch. Require a sample identifier and the relevant shape and dimensions to be recorded. A result from a flat laboratory specimen should not silently become a direct measurement of a small curved seal. The testing organization should explain whether the sample is appropriate for the specified method and whether any departure or limitation affects interpretation of the reported value.</p>
    <p className={paragraph}>Separate the part identity from the specimen identity. Record the drawing or part reference, compound designation, batch or lot identifier and the relationship between the tested sample and delivered items. If the report refers only to a generic compound name, request the missing batch connection before using it for lot acceptance. The <Link className={link} href={postUrl(getPost("gaskets-and-sealing-products-explained")!)}>sealing products overview</Link> provides context for product selection, but a product description and a hardness report answer different questions and should remain separately identifiable.</p>
    <h2 id="keep-measurement-conditions-and-results-reviewable" className={heading}>Keep measurement conditions and results reviewable</h2>
    <p className={paragraph}>Request the report to state the measurement conditions and timing information required by the selected method, together with instrument identification and any declared deviations. Avoid filling gaps with assumptions about laboratory practice. If the purchase requirement asks for individual readings, a single rounded average may be insufficient to assess the specified acceptance basis. Ask for the actual reporting format during the enquiry, including how multiple measurements and samples will be identified and summarized.</p>
    <p className={paragraph}>A reviewer should be able to trace the reported result to the method, specimen and test date without reconstructing the process from several unrelated documents. Where measurement uncertainty or a conformity statement is relevant to the agreed specification, establish the reporting and decision requirements before testing. Do not invent a universal acceptance allowance. A value close to a limit should be assessed using the project’s agreed basis and the laboratory’s reported information, with any unresolved question referred to the authorized technical reviewer.</p>
    <h2 id="use-hardness-evidence-within-a-broader-material-review" className={heading}>Use hardness evidence within a broader material review</h2>
    <p className={paragraph}>Hardness does not establish every property needed for an elastomer in service. The compound identity, compatibility assessment, temperature duty and other specified properties remain separate requirements. Do not accept a proposed replacement compound solely because its hardness is similar to the original. Ask the bidder to identify the proposed material and provide the evidence requested by the design specification. Hardness can be a useful part of a material record without becoming a general guarantee of suitability or service life.</p>
    <p className={paragraph}>If accredited testing is required, check the relevant laboratory scope through the <Link className={link} href={postUrl(getPost("iso-17025-laboratory-accreditation-scope-test-report")!)}>ISO/IEC 17025 accreditation review guide</Link>. A general laboratory accreditation statement does not by itself identify the method or specimen covered by a particular report. Likewise, use the <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>inspection document guide</Link> to clarify the document requested rather than assuming that a document label replaces test details. Match each evidence requirement to its purpose and avoid asking a hardness result to prove unrelated compliance.</p>
    <h2 id="resolve-the-report-as-an-acceptance-decision" className={heading}>Resolve the report as an acceptance decision</h2>
    <p className={paragraph}>Before accepting a batch, compare the specified method and limits with the submitted method, specimen information, results and item traceability. Record missing information and approved deviations explicitly. If the report is only a typical datasheet result, preserve that status and request the required batch evidence. A technical acceptance record can then identify what was reviewed, which supplied items it covers and which limitations remain. This is more reliable than retaining a certificate filename without a documented review outcome.</p>
    <p className={paragraph}>Oillinko can coordinate a manually reviewed enquiry through the <Link className={link} href="/oil-and-gas/equipment/gaskets-seals">gaskets and sealing equipment page</Link> using the component drawing, compound requirement, hardness specification and requested test records. Include existing reports when seeking clarification, while keeping their original scales and sample references intact. The final requirement should let a bidder quote the correct evidence and let the buyer assess it consistently. That creates a clear link from the specified material to the tested sample and the delivered batch.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
