import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post=getPost("electric-motor-rewinding-rfq-tests-data-acceptance-records")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base",heading="mt-12 text-xl font-bold",link="text-accent underline underline-offset-4";
const faqs=[
  {q:"Should a buyer authorize rewinding before the motor is inspected?",a:"Usually the quotation should separate initial inspection and diagnosis from conditional repair. Authorization follows an as-found report that identifies the failure, winding condition, mechanical findings and proposed work."},
  {q:"Does a successful insulation-resistance test prove the rewind is acceptable?",a:"No. It is one measurement within a broader test and inspection plan. The required checks depend on the motor type, voltage, condition, repair scope, applicable standard and project specification."},
  {q:"Can any repair shop rewind a hazardous-area motor?",a:"Do not assume so. Hazardous-area machines have additional equipment-protection, documentation and competency requirements. IEC 60034-23 explicitly notes that it does not supersede IEC 60079-19 or other applicable hazardous-area requirements."}
];

export default function Page(){return <><BlogPostHeader post={post}/><Prose>
<p className={paragraph}>An electric motor rewind quotation should describe more than replacement of copper wire and a final run test. The buyer needs a controlled path from the motor’s original identity and failure condition to an approved repair scope, recorded winding data, mechanical work, final testing and handover evidence. Without that path, quotations can appear comparable while including different inspections, materials, machining, balancing and acceptance tests.</p>
<p className={paragraph}>This guide focuses on the information required to purchase and evaluate a motor repair. It does not prescribe hazardous electrical work or field test voltages. Testing and repair must be performed by competent personnel under the applicable manufacturer instructions, standards, site procedures and safety controls. The responsible engineer should approve all test methods, limits and design changes for the specific machine.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Electric motor rewinding RFQ workflow from motor identity and as-found inspection through repair approval, final testing and handover records."/><figcaption className="mt-3 text-sm text-muted">A reliable rewind scope preserves the original design record and connects every authorized change to final acceptance evidence.</figcaption></figure>

<h2 id="identify-the-exact-motor-and-duty" className={heading}>Identify the exact motor and duty</h2>
<p className={paragraph}>Start with clear nameplate photographs and a typed data schedule. Record manufacturer, model, serial number, rated power, voltage, current, frequency, speed, number of phases and poles, duty, insulation and temperature-rise information, enclosure, cooling method, mounting arrangement, bearings, frame size, protection marking and efficiency designation where applicable. Include the driven-equipment tag and coupling arrangement so the repairer understands the mechanical boundary.</p>
<p className={paragraph}>Describe the supply and operating context: direct-on-line or converter-fed, starting method, load profile, ambient conditions, number of starts, recent protection trips and known process events. <a className={link} href="https://webstore.iec.ch/en/publication/66456" target="_blank" rel="noopener noreferrer">IEC TS 60034-25</a> addresses the interaction of AC machines with converter supplies, including application considerations such as shaft currents. A repairer cannot evaluate a recurring failure properly if the converter, cable and grounding context is omitted.</p>

<h2 id="separate-inspection-from-repair-authorization" className={heading}>Separate inspection from repair authorization</h2>
<p className={paragraph}>Use a staged commercial scope. The first stage covers receiving inspection, external condition, photographs, nameplate verification, shaft rotation, terminal condition and agreed non-destructive electrical checks. Disassembly should create an as-found record of winding damage, contamination, bearings, seals, fan, rotor, stator core, shaft, fits and mechanical clearances. The report should distinguish observed damage from the proposed root cause.</p>
<p className={paragraph}>The second stage begins after the buyer reviews the diagnosis and quotation for conditional work. Define approval thresholds for rewinding, core repair, shaft or journal work, bearing replacement, machining, fan replacement, enclosure repair and changes to insulation or lead arrangement. A blanket instruction to “repair as necessary” transfers uncontrolled scope and makes the final invoice difficult to audit.</p>

<h2 id="use-a-recognized-repair-basis" className={heading}>Use a recognized repair basis</h2>
<p className={paragraph}><a className={link} href="https://webstore.iec.ch/en/publication/33241" target="_blank" rel="noopener noreferrer">IEC 60034-23:2019</a> covers procedures intended to support satisfactory repair, overhaul and reclamation of rotating electrical machines. IEC explains that the work scope depends on machine type, rating, condition and the importance of plant reliability and safety. It includes failure assessment, repair extent, revised operating conditions where required, design review, proof of repaired-machine quality and customer handover.</p>
<p className={paragraph}><a className={link} href="https://easa.com/resources/resource-library/ansieasa-standard-ar100-2025-recommended-practice-for-the-repair-of-rotating-electrical-apparatus" target="_blank" rel="noopener noreferrer">ANSI/EASA AR100-2025</a> provides recommended practices for rewinding and rebuilding rotating electrical apparatus, including records, tests and analysis. EASA states that it does not replace customer or manufacturer specifications and that additional requirements apply to specialized machines. The RFQ should name the selected basis and edition, plus the owner’s technical specification.</p>

<h2 id="preserve-the-original-winding-data" className={heading}>Preserve the original winding data</h2>
<p className={paragraph}>Require the repairer to record winding data before destructive removal. The controlled record should include the connection, coil arrangement, turns, conductor details, parallel paths, lead identification, coil span, slot and phase relationships, measured resistances and relevant dimensions. Photographs and diagrams should make the data understandable to another competent repairer, not merely list an internal shop code.</p>
<p className={paragraph}>Any proposed change to conductor, turns, connection, insulation system, slot fill, winding overhang or thermal design should be identified and approved before manufacture. “Equivalent insulation” is not enough; the offer should describe the proposed system and supporting compatibility. The goal is to maintain the intended electrical, thermal and mechanical performance rather than improve one apparent feature while creating another problem.</p>

<h2 id="protect-core-condition-and-efficiency" className={heading}>Protect core condition and efficiency</h2>
<p className={paragraph}>Removing a failed winding can damage the stator core if the process is uncontrolled. Ask for the method, temperature monitoring and before-and-after core assessment required by the governing repair specification. If results indicate damage, require a documented engineering disposition before rewinding. The buyer should also state whether efficiency retention or performance testing is required and how it will be demonstrated.</p>
<p className={paragraph}>Efficiency claims need an applicable test basis. <a className={link} href="https://webstore.iec.ch/en/publication/67756" target="_blank" rel="noopener noreferrer">IEC 60034-2-1:2024</a> establishes methods for determining losses and efficiency from tests for machines within its scope. A routine no-load run is not the same as a full efficiency determination. The quotation should distinguish included routine checks from optional load or performance testing.</p>

<h2 id="define-mechanical-repair-boundaries" className={heading}>Define mechanical repair boundaries</h2>
<p className={paragraph}>Electrical failure may coexist with bearing, shaft, fit, balance or cooling problems. Specify inspection of bearing seats, shaft journals, keyways, end shields, fan, air passages, rotor condition and relevant runout or dimensional checks. Require measurements and an approved repair method before metal spraying, sleeving, welding or other dimensional restoration. Record new bearing manufacturer references and internal clearances where the project requires them.</p>
<p className={paragraph}>If the motor drives a pump or compressor, clarify who owns coupling inspection and alignment responsibility. The motor shop’s final run cannot prove field alignment or the condition of the driven machine. The <Link className={link} href={postUrl(getPost("mechanical-seal-replacement-identification-rfq-guide")!)}>mechanical seal replacement guide</Link> follows the same boundary principle: identify retained interfaces before accepting a replacement or repair proposal.</p>

<h2 id="define-final-tests-and-acceptance-records" className={heading}>Define final tests and acceptance records</h2>
<p className={paragraph}>The test plan should list examinations before disassembly, during repair and after assembly, together with the applicable method, acceptance basis and witness status. Depending on the motor and approved scope, records may address winding resistance and balance, insulation condition, surge comparison where applicable, high-potential testing, no-load current, phase balance, vibration, bearing temperature, direction of rotation, speed and mechanical observations. Do not copy a generic test voltage or limit from another machine.</p>
<p className={paragraph}>Require calibrated-equipment identification where specified and connect each result to the motor serial number and test date. Reports should show actual values, not only “pass.” The <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>ITP hold and witness guide</Link> helps define when the owner or inspector reviews winding data, approves conditional work, witnesses final testing and authorizes release.</p>

<h2 id="treat-hazardous-area-machines-separately" className={heading}>Treat hazardous-area machines separately</h2>
<p className={paragraph}>A hazardous-area motor requires review of its protection concept, certification or listing, marking, original construction and applicable repair rules. IEC 60034-23 states that it does not supersede IEC 60079-19 or other requirements for machines used in explosive atmospheres. The buyer should verify that the repair organization has the required competence and authorization for the particular protection concept and jurisdiction.</p>
<p className={paragraph}>Do not remove or recreate certification markings casually. Require records of flamepaths, fasteners, terminals, seals, cable entries, cooling and any other protection-critical feature applicable to the design. Proposed deviations must be resolved with the responsible certification and engineering parties before repair continues.</p>

<h2 id="request-a-complete-handover-dossier" className={heading}>Request a complete handover dossier</h2>
<p className={paragraph}>The final package should include the as-received record, inspection findings, approved work scope, winding data, material and component list, dimensional and electrical test results, balance or vibration records where required, photographs, deviations, nonconformance dispositions, final nameplate information, preservation and storage instructions, and the repair warranty terms. Keep replaced parts when requested for failure review.</p>
<p className={paragraph}>Send Oillinko the nameplate, photographs, failure history, motor datasheet, driven-equipment information and required test plan through the <Link className={link} href="/oil-and-gas/services/inspection-engineering">inspection and engineering service enquiry page</Link>. Oillinko coordinates the request with suitable service sources, while the asset owner and responsible electrical engineer approve the repair method and acceptance criteria. A staged RFQ turns a vague rewind request into a traceable technical and commercial scope.</p>

<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>}
