import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("equipment-rfq-revision-control-bid-clarifications")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A revised drawing can make yesterday&apos;s lowest quotation irrelevant without changing its headline price. A supplier may have priced the earlier material, dimension or inspection scope while another has allowed for the new requirement. The buyer needs a visible connection between each offer and the documents on which it was prepared. Revision control is therefore part of bid comparison, not simply an administrative filing exercise performed after award.</p>
    <p className={paragraph}><a className={link} href="https://www.iso.org/standard/70400.html" target="_blank" rel="noopener noreferrer">ISO 10007:2017 configuration management guidance</a> provides a broader framework for controlling product and service information through their life cycle. Its <a className={link} href="https://committee.iso.org/sites/tc176sc2/home/projects/published/iso-10007-2017.html" target="_blank" rel="noopener noreferrer">committee overview</a> identifies planning, configuration identification, change control, status accounting and audit. An equipment enquiry can apply those principles proportionately: identify the issued basis, authorize changes, record their status and check that the accepted offer uses the intended information. This is a practical procurement application, not a claim that every RFQ must use a particular certification scheme.</p>
    <h2 id="issue-an-attachment-register-with-the-enquiry" className={heading}>Issue an attachment register with the enquiry</h2>
    <p className={paragraph}>Give the enquiry a reference and retain stable line identifiers when the list changes. Create a register for drawings, specifications, data sheets and schedules, showing the document identifier, revision, issue date and relevant scope. Distinguish approved requirements from reference information or documents awaiting review. A filename containing the word final does not explain whether the attachment is approved, current or applicable to every line. Ask bidders to identify the document set used in their quotation.</p>
    <p className={paragraph}>Avoid relying on the order of email attachments or a supplier&apos;s memory of a previous conversation. If one drawing covers several items, map it to those line identifiers. If a specification applies only to a subset, say so. Keep quantities and units within the controlled item schedule, as described in the <Link className={link} href={postUrl(getPost("how-to-write-a-bill-of-quantities")!)}>bill of quantities guide</Link>. The register helps the buyer discover a missing drawing before comparing prices, instead of treating an incomplete quotation as a cheaper equivalent.</p>
    <h2 id="describe-a-change-and-its-affected-requirements" className={heading}>Describe a change and its affected requirements</h2>
    <p className={paragraph}>When the owner approves a correction, issue a clear change notice with its reference, date, affected lines and superseded document revisions. Describe the requirement that changed and provide the replacement document. A change from one material grade to another, for example, may affect sourcing, testing and delivery rather than only the item description. Ask each affected bidder to state its technical and commercial impact. Do not assume that the existing price or promised lead time survives the correction.</p>
    <p className={paragraph}>Keep a question, a proposed alternative and an approved change as different records. A supplier suggestion should not become the project requirement merely because it appears in the newest email. Identify the person or role authorized to approve technical changes and record the decision. <a className={link} href="https://www.nasa.gov/reference/6-5-configuration-management/" target="_blank" rel="noopener noreferrer">NASA configuration management guidance</a> explains the value of a known baseline, approved changes and tracked configuration information. The same principle supports an orderly supplier enquiry without importing NASA-specific review procedures into a commercial purchase.</p>
    <h2 id="give-relevant-bidders-a-consistent-clarification-basis" className={heading}>Give relevant bidders a consistent clarification basis</h2>
    <p className={paragraph}>Distribute approved changes to every bidder affected by the same requirement, subject to confidentiality and the applicable tender rules. A clarification that changes the common specification should not remain buried in one private supplier thread while others continue pricing a different basis. At the same time, protect each supplier&apos;s confidential design or commercial information. Prepare a neutral clarification of the requirement rather than forwarding an entire conversation containing another bidder&apos;s offer.</p>
    <p className={paragraph}>Request acknowledgement identifying the change notice or revised register. Receipt of an email is not the same as confirmation that the quotation incorporates its contents. Ask the bidder to state whether an updated offer will follow, which lines change, and whether any assumptions remain. If the correction materially affects bid preparation, agree a suitable revised response date. Keep those confirmations in the comparison record so the buyer can distinguish an updated offer from a supplier that has not yet assessed the change.</p>
    <h2 id="reconcile-the-revised-offer-against-the-current-register" className={heading}>Reconcile the revised offer against the current register</h2>
    <p className={paragraph}>Ask for a quotation reference and revision rather than accepting several conflicting documents under the same identifier. Review the offered quantities, dimensions, materials, accessories, testing and documents against the latest issued requirement. A revised total can conceal an omitted line or a reduced documentation scope. Record price and schedule changes alongside their reasons. If a supplier responds only to the corrected lines, identify exactly which earlier terms remain applicable and obtain a coherent basis for comparison.</p>
    <p className={paragraph}>Use a clarification log showing the requirement, supplier response, proposed deviation, decision and current status. Keep unresolved points visible even when the price table is complete. Conditional compliance should remain conditional until the stated inputs or approval are supplied. For mixed packages, connect the log to the <Link className={link} href={postUrl(getPost("partial-awards-equipment-rfq-package-line-item-offers")!)}>package and partial-award comparison guide</Link> so an accepted split supply arrangement does not accidentally combine incompatible document revisions.</p>
    <p className={paragraph}>Consider a hypothetical two-line enquiry in which one connection drawing changes but the other remains untouched. The buyer should preserve both line identities, issue the changed drawing with its new revision and ask the relevant bidder to confirm fit, price and delivery impact. Reissuing the whole list with new numbering can create an apparent additional item or conceal which offer was corrected. A concise change record and updated register usually provide a clearer comparison than several unexplained replacement spreadsheets.</p>
    <h2 id="carry-the-accepted-basis-into-the-next-stage" className={heading}>Carry the accepted basis into the next stage</h2>
    <p className={paragraph}>Before any authorized award, identify the accepted quotation revision, document register and resolved exceptions. Record the precedence of documents through the agreed commercial process where conflicts are possible; do not let the newest email date determine the answer by default. Separate engineering review from commercial authorization. A clarified drawing or accepted test plan does not itself issue a purchase order, release a payment or approve an unrelated change to the supplier&apos;s terms.</p>
    <p className={paragraph}>If a document changes after the accepted basis is established, handle it through the agreed change process and assess effects on work already completed. Keep approval status distinguishable from issue status: a submitted supplier drawing can still be awaiting review. The <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>inspection and test plan guide</Link> helps connect controlled requirements to later checks and witnessing. Retain the evidence showing what was accepted before the relevant manufacture or inspection stage.</p>
    <h2 id="keep-one-reviewable-record-without-losing-history" className={heading}>Keep one reviewable record without losing history</h2>
    <p className={paragraph}>Maintain a current register for working use and retain superseded issues in an identifiable history. The aim is to make the correct version easy to find while preserving the reason for a change. Agree access and distribution responsibilities so technical reviewers, procurement and suppliers can refer to the same accepted information. For a small spare-part enquiry, this may be a short register and clarification sheet. A larger fabricated package may require a more formal document-control process.</p>
    <p className={paragraph}>When requesting Oillinko&apos;s <Link className={link} href="/services">sourcing and RFQ coordination services</Link>, provide the current item list, attachment register, approved changes and known open points. State which documents may be shared and identify any confidential buyer information that must be removed. Oillinko enquiries are reviewed and routed manually. The useful outcome is a set of offers that can be traced to the same requirement, with declared deviations and revision history, rather than a collection of prices detached from their technical basis.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
