import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";
const post = getPost("heat-number-traceability-mill-certificates")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading="mt-12 text-xl font-bold";
const link="text-accent underline underline-offset-4";
const faqs=[
  {
    "q": "Does a matching heat number prove the complete order is compliant?",
    "a": "No. It helps connect the item and records, but the document and delivered product still need review against the purchase specification and acceptance requirements."
  },
  {
    "q": "Can one certificate support material divided between shipments?",
    "a": "It may, provided the required records demonstrate the connection and quantity allocation for each delivery. Confirm the applicable project and manufacturer requirements."
  },
  {
    "q": "Can PMI replace a missing traceability record?",
    "a": "PMI addresses a defined material identification question. It does not by itself reconstruct the original manufacturing and inspection history."
  }
];
export default function Page(){return <><BlogPostHeader post={post}/><Prose><p className={paragraph}>A delivery can arrive with a complete folder of material certificates and still leave the receiving team unable to identify which record belongs to which item. The problem is not necessarily a missing test result. It may be a missing connection between the marking on the product, the packing list and the certificate. Heat number traceability is useful only when that connection can be demonstrated for the material actually supplied, rather than for similar material somewhere in the supply chain.</p>
<p className={paragraph}>This guide focuses on that practical matching task for metallic products purchased for oil and gas projects. It complements the <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>guide to EN 10204 inspection document types</Link>, which explains the different documents and their validation. Here the question is narrower: can the buyer follow the delivered item back to the relevant manufacturing and inspection records, and can the records be checked against the purchase requirement without an unresolved assumption?</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Material traceability links product identification, packing and allocation records, and the relevant mill certificate, followed by review against the order."/><figcaption className="mt-3 text-sm text-muted">Preserve the connections between the delivered item and its records, then review acceptance separately.</figcaption></figure>
<h2 id="keep-heat-item-and-shipment-identifiers-separate" className={heading}>Keep heat, item and shipment identifiers separate</h2>
<p className={paragraph}>Record each identifier with its label and the organization that issued it. Do not assume a heat number, batch reference, individual serial number, certificate number and purchase order line are interchangeable. Their functions must be understood within the manufacturer’s identification system. A matching grade description is not a substitute for this connection, and a reference copied into a distributor’s spreadsheet should remain linked to the underlying manufacturer record rather than becoming an unexplained new identifier.</p>
<p className={paragraph}>Tenaris’s <a className={link} href="https://www.tenaris.com/umbraco/surface/downloads/pdf?url=/media/lhohiywe/12-30-21_ts_pipetracermanual.pdf" target="_blank" rel="noopener noreferrer">PipeTracer user manual</a>{" "}provides a concrete example: its pipe details distinguish a unique reference code, heat number, former mill code and mill test certificate. Those fields belong to that product tracking system; they are not a template imposed on every manufacturer. The example shows why an item identity and a heat reference should not be collapsed into one column when organizing the receiving record.</p>
<h2 id="define-the-matching-evidence-in-the-purchase-order" className={heading}>Define the matching evidence in the purchase order</h2>
<p className={paragraph}>Before ordering, ask the supplier how each delivered product or identified group will be linked to its certificate. Specify the document type and applicable project requirements separately from the method used to maintain identity. Agree what will appear on the packing list and whether an index linking order lines, item references and certificates is required. Request a sample document layout if the proposed format is unfamiliar, while making clear that the final evidence must cover the actual delivery.</p>
<p className={paragraph}>For an assembly, clarify which components require material traceability under the purchase specification. A certificate associated with the body does not automatically describe every internal component. Ask the supplier to identify the covered component and explain the link from that component to the assembly record. This is especially useful when comparing offers that both say certificates included but differ in the parts covered, the document type or the stage at which records will be available.</p>
<h2 id="reconcile-markings-packing-records-and-certificates" className={heading}>Reconcile markings, packing records and certificates</h2>
<p className={paragraph}>At receiving, use the agreed inspection plan to compare the physical identification with the packing records and certificate index. Capture the references accurately, including prefixes and leading zeros. If a character is unclear, record the uncertainty and request clarification instead of normalizing the number until it matches a document. Check that the description, dimensions, material designation and quantity allocation are consistent with the order and with the item being examined.</p>
<p className={paragraph}>The <a className={link} href="https://www.tenaris.com/media/bwrgp2ee/tam-high-m-v01-low.pdf" target="_blank" rel="noopener noreferrer">Tenaris TAM High M brochure</a>{" "}describes product-specific marking that includes the manufacturer and heat number, alongside its certification information. Treat this as an example of a documented marking scheme, not a universal marking rule for all pipes or fittings. For your delivery, obtain the applicable manufacturer and project requirements. Ask how identification will remain available if protective packaging, surface treatment or the supplied product form makes a marking difficult to inspect.</p>
<h2 id="preserve-the-link-through-cutting-and-split-deliveries" className={heading}>Preserve the link through cutting and split deliveries</h2>
<p className={paragraph}>An original certificate may describe stock that is later cut into shorter lengths or divided among several shipments. Ask for the records that connect the supplied pieces to that original material and explain the allocated quantity. The required identification transfer and record controls should be agreed with the responsible quality team. Do not treat a newly written label as proof by itself, or prescribe an arbitrary marking method that could conflict with the material or product requirements.</p>
<p className={paragraph}>For split shipments, keep the certificate index aligned with each packing list and identify any shared original record. Avoid confusing a certificate’s original quantity with the quantity accepted in a particular delivery. Where a processor or stockholder introduces another reference, request a documented cross-reference to the original identity. The <Link className={link} href={postUrl(getPost("consolidated-shipments-and-multi-vendor-orders")!)}>multi-vendor shipment guide</Link>{" "}provides the broader logistics context; the traceability task is to retain these links even when several suppliers’ goods are consolidated into one shipment.</p>
<h2 id="distinguish-a-matching-number-from-an-acceptable-certificate" className={heading}>Distinguish a matching number from an acceptable certificate</h2>
<p className={paragraph}>A matching identifier is an important connection, but it does not complete the technical review. The responsible reviewer still needs to assess the document against the ordered specification, required tests, delivery condition and any agreed supplementary requirements. Do not infer compliance solely from the presence of a familiar standard number or a certificate heading. Keep document completeness, authenticity questions and technical acceptance visible as separate review outcomes so an unresolved issue is not hidden by a single received checkbox.</p>
<p className={paragraph}>Where the manufacturer offers an official retrieval service, it can provide a useful route to the relevant record. For example, <a className={link} href="https://www.swagelok.com/en/resources/compliances-certifications/biopharm" target="_blank" rel="noopener noreferrer">Swagelok’s biopharm material test report page</a>{" "}uses the heat number marked on the fitting for its document search. That service is specific to the stated product scope. A retrieved document still needs to be matched to the delivered product and reviewed against the order; the existence of an online result does not resolve every receiving discrepancy.</p>
<h2 id="resolve-gaps-before-treating-the-delivery-as-accepted" className={heading}>Resolve gaps before treating the delivery as accepted</h2>
<p className={paragraph}>If a marking is missing, a certificate refers to a different identifier or the quantity cannot be reconciled, document the discrepancy and refer it through the agreed quality process. Request a corrected document or a supported explanation from the responsible supplier or manufacturer. Do not edit a certificate to make it match. Additional testing may help answer a defined material question, but it should not be described as reconstructing the original manufacturing history without a justified, approved basis.</p>
<p className={paragraph}>Keep the accepted records together: purchase requirement, item or component index, packing references, certificates and the disposition of any discrepancies. The <Link className={link} href={postUrl(getPost("positive-material-identification-xrf-oes-buyers-guide")!)}>PMI buyer guide</Link>{" "}explains a complementary inspection question, rather than replacing this documentary chain. When requesting sourcing or inspection coordination from Oillinko, include the required traceability scope through the <Link className={link} href="/oil-and-gas/services/inspection-ndt-and-material-testing">inspection and material testing enquiry page</Link>. Oillinko receives the enquiry for coordination with potential providers; the applicable inspection scope and acceptance responsibilities must be confirmed for the project.</p>
<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>;}
