import Link from "next/link";
import SiteImage from "@/components/SiteImage";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("industrial-filter-coalescer-rfq-duty-elements-pressure-drop")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>“Supply a filter skid” is not enough to compare quotations. One bidder may price a simple basket strainer, another a replaceable cartridge filter and a third a liquid or aerosol coalescer. Each treats a different contaminant and creates a different pressure-drop, maintenance and waste-handling obligation. A useful RFQ describes the process duty and the result required at the outlet before it names a preferred element or housing.</p>
    <p className={paragraph}>A publicly available <a className={link} href="https://www.eaton.com/content/dam/eaton/products/filtration-solutions/filter-systems-and-strainers/filters-and-strainers/manual-pipeline-strainers/brochures/Eaton-Manual-Pipeline-Strainer-Technical-Support-Guide-US-LowRes.pdf" target="_blank" rel="noopener noreferrer">manual pipeline strainer technical guide</a> treats differential pressure, screen selection and maintenance as connected design questions. <a className={link} href="https://www.parker.com/content/dam/Parker-com/Literature/Literature-Files/pneumatic/Literature/FRL/0700P/0700P_Engineering_Data.pdf" target="_blank" rel="noopener noreferrer">Published coalescer engineering data</a> distinguishes dry and wet pressure-drop behavior. Those documents describe their own product families; they should guide the questions in an RFQ, not be copied into an unrelated supplier&apos;s performance guarantee.</p>
    <figure className="mt-8"><SiteImage src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Filtration RFQ diagram connecting process duty, contaminant target, element choice, pressure drop and maintenance evidence."/><figcaption className="mt-3 text-sm text-muted">The equipment type follows the duty and required outlet condition.</figcaption></figure>

    <h2 id="duty" className={heading}>Define the stream before selecting hardware</h2>
    <p className={paragraph}>Tell bidders whether the stream is gas or liquid, its composition, operating and design pressure, temperature, minimum and maximum flow, density or viscosity where relevant, and expected upset conditions. Give the source of the stream and upstream equipment if they affect contamination. If the service may contain corrosive constituents or solids that abrade internals, state the known limits and let the responsible engineer approve compatible materials. A generic “oil and gas service” label cannot establish the suitability of the housing, seals or element.</p>
    <p className={paragraph}>State the contaminant to remove: coarse debris, fine particles, entrained liquid droplets, free water or another phase. Record the inlet loading if it has been measured, the required outlet condition and how acceptance will be evaluated. A nominal micron figure alone cannot describe a coalescing duty or a complete separation efficiency. If the inlet contamination is unknown, request that suppliers state their assumed basis and the effect on element life, rather than presenting an unsupported guaranteed interval.</p>

    <h2 id="equipment-choice" className={heading}>Keep equipment families distinct</h2>
    <p className={paragraph}>A temporary or permanent strainer protects downstream equipment from larger particles, with screen aperture and open area influencing both capture and pressure drop. A cartridge filter generally relies on replaceable elements and a specified filtration performance. A coalescer is intended to bring small dispersed droplets together so they can be separated, but its performance depends on the phase, flow, loading and downstream drainage arrangement. An RFQ should describe the required function rather than assume these products are interchangeable because they share a vessel-like housing.</p>
    <p className={paragraph}>Ask whether the offer includes a complete vessel or housing, internals, elements, supports, connections, differential-pressure indication, vents, drains, lifting provisions and isolation or bypass valves. Clarify which instruments are local and which signals connect to the control system. Identify the element-change method, required maintenance access and handling of captured material. A low equipment price may simply exclude valves, spare elements or an instrument that another bidder includes.</p>

    <h2 id="pressure-drop" className={heading}>Compare pressure drop at several conditions</h2>
    <p className={paragraph}>Request calculated or tested clean-element differential pressure at normal and maximum flow, plus the allowable terminal differential pressure and its basis. Ask how wet operation, contaminant loading or element fouling changes the result. A single clean pressure-drop number at one flow does not show whether the package will preserve downstream pressure at peak demand. The <Link className={link} href={postUrl(getPost("reading-a-pump-curve-explained")!)}>pump curve guide</Link> explains why available system pressure matters to liquid equipment selection; the same pressure budget needs explicit consideration for filtration.</p>
    <p className={paragraph}>For parallel or duty-standby units, state the number of housings online in each operating case. Where the system cannot be stopped for maintenance, ask how an element is isolated and changed while maintaining the required flow and safety boundary. Do not invent a universally safe terminal differential pressure: the element manufacturer, housing rating and process design set that limit. The buyer should request those limits, the alarm philosophy and the action required at the terminal condition.</p>

    <h2 id="elements" className={heading}>Make replacement elements traceable</h2>
    <p className={paragraph}>An element is a recurring cost, not a disposable afterthought. Ask for part numbers, dimensions, seal materials, rated performance basis, initial quantity, recommended spares and expected replacement criteria under the stated duty. Request a drawing or schedule that identifies which element fits each housing. If the quoted element is proprietary, ask how replacements will be identified years later and what lead time is typical, while avoiding unsupported claims about guaranteed availability.</p>
    <p className={paragraph}>Compare the commercial basis of the initial package and of recurring elements separately. One bid may include start-up and first-year spares; another may include only the installed set. The expected service life is especially sensitive to actual contaminant loading. Treat a vendor&apos;s estimated change interval as conditional on its stated assumptions, and request a plan for checking differential pressure and outlet quality once the system is operating.</p>

    <h2 id="records" className={heading}>Specify records and RFQ response fields</h2>
    <p className={paragraph}>The bid should identify applicable design code and material requirements for pressure-containing parts, the offered process and mechanical data sheets, performance basis, general arrangement, nozzle list, inspection and test plan, operating manual, element schedule and document handover. The <Link className={link} href={postUrl(getPost("pressure-vessels-tanks-and-heat-exchangers-explained")!)}>pressure equipment overview</Link> helps frame the pressure-boundary question; the <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>inspection plan guide</Link> helps state what will be reviewed or witnessed. The exact code and acceptance criteria must come from the project specification.</p>
    <p className={paragraph}>For each offer, create columns for inlet and outlet duty, contaminant target, element type, clean and terminal pressure drop, element replacement basis, included accessories, spare quantity and documented deviations. Invite alternative designs only if bidders explain how they meet the same outlet and operating requirements. Send the approved process data sheet and questions through Oillinko&apos;s <Link className={link} href="/oil-and-gas/equipment/process-packages/filtration-and-coalescing">filtration and coalescing equipment page</Link> for manual routing. No public product category establishes stock, a guaranteed performance figure or project approval.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
