import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("industrial-strainer-rfq-screen-opening-area-pressure-loss")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>Two quotations for the same line size and mesh number may cover strainers with different openings, basket areas, pressure losses and maintenance requirements. A useful enquiry starts with what the strainer must protect and the particles it is expected to retain. It then describes the flowing medium and the installed assembly. The objective is a comparable equipment offer, with declared limitations, rather than a screen designation that each bidder interprets differently.</p>
    <p className={paragraph}>The <a className={link} href="https://www.spiraxsarco.com/learn-about-steam/pipeline-ancillaries/strainers?sc_lang=en-GB" target="_blank" rel="noopener noreferrer">strainer guidance published by Spirax Sarco</a> distinguishes screening area from free area and explains that mesh opening depends on wire diameter as well as mesh designation. That distinction is useful when preparing an RFQ. It does not establish the pressure rating, particle-removal efficiency or suitability of an unselected product. Those points must be supported by the offered configuration and reviewed against the project duty.</p>
    <h2 id="define-retention-using-more-than-a-mesh-number" className={heading}>Define retention using more than a mesh number</h2>
    <p className={paragraph}>State whether the duty is protection against commissioning debris, recurring process solids or another defined contamination source. Describe particle size, shape, concentration and any available sample analysis. Ask the bidder to identify the screen construction, nominal opening, wire diameter or perforation dimensions, and material. A mesh number alone is not a complete aperture specification. Likewise, a micron value without an explanation of whether it refers to an opening or a tested removal rating leaves room for incompatible assumptions.</p>
    <p className={paragraph}>Consider an enquiry in which a buyer needs to protect a downstream nozzle from debris but sends only a line diameter. One bidder may offer a coarse perforated basket; another may add a finer mesh lining. The comparison should show the proposed retained-particle basis and its hydraulic effect separately. Long or irregular particles may behave differently from ideal spheres. Require an assessment of the actual contamination and do not describe a geometric screen as an absolute particle-removal guarantee.</p>
    <h2 id="compare-flow-area-and-pressure-loss-at-the-same-duty" className={heading}>Compare flow area and pressure loss at the same duty</h2>
    <p className={paragraph}>Screening area describes the exposed screen surface, while free area concerns the open passages through it. If an offer quotes an area ratio, ask for its numerator and denominator: open screen area, gross basket area and pipe flow area are different quantities. Request the proposed basket drawing or data sheet so the comparison can be checked. The <a className={link} href="https://www.eaton.com/us/en-us/catalog/filters-strainers/baskets.html" target="_blank" rel="noopener noreferrer">Eaton basket and screen tables</a> show opening, wire diameter and percentage open area together, illustrating why one designation cannot represent every construction.</p>
    <p className={paragraph}>Provide minimum, normal and maximum flow together with fluid temperature, density and viscosity on a consistent basis. Ask for the clean pressure-loss calculation or curve for the actual body, size and screen offered. Identify the project allowance for pressure loss and the effect on the wider system. For a pump suction installation, the responsible engineer must assess the remaining suction margin; a strainer cannot be selected solely from a nominal pipe size. See the <Link className={link} href={postUrl(getPost("reading-a-pump-curve-explained")!)}>pump curve and NPSH guide</Link> for the wider hydraulic context.</p>
    <p className={paragraph}>Keep the allowable pressure loss in normal service separate from the differential pressure that the basket can structurally withstand. Contamination changes the available passages, so a clean curve is not a prediction of every loaded condition. Ask the supplier to declare the basket differential limit and the basis for any proposed indication or maintenance criterion. The owner should approve those criteria within the equipment and process requirements. This purchasing guide does not provide cleaning setpoints or operating instructions.</p>
    <p className={paragraph}>When a bidder offers a larger body to reduce pressure loss, compare the resulting pipe transitions, dimensions and support requirements as part of the alternative. A larger body is not necessarily a drop-in replacement, and its benefit depends on the offered screen and actual flow. Conversely, retaining the old body size while changing to a finer screen may alter the hydraulic duty. Ask for both the original requirement and the proposed configuration to remain identifiable in the comparison, so the engineer can assess the complete change rather than approve a mesh substitution in isolation.</p>
    <h2 id="choose-the-arrangement-around-access-and-continuity" className={heading}>Choose the arrangement around access and continuity</h2>
    <p className={paragraph}>Identify whether a Y-type, simplex basket, duplex basket or temporary construction strainer is required, or invite a documented alternative. Explain whether the process can be stopped for maintenance and what redundancy the system design requires. A duplex arrangement introduces additional components and interfaces; it should not be treated as two interchangeable baskets without reviewing its full configuration. Ask the bidder to state flow direction, installation orientation and any restrictions that affect the proposed location.</p>
    <p className={paragraph}>Supply a layout showing nearby equipment, supports and available lifting space. Request the basket withdrawal envelope, cover access, assembly weight and drain or vent connection details. A strainer that fits between the flanges may still be impossible to maintain in the available space. Make included instruments, valves, gaskets, bolts and spare screens explicit. Their omission changes both the installable scope and the continuing maintenance cost, even when the quoted body appears to match the drawing.</p>
    <h2 id="identify-materials-ratings-and-replacement-boundaries" className={heading}>Identify materials, ratings and replacement boundaries</h2>
    <p className={paragraph}>Specify the body, cover, screen, support and seal materials where the project has approved requirements. Give operating and design conditions, connection standard, flange class or thread form, and required face-to-face dimensions. Ask for the pressure-temperature basis of the entire assembly rather than assuming the screen material sets the body rating. Corrosion, erosion and chemical compatibility require review for the particular medium. A stainless basket inside another body material is not evidence that every wetted component has the same resistance.</p>
    <p className={paragraph}>For a replacement basket, provide the installed assembly reference and verified dimensions, including seating, sealing and retaining features. Ask whether the offer is an exact replacement or a proposed alternative, and identify the approval needed for a changed aperture or construction. Include the required quantity of spare screens and seals separately from the main unit. The <Link className={link} href={postUrl(getPost("pipeline-fittings-and-schedules")!)}>piping dimensions and schedules guide</Link> supports the connection review, but it does not replace a product-specific basket or assembly drawing.</p>
    <h2 id="require-evidence-that-identifies-the-delivered-assembly" className={heading}>Require evidence that identifies the delivered assembly</h2>
    <p className={paragraph}>Agree the documentation before comparing prices: assembly drawing, screen data, material evidence where required, inspection and test records, identification and preservation instructions. Distinguish a housing pressure test from a declared basket differential capability; they address different questions. Each report should identify the equipment or batch to which it applies and the agreed acceptance basis. A catalogue page or generic certificate is useful background but cannot establish that the delivered item was manufactured and checked to the accepted order.</p>
    <p className={paragraph}>Compare bids using one schedule for duty, retained-particle basis, opening and construction, area definition, clean pressure loss, differential limits, materials, connections, maintenance space, accessories and records. Keep exceptions and assumptions visible alongside price, manufacturing origin and lead time. Use the <Link className={link} href="/oil-and-gas/equipment/process-packages/filtration-and-coalescing">filtration and coalescing enquiry page</Link> to send the confirmed requirement to Oillinko for manual routing. An enquiry path does not imply stock or supplier qualification; approval depends on the documented offer and the responsible project review.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
