import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";
const post = getPost("inspection-test-plans-hold-vs-witness-points")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";
const faqs = [
  {
    "q": "Can manufacturing proceed if a witness does not attend?",
    "a": "Only under the notification and non-attendance conditions agreed for that witness point. A witness no-show is not automatic authorization to pass a hold point."
  },
  {
    "q": "Is approving an ITP the same as accepting the equipment?",
    "a": "No. Plan approval agrees how verification will be organized. Actual results, open items, required documents and shipment release remain subject to their separate requirements."
  },
  {
    "q": "Does every ITP use the same H and W definitions?",
    "a": "Do not assume that it does. Confirm the project legend, required approvals and notification rules in the agreed plan and contract."
  }
];
export default function Page() {return <><BlogPostHeader post={post}/><Prose>
  <p className={paragraph}>An inspection and test plan can look complete while leaving the most expensive coordination question unanswered: who must act before the next manufacturing stage can begin? A supplier may allow for a customer witness visit, while the purchase order expects a mandatory release. Both parties see an inspection line in a spreadsheet, but they have priced and scheduled different obligations. Understanding hold vs witness points helps a buyer resolve that gap before committing to delivery dates.</p>
  <p className={paragraph}>This guide explains how to turn inspection participation into an agreed purchasing scope. It covers the plan legend, notification rules, authority and evidence needed for equipment orders. It does not prescribe test procedures or decide which inspections a particular pressure component or machine requires. Those choices belong to the governing specification and responsible technical authority. Oillinko receives the enquiry for sourcing coordination; the proposed supplier, inspection provider and project team must confirm their respective responsibilities.</p>
  <figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Hold point requires agreed authorization; witness point follows agreed notice and attendance rules. Both require defined criteria and records."/><figcaption className="mt-3 text-sm text-muted">Confirm the participation legend and release conditions in the project ITP.</figcaption></figure>
  <h2 className={heading}>What belongs in an inspection and test plan?</h2>
  <p className={paragraph}>An ITP connects a manufacturing or verification activity with its applicable requirements, acceptance reference, records and participating parties. It should identify the order and equipment clearly enough to distinguish one package from another. A generic blank template is a useful starting point, but it cannot show whether the quoted item follows the approved drawing revision or which project requirements have been accepted. Ask for a project-specific plan and an explicit list of outstanding inputs.</p>
  <p className={paragraph}>The <a className={link} href="https://www.api.org/~/media/files/certification/icp/icp-certification-programs/si_suite_documents/sire/sire_study%20guide_20181002.pdf" target="_blank" rel="noopener noreferrer">API rotating equipment source inspection guide</a>{" "}describes, in its centrifugal pump section, a vendor ITP addressing manufacturing, inspection, assembly, testing and shipment. Its matrix connects activities with requirements, references, supporting documents and purchaser involvement. This is a useful equipment example, not a universal inspection schedule for every purchase. The broader <a className={link} href="https://www.iso.org/standard/70398.html" target="_blank" rel="noopener noreferrer">ISO 10005:2018 quality plan guidance</a>{" "}covers establishing and maintaining quality plans; ISO identifies it as guidance rather than a document specifying requirements.</p>
  <h2 className={heading}>Hold points and witness points: define the difference</h2>
  <p className={paragraph}>A hold point normally creates a mandatory stop at a defined boundary until the stipulated authorization is obtained. A witness point normally gives a designated party the opportunity to attend an activity after the agreed notice. Whether work may proceed without that party depends on the actual plan and contract. Do not treat an unanswered invitation as automatic release of a hold point, or assume a witness invitation cancels the underlying test and reporting requirements.</p>
  <p className={paragraph}>For a published example of the distinction, the <a className={link} href="https://www-pub.iaea.org/MTCD/Publications/PDF/TE-1910_web.pdf" target="_blank" rel="noopener noreferrer">IAEA TECDOC 1910 quality plan example, Table 7</a>{" "}separates hold authorization from witness attendance following agreed notification. That example concerns nuclear procurement and is cited for terminology, not as an oil and gas acceptance standard. Put the applicable meanings directly in your own ITP legend, including any review or surveillance codes. A letter such as H, W or R is not a complete instruction without its agreed definition.</p>
  <h2 className={heading}>Make notification a priced and workable obligation</h2>
  <p className={paragraph}>State who sends the readiness notice, who receives it and what makes it valid. Useful fields include the purchase order, equipment tag, ITP activity number, location, proposed date, applicable procedure revision and a contact for coordination. Define the required notice period in the contract, including how working days, time zones and revised appointments are handled. There is no single notice period that a buyer should copy into every international order without checking the assignment.</p>
  <p className={paragraph}>Ask suppliers to disclose inspection locations and any subcontractor stages that need attendance. A final assembly shop address does not identify where an earlier casting examination will occur. Compare travel, standby, cancellation and repeat-visit assumptions alongside the equipment price. If production timing changes, the agreed process should explain how a new notice is issued and acknowledged. These are planning questions, not permission to bypass a required inspection because a flight or project deadline is inconvenient.</p>
  <h2 className={heading}>Name the authority and keep different releases separate</h2>
  <p className={paragraph}>List the manufacturer, purchaser, end user and third-party inspector in separate participation columns where relevant. Identify who can approve a document, witness an activity, release a hold and decide a nonconformance disposition. Those powers are not interchangeable. An inspector may be authorized to record observations without authority to accept a technical deviation. The <Link className={link} href={postUrl(getPost("third-party-inspection-tpi-oil-and-gas-equipment")!)}>third-party inspection scope guide</Link>{" "}helps define the assignment before an independent inspection quotation is compared.</p>
  <p className={paragraph}>Keep approval of the plan separate from acceptance of test results and authorization to ship. For example, a purchaser can approve how a pump package will be inspected while the eventual factory test remains outstanding. Likewise, attendance at a successful test does not close missing documentation or unrelated open items. The <Link className={link} href={postUrl(getPost("pump-factory-acceptance-testing-and-commissioning-checklist")!)}>pump factory acceptance and commissioning checklist</Link>{" "}explains why factory evidence and site readiness answer different questions. Define each release boundary by name instead of using a single ambiguous approved stamp.</p>
  <h2 className={heading}>Connect the plan to records and changes</h2>
  <p className={paragraph}>Each completed activity needs evidence that can be traced back to the relevant item and plan revision. Agree the expected report, sign-off or certificate, its issuing party and how it will be submitted. A signature on the ITP may document participation while the underlying test report carries the measured results and acceptance assessment. Require both when the contract calls for both. The <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>material certificate guide</Link>{" "}addresses another record whose identity must remain connected to the supplied components.</p>
  <p className={paragraph}>Agree how a revised drawing, repair or nonconforming result affects the plan before an exception arises. Identify who reviews the proposed change, whether earlier evidence remains applicable and which activities need renewed attendance or approval. Keep superseded revisions identifiable so the workshop and purchaser do not follow different copies. If someone proposes waiving attendance, document the authorized decision and its limits; do not describe it as waiving the technical acceptance requirement unless that separate change is explicitly approved.</p>
  <h2 className={heading}>Compare the same inspection commitment in every offer</h2>
  <p className={paragraph}>During tender review, use a small clarification register linking each open ITP question to the supplier response and responsible reviewer. One offer may include a detailed manufacturing record book and customer attendance, while another includes only internal quality checks. Request itemized exceptions rather than treating both offers as compliant because each mentions inspection. Where the project has not yet assigned a point classification, mark it as an unresolved technical decision instead of silently inventing one to complete the price comparison.</p>
  <p className={paragraph}>For an enquiry through Oillinko, attach the equipment list, available specification, proposed ITP or inspection requirements, planned locations and delivery milestones. Highlight the decisions that still need the project team. The <Link className={link} href="/oil-and-gas/services/inspection-ndt-and-material-testing">inspection and material testing enquiry page</Link>{" "}provides a relevant route for defining the service scope. A useful result is a quotation showing who participates, what records are supplied, how changes are handled and which approvals remain necessary before the next agreed stage.</p>
  <Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>;}
