import Link from "next/link";
import SiteImage from "@/components/SiteImage";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("iso-15848-fugitive-emissions-valve-type-vs-production-tests")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A valve quotation that says only “low emissions” does not tell a buyer what has been qualified or what will be checked on the valves delivered. External leakage at the stem or shaft and body joints is a different question from through-seat leakage. The purchasing team needs a traceable relationship between the proposed valve configuration, the type-test evidence and any production acceptance test specified for the order. An attractive catalogue statement is not a substitute for those records.</p>
    <p className={paragraph}>The <a className={link} href="https://www.iso.org/standard/61441.html" target="_blank" rel="noopener noreferrer">ISO 15848-1:2015 listing</a> describes classification and qualification procedures for valve type testing. The <a className={link} href="https://www.iso.org/standard/61442.html" target="_blank" rel="noopener noreferrer">ISO 15848-2:2015 listing</a> describes production acceptance testing of external leakage for standard production valves when fugitive-emissions requirements are specified. These public summaries establish the distinction, but they do not reproduce the complete normative test requirements. State the applicable edition, amendment and project class using the purchased standard and approved specification; do not infer a class from a web summary.</p>
    <figure className="mt-8"><SiteImage src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Valve fugitive emissions RFQ diagram separating the qualified valve design, supplied valve configuration and production acceptance record."/><figcaption className="mt-3 text-sm text-muted">The qualification boundary and delivered-unit evidence should be reviewed separately.</figcaption></figure>

    <h2 id="leakage-boundary" className={heading}>Define the leakage question first</h2>
    <p className={paragraph}>Fugitive emissions concern unintended release to the surrounding atmosphere from external sealing locations. Ask the responsible engineer to identify the service fluid, operating range and project emission requirement before asking bidders for an ISO 15848 declaration. An isolation valve may also need a seat-leakage test, but that does not demonstrate the required external-seal performance. Conversely, an external-leakage qualification does not settle the permitted seat leakage or pressure-boundary test. The <Link className={link} href={postUrl(getPost("api-598-vs-iso-5208-valve-testing-buyers-guide")!)}>API 598 and ISO 5208 valve test guide</Link> addresses that separate purchase decision.</p>
    <p className={paragraph}>Name the valve type, nominal size, pressure class, body and trim materials, stem or shaft arrangement, packing system, bonnet or body joint, actuation and intended service. Record whether the requirement applies to every valve in the package or only selected tags. A single statement on a common data sheet can conceal different sealing designs and different duty ranges. The bid schedule should have a field for the offered test evidence against each tag or family rather than treating a general brochure as evidence for all variations.</p>

    <h2 id="type-qualification" className={heading}>Connect the type test to the offered configuration</h2>
    <p className={paragraph}>A type test qualifies a design within the scope allowed by its test standard and documented qualification. Ask for the certificate or report identity, test standard and edition, test laboratory or responsible organization, tested model and size, sealing construction, applicable class and the range the manufacturer says the result covers. The buyer should compare that scope with the actual offered valve. A different packing material, stem diameter, bonnet arrangement or actuator interface may need additional justification. Do not assume one tested catalogue size automatically qualifies every size and variant.</p>
    <p className={paragraph}>Request the full report or a controlled extract sufficient to establish the link, subject to the project document policy. A marketing badge alone can omit test conditions, cycle history, thermal conditions or limitations that matter in service. If the bidder relies on a family qualification, ask for the documented extension or equivalence basis under the named standard. Any open difference belongs in a deviation register for technical review. Procurement can gather and compare evidence; the responsible engineer approves applicability to the specified plant duty.</p>

    <h2 id="production-acceptance" className={heading}>Specify what must happen to delivered units</h2>
    <p className={paragraph}>Production acceptance is a separate question. If the purchase specification calls for ISO 15848-2 testing, ask which units are tested, the test edition, the acceptance basis, the test medium and the records supplied. Identify whether the project requires inspection witnessing or a hold point. The supplier should explain any sampling plan or exclusion rather than silently treating the type-test report as the entire handover package. Where the contract specifies another production route, state it explicitly; do not add an unapproved universal test to every valve.</p>
    <p className={paragraph}>Make serial-number traceability part of the document request. A production test report should identify the tested unit and its result, not merely the valve family. Link the test record to the tag list, purchase order line and final nameplate or serial reference. If a valve is repaired, reconfigured or repacked after testing, ask the supplier to state whether the previous acceptance evidence remains applicable and what retesting is planned. This prevents a technically sound initial report from being attached to a materially different delivered assembly.</p>

    <h2 id="comparison" className={heading}>Compare offers on the same evidence boundary</h2>
    <p className={paragraph}>Separate three commercial lines in the bid comparison: the valve assembly itself, any design qualification documents included, and the production tests and witnessing included for the supplied units. Ask each bidder to identify actual manufacturer, manufacturing country, lead time for testing and document submission, and any third-party involvement. A bid can be lower because it excludes specified tests or supplies an alternative packing system. Make that difference visible before ranking the offer, rather than assuming every mention of “ISO 15848” has identical scope.</p>
    <p className={paragraph}>The project specification also needs a document review sequence. Decide when the type-test evidence, inspection and test plan, production records and final data book are due. The <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>inspection hold and witness point guide</Link> explains the difference between review and physical attendance. Do not make witness attendance a substitute for an acceptance criterion. If documents arrive after shipment, a buyer may have little opportunity to resolve a disputed qualification or missing serial link.</p>

    <h2 id="rfq" className={heading}>Build a concise RFQ schedule</h2>
    <p className={paragraph}>For each valve tag, include fluid and operating envelope, valve pattern and materials, size and pressure class, actuation, specified ISO 15848 part and edition, required class or acceptance basis from engineering, type-test evidence required, production-test scope, witnessing requirement and final records. Invite bidders to mark each item compliant, clarified or deviating, with a reference to the supporting document. If the project calls for both internal seat tightness and external-emissions performance, give each its own row. The broader <Link className={link} href={postUrl(getPost("valves-and-actuation-explained")!)}>valves and actuation overview</Link> helps separate basic valve selection from this emissions evidence.</p>
    <p className={paragraph}>Send the tag list and approved specification through Oillinko&apos;s <Link className={link} href="/oil-and-gas/equipment/valves">valve and actuation enquiry page</Link> for manual review and routing. State which evidence is mandatory and which may be proposed as an alternative. This guide is a purchasing framework, not a declaration that a particular valve is certified, available or suitable for a hazardous service. The final test interpretation, emissions target and acceptance decision belong to the project engineer and applicable contract documents.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
