import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("iso-17025-laboratory-accreditation-scope-test-report")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A laboratory can hold accreditation while an activity offered in a particular quotation falls outside its accredited scope. The buyer therefore needs more than a logo, a certificate number or the phrase ISO 17025 laboratory. The useful question is whether the current accreditation covers the work, method and circumstances required for this purchase. That check belongs before a test is commissioned and again when its report becomes part of the acceptance evidence.</p>
    <p className={paragraph}><a className={link} href="https://www.iso.org/standard/66912.html" target="_blank" rel="noopener noreferrer">ISO/IEC 17025:2017</a> concerns the competence, impartiality and consistent operation of testing and calibration laboratories. Accreditation bodies assess laboratories against this standard for defined activities. It is different from treating a general management-system certificate as proof of competence for every test. This article provides an evidence-review workflow; it does not accredit a laboratory or replace the contract, applicable testing standard and responsible technical assessment.</p>
    <h2 id="start-with-the-required-activity-and-result" className={heading}>Start with the required activity and result</h2>
    <p className={paragraph}>Write down what the project needs to establish: for example, the chemistry of an identified material sample, a mechanical property under a specified method, or the calibration results of a particular instrument over an agreed range. Identify the relevant material, parameter, method and edition, sample preparation, reporting requirements and acceptance basis. A broad request for certified testing allows each bidder to propose a different activity. A precise requirement lets the accreditation check focus on the evidence that will actually be used.</p>
    <p className={paragraph}>Distinguish testing, calibration and inspection in the service schedule. They can appear in the same project dossier but do not necessarily use the same accreditation standard or approval route. If a supplier combines several services, ask which organization performs each one and under what scope. Keep material inspection documentation separate from laboratory accreditation: the <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>EN 10204 document guide</Link> explains why an inspection certificate type and the competence of a commissioned laboratory answer different questions.</p>
    <h2 id="verify-the-laboratory-against-the-issuing-body-record" className={heading}>Verify the laboratory against the issuing body record</h2>
    <p className={paragraph}>Ask for the laboratory legal name, accreditation number, issuing body and current scope or schedule. Use the accreditation body public record to verify the identity and status rather than relying solely on a PDF forwarded by a bidder. Check whether the address and branch performing the work correspond to the listed location. If the name on the quotation differs from the accredited legal entity, request the relationship and identify the entity that will sign the report.</p>
    <p className={paragraph}>The <a className={link} href="https://www.ukas.com/resources/resources/introduction-to-the-ukas-digital-accreditation-schedule/" target="_blank" rel="noopener noreferrer">UKAS explanation of accreditation schedules</a> describes them as the formal record of accredited activities and their limits and conditions, with public verification through its website. Other accreditation bodies publish their records in their own formats. Save the relevant record and review date in the purchasing file. If the status or schedule is unclear, resolve it with the issuing body or laboratory before describing the service as covered; do not infer current validity from an old certificate alone.</p>
    <h2 id="match-the-scope-line-by-line-to-the-purchase" className={heading}>Match the scope line by line to the purchase</h2>
    <p className={paragraph}>Compare the requested activity with the scope description, including the product or material, test or calibration parameter, method, ranges and applicable location. An accredited chemistry test does not automatically cover a mechanical test, and a capability at a permanent laboratory does not automatically establish coverage for work at the project site. Ask the laboratory to identify the exact scope entry supporting its offer. Record differences as clarification items instead of replacing the required method silently.</p>
    <p className={paragraph}>For calibration, examine the measurement range and stated capabilities alongside the accuracy or uncertainty needed for the intended use. Ask the laboratory to identify the current scope entry for the measurement parameter, range and proposed location. A headline minimum uncertainty is not automatically the uncertainty of the result on your delivered instrument. Request an explanation of how the proposed service will meet the specific requirement and what the report will state.</p>
    <p className={paragraph}>Where a scope is described as flexible, ask how the laboratory demonstrates that the particular method or activity is included within its permitted boundaries. Do not interpret flexibility as unrestricted competence to perform any new test. Similarly, if a quotation uses an equivalent method, obtain the exact method reference and its effect on the project acceptance basis. The buyer should distinguish the laboratory capability question from the engineering decision to accept a substitute method.</p>
    <h2 id="declare-work-outside-the-scope-and-external-providers" className={heading}>Declare work outside the scope and external providers</h2>
    <p className={paragraph}>Ask the bidder to separate activities it will perform under its accreditation from any activities offered outside that scope. If another laboratory will perform part of the work, identify it and review its evidence as well. Decide whether the project permits that arrangement before award. The issue is clarity, not an assumption that every non-accredited activity is technically invalid. Some projects require accredited results for specified tests; others use a different approved evidence route. The quotation must reflect the actual requirement.</p>
    <p className={paragraph}>For a mixed package, retain one schedule showing each activity, performing entity, method and proposed accreditation status. Include sample transport, preparation and any site attendance, with their responsibility boundaries. Ask how sample identity and condition will be recorded from collection to testing. Competence evidence cannot resolve a missing link between the tested sample and the purchased material. Define that traceability with the supplier and laboratory before relying on the result for acceptance.</p>
    <h2 id="review-the-report-and-its-acceptance-statement-separately" className={heading}>Review the report and its acceptance statement separately</h2>
    <p className={paragraph}>When the report arrives, match its laboratory identity and activity to the reviewed scope, and confirm that the item or sample, method and relevant conditions correspond to the order. Identify any limitations, external results or departures from the planned work. Keep numerical results distinguishable from a statement that the item passes a specification. If a conformity statement is required, agree the acceptance criterion and how uncertainty is considered before testing, rather than treating an unexplained pass label as a complete decision.</p>
    <p className={paragraph}>The <a className={link} href="https://ilac.org/about-ilac/faqs/" target="_blank" rel="noopener noreferrer">ILAC frequently asked questions</a> explain the role of accreditation bodies and the mutual recognition arrangement. Recognition supports confidence in covered conformity assessment activities; it does not automatically satisfy every local regulation or customer contract. Verify any additional project approval or reporting condition explicitly. For instrument work, use the <Link className={link} href={postUrl(getPost("pressure-gauge-calibration-certificate-buyers-guide")!)}>pressure gauge calibration certificate guide</Link> to examine the result and measurement information after the scope check.</p>
    <h2 id="keep-the-evidence-linked-to-the-enquiry-and-order" className={heading}>Keep the evidence linked to the enquiry and order</h2>
    <p className={paragraph}>A practical purchasing file can contain the accepted activity schedule, accreditation-body record with review date, scope entry, technical clarifications, sample identification and final report. For repeated orders, review changes in method, location and status rather than assuming an earlier approval covers every later assignment. An independent material test on one sample should remain associated with that sample and its stated relevance; it is not a blanket approval of a manufacturer or future deliveries.</p>
    <p className={paragraph}>Send the defined test, material identity, method and evidence requirements through Oillinko&apos;s <Link className={link} href="/oil-and-gas/services/inspection-ndt-and-material-testing">inspection and material testing enquiry page</Link> for manual review and routing. Compare bids on the covered activity and usable acceptance evidence alongside price and schedule. A directory entry or an advertised laboratory standard is a starting point for assessment. The purchasing decision should rest on the current scope, agreed work and report that can be connected to the actual equipment or material.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
