import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, CheckList, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("liquid-penetrant-vs-magnetic-particle-testing-rfq")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";
const faqs = [
  {q:"Can liquid penetrant testing replace magnetic particle testing?",a:"Only when the responsible technical authority approves the method for the material, examination objective and governing requirements. A lower quote is not evidence that two scopes are equivalent."},
  {q:"Does PT detect internal defects?",a:"Liquid penetrant testing reveals discontinuities open to the examined surface in suitable nonporous materials. It does not establish the condition of the full internal volume."},
  {q:"Does an NDT report replace a material certificate?",a:"No. The documents answer different questions. Link the inspection report to the component identity and required material records rather than substituting one for the other."},
];

export default function Page() {return <>
  <BlogPostHeader post={post}/><Prose>
  <p className={paragraph}>Comparing liquid penetrant vs magnetic particle testing starts with the inspection question, not the price per weld. A buyer may receive two quotations both labelled surface NDT, yet each can cover different materials, areas and deliverables. Before treating them as alternatives, establish what the project needs to find, where the examination applies and who approves the method. A clear request protects the comparison from a simple but costly mistake: buying a test name without buying an agreed scope.</p>
  <p className={paragraph}>This guide concerns procurement of PT and MT examinations for components such as welds, forgings and castings. It explains the main applicability differences and the information needed before requesting prices. It is not a procedure for performing either examination or deciding whether equipment may return to service. Those decisions depend on the governing requirements, approved procedures and competent personnel responsible for the particular item. Oillinko receives the enquiry and coordinates the sourcing request; the proposed inspection provider and project team define and confirm the technical assignment.</p>
  <figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="PT and MT comparison: suitable nonporous materials versus ferromagnetic materials, with coverage, criteria and reporting required for both."/><figcaption className="mt-3 text-sm text-muted">Method suitability is one decision. Coverage, acceptance and reporting must also be defined.</figcaption></figure>
  <h2 id="pt-vs-mt-applicability" className={heading}>PT vs MT: understand the applicability difference</h2>
  <p className={paragraph}>The <a className={link} href="https://www.asnt.org/what-is-nondestructive-testing/methods/liquid-penetrant-testing" target="_blank" rel="noopener noreferrer">ASNT overview of liquid penetrant testing</a>{" "}describes PT as a method for revealing discontinuities open to the surface of suitable nonporous materials. It does not detect enclosed subsurface discontinuities. The method is not restricted to ferromagnetic metals, but that broader applicability does not make every material, surface condition or chemical system suitable. For purchasing, ask the inspection provider to confirm applicability to the actual material and component condition specified in the enquiry.</p>
  <p className={paragraph}>The <a className={link} href="https://www.asnt.org/what-is-nondestructive-testing/methods/magnetic-particle-testing" target="_blank" rel="noopener noreferrer">ASNT overview of magnetic particle testing</a>{" "}identifies MT as a method for surface and near-surface discontinuities in ferromagnetic materials. Magnetic particles produce indications associated with leakage fields. A description such as metal component therefore does not establish MT suitability. State the material specification and grade, and obtain confirmation from the technical reviewer. Neither the word magnetic nor a successful surface examination establishes that the entire internal volume has been examined.</p>
  <h2 id="define-the-item-and-objective" className={heading}>Identify the item and the question the test must answer</h2>
  <p className={paragraph}>Attach an item list with drawing references, quantities, material descriptions and the relevant fabrication or service stage. Distinguish an examination of new supplied parts from an assessment of installed equipment. A request for ten valve bodies is different from a request for ten specified weld areas on those bodies. Include the component identifiers used elsewhere in the purchase order so the provider can quote and report against the same list rather than create a separate numbering system that later needs reconciliation.</p>
  <p className={paragraph}>Explain the objective in ordinary project language before shortening it to an acronym. For example, a buyer might need evidence for designated accessible weld surfaces before an agreed manufacturing release. That is a more useful starting point than a blanket request to check for defects everywhere. If the objective is actually alloy verification, the <Link className={link} href={postUrl(getPost("positive-material-identification-xrf-oes-buyers-guide")!)}>PMI method selection guide</Link>{" "}addresses a different question. Keep chemical composition checks and discontinuity examinations as separate, identifiable requirements when both are needed.</p>
  <h2 id="coverage-and-access" className={heading}>Make coverage and access visible in the quotation</h2>
  <p className={paragraph}>Specify the examination areas on a drawing or marked component schedule. State how quantities will be measured for pricing: pieces, weld lengths, defined areas or another agreed basis. If sampling is permitted, reference the approved sampling requirement and who selects the items. A percentage alone leaves room for disagreement about whether it describes weld count, length or surface area. Ask the provider to identify inaccessible areas and qualifications to the proposed coverage before comparing the total price.</p>
  <p className={paragraph}>ASNT notes that cleanliness and surface condition matter for penetrant testing. Describe coatings, contamination and surface access in the enquiry instead of assuming every part arrives ready for examination. Allocate responsibility for any approved preparation, handling and restoration. For site work, identify the available work window and the party responsible for safe access and equipment release. The inspector should not discover at arrival that the quoted scope depends on work assigned to nobody. Do not prescribe improvised preparation steps in the purchasing document.</p>
  <h2 id="criteria-and-responsibilities" className={heading}>Separate the examination method from acceptance</h2>
  <p className={paragraph}>An instruction naming PT or MT does not by itself state which indications the project accepts. Provide the governing specification, applicable edition and acceptance references, with a clear document priority where several requirements apply. Ask for the proposed procedure reference and any deviations for review before the work starts. If a quotation says testing to standard, request the exact document and scope. Resolving that ambiguity during tender review is easier than arguing about the meaning of a pass statement after the inspection.</p>
  <p className={paragraph}>Name the person or organization responsible for technical approval and the party authorized to disposition a nonconforming result. Require evidence of the personnel qualifications and authorization relevant to the specified method and assignment under the project requirements. A generic training certificate or an unrelated method credential should prompt a clarification. Keep witnessing separate from performing the examination: a customer representative attending the work does not automatically become the examiner or the authority approving a repair.</p>
  <h2 id="reports-and-reinspection" className={heading}>Order a traceable report and a clear reinspection boundary</h2>
  <p className={paragraph}>Agree the report contents before placing the order. A useful deliverable identifies the component, examined areas, procedure and acceptance references, examination date, responsible personnel, results and stated limitations. Request location sketches or photographs when they are needed to connect a reported indication to the actual item. The report should make it possible to distinguish an accepted examined area from an area excluded from the assignment. An unqualified certificate saying NDT satisfactory offers little help when the delivered equipment list contains multiple similar parts.</p>
  <p className={paragraph}>Keep inspection evidence connected to the material and manufacturing records without assuming those records are interchangeable. The <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>EN 10204 material certificate guide</Link>{" "}explains the documentation side. Where a result requires further action, identify who authorizes that action and how a subsequent examination will reference the earlier record. Request separate pricing assumptions for repeat visits or reinspection where appropriate. Do not let the original report disappear from the history simply because a later result is acceptable.</p>
  <h2 id="compare-the-complete-scope" className={heading}>Compare the complete scope before accepting the lowest price</h2>
  <p className={paragraph}>Build a comparison with separate entries for method, coverage, preparation responsibilities, access, reporting and review. A lower inspection rate can accompany a narrower scope or exclude mobilization and repeat attendance. Ask each bidder to state exclusions and assumptions explicitly. For factory work with other acceptance activities, use the <Link className={link} href={postUrl(getPost("third-party-inspection-tpi-oil-and-gas-equipment")!)}>third-party inspection coordination guide</Link>{" "}to organize the wider assignment. Avoid treating attendance, document review and the actual PT or MT examination as the same deliverable.</p>
  <p className={paragraph}>Send the item list, drawings, inspection objective and project requirements through the <Link className={link} href="/oil-and-gas/services/inspection-ndt-and-material-testing">inspection, NDT and material testing enquiry page</Link>. State the work location and required dates, and identify unresolved technical questions rather than choosing a method solely to complete the form. Oillinko can use that information to coordinate a defined request for suitable proposals. Final method selection, acceptance and any return-to-service decision remain with the responsible technical parties under the applicable project requirements.</p>
  <CheckList items={["Component list, material specification and drawing references","Inspection objective, stage and exact examination areas","Approved method, procedure and acceptance references","Coverage basis, exclusions and access limitations","Preparation, restoration and safe-access responsibilities","Relevant personnel qualification and authorization evidence","Traceable report, review responsibilities and reinspection scope"]}/>
  <Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/>
</>;}
