import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";
const post = getPost("mechanical-seal-replacement-identification-rfq-guide")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading="mt-12 text-xl font-bold";
const link="text-accent underline underline-offset-4";
const faqs=[
  {
    "q": "Is shaft diameter enough to order a replacement mechanical seal?",
    "a": "No. Confirm the identified assembly, interfaces, materials and duty with the manufacturer or responsible technical reviewer."
  },
  {
    "q": "Is a repair kit the same as a complete cartridge seal?",
    "a": "No. Specify the required supply boundary and ask for an itemized description tied to the assembly drawing and revision."
  },
  {
    "q": "Can an alternative seal be accepted solely on a cross-reference number?",
    "a": "A cross-reference can start an enquiry, but acceptance requires confirmation of the offered configuration, compatibility and any deviations."
  }
];
export default function Page(){return <><BlogPostHeader post={post}/><Prose><p className={paragraph}>A mechanical seal replacement enquiry often starts with a photograph, a shaft diameter and an urgent delivery date. Those details can help a supplier begin an assessment, but they do not define a complete replacement. Two offers describing the same nominal size may cover different assemblies, materials or interfaces. Before comparing prices, establish whether the enquiry concerns an identified spare, a repair kit for that spare, or an alternative design that still needs technical approval.</p>
<p className={paragraph}>This guide helps purchasing teams assemble a traceable RFQ for a pump mechanical seal. It is not an installation procedure or a seal selection calculation. The equipment owner and the proposed manufacturer must confirm suitability for the actual duty. Keep the original equipment identity, current configuration and requested supply scope together throughout the enquiry so that commercial discussions do not gradually replace an unresolved technical question with an assumed answer.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Mechanical seal RFQ checklist: establish assembly identity, confirm interfaces and duty, and define the offered supply scope."/><figcaption className="mt-3 text-sm text-muted">A replacement enquiry needs identity, compatibility evidence and a defined supply boundary.</figcaption></figure>
<h2 id="start-with-the-installed-seal-identity" className={heading}>Start with the installed seal identity</h2>
<p className={paragraph}>Collect the pump manufacturer, model, serial number and equipment tag, then record the seal manufacturer and every legible seal reference separately. A plant tag identifies an asset in your records; it is not necessarily a manufacturer part number. Include the seal drawing number and revision, previous purchase description and available bill of materials. Where the records disagree, show the discrepancy instead of selecting the most convenient description and presenting it as confirmed.</p>
<p className={paragraph}>Use photographs as supporting evidence: markings, the complete assembly and its documented connection arrangement can help explain what is being requested. Do not ask a purchasing team to dismantle equipment merely to complete an enquiry. Obtain additional information through the site’s approved maintenance arrangements. If a reference has become obsolete, ask the supplier to identify the successor in writing and state whether the change affects dimensions, materials, connections or the required supporting equipment.</p>
<h2 id="specify-the-assembly-boundary-before-requesting-a-price" className={heading}>Specify the assembly boundary before requesting a price</h2>
<p className={paragraph}>AESSEAL’s <a className={link} href="https://www.aesseal.com/en/product/cartridge-mechanical-seals/" target="_blank" rel="noopener noreferrer">cartridge mechanical seal overview</a>{" "}describes cartridge seals as factory-assembled units and distinguishes several seal families. That is useful context for purchasing: the word seal does not by itself define what is inside the package. Ask whether the offer is for a complete cartridge, individual components, a repair kit or an assessed repair service. Confirm the offered contents against the assembly drawing rather than expecting a product family name to settle the scope.</p>
<p className={paragraph}>List the quantity by assembly and identify any separately required spare components. Ask which sleeves, glands, secondary seals, fasteners and accessories are included where those items apply to the identified design. Keep tools and installation services separate unless expressly included. If the enquiry is for a repair kit, obtain confirmation that it belongs to the exact assembly revision; a lower-priced kit is not a like-for-like commercial comparison with a complete replacement cartridge.</p>
<h2 id="treat-dimensions-as-identification-evidence-not-complete-approval" className={heading}>Treat dimensions as identification evidence, not complete approval</h2>
<p className={paragraph}>Provide the approved dimensional drawing when available and identify the units used. Ask the technical reviewer which interfaces need confirmation, including the shaft or sleeve interface, available axial space, seal chamber, mounting arrangement and connections as applicable. A single measured diameter leaves many questions unanswered. Where only field measurements exist, label them as such and ask what tolerances or additional checks the manufacturer needs before it can confirm interchangeability.</p>
<p className={paragraph}>An example appears in AESSEAL’s <a className={link} href="https://static.aesseal.com/industry/LIT-UK-L-H-Pump.pdf" target="_blank" rel="noopener noreferrer">horizontal pumping system seal brochure</a>: its coding logic distinguishes seal type, size, pump reference, metallurgy, O-ring combination and face combination. These are product-specific codes, not a universal numbering system. The procurement lesson is to preserve the full reference and its supporting documentation. Do not shorten a code to the size portion or transfer a material code from one manufacturer’s catalogue into another without confirmation.</p>
<h2 id="record-the-duty-and-materials-without-guessing" className={heading}>Record the duty and materials without guessing</h2>
<p className={paragraph}>Attach the current approved datasheet and identify the process fluid, relevant constituents, operating conditions and any known changes since the previous seal was selected. Where the seal chamber conditions are available, supply them with their source. Do not substitute pump discharge pressure for an unconfirmed seal chamber value. Mark unknown information explicitly so the responsible engineer can resolve it rather than allowing different bidders to price different assumptions.</p>
<p className={paragraph}>Request the proposed face materials, secondary sealing materials and relevant metallic components in the supplier’s own traceable designation. If the quotation proposes a material change, ask for the basis of suitability for the stated duty and identify who must approve it. General material labels and photographs do not establish every compound or grade. For document retrieval, <a className={link} href="https://www.johncrane.com/en/products/product-documents" target="_blank" rel="noopener noreferrer">John Crane’s product documentation library</a>{" "}illustrates the value of locating the actual product documentation rather than relying on an unattributed cross-reference table.</p>
<h2 id="separate-exact-replacement-from-an-engineered-alternative" className={heading}>Separate exact replacement from an engineered alternative</h2>
<p className={paragraph}>Ask each bidder to classify its proposal as the specified replacement, a confirmed successor or an alternative requiring review. For an alternative, request a clear deviation schedule and a drawing that shows the proposed interfaces. Avoid accepting the word equivalent as the entire technical justification. The reviewer needs to know what changes, what remains compatible and whether any modifications or additional components are excluded from the quoted price.</p>
<p className={paragraph}>Include the existing support-system description when relevant. The <Link className={link} href={postUrl(getPost("api-682-mechanical-seal-piping-plans-explained")!)}>API 682 seal piping plan guide</Link>{" "}helps buyers distinguish those support arrangements; it does not approve a replacement seal. Ask the supplier to confirm the relationship between its offered assembly and the documented arrangement. Any proposed change to the seal or support system needs an equipment-specific technical decision, with installation and operating requirements taken from the applicable manufacturer documentation.</p>
<h2 id="compare-evidence-delivery-and-acceptance-together" className={heading}>Compare evidence, delivery and acceptance together</h2>
<p className={paragraph}>Build the commercial comparison around the agreed assembly and revision. Request the offered manufacturer reference, supply condition, quantity, manufacturing origin, lead time and delivery basis, together with the documents included in the price. Manufacturing origin means where the product is made, not the distributor’s address. If inspection, testing or material documentation is required, identify the requirement before order placement and ask the supplier to confirm what evidence it will actually provide.</p>
<p className={paragraph}>Send the identified equipment records and open questions through Oillinko’s <Link className={link} href="/oil-and-gas/equipment/pumps/seals-couplings-and-bearings">pump seals and rotating-equipment spares enquiry page</Link>. Oillinko receives the enquiry and coordinates it with potential providers; stock and technical suitability must be confirmed in the resulting offer. Retain the approved drawing, deviations and final scope with the order. These records give receiving personnel a defined basis for checking the delivery and help the next replacement enquiry start from verified information rather than another unidentified photograph.</p>
<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>;}
