import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post=getPost("nace-mr0175-iso-15156-sour-service-buyers-guide")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base",heading="mt-12 text-xl font-bold",link="text-accent underline underline-offset-4";
const faqs=[
  {q:"Does a material grade automatically comply with NACE MR0175 / ISO 15156?",a:"No. Suitability depends on the applicable standard part, defined service environment, product form, material condition, manufacturing and fabrication controls, and any required qualification evidence."},
  {q:"Is an EN 10204 3.1 certificate proof of sour-service suitability?",a:"It can provide material and test information required by the order, but the document type alone does not establish suitability for a particular H2S-containing environment."},
  {q:"Does ISO 15156 cover every refinery or downstream H2S application?",a:"No. ISO describes the current Part 1 scope as oil and gas production and natural-gas sweetening, and says it is not necessarily applicable to refining or downstream equipment. Confirm the correct project standard and scope."}
];

export default function Page(){return <><BlogPostHeader post={post}/><Prose>
<p className={paragraph}>“NACE compliant” is not a complete material description. For equipment exposed to wet hydrogen sulfide, the buyer needs to connect a defined service environment to the exact product, material condition, manufacturing route and acceptance evidence. A grade name on a quotation cannot make that connection by itself. Two components described with the same alloy designation may differ in product form, strength, heat treatment, cold work, weld condition or hardness, and those differences can change how the applicable sour-service requirements are assessed.</p>
<p className={paragraph}>This guide explains what to place in a request for quotation when NACE MR0175 / ISO 15156 is part of the project basis. It is a procurement framework, not a materials-selection calculation. The operator, materials engineer and responsible design parties must define the environment, select the material and approve any qualification route using the purchased edition, applicable amendments and project specifications.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Sour-service RFQ evidence chain connecting the service environment, material and product condition, fabrication controls, verification records and engineering approval."/><figcaption className="mt-3 text-sm text-muted">A sour-service claim becomes reviewable when the environment, supplied condition, fabrication controls and records form one evidence chain.</figcaption></figure>

<h2 id="name-the-standard-part-and-edition" className={heading}>Name the standard, part and edition</h2>
<p className={paragraph}>State the project’s controlled reference rather than writing only “NACE.” The current published series is ISO 15156:2020, issued in three parts and also published by AMPP as ANSI/NACE MR0175-2021/ISO 15156:2020. <a className={link} href="https://www.iso.org/standard/79658.html" target="_blank" rel="noopener noreferrer">ISO 15156-1:2020</a> gives the general principles for selecting and qualifying cracking-resistant metallic materials. Part 2 addresses carbon and low-alloy steels and cast irons, while Part 3 addresses corrosion-resistant alloys and other alloys.</p>
<p className={paragraph}>Edition control matters because the series is maintained and revised. ISO currently lists the 2020 edition as published while a replacement is under development. A draft is not automatically the contractual requirement. The purchase order should identify the agreed edition, any applicable technical circulars or project addenda, and the hierarchy between the standard, equipment specification and owner requirements. Ask suppliers to record exceptions explicitly instead of assuming that a newer internal practice overrides the order.</p>

<h2 id="confirm-that-the-scope-fits-the-application" className={heading}>Confirm that the scope fits the application</h2>
<p className={paragraph}>ISO describes Part 1 as applying to metallic materials for equipment used in oil and gas production and natural-gas sweetening plants where H2S-related failure can create safety, environmental or equipment risk. It also states that the document supplements rather than replaces the material requirements of design codes, standards and regulations. Its scope is not necessarily suitable for refining or downstream equipment. The RFQ should therefore identify the facility, process service and governing equipment code before citing ISO 15156.</p>
<p className={paragraph}>Do not treat the standard as a general corrosion guarantee. ISO 15156 addresses cracking mechanisms caused by H2S, including sulfide stress cracking, hydrogen-induced cracking and other listed mechanisms. It does not promise immunity under every operating condition or replace a corrosion allowance, erosion review, general-corrosion assessment, coating specification, chemical-injection plan or complete mechanical design. Separate each engineering question and name the evidence expected for it.</p>

<h2 id="define-the-service-environment" className={heading}>Define the service environment before requesting a material</h2>
<p className={paragraph}>Give the materials engineer and supplier a controlled service-data sheet. Depending on the applicable assessment, relevant inputs can include phase and water presence, H2S concentration and partial pressure or fugacity, total pressure, temperature range, pH, chloride concentration, elemental sulfur and other constituents. Identify normal, start-up, shutdown, upset and temporary conditions where the project requires them. State the source of the process data and distinguish confirmed values from design margins or unknowns.</p>
<p className={paragraph}>Avoid copying a single H2S threshold from a previous project. The ISO introduction explains that material susceptibility and alloy application limits can depend on several environmental variables, including composition, pH, temperature and H2S partial pressure. The responsible reviewer should determine which conditions govern for the specific material and damage mechanism. If data are missing, record a technical clarification or conservative project assumption for approval rather than allowing each bidder to choose an undisclosed basis.</p>

<h2 id="identify-every-wetted-component" className={heading}>Identify every pressure-containing and wetted component</h2>
<p className={paragraph}>Define the equipment tag, size, pressure class, temperature class, design code and service, then list the components within the sour-service boundary. A valve body, bonnet, stem, bolting, trim, spring, weld overlay and seal-retaining metal can have different material requirements. A statement applying only to the body should not be read as evidence for the complete valve. For fabricated equipment, identify plates, forgings, pipe, fittings, weld metal and heat-affected zones within the required scope.</p>
<p className={paragraph}>Ask bidders to return a component-level material schedule showing the offered grade, product form, applicable specification, manufacturing route and delivery condition. The same approach applies to flanges, wellhead equipment, pumps and piping assemblies. It lets the buyer compare actual configurations and prevents a broad catalogue statement from replacing the item-specific technical offer.</p>

<h2 id="record-product-form-and-material-condition" className={heading}>Record product form, heat treatment, strength and hardness</h2>
<p className={paragraph}>Material identity needs more detail than chemical composition. Record whether a component is a casting, forging, plate, bar, pipe or another product form. State the material specification and grade, heat-treatment condition, strength level and hardness requirements applicable to that product. Include any restrictions on cold work, surface hardening or local repair. These details belong in the purchase description and in the records used to verify the supplied condition.</p>
<p className={paragraph}>Do not invent a universal hardness ceiling. Limits and measurement requirements depend on the material, product, fabrication route and applicable clause. The RFQ should cite the approved basis and say where measurements are required, which method is accepted, how sampling is defined and how results remain traceable. Actual values are more useful than a certificate that says only “NACE OK.”</p>

<h2 id="control-welding-and-fabrication" className={heading}>Control welding, forming and repair</h2>
<p className={paragraph}>Fabrication can change an otherwise acceptable material condition. Identify the required welding procedure qualifications, welder qualifications, consumables, preheat, heat input, post-weld heat treatment and hardness survey or other examinations according to the approved project basis. Define the scope for production welds, attachment welds, cladding or overlay, cast repair welding and temporary fabrication welds. Any proposed repair route should require approval before work starts.</p>
<p className={paragraph}>The quotation should distinguish base-material compliance from fabrication compliance. A mill certificate for plate does not verify the completed pressure-vessel weld, and a procedure qualification record does not prove that every production weld followed the approved procedure. Connect the material, procedure, personnel, production record, examination and final release through the inspection and test plan. The <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>ITP hold and witness guide</Link> explains how to place review and release points around those records.</p>

<h2 id="ask-for-a-reviewable-evidence-package" className={heading}>Ask for a reviewable evidence package</h2>
<p className={paragraph}>Define the documents required with the offer, before manufacture and in the final dossier. They may include the component material schedule, manufacturing route, material certificates, heat-treatment charts, hardness results, welding and repair records, non-destructive examination reports, qualification evidence, deviations and a compliance matrix against the project specification. Ask the supplier to identify the clause or approved qualification basis supporting each material condition rather than issuing an unqualified declaration.</p>
<p className={paragraph}>An <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>EN 10204 inspection document</Link> answers questions about the stated material and inspection basis; its document type alone does not demonstrate sour-service suitability. Preserve the link between the delivered component and those records using the practices in the <Link className={link} href={postUrl(getPost("heat-number-traceability-mill-certificates")!)}>heat-number traceability guide</Link>. PMI can help verify alloy identity for a defined scope, but the <Link className={link} href={postUrl(getPost("positive-material-identification-xrf-oes-buyers-guide")!)}>PMI buyer guide</Link> explains why it cannot prove heat treatment, mechanical properties or the full manufacturing history.</p>

<h2 id="handle-alternatives-and-qualification-claims" className={heading}>Handle alternatives and qualification claims before award</h2>
<p className={paragraph}>A supplier may propose a material outside a listed condition or rely on laboratory testing or field experience. ISO 15156-1 includes routes for material qualification and reporting, but the offer must describe the proposed basis and its limits. Require the purchaser’s materials engineer to approve it before substitution. Evidence developed for one environment, product form, heat treatment or manufacturing process should not be extended to another without a justified engineering basis.</p>
<p className={paragraph}>Use a deviation register with the original requirement, offered alternative, technical evidence, affected components and approval status. Commercial evaluation should keep conditional deviations visible; a low price is not comparable if one bidder has excluded sour-service welding controls or final hardness records. Carry approved deviations into the purchase order and final dossier so the receiving team does not have to reconstruct decisions from email.</p>

<h2 id="build-a-complete-sour-service-rfq" className={heading}>Build a complete sour-service RFQ</h2>
<p className={paragraph}>Send the equipment datasheet, process and environmental data, applicable ISO 15156 or NACE MR0175 edition, component-level material requirements, product forms, fabrication controls, inspection plan, document register and deviation format. Identify the parties responsible for environmental definition, material selection and final technical approval. Ask each bidder to return a completed compliance matrix and list every assumption.</p>
<p className={paragraph}>Submit the package through Oillinko’s <Link className={link} href="/oil-and-gas/services/inspection-ndt-and-material-testing">inspection and material testing enquiry page</Link>. Oillinko reviews the sourcing request and coordinates it manually with suitable sources. The asset owner and responsible engineering parties retain approval of the service definition, material selection, qualification basis and acceptance criteria. That division keeps procurement efficient without turning a sourcing response into an unsupported materials decision.</p>

<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>}
