import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("ndt-personnel-certification-iso-9712-employer-based-rfq")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>An inspection quotation that promises certified NDT personnel still leaves important purchasing questions unanswered. Who issued the certificate, which method and work scope does it cover, and does the proposed person meet the project requirement on the planned inspection date? NDT personnel certification should be reviewed against an assignment, rather than treated as a general credential that covers every examination a contractor offers.</p>
    <p className={paragraph}>This guide helps buyers request an understandable personnel package for nondestructive testing. It does not replace the applicable code, certification scheme or employer procedure, and it does not approve a technician to perform work. The practical objective is to make the contractor response reviewable before mobilization, with clear references for the person performing the examination and the person responsible for technical supervision or report approval.</p>
    <h2 id="start-with-the-project-requirement" className={heading}>Start with the project requirement</h2>
    <p className={paragraph}>Identify the examination method, technique, product or sector, applicable specification and required personnel level. Include the relevant document revision in the RFQ. If the project accepts more than one certification route, reproduce that choice accurately and ask the bidder to identify the route offered. Avoid combining several familiar scheme names into an ambiguous requirement that bidders interpret differently.</p>
    <p className={paragraph}>Connect the personnel requirement to the actual inspection scope. For example, examining an identified weld population and reviewing existing thickness records are different assignments, even if both involve ultrasonic terminology. Define who performs the work, evaluates indications, approves procedures and signs reports. The <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>inspection and test plan guide</Link> helps place the personnel review before the relevant work or witness point.</p>
    <h2 id="identify-the-certification-route" className={heading}>Identify the certification route</h2>
    <p className={paragraph}>Central certification and employer-based certification have different issuing arrangements. <a className={link} href="https://www.asnt.org/certification" target="_blank" rel="noopener noreferrer">ASNT describes its NDT and 9712 programmes</a> and their relationship to those models. Ask for the precise programme and certificate being offered; an acronym on a proposal is insufficient. The accepted route must be determined from the project requirement, not from a buyer preference for a familiar logo.</p>
    <p className={paragraph}>For an employer-based route, request the employer certification and the applicable written-practice reference. <a className={link} href="https://www.asnt.org/standards-publications/blog/employer-based-certification-programs" target="_blank" rel="noopener noreferrer">ASNT explains that SNT-TC-1A-based certification is the employer responsibility</a> and distinguishes it from certificates issued directly by ASNT. A training-course document can support qualification evidence but should not be relabelled as the employer certification. Ask the contractor to explain any unclear issuing arrangement.</p>
    <h2 id="match-the-certificate-to-the-assignment" className={heading}>Match the certificate to the assignment</h2>
    <p className={paragraph}>Create a small review schedule with the proposed person, certificate identifier, issuer, method, level, relevant scope and validity information. Compare the actual certificate wording with the work package. Where abbreviations or restrictions are unclear, request an explanation from the appropriate issuing or responsible party. Do not infer a specialist technique or an unrestricted product scope merely because a broader method appears on a wallet card.</p>
    <p className={paragraph}>BINDT describes <a className={link} href="https://www.bindt.org/Certification/" target="_blank" rel="noopener noreferrer">PCN personnel certification across specified methods and products</a>. This is a useful reminder to read what the individual record covers. Keep the qualification of a named person distinct from the capabilities advertised by the inspection company. If a bidder lists several employees, identify which one is proposed for each required activity rather than assuming the entire team can cover every task.</p>
    <h2 id="verify-status-and-record-the-check" className={heading}>Verify status and record the check</h2>
    <p className={paragraph}>Use the issuing body&apos;s official verification route where one is provided, such as the <a className={link} href="https://www.bindt.org/Certification/pcn-certificate-verification/" target="_blank" rel="noopener noreferrer">BINDT PCN certificate verification service</a>. Record the identifier checked, the date and the relevant outcome in the procurement file. A search result for someone with a similar name is not enough to link the proposed inspector to the submitted certificate. Resolve discrepancies before relying on the record.</p>
    <p className={paragraph}>Check validity against the planned work date, including the effect of a delayed mobilization. Request confirmation of any scheme or employer conditions relevant to the assignment through the contractor&apos;s responsible technical contact. Ask for the necessary evidence without circulating unrelated personal records through a broad RFQ mailing list. Retain the verification result with the controlled review package so the next reviewer knows what was established and when.</p>
    <h2 id="keep-authorization-and-procedure-review-visible" className={heading}>Keep authorization and procedure review visible</h2>
    <p className={paragraph}>Ask the contractor to identify the employment or engagement arrangement and the authorization or approvals required for the proposed work. Record the applicable procedure and the responsible technical authority. Personnel certification alone does not identify which project procedure the person will use, which equipment is included or who is permitted to accept a result on behalf of the purchaser. Those responsibilities belong in the service scope.</p>
    <p className={paragraph}>If a subcontractor will perform part of the examination, make that boundary explicit. The offer should identify whose personnel system and procedures apply, who issues the report and which approvals must precede mobilization. Confirm that the proposed people are available for the planned inspection dates. Keep the same question open when an inspector is replaced. A substitution after award should come with the replacement person&apos;s relevant records and the agreed review, rather than relying on approval of the original individual.</p>
    <h2 id="separate-personnel-evidence-from-company-credentials" className={heading}>Separate personnel evidence from company credentials</h2>
    <p className={paragraph}>A company management certificate, laboratory accreditation and a technician&apos;s personnel certificate serve different purposes. Ask which credentials the contract actually requires and compare each against its own scope. The <Link className={link} href={postUrl(getPost("iso-17025-laboratory-accreditation-scope-test-report")!)}>laboratory accreditation scope guide</Link> covers an organizational evidence check. Neither a company logo nor an accreditation claim should hide missing information about the person assigned to the inspection.</p>
    <p className={paragraph}>For bid comparison, record gaps concretely: issuer not identified, method scope unclear, proposed inspector not named, certificate status unresolved or procedure review excluded. Keep these separate from price differences. One contractor may include the personnel-document review and technical reporting while another prices site attendance only. A comparable offer states the required deliverables, review responsibilities, mobilization assumptions and treatment of a personnel change.</p>
    <h2 id="link-personnel-review-to-the-final-report" className={heading}>Link personnel review to the final report</h2>
    <p className={paragraph}>At handover, retain the connection between the approved assignment and the issued inspection report. Check that the report identifies the relevant personnel and roles, procedure reference, examined items and stated limitations. If another person performed or approved the work, request the controlled explanation and supporting records. A complete personnel file does not by itself establish that the inspection coverage or product acceptance criteria were satisfied.</p>
    <p className={paragraph}>Send the examination scope, project requirements and expected records through Oillinko&apos;s <Link className={link} href="/oil-and-gas/services/inspection-ndt-and-material-testing">inspection and material-testing enquiry page</Link>. The <Link className={link} href="/">Oillinko sourcing service</Link> coordinates enquiries manually; the actual provider and personnel remain subject to review for the assignment. Agree the document-review point before the service begins, then preserve the resulting approvals alongside the final report. This makes both the quotation and the eventual handover easier to assess.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
