import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";
const post=getPost("npt-bspt-bspp-threaded-fitting-buyers-guide")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading="mt-12 text-xl font-bold";
const link="text-accent underline underline-offset-4";
const faqs=[
  {
    "q": "Are NPT and BSPT interchangeable because both are tapered?",
    "a": "No. Taper alone does not establish matching thread geometry or an acceptable connection. Confirm the exact thread and end connection against the applicable manufacturer documentation."
  },
  {
    "q": "Does BSPP identify the complete seal arrangement?",
    "a": "No. Obtain the complete connection drawing and required sealing components. Different designs using parallel threads can have different mating and sealing details."
  },
  {
    "q": "What information should a threaded adapter RFQ include?",
    "a": "Describe both ends by family, size, gender and sealing detail. Add material, service requirements, dimensions, quantity, documentation and any unresolved identification questions."
  }
];
export default function Page(){return <><BlogPostHeader post={post}/><Prose><p className={paragraph}>A request for a half-inch threaded fitting can describe several different products. The size may be correct while the thread standard, connection gender or sealing arrangement is wrong. This becomes particularly important when a replacement instrument comes from a different manufacturer or an equipment package must connect to existing piping. Before asking suppliers to quote, separate three questions: what thread is present, what complete end connection is required, and what evidence establishes suitability for the intended service?</p>
<p className={paragraph}>This guide explains the purchasing differences between NPT, BSPT and BSPP without turning a general identification guide into an installation procedure. It supports enquiries for <Link className={link} href="/oil-and-gas/equipment/flanges-fittings-bolting/forged-and-branch-fittings">threaded and forged fittings</Link>{" "}and related connection components. It does not establish an operating rating or approve mixing unlike connections. The manufacturer’s product documentation, project specification and responsible technical review remain necessary when selecting an actual fitting or adapter.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Buyer comparison: identify the thread family, confirm the complete mating and sealing arrangement, then review the actual product rating."/><figcaption className="mt-3 text-sm text-muted">The thread designation is one part of a complete connection specification.</figcaption></figure>
<h2 id="recognize-the-families-without-assuming-interchangeability" className={heading}>Recognize the families without assuming interchangeability</h2>
<p className={paragraph}>NPT is a tapered pipe thread family, while BSPT denotes British Standard Pipe Tapered and BSPP denotes British Standard Pipe Parallel. Swagelok’s <a className={link} href="https://www.swagelok.com/downloads/webcatalogs/en/ms-13-77.pdf" target="_blank" rel="noopener noreferrer">thread and end connection identification guide</a>{" "}distinguishes these thread families and their associated standards. It also distinguishes the thread form from the complete end connection, which includes the sealing geometry. A family name is therefore useful purchasing information, but it is not the entire connection specification.</p>
<p className={paragraph}>Use the full designation from the approved drawing or manufacturer record rather than shortening every British pipe thread reference to BSP. Keep male and female ends explicit and record the required size for each end of a reducer or adapter. If a supplier proposes a different family, treat that as a technical deviation requiring review. The fact that two parts appear to engage is not evidence that the resulting connection meets the project requirement.</p>
<h2 id="record-the-sealing-arrangement-as-a-separate-requirement" className={heading}>Record the sealing arrangement as a separate requirement</h2>
<p className={paragraph}>The sealing detail deserves its own line in the enquiry. For example, <a className={link} href="https://ipd.parker.com/category/iso-conversion-fittings-1" target="_blank" rel="noopener noreferrer">Parker’s ISO conversion fitting catalogue</a>{" "}specifies a bonded seal for particular BSPP ends and notes that their pressure rating depends on the sealing washer used. That statement applies to the listed designs; it should not be generalized into a claim that every BSPP connection uses the same washer. Request the actual drawing and specified seal for the proposed product.</p>
<p className={paragraph}>Ask whether the quoted supply includes the required sealing component, its identified material and any associated retaining parts. If these are excluded, resolve how they will be specified and procured. A replacement that has the desired thread but a different mating face may create another compatibility question. Include clear views of the port and fitting shoulder in the enquiry, and ask the technical reviewer to confirm the complete mating arrangement before the order is released.</p>
<h2 id="use-identification-evidence-rather-than-a-photograph-alone" className={heading}>Use identification evidence rather than a photograph alone</h2>
<p className={paragraph}>Start with the equipment drawing, original order code, manufacturer name and any legible markings. A photograph is valuable context but should not become the only basis for identifying a critical connection. <a className={link} href="https://www.swagelok.com/en/blog/fittings-identifying-thread-size-pitch" target="_blank" rel="noopener noreferrer">Swagelok’s explanation of thread size and pitch</a>{" "}identifies diameter, pitch and taper as useful characteristics and discusses appropriate identification tools. Measurements should be supplied with units and their source, while uncertain observations should be labeled as uncertain rather than converted into a guessed part number.</p>
<p className={paragraph}>The Swagelok identification guide cautions that some BSPT and NPT sizes are especially difficult to distinguish and that its reference tables are identification aids, not inspection acceptance criteria. For a damaged or unmarked sample, request competent identification and explain what evidence is missing. Do not make trial assembly under pressure part of a purchasing check. Site examination and removal of installed components belong to authorized personnel working under the applicable site controls.</p>
<h2 id="describe-both-sides-of-a-conversion-fitting" className={heading}>Describe both sides of a conversion fitting</h2>
<p className={paragraph}>A conversion fitting has two interfaces, and both need a complete description. Label them end A and end B on a sketch, with the connection family, nominal size, gender and sealing detail for each. Include the mating equipment references so that a supplier can check the intended arrangement. Avoid an enquiry that simply says BSP to NPT when the required direction, male or female ends, and parallel or tapered BSP connection remain unresolved.</p>
<p className={paragraph}>Also provide available space, orientation constraints and drawing dimensions that matter to the installation. Ask the supplier to identify differences between its proposed product and the requested envelope. A longer adapter or different body shape can change access and fit even when the thread descriptions match. Do not approve a chain of additional adapters solely because each individual part is available; the responsible engineer should evaluate the proposed assembly and its interfaces as a whole.</p>
<h2 id="review-materials-and-ratings-independently-of-thread-identity" className={heading}>Review materials and ratings independently of thread identity</h2>
<p className={paragraph}>An identified thread is only one element of selection. Supply the required body material, process medium, design conditions and applicable project specification. Ask for the manufacturer’s rating basis for the actual configuration, including any seal-dependent limits. Do not derive an allowable pressure from the NPT or BSP label alone. Where an alternative material or seal is proposed, keep that substitution visible in the comparison and obtain the required technical approval before treating the offer as compliant.</p>
<p className={paragraph}>Clarify documentation requirements at the same time. The <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>guide to EN 10204 material certificates</Link>{" "}explains document types, while the supplier still needs to state which items and materials its offered documents cover. Request traceability or inspection evidence when required by the purchase specification, rather than assuming that a certificate heading proves every connection detail. For small quantities, confirm whether documentation and seals are priced per item, per batch or as separate charges.</p>
<h2 id="compare-quotations-against-a-complete-item-description" className={heading}>Compare quotations against a complete item description</h2>
<p className={paragraph}>Build the comparison around the same item identity: manufacturer and order code where known, end A and end B details, body and seal materials, required drawing, quantity, documentation and delivery scope. Ask suppliers to list deviations explicitly. If the enquiry began with an unidentified sample, keep the identification step separate from acceptance of the proposed replacement. This prevents a commercial quotation from being mistaken for a completed engineering assessment of an uncertain installed component.</p>
<p className={paragraph}>The <Link className={link} href={postUrl(getPost("pipeline-fittings-and-schedules")!)}>pipeline fittings and schedules guide</Link>{" "}provides broader piping context. When sending an enquiry to Oillinko, attach the available drawing or photographs, preserve the exact connection notation and describe what still needs confirmation. Oillinko receives the request for sourcing coordination with potential suppliers. Confirm the final product configuration and approval responsibilities before purchase, then retain the accepted drawing and quotation with the order so receiving personnel can check the delivered items against the same description.</p>
<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>;}
