import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";
const post = getPost("oil-flushing-service-rfq-cleanliness-acceptance")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading="mt-12 text-xl font-bold";
const link="text-accent underline underline-offset-4";
const faqs=[
  {
    "q": "Does ISO 4406 specify the cleanliness target for every oil system?",
    "a": "No. Its stated scope defines the particle contamination code for hydraulic fluid. Obtain the acceptance requirement from the applicable equipment and project documentation."
  },
  {
    "q": "Does a satisfactory particle result prove the oil is suitable for service?",
    "a": "It answers a defined particle contamination question. Other oil-condition questions and the authority to release equipment must be addressed under the approved project requirements."
  },
  {
    "q": "What should an oil flushing RFQ include?",
    "a": "Provide the circuit boundary, reason for the work, drawings, fluid details, applicable acceptance requirements, proposed sampling and reporting expectations, site interfaces and required dates."
  }
];
export default function Page(){return <><BlogPostHeader post={post}/><Prose><p className={paragraph}>An oil flushing quotation is difficult to compare when the enquiry asks only for a clean system. One provider may price temporary filtration and a final particle count, while another includes circuit preparation, several sampling locations, laboratory analysis and documented reinstatement. The difference can remain hidden until the shutdown begins. A useful request for quotation defines the equipment boundary, the evidence needed for acceptance and who is responsible for each interface before commercial offers are evaluated.</p>
<p className={paragraph}>This guide covers procurement questions for flushing oil circuits associated with hydraulic or lubrication equipment. It does not prescribe a flushing procedure or a cleanliness value for a particular machine. Those requirements need the applicable equipment documentation and approval by the responsible engineering team. Start with the <Link className={link} href="/oil-and-gas/services/chemical-cleaning-and-oil-flushing">chemical cleaning and oil flushing enquiry scope</Link>, then identify which part of that broader service is actually required. Chemical cleaning and oil flushing should not be treated as interchangeable descriptions in a purchase order.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Oil flushing procurement connects the defined circuit, approved acceptance requirements, and traceable sampling and handover evidence."/><figcaption className="mt-3 text-sm text-muted">Agree the service boundary and acceptance evidence before comparing quotations.</figcaption></figure>
<h2 id="define-the-circuit-and-the-reason-for-the-work" className={heading}>Define the circuit and the reason for the work</h2>
<p className={paragraph}>Attach the available circuit drawings, equipment tags and current revision of the project specification. Describe whether the enquiry follows new construction, a component replacement, an observed contamination problem or planned maintenance. Include known oil identification and available condition reports without turning an unconfirmed observation into a diagnosis. A service provider needs to understand what changed and which parts of the installation are covered before proposing resources, a programme or an acceptance plan.</p>
<p className={paragraph}>Mark the proposed boundary and ask the provider to identify assumptions about tanks, piping, coolers, hoses and connected equipment. Clarify who will confirm components requiring protection, exclusion or special treatment under the approved method. Temporary connections and reinstatement should have named owners. The buyer should request a reviewed method statement and interface schedule, rather than attempting to specify improvised operating conditions from a generic article. Unresolved drawing gaps should remain visible in the offer and be closed before execution.</p>
<h2 id="separate-the-cleanliness-code-from-the-acceptance-target" className={heading}>Separate the cleanliness code from the acceptance target</h2>
<p className={paragraph}><a className={link} href="https://www.iso.org/standard/79716.html" target="_blank" rel="noopener noreferrer">ISO 4406:2021</a>{" "}defines a code for expressing the quantity of solid particles in hydraulic fluid. Citing that document tells the bidder how a particular contamination result is described; it does not, by itself, select the acceptable result for your installation. State the applicable OEM or project requirement, its revision and the authority responsible for resolving conflicting requirements. Do not copy a target from another machine simply because both systems use oil.</p>
<p className={paragraph}>Ask the responsible engineer to define which results are required at which acceptance locations and stage. If the target is still undecided, request a separately identified engineering clarification instead of inviting each bidder to choose a different value. The quotation should distinguish the proposed assessment method from the acceptance criterion. This distinction is particularly valuable when offers use similar language such as cleanliness certification but attach different reporting formats or leave the actual pass condition unstated.</p>
<h2 id="identify-contamination-questions-beyond-particle-counts" className={heading}>Identify contamination questions beyond particle counts</h2>
<p className={paragraph}>A particle result should not be presented as a complete assessment of oil condition. <a className={link} href="https://www.donaldson.com/en/resources/technical-articles/maintain-hoses-hydraulic-cleanliness/" target="_blank" rel="noopener noreferrer">Donaldson’s hydraulic cleanliness guidance</a>{" "}discusses water, chemical issues and varnish alongside particulate contamination. It also identifies hose assembly and installation as possible sources of debris. These points support asking what problem the service is intended to address. They do not establish that one flushing method will remove every kind of contamination or restore every degraded fluid.</p>
<p className={paragraph}>Include existing laboratory results and ask the responsible technical team whether additional oil-condition testing belongs in the scope. Where water, mixed fluids or deposits are suspected, describe the evidence and request a justified proposal with limitations. Confirm compatibility requirements for any proposed flushing medium, temporary equipment and final service oil through the relevant manufacturer documentation. Keep fluid replacement, disposal and additional treatment as explicit scope items; do not assume that they are included in a price described only as flushing.</p>
<h2 id="agree-the-sampling-record-before-comparing-prices" className={heading}>Agree the sampling record before comparing prices</h2>
<p className={paragraph}>A final report needs to show what was sampled, where and when. Ask for a proposed sampling plan that identifies circuit locations, sample identification, the analysis method and the reporting route. Clarify whether results will come from site instruments, an external laboratory or both, and what instrument or laboratory evidence the project requires. The approved procedure should govern how samples are obtained. Buyers should avoid accepting an unlabeled result whose relationship to the specified circuit cannot be demonstrated.</p>
<p className={paragraph}>Define how the parties will handle repeat samples, disputed results and additional work before mobilization. Ask who can authorize another sampling round and whether laboratory turnaround affects the shutdown programme. If witnessing is required, identify notice periods and the person empowered to release the next stage. The <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>guide to inspection hold and witness points</Link>{" "}explains that coordination question. The sampling plan and inspection plan should describe the same acceptance event rather than creating two inconsistent approval routes.</p>
<h2 id="make-site-interfaces-and-price-boundaries-explicit" className={heading}>Make site interfaces and price boundaries explicit</h2>
<p className={paragraph}>Request a responsibility matrix for access, utilities, temporary equipment, consumables, oil supply, waste handling and reinstatement records. Ask the provider to state the basis of the quoted duration and assumptions about site readiness. Mobilization dates are easier to assess when the offer identifies prerequisites such as approved drawings, permits and equipment availability. Safety planning, isolation and execution remain matters for the competent site team and the approved procedure; the RFQ should make those responsibilities visible without attempting to replace them.</p>
<p className={paragraph}>Compare offers using the same commercial boundaries. Identify whether consumables, laboratory charges, standby, repeat attendance and work outside the original circuit are included, provisional or charged separately. Ask how variations will be approved and documented. A low initial price can be misleading if the final report, additional sampling or reinstatement support sits outside the quoted scope. Conversely, a broader proposal may contain work the project does not require. Resolve those differences through a written clarification schedule before selecting the supplier.</p>
<h2 id="specify-the-handover-package-and-release-authority" className={heading}>Specify the handover package and release authority</h2>
<p className={paragraph}>Agree the final deliverables before award: the approved scope and method references, circuit identification, sampling records, results, deviations and their disposition, and the responsible parties’ acceptance record. Include reinstatement and preservation documentation where required by the project. A service completion statement should not be confused with permission to start the equipment. Identify who reviews the evidence and who authorizes the next project stage, especially when the flushing contractor and commissioning team are different organizations.</p>
<p className={paragraph}>The <Link className={link} href={postUrl(getPost("pump-factory-acceptance-testing-and-commissioning-checklist")!)}>pump testing and commissioning guide</Link>{" "}provides useful context for that later handover. For an Oillinko enquiry, send the circuit scope, location, required dates, known fluid details, applicable acceptance requirements and available drawings together. Oillinko receives the request for coordination with potential providers; provider capability, method approval and project acceptance must be confirmed for the actual assignment. A well-defined enquiry makes those discussions more useful and reduces the chance that a missing scope assumption becomes a shutdown dispute.</p>
<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>;}
