import Link from "next/link";
import SiteImage from "@/components/SiteImage";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("partial-awards-equipment-rfq-package-line-item-offers")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>An equipment RFQ may contain valves, instruments, spares and fabricated items that no single bidder makes. One supplier may quote the full package through several sources, while others quote only the lines they can produce. A package total cannot be fairly compared with the sum of the cheapest visible line prices until delivery, documentation, interfaces and contract responsibilities are placed on the same basis. The buyer should decide before issuing the RFQ whether partial bids and awards by line or lot are allowed.</p>
    <p className={paragraph}>The <a className={link} href="https://content.unops.org/service-Line-Documents/Procurement/UNOPS-Procurement-Manual-2021_EN.pdf" target="_blank" rel="noopener noreferrer">UNOPS procurement manual, revision 7</a> explicitly discusses stating whether partial bids and split orders are permitted and weighing transaction, supply-chain, logistics and warranty implications. It is an example of a documented procurement method, not a rule imposed on every private buyer. The useful principle is to tell bidders the award basis and evaluate the whole consequence of splitting, not only the lowest unit price.</p>
    <figure className="mt-8"><SiteImage src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Equipment RFQ comparison diagram contrasting one package award with line-item awards and their delivery, interface and documentation costs."/><figcaption className="mt-3 text-sm text-muted">The apparent line-price saving must survive a full-scope comparison.</figcaption></figure>

    <h2 className={heading}>Set the award structure in the enquiry</h2>
    <p className={paragraph}>Number every line and give its quantity, unit, technical specification, required documents and delivery destination. Group inseparable items into a lot when their design or warranty responsibility needs to stay together. State whether bidders may offer the entire package, selected lots, individual lines or an approved alternative. If a package discount applies only when every line is awarded, require the bidder to show the condition explicitly. Do not promise a split award unless the buyer retains that option in the enquiry and the governing procurement rules permit it.</p>
    <p className={paragraph}>State how deviations and no-bid lines should be marked. A blank price can mean excluded, unavailable, included elsewhere or simply overlooked. Give bidders a response template with line number, offered description, manufacturer, manufacturing origin, quantity, unit price, currency, validity and lead time. Ask them to identify whether any item is offered as an equivalent and what approval evidence supports it. The <Link className={link} href={postUrl(getPost("country-of-origin-vs-dispatch-equipment-rfq")!)}>origin versus dispatch guide</Link> explains why the country of manufacture should not be inferred from the trading company location.</p>

    <h2 className={heading}>Compare the technical scope first</h2>
    <p className={paragraph}>Create a compliance matrix before ranking prices. For each line, record required and offered pressure rating, materials, size, connection, testing, certificates and spare or accessory scope as applicable. Mark full compliance, documented deviation and missing information separately. Do not silently score an unspecified material as compliant. A package bidder may include integration engineering or tests that a line bidder does not; a line bidder may offer a technically superior item but exclude common documentation. Those differences must be visible in the comparison.</p>
    <p className={paragraph}>Identify interfaces between lines. A valve and actuator, a pump and driver, or a hose and mating adapter can each be individually acceptable yet fail as a combination. If the award is split, name the party who verifies drawings, dimensions and control signals across suppliers. The buyer may need an integrator or an additional acceptance stage. The cheapest line price is not the cheapest workable package if interface responsibility becomes an unpriced task.</p>

    <h2 className={heading}>Bring commercial terms to one basis</h2>
    <p className={paragraph}>Compare quoted delivery terms, named place, export packing, freight, insurance, customs responsibility and taxes separately. A price at a factory gate is not equivalent to a delivered-site price. Record the location from which each supplier will dispatch, but keep that separate from manufacturing origin. The <Link className={link} href={postUrl(getPost("exw-vs-fca-oil-gas-equipment-buyers")!)}>EXW and FCA guide</Link> explains two common handover structures. Ask for an itemized freight or consolidation option if it could change the decision, rather than applying an arbitrary percentage to every offer.</p>
    <p className={paragraph}>Lead time also changes when several suppliers must deliver into one shipment. Record time from order acceptance to manufacturing completion, inspection, document approval and dispatch, and identify the latest item controlling the project deadline. A package supplier may consolidate all items, while a split award creates multiple collections and invoices. Compare payment milestones, validity, cancellation terms and currency exposure on the same timeline. A summary total without these conditions can hide the real cash and scheduling burden.</p>

    <h2 className={heading}>Count the costs of several awards</h2>
    <p className={paragraph}>A split award can improve access to specialists and reduce certain unit prices, but it adds purchase orders, expediting, separate inspections, shipping events and possibly different warranty administrators. Estimate these efforts using the actual project plan. Do not assume the package offer is always safer: it may contain a large markup on a weakly sourced line or a long lead-time item. Request both package and line options where feasible, then compare the total evaluated cost and technical risk under stated assumptions.</p>
    <p className={paragraph}>If a supplier quotes a package discount, calculate the discount only when its stated conditions are met. If one line is excluded after clarification, ask whether the discount still applies. For split awards, identify which documents each supplier must deliver and who assembles the final dossier. The <Link className={link} href={postUrl(getPost("consolidated-shipments-and-multi-vendor-orders")!)}>multi-vendor shipment guide</Link> covers the practical coordination that follows a split purchase. The comparison should explain why an award was selected, not merely show the lowest number in one column.</p>

    <h2 className={heading}>Document the decision and its exceptions</h2>
    <p className={paragraph}>Keep the original RFQ, technical clarifications, bid revisions and a dated evaluation sheet. For each selected line, record the compliant scope, supplier, manufacturing origin, price basis, delivery commitment, documents and unresolved condition. If a deviation needs engineering approval, keep it open until the responsible authority resolves it. No quotation should be converted into an unconditional promise to the final customer while those decisions remain outstanding.</p>
    <p className={paragraph}>Send the item schedule and approval basis through Oillinko&apos;s <Link className={link} href="/services">sourcing and procurement enquiry page</Link> for manual review and distribution. Oillinko can coordinate comparable enquiries, but a public directory or catalogue does not prove availability, authorization or a firm price. The sound RFQ makes both a complete package and a carefully managed partial award possible to evaluate without concealing gaps.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
