import Link from "next/link";
import SiteImage from "@/components/SiteImage";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("phased-array-ut-weld-inspection-scope-records")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A request for “PAUT of all welds” is not yet an inspection scope. Phased-array ultrasonic testing can record and display information from multiple beam angles, but its coverage depends on the weld geometry, access, material, surface condition and the written procedure. A buyer who specifies only a method may receive reports that look complete while important areas were never accessible or evaluated to the project&apos;s acceptance criteria. The RFQ should define what will be examined, how coverage is demonstrated and what evidence will be retained.</p>
    <p className={paragraph}>The public description of <a className={link} href="https://www.iso.org/obp/ui?_escaped_fragment_=iso%3Astd%3Aiso%3A13588%3Aed-2%3Av1%3Aen" target="_blank" rel="noopener noreferrer">ISO 13588:2019</a> covers semi- or fully automated phased-array ultrasonic testing of fusion-welded joints, with a stated scope involving full-penetration welds in low-alloy or fine-grained steel and specified geometry. It notes that additional guidance is needed for other materials. That is a boundary, not a promise that every weld can be inspected under one standard setup. The engineer must name the project code, examination extent and acceptance standard separately.</p>
    <figure className="mt-8"><SiteImage src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Phased-array weld inspection scope diagram showing weld map, access, procedure, coverage and traceable records."/><figcaption className="mt-3 text-sm text-muted">A defensible record connects each weld to its procedure, coverage and reviewed result.</figcaption></figure>

    <h2 id="weld-list" className={heading}>Start with a weld list and inspection objective</h2>
    <p className={paragraph}>Provide a weld map or isometric drawing with unique weld identifiers, joint type, nominal thickness, outside diameter where relevant, base and filler materials, weld process and whether the weld is new or in service. Identify the examination stage, required percentage or weld selection rule and any areas of particular concern. The inspection objective may be fabrication acceptance, repair verification or an in-service condition assessment; each requires a different basis for reporting and disposition. Do not let a method name silently define the contractual acceptance target.</p>
    <p className={paragraph}>State the applicable construction or inspection code, the examination procedure and the acceptance criteria approved by the responsible engineer. ISO 13588 describes a test method; it does not itself choose the project&apos;s acceptance level for every application. The public <a className={link} href="https://www.iso.org/obp/ui?_escaped_fragment_=iso%3Astd%3Aiso%3A17640%3Aed-4%3Av1%3Aen" target="_blank" rel="noopener noreferrer">ISO 17640:2018 scope</a> concerns manual ultrasonic testing of fusion welds and provides a useful reminder that conventional UT and automated PAUT are distinct procedure choices. The project team should decide which method is required and when supplementary methods are appropriate.</p>

    <h2 id="coverage" className={heading}>Show that the sound can reach the target volume</h2>
    <p className={paragraph}>Ask bidders to evaluate access from each side of the weld, scanner clearance, coating, surface profile, curvature, nearby attachments and the available scanning surface. A weld next to a flange or support may prevent a planned scan path. A thick section or complicated joint can require a different probe and scan plan from a simple butt weld. Where the full target volume cannot be covered, the procedure and final report should identify the limitation by weld and region, with an agreed alternative or concession process.</p>
    <p className={paragraph}>The written scan plan should identify probe and wedge configuration, relevant beam coverage, reference blocks or calibration approach, encoded position reference if used, and the method for relating indications to the weld location. These are items for qualified inspection personnel and the responsible engineer to approve, not operating instructions to improvise in the field. Request a demonstration or procedure review when access or material makes the proposed coverage uncertain. A polished image of a scan is not evidence of complete coverage without its geometry and position basis.</p>

    <h2 id="materials" className={heading}>Account for material and weld differences</h2>
    <p className={paragraph}>Grain structure, attenuation, anisotropy and geometry can change how ultrasonic signals behave. Do not presume that a procedure qualified on a straightforward carbon-steel weld is transferable without review to austenitic, dissimilar-metal, cast or clad joints. Ask the inspection provider to identify which weld groups are within its demonstrated procedure and which need additional qualification, reference samples or another method. If a request contains several weld families, price and schedule them separately so technical exceptions remain visible.</p>
    <p className={paragraph}>Surface temperature and coating status also matter. If inspection will occur during fabrication, define whether it is before or after heat treatment, painting or pressure testing and identify the hold or witness points. If in service, describe access and operating constraints for engineering assessment. The <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>hold versus witness point guide</Link> can help build an inspection sequence. It does not replace a site-specific safety or examination procedure.</p>

    <h2 id="records" className={heading}>Request reviewable records, not just a pass stamp</h2>
    <p className={paragraph}>Require the procedure and revision, personnel qualification records applicable to the job, equipment identification, calibration or verification records, weld map, scan plan, coverage statement, indication evaluation, acceptance reference and final report. The <a className={link} href="https://www.iso.org/standard/82513.html" target="_blank" rel="noopener noreferrer">ISO 18563-1:2022 listing</a> addresses verification of phased-array ultrasonic instruments, while other elements of the examination system and project procedure need their own specified controls. A bidder should say what raw or encoded data will be retained, the file format, retention period and how the owner can access it.</p>
    <p className={paragraph}>Make the weld identifier the key that connects drawings, scan data, interpreted indications, repairs and re-examination. If an indication requires disposition, distinguish the technician&apos;s reported finding from the engineer&apos;s acceptance decision. A repair cycle should preserve the original and subsequent reports rather than overwrite them. The <Link className={link} href={postUrl(getPost("ultrasonic-thickness-measurement-reports-rfq-guide")!)}>ultrasonic thickness report guide</Link> covers a different measurement task, but its emphasis on location and traceability applies here too. A single summary count of accepted welds is not enough for later audit.</p>

    <h2 id="rfq" className={heading}>Price the defined scope and its exceptions</h2>
    <p className={paragraph}>Ask each bidder to state the weld count and families covered, mobilisation and access assumptions, procedure qualification basis, extent of scanning, deliverable format, review and reinspection terms, and every area excluded from coverage. Separate optional work for unusual materials, geometry or site constraints. The <Link className={link} href={postUrl(getPost("liquid-penetrant-vs-magnetic-particle-testing-rfq")!)}>PT versus MT guide</Link> helps identify surface methods that may complement, but do not automatically replace, volumetric examination. Send the approved weld list and project criteria through Oillinko&apos;s <Link className={link} href="/oil-and-gas/services/inspection-ndt-and-material-testing">inspection and material testing enquiry page</Link> for manual routing. No public service listing proves a technician is assigned, qualified or available for a particular job.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
