import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";
const post = getPost("plate-heat-exchanger-cleaning-reconditioning-rfq")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading="mt-12 text-xl font-bold";
const link="text-accent underline underline-offset-4";
const faqs=[
  {
    "q": "Does cleaning include replacing all gaskets?",
    "a": "Not automatically. Cleaning, gasket replacement and plate reconditioning must be listed separately in the agreed scope."
  },
  {
    "q": "Can a cleaned exchanger be accepted without further records?",
    "a": "Acceptance depends on the contract and equipment requirements. Specify the required examination, final verification and reporting rather than assuming cleaning proves condition or performance."
  },
  {
    "q": "Is retubing part of plate heat exchanger reconditioning?",
    "a": "Retubing concerns tubular equipment. Identify a gasketed plate exchanger clearly and request a plate-specific service assessment."
  }
];
export default function Page(){return <><BlogPostHeader post={post}/><Prose><p className={paragraph}>A request to service a plate heat exchanger can produce very different quotations. One may allow for cleaning the fluid passages without opening the unit. Another may include removing the plate pack, examining individual plates and replacing gaskets. A third may price only transport and an initial assessment, with repair costs to follow. Comparing those totals without comparing their boundaries gives a misleading picture of cost and downtime. The first purchasing decision is therefore what problem the service must investigate or address.</p>
<p className={paragraph}>This guide concerns gasketed plate heat exchangers, including those used in plant cooling and other process duties. It is a guide to buying a defined service, not a cleaning procedure. Brazed, welded and shell-and-tube equipment require different maintenance assessments. If the equipment type is uncertain, use the <Link className={link} href={postUrl(getPost("pressure-vessels-tanks-and-heat-exchangers-explained")!)}>heat exchanger equipment overview</Link>{" "}to organize the initial enquiry, then obtain the manufacturer and model details before asking a provider to commit to a method.</p>
<figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Plate heat exchanger service scope separates cleaning, plate reconditioning and frame repair, with agreed inspection and handover records."/><figcaption className="mt-3 text-sm text-muted">Specify each work boundary; a service label does not define every included activity.</figcaption></figure>
<h2 id="separate-cleaning-plate-reconditioning-and-frame-repair" className={heading}>Separate cleaning, plate reconditioning and frame repair</h2>
<p className={paragraph}>Alfa Laval’s <a className={link} href="https://www.alfalaval.com/en-us/microsites/gasketed-plate-heat-exchangers/service/cleaning/" target="_blank" rel="noopener noreferrer">gasketed plate heat exchanger cleaning overview</a>{" "}distinguishes mechanical cleaning from cleaning in place, which can clean the exchanger without dismantling it. That describes a service approach, not proof that it suits every deposit or equipment condition. Ask the provider to identify the proposed route and the evidence needed to confirm it. A quotation should also state what examination is possible within that route and what remains outside the assignment.</p>
<p className={paragraph}>The manufacturer’s <a className={link} href="https://www.alfalaval.com/microsites/gphe/services/reconditioning-and-repair/" target="_blank" rel="noopener noreferrer">reconditioning and repair explanation</a>{" "}separates work on the plates from work on the frame. Its service packages also differ in whether crack detection is included. This is a useful warning against treating reconditioning as a universal checklist. In your order, name the actual activities: cleaning, plate examination, gasket replacement, frame assessment, reassembly and verification, where required. Confirm each activity with the proposed provider rather than assuming a familiar service label includes them all.</p>
<h2 id="give-the-service-provider-an-equipment-identity-and-a-baseline" className={heading}>Give the service provider an equipment identity and a baseline</h2>
<p className={paragraph}>Begin with the nameplate, model, serial number, plate arrangement drawing and available operating manual. Include the recorded plate count, plate material and gasket identification if known, and distinguish confirmed records from information inferred from appearance. Photographs can help explain access or external condition but do not replace the equipment documentation. Ask the provider to list missing information before issuing a firm proposal, particularly if the installed unit has been modified since its original delivery.</p>
<p className={paragraph}>Describe the observed symptoms and their timing: reduced thermal duty, changed pressure loss, visible external leakage or a concern about cross-contamination, for example. Provide operating records with the associated flow, temperature and pressure conditions when available. A before-and-after comparison only becomes useful when the conditions behind the readings are understood. Avoid declaring that fouling is the cause solely because the exchanger is performing differently; ask the responsible technical reviewer to distinguish a confirmed diagnosis from a working hypothesis.</p>
<h2 id="define-what-can-be-priced-now-and-what-needs-inspection" className={heading}>Define what can be priced now and what needs inspection</h2>
<p className={paragraph}>A service enquiry can contain a firm base scope and conditional work without becoming an open-ended purchase. Ask for separate prices or an agreed pricing basis for the initial assessment, planned cleaning, examination and any proposed replacement parts. State what discovery triggers a revised quotation and who may authorize it. A contractor should not have to guess whether a damaged plate may be replaced automatically or must be photographed, reported and held for the purchaser’s decision.</p>
<p className={paragraph}>For offsite work, clarify whether the shipment contains loose plates, a plate pack or the complete unit. Allocate packing, collection, lifting, preservation and return transport. For onsite work, identify the available access window and the party responsible for making the equipment ready under the site’s approved arrangements. Include any constraints on utilities, work areas and waste handling. These commercial boundaries can affect duration and price as much as the advertised cleaning method, especially during a constrained plant shutdown.</p>
<h2 id="request-compatibility-evidence-rather-than-a-generic-chemical-recipe" className={heading}>Request compatibility evidence rather than a generic chemical recipe</h2>
<p className={paragraph}>Provide the process fluids and relevant contamination information needed for the service assessment. Ask the provider to confirm compatibility of its proposed cleaning approach with the actual plates, gaskets and other exposed materials. Identify who reviews the method and what documentation is required before work begins. A purchasing team should not select a chemical concentration, exposure time or temperature from a general article and insert it into the work order as a validated procedure.</p>
<p className={paragraph}>Where regasketing is proposed, request identification of the offered gasket material and part configuration, together with the basis for its suitability. Confirm whether the supply is an exact replacement or an alternative requiring approval. Ask how the provider will preserve plate identification and the required arrangement through the work. A lower parts price should be assessed with the full proposal, including the supporting compatibility information and the responsibility for addressing a mismatch discovered before reassembly.</p>
<h2 id="keep-examination-leak-verification-and-thermal-performance-distinct" className={heading}>Keep examination, leak verification and thermal performance distinct</h2>
<p className={paragraph}>Agree what plate examination will be performed and what the report will say about the examined items. Cleaning a surface does not itself document that the plate is free from every relevant defect. If an examination method is proposed, request its coverage, acceptance basis and limitations. The <Link className={link} href={postUrl(getPost("liquid-penetrant-vs-magnetic-particle-testing-rfq")!)}>surface examination RFQ guide</Link>{" "}explains why method names alone are insufficient; it does not select a method for the plates in your exchanger. That selection remains a technical decision for the specific equipment.</p>
<p className={paragraph}>Specify the required final verification and the records needed for acceptance. Keep a reported leak test separate from a commitment about thermal performance in service. If the quotation promises restored performance, ask which duty and measurement conditions define that promise and what exclusions apply. Testing must follow the applicable equipment documentation and approved project requirements. Where attendance or formal release is required, use an agreed <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>inspection and test plan</Link>{" "}to identify who participates and who authorizes the next stage.</p>
<h2 id="compare-the-final-service-offer-and-handover-records" className={heading}>Compare the final service offer and handover records</h2>
<p className={paragraph}>A useful handover package links the incoming equipment identity to the work actually performed. Request the initial findings, approved additional work, replaced parts, examination results, final verification and any remaining recommendations. Ask the provider to distinguish completed corrective work from items referred back to the owner for a future decision. This prevents an invoice stating fully serviced from becoming the only surviving description of a job whose scope changed after inspection.</p>
<p className={paragraph}>Send the equipment records, symptoms, preferred work location and required completion date to Oillinko through the <Link className={link} href="/oil-and-gas/services/heat-exchanger-cleaning-and-retubing">heat exchanger service enquiry page</Link>. Identify the unit as a gasketed plate exchanger so a general enquiry is routed for the appropriate service assessment; retubing is a different task for tubular equipment. Oillinko coordinates the request with potential providers, while the proposed service scope and capability must be confirmed in the offer. Compare the accepted activities, conditional costs, evidence and delivery responsibilities together before placing the order.</p>
<Faq faqs={faqs}/></Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/><CtaBand/></>;}
