import Link from "next/link";
import SiteImage from "@/components/SiteImage";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("pressure-vessel-nameplates-data-reports-replacement-rfq")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>An enquiry for a “same-as-existing” separator or pressure vessel is difficult to price when the buyer sends only a photograph of the equipment. The visible nameplate can identify the original item, but a replacement also needs its current duty, governing code, design conditions, interfaces and required documentation. Likewise, a manufacturer&apos;s data report can describe what was built without proving that an unchanged copy fits a revised process or installation. Treat both records as the beginning of an engineering review, not permission to replicate an old vessel automatically.</p>
    <p className={paragraph}>This is a purchasing checklist, not a design or repair instruction. A responsible pressure-equipment engineer must establish the required design and jurisdictional basis, evaluate any change in service and approve the final drawings. The applicable code edition and local requirements may differ from those used for the installed vessel. Oillinko can coordinate a documented sourcing enquiry; a catalogue listing does not establish a particular maker&apos;s authorization, inventory or project acceptance.</p>
    <figure className="mt-8"><SiteImage src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Pressure vessel replacement RFQ diagram connecting installed nameplate, original data report, current process duty, interfaces and required handover records."/><figcaption className="mt-3 text-sm text-muted">Match the existing identity to current requirements before asking bidders for a replacement configuration.</figcaption></figure>

    <h2 id="identify-installed-vessel" className={heading}>Capture the installed vessel identity</h2>
    <p className={paragraph}>Record clear photographs of the complete nameplate and equipment, including its serial number, maker, year, code marking and any National Board number if present. Note the tag number used by the plant, since that tag may be different from the manufacturer&apos;s serial number. Check that the photo belongs to the exact item being replaced. Similar vessels in the same area can have different design pressures, internals, nozzle orientations or support arrangements. Include the site location and equipment tag in the RFQ document index, while keeping personal or site-sensitive information in the controlled enquiry package.</p>
    <p className={paragraph}>Do not infer missing values from a blurred photograph. If the plate is damaged or inaccessible, ask the owner for the original file, drawings and inspection records and refer the gap to the responsible engineer. A replacement quotation based on an assumed rating can be commercially attractive yet technically unusable. Do not change, reproduce or reapply a certification marking yourself; questions about a missing or damaged mark require the applicable authority and original records.</p>

    <h2 id="read-data-report" className={heading}>Use the manufacturer&apos;s data report as a traceable record</h2>
    <p className={paragraph}>For a vessel originally constructed under ASME BPVC Section VIII Division 1, the <a className={link} href="https://www.asme.org/codes-standards/publications-information/asme-data-report-forms" target="_blank" rel="noopener noreferrer">ASME forms listing</a> identifies U-1 and U-1A manufacturer&apos;s data reports, among other forms. The correct form depends on the actual equipment and code route; do not request U-1 for every vessel worldwide. Ask for the report that belongs to the identified serial number, and compare the reported manufacturer, drawing, code edition, construction details and inspection information with the physical item. Request supplementary or partial reports where the original file indicates they form part of the record.</p>
    <p className={paragraph}>A report is evidence of the original construction, not a complete replacement specification. Material, corrosion allowance, pressure and temperature entries, examination and test records may answer some questions but not describe all current internals, instruments, supports or process requirements. Put a revision-controlled copy beside the latest general arrangement and process datasheet. If the original report cannot be located, say so in the enquiry and ask bidders to state what information remains necessary; do not describe an undocumented vessel as fully certified.</p>

    <h2 id="certification-basis" className={heading}>State the required certification basis precisely</h2>
    <p className={paragraph}>ASME&apos;s <a className={link} href="https://www.asme.org/certification-accreditation/boiler-and-pressure-vessel-certification" target="_blank" rel="noopener noreferrer">Boiler and Pressure Vessel Certification program</a> distinguishes certification scopes, including U for Section VIII Division 1 pressure vessels and U2 for Division 2. A buyer should name the applicable construction code, division, edition, certification scope and any jurisdictional registration requirement that the project actually needs. “ASME stamped” alone leaves the design route and document package unclear. Ask a bidder to identify its proposed manufacturing and certification route and any subcontracted pressure-boundary work, without assuming every potential source holds the necessary certificate.</p>
    <p className={paragraph}>Terminology matters when reviewing older assets. ASME&apos;s <a className={link} href="https://www.asme.org/certification-accreditation/resources-and-events/frequently-asked-questions" target="_blank" rel="noopener noreferrer">certification FAQ</a> explains the modern ASME Certification Mark and notes that the former code-symbol stamps were discontinued in 2013. People may still say “U-stamp,” but the RFQ should describe the actual mark and designator required under the governing edition. The project engineer must also confirm whether the replacement is a new vessel, a modification, or another scope; this guide addresses a new replacement purchase and does not turn an alteration into new construction by wording alone.</p>

    <h2 id="current-duty" className={heading}>Replace the old operating assumption with a current design basis</h2>
    <p className={paragraph}>Provide a current process datasheet: fluid and composition, design and operating pressure and temperature, volume or capacity, required corrosion allowance, cyclic or other special service considerations, and any process internals or separation duty. Those inputs should come from the owner and responsible engineering team. If the plant duty has changed since installation, mark the differences explicitly. A matching external shell can conceal a changed process requirement, material compatibility issue or relief-system interface that the original data report could not anticipate.</p>
    <p className={paragraph}>Define the destination jurisdiction and any project-specific inspection, registration or approval needs early. A certification mark is not a universal import or operating permit. The purchaser must establish local requirements and applicable contract documents. For a broader overview of how different equipment codes are selected, see the <Link className={link} href={postUrl(getPost("pressure-vessels-tanks-and-heat-exchangers-explained")!)}>pressure vessels, tanks and heat exchangers code guide</Link>. It is a companion to this identification checklist, not a substitute for the project specification.</p>

    <h2 id="interfaces" className={heading}>Survey mechanical and site interfaces</h2>
    <p className={paragraph}>Attach the current general arrangement with overall dimensions, orientation, nozzle schedule, flange details, internals, manways, drains, vents, lifting points, support type and foundation connections. Identify transport limits and whether the vessel must pass through an existing access route. Request a site survey when old drawings and reality disagree. Specify whether instruments, valves, platforms, insulation, coating and spare parts are included in the equipment quotation or supplied separately. A “drop-in replacement” claim is not reviewable unless those interfaces are dimensioned and checked.</p>
    <p className={paragraph}>Ask for a drawing-and-deviation matrix that makes each offer easy to compare. A bidder may propose a different support arrangement, nozzle position or material because of its fabrication method; those differences require engineering review before award. The <Link className={link} href={postUrl(getPost("heat-number-traceability-mill-certificates")!)}>heat-number traceability guide</Link> explains how the delivered pressure-boundary materials should connect to mill evidence. Matching an alloy name in a brochure is not the same as linking physical material to the final vessel dossier.</p>

    <h2 id="handover" className={heading}>Specify inspection and handover before comparing prices</h2>
    <p className={paragraph}>Request a proposed drawing list, material records, welding and examination documentation, inspection and test plan, required manufacturer data report, marking evidence, final as-built drawings, preservation and shipping documents. The exact examinations, test basis and witness points follow the governing code, design and purchase specification; buyers should not invent universal acceptance criteria. Use the <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>hold and witness point guide</Link> to decide which review events must be visible in the procurement plan.</p>
    <p className={paragraph}>Compare quotes on the same equipment boundary: vessel shell and internals, accessories, documentation, certification, inspection participation, packing and destination. Ask each bidder to list exceptions and the manufacturing country of the offered unit. Send the identified vessel records, current datasheet, drawings and quantity through Oillinko&apos;s <Link className={link} href="/oil-and-gas/equipment/pressure-vessels-tanks/pressure-vessels-and-separators">pressure vessels and separators enquiry page</Link> for manual review and routing. A sound replacement RFQ makes gaps visible before the buyer commits to a price or delivery promise.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
