import Link from "next/link";
import SiteImage from "@/components/SiteImage";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("pump-shaft-alignment-service-scope-handover")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A request to align a pump and motor does not yet describe a complete service. It may mean checking an installed train, correcting a coupling after motor replacement, or providing final alignment following foundation and piping work. Those jobs differ in access, preparation, shutdown duration and deliverables. The service enquiry should identify the machine, its operating conditions, who can make mechanical corrections and what measurement record will be accepted at handover.</p>
    <p className={paragraph}>The <a className={link} href="https://cdn.skfmediahub.skf.com/api/public/0901d19680536c71/pdf_preview_medium/0901d19680536c71_pdf_preview_medium.pdf" target="_blank" rel="noopener noreferrer">alignment instrument instructions</a> distinguish measurement from correction and include soft-foot checks, thermal-growth considerations and reports. They describe a specific instrument workflow. They do not establish a universal allowable offset for every pump, coupling and operating temperature. The project, equipment and coupling requirements must determine the acceptance target.</p>
    <figure className="mt-8"><SiteImage src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Pump shaft alignment service flow from machine identity and access through baseline checks, correction and signed handover records."/><figcaption className="mt-3 text-sm text-muted">A measurable handover begins with an agreed machine and work boundary.</figcaption></figure>

    <h2 className={heading}>Identify the train and the reason for the work</h2>
    <p className={paragraph}>Provide the pump and driver tags, manufacturer and model, coupling type, shaft speeds, baseplate arrangement and any intermediate gearbox. Include drawings or photographs showing coupling guards, measurement access and nearby piping. Explain whether the unit is new, recently overhauled, moved, or exhibiting vibration or seal problems. This history informs the scope but does not prove that misalignment is the only fault. A vibration concern may require separate condition assessment rather than an alignment-only purchase.</p>
    <p className={paragraph}>State whether the equipment is installed and ready, in a workshop, or awaiting final grouting or pipe connections. Identify which machine is intended to move, available adjustment travel and whether shims, bolts or jacking points are available. If these facts are unknown, ask the service provider to price a survey and a separately authorized correction stage. A fixed price for an unspecified mechanical repair creates an ambiguous change-order boundary.</p>

    <h2 className={heading}>Agree site preconditions and responsibilities</h2>
    <p className={paragraph}>The site owner should confirm isolation, safe access and permit arrangements under its own procedures before measurement or mechanical work. The RFQ should state who removes and replaces guards, disconnects the coupling if needed, supplies lifting support, checks foundation bolts and addresses pipe strain. Do not treat an alignment technician as automatically authorized to alter process piping, coupling components or electrical connections. Describe those tasks explicitly and assign them to competent parties.</p>
    <p className={paragraph}>Ask for a baseline condition record before correction. This can include as-found shaft positions, coupling condition, obvious looseness, available shim packs and soft-foot findings. If the machine moves when its feet are tightened or the piping is connected, a final measurement taken at an earlier configuration may no longer represent the installed condition. Define the sequence of other maintenance tasks so bidders know when to perform the final check and whether a return visit is required.</p>

    <h2 className={heading}>Set the measurement and acceptance basis</h2>
    <p className={paragraph}>Specify the required method or allow an equivalent instrument with documented calibration or verification. Ask for the measurement planes, coupling dimensions and shaft rotation assumptions used by the provider. Distinguish offset from angular misalignment and request as-found and as-left values in units that can be compared with the approved tolerance. A simple statement that the machine was aligned is not enough for later maintenance review.</p>
    <p className={paragraph}>The cold target may differ from the operating target when pump and driver expand differently. If the equipment manufacturer provides thermal growth or hot alignment targets, give them to the bidder; otherwise ask the responsible engineer to establish whether a calculated offset is needed. Do not invent a universal thermal-growth correction. The <Link className={link} href={postUrl(getPost("api-671-couplings-and-baseplate-design")!)}>coupling and baseplate guide</Link> describes related interface questions, while the exact machine tolerance still belongs in the approved specification.</p>

    <h2 className={heading}>Separate diagnosis, correction and restart</h2>
    <p className={paragraph}>Some deviations can be corrected with available shims and adjustment travel; others reveal soft foot, distorted bases, worn couplings or pipe loads beyond the planned service. Ask bidders to state what their base price includes and how they will report a condition that needs additional engineering or parts. The technician should not be assumed to accept responsibility for all surrounding defects simply because an alignment instrument produced readings.</p>
    <p className={paragraph}>Define whether the scope ends with a static as-left alignment report or includes a post-run review, vibration measurement or witness during startup. If a warm recheck is needed, record the operating conditions and who authorizes the second visit. Alignment is one input to reliable operation, not proof of pump performance or seal integrity. The <Link className={link} href={postUrl(getPost("pump-factory-acceptance-testing-and-commissioning-checklist")!)}>pump testing and commissioning guide</Link> distinguishes wider machine acceptance from an individual maintenance measurement.</p>

    <h2 className={heading}>Request a usable handover package</h2>
    <p className={paragraph}>The deliverable should identify the machine tags, date, technician, instrument, measurement setup, baseline and final readings, correction made, soft-foot observations and any unresolved limitation. Record the equipment state during each reading, including whether guards and piping were in their final condition. Ask for a clear exception list and the person who accepted the final result. These records let a later team understand what changed without mistaking an instrument screenshot for a complete work report.</p>
    <p className={paragraph}>For quotation comparison, list mobilization, survey time, expected correction time, return visits, consumables, mechanical repair exclusions and handover format as separate fields. Send the machine identity, approved tolerance and site constraints through Oillinko&apos;s <Link className={link} href="/oil-and-gas/services/equipment-repair-and-overhaul">equipment repair and overhaul service page</Link> for manual review. The service catalogue describes an enquiry route; it does not claim an in-house crew or a completed alignment project.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
