import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("quotation-validity-equipment-lead-time-delivery-milestones")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>Quotation validity tells the buyer how long an offer remains open on its stated terms. Equipment lead time describes the time needed to reach a specified event from a stated starting point. Neither should be interpreted as the other. An offer valid for a month may quote a longer manufacturing period, and a short manufacturing period may depend on approvals that have not yet occurred. The RFQ should make these timelines explicit before the buyer compares prices or promises a project delivery date.</p>
    <p className={paragraph}>The <a className={link} href="https://content.unops.org/service-Line-Documents/Procurement/UNOPS-Procurement-Manual-2021_EN.pdf" target="_blank" rel="noopener noreferrer">UNOPS procurement manual</a> treats bid validity as a period that allows evaluation and award. It is an institutional procurement reference, not a set of commercial terms that automatically governs a private equipment order. The practical lesson for an RFQ is to specify the evaluation window and ask for a clear validity response. The remaining delivery timeline still needs its own scope, starting events and milestone definitions.</p>
    <h2 id="record-offer-validity-with-an-identifiable-expiry" className={heading}>Record offer validity with an identifiable expiry</h2>
    <p className={paragraph}>Ask the bidder to state the quotation reference, revision, issue date and validity basis. A stated calendar expiry is easier to reconcile than a number of days without a start date. If time zones or business-day definitions could affect a deadline, clarify them in the enquiry. Keep the validity requirement beside the commercial comparison so the buyer can see whether an offer will remain available during the planned review and approval process.</p>
    <p className={paragraph}>If evaluation continues beyond the stated validity, request written confirmation of the current offer rather than assuming that the old price and schedule still apply. Ask the bidder to identify any revised terms and issue a clear reference for the extension. An expiry date passing should trigger reconciliation of the offer status in the purchasing record. It should not silently turn an old quotation into a current commitment, particularly where availability or production scheduling was conditional when the offer was first issued.</p>
    <h2 id="define-the-event-that-starts-the-quoted-lead-time" className={heading}>Define the event that starts the quoted lead time</h2>
    <p className={paragraph}>A lead time stated as several weeks is incomplete unless the starting event is clear. Ask whether it runs from order receipt, order acceptance, a defined approval, completion of commercial prerequisites or another stated event. Where several prerequisites apply, ask the bidder to explain their relationship and identify the last unresolved dependency. Record those conditions in the comparison. Do not describe the quotation as offering delivery from today when it actually starts after information or decisions that the buyer has not yet supplied.</p>
    <p className={paragraph}>For example, one bidder may quote a manufacturing period from order acceptance while another starts after an approved drawing is returned. Those periods cannot be compared as if they begin together. The buyer should show the expected time to reach each start event separately, with the assumption owner identified. This produces a useful planning timeline while preserving uncertainty. It also helps the project team decide whether early technical clarification is more valuable than requesting a nominally shorter number of manufacturing weeks.</p>
    <h2 id="distinguish-manufacturing-completion-from-delivery" className={heading}>Distinguish manufacturing completion from delivery</h2>
    <p className={paragraph}>Ask what the end of the quoted period means: completion of fabrication, readiness for inspection, release for packing, availability for collection, dispatch or arrival at a named place. Keep these as separate milestones where they are separate activities. A machine can be physically assembled while required inspection or documentation remains incomplete. Conversely, a ready-for-collection date does not establish the transit duration or destination handover date. The quotation should identify the exact event it is offering.</p>
    <p className={paragraph}>Use the <Link className={link} href={postUrl(getPost("exw-vs-fca-oil-gas-equipment-buyers")!)}>EXW and FCA comparison</Link> to clarify the delivery responsibility boundary, with the agreed rule, named place and version stated in the commercial documents. Do not infer a destination date from a factory readiness estimate. Ask for packing readiness and shipment release information through the <Link className={link} href={postUrl(getPost("export-packing-oil-gas-equipment-rfq")!)}>export packing guide</Link>. These details help the logistics reviewer build a realistic onward plan without changing what the equipment bidder actually quoted.</p>
    <h2 id="identify-approval-and-inspection-dependencies" className={heading}>Identify approval and inspection dependencies</h2>
    <p className={paragraph}>List the drawings, datasheets, inspection plans and other submissions that require review, together with the proposed submission dates and response assumptions. A schedule should identify which approvals are prerequisites to production or release, rather than describing every document as equally critical. Ask who reviews each item and how revisions will be handled. The buyer can then assess the proposed sequence against its actual review capacity and avoid a schedule that depends on approvals no one has planned to provide.</p>
    <p className={paragraph}>Maintain those documents through the <Link className={link} href={postUrl(getPost("equipment-rfq-revision-control-bid-clarifications")!)}>RFQ revision and clarification guide</Link>. If the specification changes during evaluation, ask the bidder to confirm the effect on the offer’s validity, technical scope and timeline together. Do not retain the original lead time beside a revised equipment configuration without confirmation. Inspection and witness arrangements should also be visible in the planning basis where required, with unresolved dates shown as dependencies rather than silently treated as completed steps.</p>
    <h2 id="compare-partial-readiness-and-shipment-options-explicitly" className={heading}>Compare partial readiness and shipment options explicitly</h2>
    <p className={paragraph}>For a multi-item enquiry, request line-level readiness where the bidder can establish it and identify items tied to a shared package or release. Ask whether the quoted date applies to the first item, the last item or the complete order. Where partial shipment is an option, compare the added packing, documentation and logistics implications separately. A faster first shipment is not necessarily a faster complete delivery, and it may not help the site if the missing component is required to use the package.</p>
    <p className={paragraph}>Avoid treating all quoted lead times as guaranteed dates. Identify whether each is indicative, subject to confirmation or offered as a specific commitment under stated terms. Preserve the bidder’s exact status and ask for evidence or clarification appropriate to the decision. The <a className={link} href="https://www.unops.org/business-opportunities/supplier-resource-centre" target="_blank" rel="noopener noreferrer">UNOPS supplier resource centre</a> emphasizes understanding the requirements and solicitation process; for an equipment buyer, that supports asking clear questions before comparing responses. It does not establish the production capacity or availability of any particular supplier.</p>
    <h2 id="turn-the-comparison-into-a-controlled-procurement-timeline" className={heading}>Turn the comparison into a controlled procurement timeline</h2>
    <p className={paragraph}>A useful review record contains the offer expiry, required decision date, lead-time start event, open prerequisites, manufacturing milestone, shipment boundary and planned destination event. Put an owner beside each buyer-controlled action. Keep the expected dates and confirmed commitments distinguishable. If the project requires an earlier date than the offered timeline supports, raise the gap directly for review. A purchasing spreadsheet should not create certainty by subtracting unconfirmed weeks from a required installation date.</p>
    <p className={paragraph}>Oillinko can coordinate a manually reviewed enquiry through the <Link className={link} href="/oil-and-gas/services/freight-expediting-and-project-logistics">freight, expediting and project logistics service page</Link> with the equipment schedule, offered terms and project milestone requirements. Send the latest quotation references and unresolved approvals so the timeline can be reconciled before logistics planning. Before placing an order, agree which offer is current and which delivery event is being accepted. That gives the buyer a clearer commercial decision and a more useful basis for monitoring progress after award.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
