import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost } from "@/lib/blog";

const post = getPost("replacement-electric-motors-nameplate-interface-rfq-guide")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A motor can match the power printed on an existing nameplate and still be the wrong replacement. A different shaft position, mounting pattern, electrical supply or control arrangement can make an apparently suitable offer unusable without redesign. A buyer needs to describe the installed machine and its interfaces, not merely ask for a motor of the same kilowatt rating. The replacement RFQ should turn uncertain identification into explicit questions that bidders can answer in writing.</p>
    <p className={paragraph}>This guide focuses on purchasing a complete replacement electric motor for an industrial machine, including a pump driver. It does not specify a winding repair or authorize an installation. The related <Link className={link} href="/blog/category/oil-and-gas-services/maintenance-repair/electric-motor-rewinding-rfq-tests-data-acceptance-records">motor rewinding RFQ guide</Link> addresses the different question of assessing and repairing the existing unit. Oillinko can coordinate a replacement enquiry, but catalogue coverage is not a claim of available stock, manufacturer appointment or project approval.</p>

    <h2 id="identify-installed-motor" className={heading}>Identify the installed motor and the replacement boundary</h2>
    <p className={paragraph}>Record the equipment tag, motor model and serial number as legibly as possible. Attach photographs of the complete nameplate, motor body, terminal box, mounting feet or flange, shaft end and coupling area. Include the controlled general-arrangement drawing and any earlier modification records. A number copied from an old purchase order may refer to the original machine rather than the one currently installed. Mark each item as observed, documented or assumed so the bidder can distinguish evidence from an unverified memory.</p>
    <p className={paragraph}>State whether the quotation is for the motor alone or also covers a coupling element, adapter, terminal accessories, sensors, space heater or drive changes. If an exact manufacturer model is required by the plant standard, identify that restriction. If alternatives are allowed, request a side-by-side compliance statement and dimensional drawing before calling an offer interchangeable. A substituted motor can affect the driven equipment, its protection settings and the physical work needed to fit it; those interfaces need responsible technical review.</p>

    <h2 id="read-nameplate" className={heading}>Read the nameplate as a set of operating conditions</h2>
    <p className={paragraph}>Capture rated output power, voltage, frequency, phase, full-load current, speed and duty as a connected set of values. A dual-frequency or multi-voltage plate may show different ratings in separate rows; do not mix the power from one row with the speed or current from another. The <a className={link} href="https://new.abb.com/news/detail/132261/how-to-read-a-nema-motor-nameplate" target="_blank" rel="noopener noreferrer">manufacturer&apos;s NEMA nameplate guide</a> explains how rated voltage, frequency, full-load speed and frame information relate to motor selection. It is an example of reading a plate, not a substitute for the actual installed unit&apos;s documentation.</p>
    <p className={paragraph}>Record efficiency class, insulation or thermal information, enclosure marking and ambient limits when present, along with any bearing, brake or sensor details that affect the replacement. Do not infer an absent field from a similar-looking motor. A worn or unreadable plate calls for a controlled identification exercise using drawings, order records and physical measurements. The RFQ should ask bidders to list values they can confirm and assumptions needing approval, rather than quietly treating a guessed rating as a firm requirement.</p>

    <h2 id="mechanical-fit" className={heading}>Confirm mounting, shaft and space before claiming interchangeability</h2>
    <p className={paragraph}>Specify the existing frame or dimensional standard and provide measurements or drawings for foot-hole spacing, shaft height, shaft diameter and extension, keyway, flange register and bolt circle as applicable. Record the mounting orientation, terminal-box position, cable-entry direction and space needed for cooling and maintenance. A familiar frame designation helps narrow the search, but it does not prove that every body, conduit, coupling or guard will clear the installed arrangement. Ask for the offered motor&apos;s certified dimensions and compare the actual interfaces.</p>
    <p className={paragraph}>For an IEC motor, <a className={link} href="https://webstore.iec.ch/en/publication/64225" target="_blank" rel="noopener noreferrer">IEC 60034-7:2020</a> identifies the IM mounting code and terminal-box-position classification. An RFQ should record the required arrangement and the physical details that matter in the plant, rather than assume a code alone settles shaft and cable access. The coupling and baseplate may also require evaluation by the driven-equipment engineer. The <Link className={link} href="/blog/category/oil-and-gas-equipment/pumps-rotating-equipment/api-671-couplings-and-baseplate-design">coupling and baseplate guide</Link> explains why a driver change cannot be reviewed independently of the machine train.</p>

    <h2 id="electrical-control" className={heading}>Match the electrical supply and control arrangement</h2>
    <p className={paragraph}>State the available supply voltage and frequency, the starter or variable-speed-drive arrangement, the applicable project electrical specification and any known starting or load constraints. Request the offered current, speed, efficiency and starting information on the same declared rating basis. Output power on a nameplate is not a complete description of starting behavior or supply compatibility. Any proposed change to protective devices, cables, drive settings or control logic belongs in a separate reviewed scope, not in an assumption buried in the motor price.</p>
    <p className={paragraph}>The current <a className={link} href="https://webstore.iec.ch/en/publication/112762" target="_blank" rel="noopener noreferrer">IEC 60034-1:2026 listing</a> addresses rating and performance, while the <a className={link} href="https://webstore.iec.ch/en/publication/66456" target="_blank" rel="noopener noreferrer">IEC TS 60034-25:2022 listing</a> addresses machine and converter interactions in a power-drive system. Cite the edition specified by the project and ask the electrical specialist to confirm which requirements apply to a line-operated or converter-fed replacement. Merely naming a motor standard does not prove compatibility with the installed drive or its operating range.</p>

    <h2 id="environment-and-approval" className={heading}>Separate environment and approval evidence from the model name</h2>
    <p className={paragraph}>Describe indoor or outdoor location, ambient conditions, washdown or corrosive exposure and the enclosure or cooling arrangement required by the project. Where the installation has a hazardous-area classification, supply its actual design basis and require evidence for the exact offered motor configuration, marking, temperature class and applicable certificate scope. Do not copy an approval symbol from an old nameplate and assume it covers a different model or location. The responsible electrical and area-classification reviewers must evaluate the proposed product.</p>
    <p className={paragraph}>Identify project-specific monitoring requirements such as winding temperature sensors, bearing sensors, space heaters or terminal provisions, but distinguish installed evidence from desired upgrades. A quotation may include the motor yet exclude external monitoring devices or field wiring. Ask the bidder to identify each included item and each interface requiring purchaser work. This makes price comparisons more meaningful and prevents an unpriced accessory or approval gap from appearing only after purchase.</p>

    <h2 id="compare-offers" className={heading}>Request a comparable technical and commercial return</h2>
    <p className={paragraph}>Require an offered datasheet, nameplate schedule, dimensional drawing, connection information, applicable compliance documents and a clear deviations list. Compare the offer against a single RFQ revision: power and duty, rated speed, voltage and frequency, mounting and shaft geometry, control compatibility, environmental requirements, included accessories and documentary evidence. Ask for the manufacturing origin of the proposed product, lead time and the point at which that lead time begins. Do not confuse the distributor&apos;s location with the motor&apos;s country of manufacture.</p>
    <p className={paragraph}>Distinguish product supply from installation, alignment, testing and commissioning. A factory test or catalogue datasheet does not establish readiness of the installed pump or system. The <Link className={link} href="/blog/category/oil-and-gas-equipment/pumps-rotating-equipment/pump-factory-acceptance-testing-and-commissioning-checklist">pump testing and commissioning guide</Link> describes this boundary. Record what is included in packing, spares, warranty documentation and after-sales support, and how deviations will be accepted. A lower price should remain visibly associated with its actual technical and delivery scope.</p>

    <h2 id="send-rfq" className={heading}>Send a replacement request that can be answered</h2>
    <p className={paragraph}>A practical package contains the existing nameplate and photographs, equipment tag, electrical supply and control details, mounting and shaft drawing, environmental and approval requirements, required documents, quantity and delivery destination. Include the driven equipment&apos;s identification and explain any dimensional or electrical constraints that cannot change. If data are missing, ask for an identification stage or written clarification before requesting a firm interchangeable offer. The buyer should not turn uncertainty into an unreviewed specification just to obtain a quick price.</p>
    <p className={paragraph}>Send the package through Oillinko&apos;s <Link className={link} href="/oil-and-gas/equipment/electrical-power/motors-and-variable-speed-drives">motors and variable-speed drives catalogue page</Link> for manual enquiry review. Oillinko can compare responses on the agreed basis and route technical questions to the responsible parties. Final motor suitability, site changes and approval of any exception remain project-specific decisions; an online category listing alone cannot settle them.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
