import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, CheckList, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post=getPost("replacement-heat-exchanger-tube-bundles-rfq")!;
const paragraph="mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading="mt-12 text-xl font-bold";
const link="text-accent underline underline-offset-4";
const faqs=[
  {q:"Can a replacement bundle be ordered from outside dimensions alone?",a:"Outside dimensions are only part of the identification. Provide the approved assembly drawings, equipment identity and process basis, and ask the manufacturer to confirm all retained interfaces and the proposed performance scope."},
  {q:"Does a new bundle increase the exchanger pressure rating?",a:"Do not assume so. The retained equipment and the applicable design basis must be assessed by the responsible engineer. A bundle purchase alone does not establish a revised rating for the complete exchanger."},
  {q:"What if the original drawings are missing?",a:"Request a defined survey and engineering scope before a firm manufacturing commitment. Agree access, records, dimensional verification and approval responsibilities. Keep a preliminary estimate distinct from a confirmed replacement proposal."},
];

export default function Page(){return <>
  <BlogPostHeader post={post}/>
  <Prose>
    <p className={paragraph}>Replacement heat exchanger tube bundles are purchased against an existing assembly, not just a nominal shell diameter. A buyer may have a nameplate photograph and an urgent shutdown date, while the manufacturer needs enough evidence to define what will fit, what duty it must deliver and which parts remain in service. The useful starting point is a controlled enquiry package that separates confirmed information from assumptions. That distinction makes a preliminary quotation easier to develop into an accountable manufacturing proposal.</p>
    <p className={paragraph}>Begin by identifying the decision you are making. Is the requirement an interchangeable spare for an unchanged duty, a response to repeated tube damage, or a proposed capacity change? Each raises different review questions. A replacement order should not conceal an unresolved performance problem or turn an assumed material improvement into an approved redesign. This guide explains what to request from the owner, engineer and manufacturer before comparing offers. It does not provide removal instructions, fabrication dimensions or pressure-test procedures.</p>
    <figure className="mt-8">
      <Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Tube bundle enquiry review connects the existing equipment record to separate fit, duty and acceptance decisions."/>
      <figcaption className="mt-3 text-sm text-muted">The equipment record supports three separate reviews. Agreement on one does not resolve the others.</figcaption>
    </figure>
    <h2 id="identify-the-installed-assembly" className={heading}>Identify the installed assembly and replacement boundary</h2>
    <p className={paragraph}>Collect the exchanger tag, manufacturer, serial number, nameplate information and available assembly drawings. Include revisions and repair records so an old drawing is not mistaken for the present configuration. State whether the requested supply includes the entire bundle, selected internals, gaskets or other replacement parts. Identify the shell, channel and covers intended to remain. Ask the manufacturer to list exclusions explicitly, including engineering, site measurement and any work needed on retained components. The purchase description should identify the deliverable rather than rely on the word complete.</p>
    <p className={paragraph}>Do not assume every shell-and-tube arrangement has a bundle that can be exchanged in the same manner. Have the responsible engineer confirm the construction and replacement concept before committing to a delivery plan. If drawings are missing, obtain a scoped survey proposal that explains what evidence can be established and what remains inaccessible until the equipment is available. Inspection access, isolation and handling belong to the owner&apos;s approved work arrangements. A supplier&apos;s ability to quote from photographs is not evidence that every interface has been verified.</p>
    <h2 id="confirm-bundle-interfaces" className={heading}>Confirm interfaces on a controlled drawing</h2>
    <p className={paragraph}>Ask for a drawing register and an agreed reference revision for the replacement. The review should identify which interfaces must match the retained equipment and which details the supplier proposes to change. Record the source of critical information: an original drawing, a later approved modification or a verified measurement. Where these disagree, resolve the discrepancy before releasing manufacture. An unexplained dimension copied from a worn or damaged component can create a new problem rather than reproduce the intended arrangement.</p>
    <p className={paragraph}>TEMA&apos;s <a className={link} href="https://support.tema.org/images/TEMA_MetricDataSheet2026.pdf" target="_blank" rel="noopener noreferrer">2026 heat exchanger specification sheet</a>{" "}distinguishes tube geometry, tube-to-tubesheet joints, baffles, materials and operating data. That breadth shows why an overall length and diameter are not a full specification. Ask the manufacturer to reconcile the relevant entries with the installed assembly and its drawings. Agree the dimensional inspection report required for acceptance and who approves deviations. The RFQ should name the responsible reviewer instead of leaving drawing approval as an undefined administrative step.</p>
    <h2 id="retain-the-process-basis" className={heading}>Keep thermal duty separate from mechanical fit</h2>
    <p className={paragraph}>Provide the process basis for both sides, including the fluids, required duty and operating cases supplied by the project engineer. Make changed service conditions visible. For example, an illustrative cooling-water system may now receive warmer water than the original design assumed. Ordering a geometrically similar spare would not, by itself, resolve that difference. Ask whether the offer reproduces an approved design or includes a thermal review against current conditions. Any performance commitment needs its stated inputs, exclusions and acceptance basis.</p>
    <p className={paragraph}>Alfa Laval&apos;s <a className={link} href="https://www.alfalaval.com/en-GB/products/heat-transfer/tubular-heat-exchangers/shell-and-tube-heat-exchanger/" target="_blank" rel="noopener noreferrer">shell-and-tube exchanger explanation</a>{" "}describes separate fluid paths and the role of baffles in supporting tubes and directing shell-side flow. This is general background, not confirmation of a particular replacement design. Changes inside an assembly deserve review even when its outside envelope stays the same. Require proposed changes to be identified in the offer, along with the engineering checks and approvals needed. Keep a claimed fit and a claimed duty as separately reviewable commitments.</p>
    <h2 id="materials-and-condition" className={heading}>Resolve material changes and the reason for replacement</h2>
    <p className={paragraph}>Supply available inspection findings and the reason the old bundle is being replaced. Distinguish documented damage from a suspected cause and attach the relevant reports rather than diagnosing the failure through the RFQ title. Ask the engineer whether the replacement basis remains unchanged or needs further investigation. A new material proposal should explain its scope and consequences for the complete assembly. A more expensive alloy is not automatically the right response to a problem whose mechanism has not been established.</p>
    <p className={paragraph}>Specify the required material identification and records for the purchased components, including how they will connect to the final assembly. Keep commercial descriptions such as stainless steel distinct from the approved grades and manufacturing requirements. The <Link className={link} href={postUrl(getPost("en-10204-material-certificates-explained")!)}>material certificate guide</Link>{" "}explains the evidence question. Ask which existing parts the proposal assumes are reusable and who assesses them. A new bundle does not establish the condition or a higher pressure rating of the shell and other retained pressure-containing parts.</p>
    <h2 id="acceptance-and-project-requirements" className={heading}>Agree acceptance evidence before fabrication</h2>
    <p className={paragraph}>State the project&apos;s applicable code, standard editions and supplementary requirements, with their applicability confirmed by the responsible engineer. <a className={link} href="https://tema.org/standards/" target="_blank" rel="noopener noreferrer">TEMA currently lists its 2026 edition</a>; naming the association alone leaves the contractual basis unclear. Preserve the installed equipment records and ask how the proposed replacement relates to them. Do not infer certification or manufacturer authorization from a quotation that merely mentions a standard. Obtain the specific evidence required for the agreed scope.</p>
    <p className={paragraph}>Define the inspection and test plan, document review points and release responsibilities before work begins. Specify what the final dossier must demonstrate, while leaving test methods and conditions to the approved technical requirements. The <Link className={link} href={postUrl(getPost("third-party-inspection-tpi-oil-and-gas-equipment")!)}>third-party inspection guide</Link>{" "}helps frame witness and reporting responsibilities. Separate dimensional acceptance, material evidence and any agreed performance verification. A satisfactory result in one category does not establish the others. Identify whether installation checks are excluded from the supply contract and how remaining actions will be handed over.</p>
    <h2 id="compare-the-complete-proposal" className={heading}>Compare engineering milestones as well as delivery dates</h2>
    <p className={paragraph}>Ask when the delivery period starts: purchase order, receipt of missing data or approval of manufacturing drawings. Separate material availability, engineering approval, fabrication, inspection and dispatch milestones. If a turnaround is approaching, expose unresolved dependencies before treating a quoted number of weeks as a firm arrival date. Include preservation, packing and transport scope using the <Link className={link} href={postUrl(getPost("export-packing-oil-gas-equipment-rfq")!)}>equipment export packing checklist</Link>. Keep site extraction, installation and commissioning responsibilities distinct from factory supply.</p>
    <p className={paragraph}>Send the equipment identity, drawings and process basis through the <Link className={link} href="/oil-and-gas/equipment/pressure-vessels-tanks/shell-and-tube-heat-exchangers">shell-and-tube heat exchanger enquiry page</Link>. If condition assessment points toward repair instead, describe that requirement through <Link className={link} href="/oil-and-gas/services/heat-exchanger-cleaning-and-retubing">heat exchanger cleaning and retubing enquiries</Link>. Oillinko receives and reviews these requests for manual sourcing coordination. The selected provider confirms engineering, availability and the contracted scope. Compare the complete proposal, including assumptions and open decisions, before selecting an offer on price or promised speed.</p>
    <CheckList items={["Equipment identity and controlled drawing revisions","Replacement boundary and retained-component assumptions","Verified interfaces and deviation approval","Current process basis and performance scope","Material requirements and traceable evidence","Inspection plan, release records and site exclusions","Engineering milestones, delivery basis and packing"]}/>
    <Faq faqs={faqs}/>
  </Prose>
  <RelatedPosts post={post}/>
  <JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post),faqJsonLd(faqs)]}/>
  <CtaBand/>
</>;}
