import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("replacement-bearing-rfq-full-designation-suffixes")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <div className="-mt-4 mb-8 text-sm text-muted">An original conceptual illustration of the product, package and document link; it does not identify a specific bearing model.</div>
    <p className={paragraph}>A replacement bearing enquiry often starts with a photograph, a few readable characters and a request for urgent delivery. That is useful evidence, but it may leave the actual variant unresolved. The purchasing task is to connect the installed equipment, the complete bearing identity and the supplier&#x27;s proposed scope. A familiar size or a matching series number should not become an approval by default. This guide sets out the information buyers can collect and the questions they can put into a quotation request before a technical reviewer decides whether the offered replacement is acceptable.</p>
    <h2 id="keep-the-original-identification-evidence" className={heading}>Keep the original identification evidence</h2>
    <p className={paragraph}>Record the machine tag, manufacturer, model and serial number alongside the bearing&#x27;s position in the assembly. Use the approved parts list, drawing item number and maintenance records when available. Label each photograph with the equipment and position it belongs to. If several bearings have been removed, avoid sending an unlabelled collection of photographs: a supplier may otherwise associate the clearest marking with the wrong assembly location. Keep the original photograph even after transcribing its text, because punctuation and faint characters can affect the identification.</p>
    <p className={paragraph}>Transcribe every visible character, including prefixes, suffixes, separators and any additional references. Record an unreadable character as uncertain instead of guessing it. Photograph the packaging label too, when the packaging is known to belong to that bearing. The <a className={link} href="https://www.skf.com/binaries/pub12/Images/0901d196807026e8-100-700_SKF_bearings_and_mounted_products_2018_tcm_12-314117.pdf" target="_blank" rel="noopener noreferrer">SKF bearing catalogue</a>, printed page 4, explains that supplementary designations identify components or variants, and that the complete designation on a package can be longer than the marking on the product. This manufacturer example supports retaining both records; it does not establish that an old box belongs to the removed component.</p>
    <h2 id="separate-identification-from-the-approved-replacement-basis" className={heading}>Separate identification from the approved replacement basis</h2>
    <p className={paragraph}>The bearing currently installed is evidence of what was found, not necessarily proof of what the equipment requires. It may have been changed during an earlier repair, and the current parts list may describe a different revision. Show those conflicts explicitly. An RFQ can say that a marking was observed on the removed item while the approved parts list specifies another reference. Ask the supplier to explain the identification basis it used and leave the discrepancy open for the responsible engineer to resolve.</p>
    <p className={paragraph}>For a pump overhaul, the broader <Link className={link} href={postUrl(getPost("centrifugal-pump-spare-parts-rfq-identification")!)}>centrifugal pump spare-parts identification guide</Link> helps connect the component to the installed machine. For a motor replacement or repair, the <Link className={link} href={postUrl(getPost("replacement-electric-motors-nameplate-interface-rfq-guide")!)}>motor nameplate and interface guide</Link> provides related equipment context. Neither equipment description replaces a complete bearing designation. In the RFQ, place the equipment reference and the component reference in separate fields so the bidder can confirm both without treating one as a substitute for the other.</p>
    <h2 id="ask-for-the-meaning-of-the-offered-variant" className={heading}>Ask for the meaning of the offered variant</h2>
    <p className={paragraph}>Request the complete proposed manufacturer designation on every quotation line, rather than accepting a shortened internal stock code. Ask the bidder to identify the relevant product document and explain any difference between the requested and offered references. Where applicable, the comparison should address closure arrangement, internal-clearance designation, cage, lubrication specification, precision and other features identified in the equipment requirement. These are questions for the supplier and technical reviewer; they are not a recommendation to choose a particular configuration from a generic checklist.</p>
    <p className={paragraph}>Do not transfer a suffix explanation from one manufacturer&#x27;s catalogue to another without supporting documentation. Also avoid deleting unfamiliar characters because the basic number appears to match. A useful quotation distinguishes an exact requested reference, an officially documented superseding reference and a proposed alternative. Require the evidence for the selected description. A cross-reference entry can help identify a candidate, but the purchase file should still show what has been compared, what remains unverified and who is responsible for accepting a difference.</p>
    <h2 id="define-pieces-sets-and-associated-components" className={heading}>Define pieces, sets and associated components</h2>
    <p className={paragraph}>State whether the quantity means individual bearings, complete sets or assembled units. If the equipment documentation calls for a matched set, preserve that wording and reference in the enquiry. Ask the bidder to state how the offered set is identified and supplied. Do not allow a quotation for two separate stock pieces to be treated silently as a quotation for an identified set. The article does not prescribe pairing, preload, adjustment or installation; those requirements belong to the approved equipment and manufacturer documentation.</p>
    <p className={paragraph}>List associated items separately when they are required: a housing, sleeve, locking component, seal or other accessory should not be assumed to accompany a bare bearing. Ask for the contents of any kit, including quantities and exclusions. For example, an overhaul request might require one bearing arrangement for each of two machines, but the supplier&#x27;s price could cover only one component in each arrangement. A line-by-line scope comparison exposes that difference before the buyer compares totals or places an order.</p>
    <h2 id="make-alternatives-and-commercial-assumptions-visible" className={heading}>Make alternatives and commercial assumptions visible</h2>
    <p className={paragraph}>Use separate quotation columns for the requested designation, offered designation, quantity, supporting document and deviation. Ask the bidder to state whether its proposal is based on stock it has identified or future production, and to give a lead time appropriate to that basis. Request currency, unit and total prices, quotation validity, delivery term and named dispatch location. Where manufacturing origin is required, ask for the actual country of manufacture of the offered product; the seller&#x27;s office or dispatch warehouse is a different fact.</p>
    <p className={paragraph}>An urgent lead time should not close an unresolved technical question. If an alternative can arrive sooner, record it as a separate option with its outstanding review points. The buyer can then compare the time advantage against the evidence still needed. Avoid rewriting the original RFQ reference to match the quickest offer, because doing so obscures the change from later reviewers. Keep the requested basis, the proposed change and the approval record together throughout quotation review and purchasing.</p>
    <h2 id="plan-the-receiving-check-before-ordering" className={heading}>Plan the receiving check before ordering</h2>
    <p className={paragraph}>Agree which identification and supply documents must accompany the goods, using the purchase specification rather than inventing a universal certificate requirement. At receipt, compare the order, supplier documents, package label and accessible product markings. Record quantities and preserve the association between each package and its documents. If a reference is incomplete or differs from the approved order, document the discrepancy and obtain clarification before releasing the item through the project&#x27;s normal acceptance process. A photograph or certificate alone should not be presented as conclusive proof of authenticity or suitability.</p>
    <p className={paragraph}>Send the equipment references, photographs, approved part requirement, quantities and open questions through Oillinko&#x27;s <Link className={link} href="/oil-and-gas/equipment/pumps/seals-couplings-and-bearings">seals, couplings and bearings enquiry page</Link>. Requests are reviewed and routed manually through <Link className={link} href="/">Oillinko</Link>. The practical objective is a quotation whose identity, scope and exceptions can be checked by the buyer and responsible engineer. Complete identification makes that review more useful; it does not replace the engineering decision or the manufacturer&#x27;s instructions for the actual machine.</p>
  </Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
