import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("rotating-equipment-vibration-survey-scope-baseline-records")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A request to check vibration on ten pumps leaves several commercial and technical questions open. Does the assignment cover ten individual machines or ten complete motor-pump trains? Is it a screening survey, a diagnostic investigation or the start of a recurring monitoring route? Which operating conditions will be available? A service enquiry should define the expected decision and evidence before suppliers estimate attendance, equipment and analysis time.</p>
    <p className={paragraph}><a className={link} href="https://www.iso.org/standard/21831.html" target="_blank" rel="noopener noreferrer">ISO 13373-1:2002 general procedures</a> addresses vibration measurement and data collection for condition monitoring, including measurement parameters, sensor selection and attachment, operating conditions and monitoring arrangements. Its public scope helps organize an enquiry, but does not provide an acceptance limit for every machine. The following checklist is procurement guidance; measurement methods and machine assessment must be agreed with competent personnel using the applicable project requirements.</p>
    <h2 id="identify-the-train-and-the-reason-for-the-survey" className={heading}>Identify the train and the reason for the survey</h2>
    <p className={paragraph}>Provide an asset list with tags, machine type, manufacturer and model where known, rated and actual speed, drive arrangement and principal components. Identify motors, couplings, gearboxes and driven equipment within each train. Include bearing references and available drawings if detailed diagnosis is required. A quoted price per machine is difficult to compare unless both parties count the same assets and measurement coverage. Separate accessible assets from those needing special preparation or a later visit.</p>
    <p className={paragraph}>Describe the trigger without presenting an unverified fault as a conclusion. Examples include a change after overhaul, an unexplained trend, an acceptance survey or a request to establish condition history. Supply maintenance records and previous measurements with their dates and operating context. Explain whether the service should identify suspected causes, recommend further checks or only collect data. Repair, balancing and alignment are separate scopes, even when the survey may recommend them; see the <Link className={link} href={postUrl(getPost("pump-shaft-alignment-service-scope-handover")!)}>shaft alignment service guide</Link> for that boundary.</p>
    <h2 id="state-the-operating-states-that-will-be-available" className={heading}>State the operating states that will be available</h2>
    <p className={paragraph}>Give the speed range, normal loads and relevant process conditions, and identify which conditions can be recorded during the visit. Measurements at different speeds or loads may not be directly comparable. If a variable-speed train cannot run at the required state, ask the provider to explain the effect on the assignment and reporting. The site remains responsible for operating the equipment within its approved procedures; a survey purchase should not authorize the service provider to change plant conditions independently.</p>
    <p className={paragraph}>Record site constraints such as access permits, escort, hazardous-area requirements, environmental exposure and the condition of guards or measurement access. Ask what information and safe preparation the provider needs before mobilization. Any restricted measurement location should be identified in the proposed coverage rather than omitted silently. Agree how unavailable assets, delayed operating windows and additional attendance will be recorded and priced. These details often explain a difference between a short screening visit and a more extensive investigation.</p>
    <h2 id="agree-repeatable-points-and-measurement-settings" className={heading}>Agree repeatable points and measurement settings</h2>
    <p className={paragraph}>Request a measurement-point schedule or annotated asset sketch. It should distinguish locations and directions, the signal quantity and units, and the proposed sensor and mounting arrangement. Ask the provider to identify relevant acquisition settings and the reason for choosing them. The delivered record should contain enough information for later measurements to be compared on a consistent basis. A number without its units, location and acquisition context has limited value when the site tries to build a trend.</p>
    <p className={paragraph}>Clarify whether the deliverables include overall readings, spectra, time records or additional analysis selected for the particular machine question. An overall level can support screening, but does not by itself establish a specific fault. <a className={link} href="https://evolution.skf.com/us/vibrations-help-find-faulty-components-3/" target="_blank" rel="noopener noreferrer">SKF guidance on vibration interpretation</a> describes comparison with earlier readings and machines operating under similar conditions, as well as the additional information in frequency analysis. Ask for the evidence behind conclusions and avoid buying a guaranteed diagnosis from a predefined list of readings.</p>
    <p className={paragraph}>For a recurring route, define naming conventions, file formats and how the collected data will be returned. Existing systems may use particular sensor interfaces or analysis formats; confirm compatibility before assuming a new survey can extend the old history. Include instrument identification and evidence of suitability or calibration where required by the agreed method. If the provider proposes to install permanent sensors, treat installation, hardware and integration as an additional reviewed scope rather than an implicit part of a portable survey.</p>
    <h2 id="separate-the-baseline-from-the-evaluation-criterion" className={heading}>Separate the baseline from the evaluation criterion</h2>
    <p className={paragraph}>A baseline is a reference record collected in a stated condition. It is not automatically proof that the machine was healthy or that its design was acceptable. Supply any verified commissioning or post-repair records, and describe what is known about the condition at that time. If no useful baseline exists, the provider should state that limitation and identify the proposed comparison method. A first survey can establish an initial record without claiming to reconstruct the missing operating history.</p>
    <p className={paragraph}>Ask which evaluation documents and machine-specific criteria will be used, with edition, applicability and agreed responsibility for interpretation. Do not copy a threshold from another equipment class or assume that one general standard supplies every required limit. Distinguish the survey findings from permission to continue operation or approval of a repair. If the assignment follows an overhaul, link the evaluation to the accepted work and test basis described in the <Link className={link} href={postUrl(getPost("electric-motor-rewinding-rfq-tests-data-acceptance-records")!)}>motor repair and acceptance guide</Link>.</p>
    <p className={paragraph}>For example, a survey taken after an overhaul at one speed should not be presented as a directly comparable improvement over an earlier reading taken at another speed without explanation. Retain both records and their operating conditions, then ask the reviewer which comparison is technically meaningful. If the site needs a future recurring trend, the enquiry can include preparation of a repeatable route and an initial reference dataset. That deliverable is more useful than a single reassuring status label whose measurement basis cannot be reproduced at the next visit.</p>
    <h2 id="make-the-report-useful-for-the-next-decision" className={heading}>Make the report useful for the next decision</h2>
    <p className={paragraph}>Require a report that connects each finding to an asset, point, date, operating condition and underlying result. It should identify unavailable measurements, changes from the agreed route, assumptions and confidence limits on the diagnosis. Separate observed evidence from suspected causes and recommended further investigation. Ask for priority and justification rather than a color-coded status alone. The owner can then decide whether further inspection, operational review or a separately scoped maintenance activity is warranted.</p>
    <p className={paragraph}>Agree the delivery date, review meeting, data retention and whether one clarification round is included. Request the editable or native data needed by the existing maintenance system alongside the readable report, subject to agreed access and licensing. Compare quotations by asset coverage, available states, methods, analysis depth, mobilization and records. Use Oillinko for manual coordination of the service requirement, and consult the <Link className={link} href="/oil-and-gas/equipment/instrumentation-control/vibration-and-machinery-monitoring">vibration and machinery monitoring equipment page</Link> when hardware interfaces also need review. No catalogue entry demonstrates a booked team or a confirmed diagnostic outcome.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
