import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("rotor-balancing-service-rfq-configuration-tolerances-reports")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A rotor balancing quotation should identify what will be balanced, in which configuration, against what tolerance and with what report. A price for balancing a rotor is difficult to compare when one bidder includes a complete assembled unit and another assumes a bare shaft. Start with the equipment identity and the approved acceptance basis. Then define the physical scope and evidence that the service provider must return with the actual component.</p>
    <p className={paragraph}>The enquiry may concern a new component, a repaired rotor or an installed machine with a reported vibration concern. Keep those starting points distinct. An observation of high vibration is not itself a confirmed diagnosis of unbalance. If the cause is uncertain, request a defined diagnostic assessment before assuming that a balancing intervention will resolve it. Record any existing inspection findings and operating data as evidence, with their source and date.</p>
    <h2 id="identify-the-delivered-rotor-configuration" className={heading}>Identify the delivered rotor configuration</h2>
    <p className={paragraph}>Supply the equipment tag, component reference, drawing revision, approximate dimensions and mass, plus photographs of the delivered assembly. List mounted parts included in the balancing configuration and components that will be removed or fitted later. Describe how keyways, keys, couplings and other relevant interfaces are to be represented, using the approved equipment instructions. Where the required convention is unknown, make it a clarification item rather than leaving the provider to assume it.</p>
    <p className={paragraph}>For a repaired rotor, identify which work precedes balancing and which work follows it. A report should remain connected to the condition of the item actually tested. Ask how later changes to the assembly will be controlled and whether another check is included. Keep the incoming condition record, repair reference and final configuration together. This gives the purchaser a way to investigate a mismatch without treating every certificate carrying the equipment name as equivalent.</p>
    <h2 id="separate-workshop-field-and-specialist-scopes" className={heading}>Separate workshop, field and specialist scopes</h2>
    <p className={paragraph}>State whether the request is for a workshop service on a removed rotor or work on equipment at site. Ask the provider to describe the proposed arrangement and the information needed to assess applicability. The <a className={link} href="https://www.schenck-rotec.com/en-de/service/balancing-service" target="_blank" rel="noopener noreferrer">Schenck balancing service overview</a> distinguishes several service types, including high-speed work for shaft-elastic rotors. Its scope illustrates why a generic balancing label should not be read as a promise that every workshop can handle every rotor configuration.</p>
    <p className={paragraph}>For workshop work, clarify transport, reception inspection, storage and responsibility for fixtures or special adapters. For a site assignment, describe access, equipment availability and which party provides plant coordination. Request an agreed work plan from the responsible technical parties. Do not turn the RFQ into instructions for running machinery or applying correction weights. The supplier should identify the service boundary and exclusions before the buyer compares a workshop price with a field-service allowance.</p>
    <h2 id="establish-the-approved-tolerance-basis" className={heading}>Establish the approved tolerance basis</h2>
    <p className={paragraph}>The <a className={link} href="https://www.iso.org/standard/54074.html" target="_blank" rel="noopener noreferrer">public abstract for ISO 21940-11:2016</a> identifies a standard for rotors with rigid behaviour, covering permissible residual unbalance, correction planes, allocation to tolerance planes and balancing errors. It directs flexible-behaviour rotor work to Part 12 and lists Amendment 1:2022. The public description establishes document scope; it does not select the tolerance, speed or procedure appropriate to an unidentified rotor.</p>
    <p className={paragraph}>Provide the equipment specification and approved standard edition, including applicable amendments. Supply operating speed information and the rotor classification determined by the responsible engineer. Ask the bidder to identify the acceptance requirement used and the basis for any proposed alternative. A familiar balance quality grade should not be inserted as a default simply because it appears on an earlier order. The project must confirm that the requirement applies to this rotor and service.</p>
    <h2 id="make-the-report-comparable" className={heading}>Make the report comparable</h2>
    <p className={paragraph}>Request a report identifying the component, configuration, date, service location and provider reference. Agree which initial and final results will be recorded, their units and the relationship between reported planes and the assembly drawing. The report should state the permissible values used for acceptance and the final result against them. If only a pass statement is offered, ask what supporting data is available and whether it satisfies the purchase specification.</p>
    <p className={paragraph}>Have the provider explain how its measurement and checking arrangement supports the claimed result, including relevant equipment identification and verification records where required. Keep a documented residual-unbalance result distinct from a general statement about reduced vibration. If additional measurements are requested on the installed machine, define those conditions and acceptance criteria separately. A workshop result should not be presented as proof of performance in a different configuration or under an unspecified operating condition.</p>
    <h2 id="separate-balancing-from-other-acceptance-decisions" className={heading}>Separate balancing from other acceptance decisions</h2>
    <p className={paragraph}>Identify whether dimensional inspection, runout checks, NDT, repair or an overspeed test belongs in the service package. Each requested activity needs its own scope and acceptance basis. Do not assume that a balancing price includes them, or that successful balancing establishes their results. The <Link className={link} href={postUrl(getPost("rotating-equipment-vibration-survey-scope-baseline-records")!)}>rotating equipment vibration survey guide</Link> helps specify diagnostic records when the enquiry begins with a machine condition concern rather than a defined workshop balancing requirement.</p>
    <p className={paragraph}>Likewise, keep alignment and reinstallation requirements visible. The <Link className={link} href={postUrl(getPost("pump-shaft-alignment-service-scope-handover")!)}>shaft alignment service guide</Link> addresses a separate set of interfaces and handover questions. If a broader overhaul is planned, the purchase should distinguish completion of each workshop activity from authorization to return equipment to service. Acceptance of a balancing report does not automatically release the complete machine, its auxiliaries or the surrounding installation.</p>
    <h2 id="control-corrections-and-unexpected-findings" className={heading}>Control corrections and unexpected findings</h2>
    <p className={paragraph}>Ask which proposed corrections need approval before work begins, with reference to the equipment owner&apos;s instructions and component drawings. Identify restrictions on modifying critical features and the process for reporting defects or missing information. The contractor should describe its proposal for technical review, without the purchaser prescribing a correction method from generic guidance. A repair authorization and a balancing authorization should remain distinguishable when the incoming item requires work beyond the original enquiry.</p>
    <p className={paragraph}>Agree how additional work will be priced and approved, and how a halted assignment will be documented. A useful exception report records the affected component, observation, supporting evidence and decision needed. It should not silently replace the original acceptance requirement with a more convenient one. For electric machinery, the <Link className={link} href={postUrl(getPost("electric-motor-rewinding-rfq-tests-data-acceptance-records")!)}>motor rewinding RFQ guide</Link> provides complementary questions for a repair package whose electrical checks and balancing records require separate review.</p>
    <h2 id="compare-the-complete-service-and-handover" className={heading}>Compare the complete service and handover</h2>
    <p className={paragraph}>Compare each offer against the same delivered configuration, approved tolerance basis, proposed service location and reporting scope. Show handling, fixtures, inspection, corrections, witness attendance and return packing as identifiable inclusions or exclusions. Clarify whether lead time begins with receipt of the rotor or receipt of complete approved data. If the configuration or technical requirement is still unresolved, retain the quotation&apos;s provisional status instead of ranking it as an unconditional complete service.</p>
    <p className={paragraph}>Use Oillinko&apos;s <Link className={link} href="/oil-and-gas/services/equipment-repair-and-overhaul">equipment repair and overhaul service page</Link> to submit the rotor records, planned work and reporting requirements for manual coordination. The enquiry should make the desired deliverable concrete: an identified component in an agreed configuration, accompanied by results that can be assessed against the approved requirement. Final equipment release remains with the responsible parties reviewing the complete repair, installation and operating readiness scope.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
