import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("rupture-disc-replacement-rfq-burst-temperature-holder")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A replacement rupture disc enquiry often starts with a photograph of a tag and a request for the same size and pressure. Those details help identify the requirement, but they do not describe the complete assembly or establish that another disc is interchangeable. A useful RFQ connects the installed item, the approved pressure-protection basis and the supplier&apos;s proposed replacement. It also distinguishes a replacement disc from a new holder, signaling accessories and other parts of the supply.</p>
    <p className={paragraph}>The buyer&apos;s task is to make that information reviewable. Selecting a burst condition or changing a relief arrangement remains an engineering decision. This guide sets out a procurement record, not a sizing method or installation procedure. If the existing identification is incomplete, preserve the uncertainty in the enquiry and request an identification review. Do not turn a damaged label, an unavailable part or a short delivery requirement into permission to select a different protection setting.</p>
    <h2 id="identify-the-installed-disc-and-the-supply-boundary" className={heading}>Identify the installed disc and the supply boundary</h2>
    <p className={paragraph}>Collect legible photographs of the disc identification and holder markings where these can be obtained under the site&apos;s normal access controls. Add the equipment tag, previous purchase reference, part number, manufacturer, drawing revision and any surviving certificate. Keep the original files alongside the transcription so that a reviewer can distinguish an observed marking from a buyer&apos;s interpretation. A question mark in the record is more useful than a guessed suffix that sends the enquiry toward the wrong assembly.</p>
    <p className={paragraph}>State whether the quotation is for spare discs only, a complete disc-and-holder assembly, or an identified set of replacement accessories. List each scope separately with its quantity. For an existing holder, ask the bidder to confirm the proposed disc&apos;s compatibility with that exact holder reference. Do not infer compatibility from a common nominal diameter. The <a className={link} href={"https://rembe.de/en/forward-acting-rupture-discs/odv"} target="_blank" rel="noopener noreferrer">REMBE ODV product information</a> illustrates why this matters: it describes different seating and holder arrangements, with application-specific alternatives. That is product evidence, not a universal interchangeability rule.</p>
    <h2 id="keep-pressure-and-temperature-together-in-the-requirement" className={heading}>Keep pressure and temperature together in the requirement</h2>
    <p className={paragraph}>Transmit the approved specified burst pressure with its associated temperature and units, preserving the pressure reference used in the source document. Record the normal and other relevant operating cases separately, including process medium, phase and the engineering description of any vacuum, back-pressure or cycling exposure. If a datasheet and a tag disagree, identify both references and request a resolved engineering basis before treating the quotation as technically accepted. Do not silently substitute an operating pressure for the specified burst condition.</p>
    <p className={paragraph}><a className={link} href={"https://my.fike.com/phoenix/api/files/download/?did=6183"} target="_blank" rel="noopener noreferrer">Fike&apos;s Graphite Rupture Disc Series datasheet</a> links the requested burst pressure to the requested temperature and separately describes rupture tolerance. This supports keeping those fields together in a purchase enquiry; it does not establish the correct values for another product or system. Where a supplier proposes a different rating temperature, ask for the change to be explained against the approved requirement. The related <Link className={link} href={postUrl(getPost("api-526-pressure-relief-valves-rfq-guide")!)}>pressure-relief valve RFQ guide</Link> covers the wider distinction between a purchasing specification and the underlying relief-system design.</p>
    <h2 id="compare-declared-tolerances-without-combining-unlike-terms" className={heading}>Compare declared tolerances without combining unlike terms</h2>
    <p className={paragraph}>Ask each bidder to state the specified and proposed marked burst conditions, the manufacturing design range where applicable, the burst tolerance and the basis of any operating-ratio claim. These should be separate entries in the technical comparison. REMBE&apos;s ODV data lists manufacturing design range, burst tolerance and operating ratio independently. Copying one percentage into a generic tolerance column would lose that distinction. Request the definitions applicable to the offered product instead of assuming every catalogue expresses the terms on the same basis.</p>
    <p className={paragraph}>A practical bid comparison can use columns for the requirement reference, offered value, supporting document and unresolved exception. For example, a quotation might identify the disc model and nominal size but omit the tolerance document. Record that as missing evidence rather than marking the whole line compliant. Keep numerical evaluation with the responsible technical reviewer. A procurement table can expose the unanswered question without calculating a new setpoint or converting an unverified catalogue value into an acceptance limit.</p>
    <h2 id="review-interfaces-and-proposed-changes-as-an-assembly" className={heading}>Review interfaces and proposed changes as an assembly</h2>
    <p className={paragraph}>Request a drawing or other suitable identification evidence showing the proposed assembly and its connection details. Compare holder references, flange standard and facing, material specification and accessory interfaces against the enquiry. The <Link className={link} href={postUrl(getPost("asme-b16-5-flange-pressure-classes")!)}>flange pressure-class guide</Link> can help organize the connection record, but a matching flange designation alone does not prove that the internal seating arrangement is suitable. Ask the supplier to identify what is retained from the installed assembly and what must change with the proposed replacement.</p>
    <p className={paragraph}>Treat an obsolete-part replacement as a documented alternative. Ask for the superseded and replacement references, the manufacturer&apos;s explanation of the change and a clear list of affected parts. If a burst-indication device is included, identify its reference and required signal interface separately. Avoid accepting a general phrase such as complete equivalent when the bidder has not described the supplied components. Any proposed change should remain conditional until the authorized reviewer has assessed its effect on the existing protection arrangement.</p>
    <h2 id="define-the-records-needed-before-release-and-at-receipt" className={heading}>Define the records needed before release and at receipt</h2>
    <p className={paragraph}>The document schedule should identify which approvals are needed before manufacture or dispatch and which records accompany the goods. Request the product identification, batch or lot references and the certification or test evidence required by the applicable purchase specification. Ask for the actual country of manufacture rather than the distributor&apos;s address. A sample certificate can demonstrate a reporting format, but the final handover record must identify the supplied items. Keep any requested witness or review point explicit in the quotation scope.</p>
    <p className={paragraph}>Consider a shipment split across two production lots. The receiving record should show which quantity belongs to each lot and where its supporting records are stored. If cartons carry different identifiers from the packing list, resolve that link before distributing the spares into several stores. This is an example of a traceability control, not a claim about a supplier&apos;s normal packaging. Preserve the manufacturer&apos;s protective packaging and handling information, and route damaged or inconsistent deliveries through the agreed receiving process.</p>
    <h2 id="compare-the-complete-quotation-before-placing-an-order" className={heading}>Compare the complete quotation before placing an order</h2>
    <p className={paragraph}>Separate disc prices, holder prices, accessories and documentation charges so that a low unit price does not hide a different supply boundary. Request quotation validity, quantity breaks where relevant, lead-time starting conditions and the named dispatch or delivery point. Record any statement that drawings become available only after an order. That commercial condition should be visible to the buyer because it may leave an interface review incomplete at the proposed commitment date. Do not describe the product as approved merely because a quotation has arrived.</p>
    <p className={paragraph}>Use <Link className={link} href={postUrl(getPost("equipment-rfq-revision-control-bid-clarifications")!)}>revision control</Link> to keep the enquiry, supplier clarification and final accepted scope aligned. Oillinko&apos;s <Link className={link} href={"/oil-and-gas/equipment/valves/rupture-discs-and-holders"}>rupture discs and holders catalogue page</Link> provides a route for submitting the available identification and specification for manual review. The <Link className={link} href={"/"}>Oillinko homepage</Link> also explains the broader sourcing scope. A strong enquiry ends with a traceable requirement, a clearly identified offer and a record of the remaining decisions. That lets the buyer progress the commercial discussion while preserving the engineering authority responsible for the pressure-protection system.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
