import Image from "next/image";
import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, Faq, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd, faqJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("seawater-pressure-reducing-valves-offshore-rfq-guide")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";
const faqs = [
  { q: "Is a pressure reducing valve the same as a pressure relief valve?", a: "No. A reducing valve controls downstream pressure during normal flow. A relief device addresses a defined overpressure scenario. Their duties, sizing bases and acceptance evidence differ." },
  { q: "Are inlet and outlet pressures enough to select a seawater reducing valve?", a: "No. The responsible engineer also needs flow cases, temperature, seawater chemistry, allowable pressure variation, connection data and any cavitation or noise limits." },
  { q: "Does a Super Duplex body prove that the whole assembly suits seawater?", a: "No. The pilot, trim, tubing, fasteners, diaphragms, seals and other wetted parts need a documented material and compatibility review." },
];

export default function Page() {
  return <>
    <BlogPostHeader post={post}/>
    <Prose>
      <p className={paragraph}>A seawater pressure reducing valve enquiry needs more than a nominal pipe size and two pressure numbers. The buyer is purchasing a pressure-control assembly that must hold the required downstream condition over a defined range of flows and inlet pressures. Seawater adds a material-selection problem: the body may be corrosion resistant while a pilot, spring, tubing connection or fastener is not. The best RFQ makes the complete duty and the evidence expected from the bidder visible before prices are compared.</p>
      <p className={paragraph}>This guide is for procurement preparation, not for setting a valve in service or approving a piping design. The project engineer should establish the operating envelope, required downstream pressure, material basis, installation constraints and acceptance criteria. The manufacturer then selects and documents the proposed model against that approved basis. Any proposed alternative should identify its differences rather than relying on a broad “marine suitable” description.</p>
      <figure className="mt-8"><Image src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Seawater pressure reducing valve RFQ flow from operating envelope through materials and connections to tests and documented quotation."/><figcaption className="mt-3 text-sm text-muted">A comparable offer connects operating data, the full wetted-material schedule and acceptance evidence.</figcaption></figure>

      <h2 id="define-the-pressure-control-duty" className={heading}>Define the pressure-control duty before naming a valve</h2>
      <p className={paragraph}>Record the fluid source and its connection to the system, normal and maximum inlet pressure, required downstream set range and permitted variation. State whether the pressure values are gauge or absolute. Provide the minimum, normal and maximum flow rates, including intermittent and low-flow conditions, and identify whether the line may see no-flow periods. Supply the minimum and maximum operating temperatures and the site’s seawater composition or project corrosion-design basis. A nominal “6 bar to 3 bar” requirement is a starting point, not a capacity calculation.</p>
      <p className={paragraph}>Ask the responsible engineer to identify what happens at the limits of the envelope: changing upstream supply pressure, high demand, low demand and start or stop transients. The bidder should return a model-specific performance assessment for those cases, including minimum controllable flow where relevant. A valve that meets the normal point may behave differently at the extremes. Do not copy a generic flow coefficient or pressure range from another size into the project schedule.</p>
      <p className={paragraph}>The manufacturer’s <a className={link} href="https://www.cla-val.com/fire-protection/pressure-reducing-valves/90-42" target="_blank" rel="noopener noreferrer">seawater pressure reducing valve description</a> illustrates the distinction: its pilot-controlled model is intended to maintain a lower downstream pressure as demand and inlet pressure vary. That published product family is an example of the information to request, not an endorsement of a specific model for an unreviewed project.</p>

      <h2 id="do-not-confuse-pressure-control-with-overpressure-protection" className={heading}>Keep pressure reduction separate from relief protection</h2>
      <p className={paragraph}>A reducing valve regulates pressure during ordinary operation. A pressure-relief valve opens against an approved overpressure scenario and is selected under a different engineering and code basis. These functions should not be exchanged because both devices are sometimes abbreviated “PRV.” Specify the function in words on the RFQ and on every bidder response. If the downstream system needs independent overpressure protection, that requirement belongs to the responsible design engineer and should appear as a separate scope.</p>
      <p className={paragraph}>Our <Link className={link} href={postUrl(getPost("api-526-pressure-relief-valves-rfq-guide")!)}>pressure-relief valve RFQ guide</Link> explains the distinct relief-device information and evidence. It should not be used to select a pressure reducing valve, just as a pressure reducing valve catalogue cannot establish a relief device’s certified capacity.</p>

      <h2 id="specify-the-complete-wetted-material-system" className={heading}>Specify the complete wetted-material system</h2>
      <p className={paragraph}>State the required body and cover grade, then request a bill of materials for every wetted component: seat, disc, stem, pilot body and trim, control tubing, fittings, fasteners, diaphragm and elastomers. Corrosion resistance of one casting does not establish compatibility of the assembled pressure-control package. Seawater temperature, chloride concentration, oxygenation, possible cleaning chemicals and periods of stagnation may affect the acceptable choices. The owner’s materials specialist should approve the selection for the actual service.</p>
      <p className={paragraph}>If the project names a cast Super Duplex grade, retain the exact ASTM designation and grade in the comparison. <a className={link} href="https://store.astm.org/a0995_a0995m-20.html" target="_blank" rel="noopener noreferrer">ASTM A995/A995M</a> covers duplex stainless-steel castings for pressure-containing parts, including Grade 5A. A forged or wrought Super Duplex product may be proposed as an alternative, but a similar alloy name alone does not prove an identical product form, heat treatment, design rating or project acceptance. Request material certificates linked to the offered pressure-containing parts and written engineering acceptance of any substitution.</p>
      <p className={paragraph}>Ask the bidder to identify the pilot-system materials separately. A manufacturer’s <a className={link} href="https://www.cla-val.com/wp-content/uploads/2020/06/90-42-Data-Sheet-US_Metric.pdf" target="_blank" rel="noopener noreferrer">marine reducing-valve data sheet</a> lists body and pilot-control material options and shows that a Super Duplex option does not automatically describe every component. The quotation must state which option is actually included.</p>

      <h2 id="lock-down-connections-and-installation-interface" className={heading}>Lock down the connection and installation interface</h2>
      <p className={paragraph}>Provide the nominal valve size, flange rating, facing, mating-flange standard, bore, available face-to-face space and preferred globe or angle flow path. Include the installed orientation, straight-pipe or access constraints specified by the engineer, and the available space for pilot tubing and maintenance. Record the direction of flow and any supplied strainers, isolation valves or bypass equipment as separate line items so their inclusion is unambiguous.</p>
      <p className={paragraph}><a className={link} href="https://www.asme.org/codes-standards/find-codes-standards/b16-5-pipe-flanges-flanged-fittings-nps-1-2-nps-24-metric-inch-standard" target="_blank" rel="noopener noreferrer">ASME B16.5</a> covers flange ratings and dimensions, among other requirements; it does not specify the entire pressure-control assembly. A quotation that says only “Class 150 flanged” still leaves the facing, material rating, gasket interface and actual model dimensions to be confirmed. Request a dimensioned outline drawing before treating two bids as interchangeable.</p>

      <h2 id="compare-control-performance-and-serviceability" className={heading}>Compare control performance and serviceability</h2>
      <p className={paragraph}>Ask each bidder to state the proposed pressure-control range, expected operating behavior across the flow cases, pilot arrangement and any required sensing connection. The engineer should review pressure drop, potential cavitation or noise, and downstream stability for the proposed configuration. These are model- and duty-specific questions; a catalogue’s maximum pressure rating cannot answer them. Request the assumptions used in the manufacturer’s selection and identify any limits or protective components that affect the price.</p>
      <p className={paragraph}>For an offshore or remote installation, ask about maintainable components, spare kits, access requirements and the document revision supplied with the valve. If the offered valve requires special flushing, filtration or water-quality conditions, the bidder should declare those conditions for review. Do not let a low purchase price conceal an excluded pilot accessory, missing coating system or unavailable replacement trim.</p>

      <h2 id="define-testing-documents-and-commercial-boundaries" className={heading}>Define testing, documents and commercial boundaries</h2>
      <p className={paragraph}>The RFQ should list the required shell and seat tests, functional or set-point verification, test medium, acceptance criteria, witness points and final records under the approved project specification. Request the manufacturer’s test procedure, traceable test report, material certificates, general arrangement drawing, full material schedule and operating documentation. The <Link className={link} href={postUrl(getPost("api-598-vs-iso-5208-valve-testing-buyers-guide")!)}>valve-testing buyer guide</Link> explains why naming a test standard without the required test scope and reports makes bids difficult to compare.</p>
      <p className={paragraph}>Commercially, request a price for the complete valve and pilot package, country of manufacture for the offered item, lead time, packing, delivery term with its named place, document schedule, warranty basis and any spare-parts option. Identify whether partial delivery is acceptable. Require a line-by-line compliance statement and a separate list of deviations, including a different material grade, pilot arrangement, connection, test scope or delivery assumption. Do not merge an alternative into a nominally compliant price without identifying it.</p>
      <p className={paragraph}>Send the controlled datasheet and drawings through Oillinko’s <Link className={link} href="/oil-and-gas/equipment/valves/globe-and-control-valves">control valve enquiry page</Link>. Oillinko reviews the request and routes it manually to suitable sources for comparison. Final engineering approval remains with the project’s responsible team; a website category, a preliminary price or a manufacturer brochure is not evidence that a particular valve is approved or available.</p>
      <Faq faqs={faqs}/>
    </Prose>
    <RelatedPosts post={post}/>
    <JsonLd data={[articleJsonLd(post), breadcrumbJsonLd(post), faqJsonLd(faqs)]}/>
    <CtaBand/>
  </>;
}
