import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("steam-trap-rfq-condensate-load-differential-pressure")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A steam trap enquiry should identify the application, the condensate load and the pressure available across the trap at the relevant operating conditions. Connection size is an interface requirement; it does not establish drainage capacity. A useful quotation identifies the proposed trap, the selected operating range and the assumptions behind its capacity. That approach makes it easier to distinguish a compatible replacement from an alternative that requires changes to the surrounding system.</p>
    <p className={paragraph}>Begin with a drainage-point tag and the equipment or steam line it serves. A trap on a distribution main, a tracing circuit and a temperature-controlled heat exchanger may face different load patterns. Record the existing arrangement without assuming that its original selection remains appropriate. The <a className={link} href="https://www.spiraxsarco.com/global/gb/products/steam-traps" target="_blank" rel="noopener noreferrer">steam trap product overview</a> describes different trap families; a family name alone is not evidence that a particular model satisfies the stated duty.</p>
    <h2 id="describe-condensate-load-as-an-operating-profile" className={heading}>Describe condensate load as an operating profile</h2>
    <p className={paragraph}>Give the bidder the normal, maximum and minimum condensate loads where these have been established, together with the units and the calculation or measurement basis. Identify whether start-up has a separate requirement. If the load is unknown, mark it as an information gap and request a selection assessment from the equipment data. Do not replace missing process information with the capacity printed on an old quotation, since that may describe the old trap rather than the actual drainage requirement.</p>
    <p className={paragraph}>For example, a buyer replacing traps across several heating stations might issue one line for each tag. Each line should distinguish its served equipment and available duty information, even when the connection sizes match. Ask bidders to show the load used in selection and any allowance applied. This creates a reviewable difference between a documented engineering allowance and an unexplained oversized selection. It also lets the engineer identify which tags still need a site survey before a firm equipment comparison.</p>
    <h2 id="pair-each-load-with-the-pressure-available-across-the-trap" className={heading}>Pair each load with the pressure available across the trap</h2>
    <p className={paragraph}>State the pressure at the trap inlet and the condensate return pressure for each relevant condition, using an unambiguous pressure reference. Supply the return-system arrangement and any known elevation or resistance information for the selection reviewer. Request the capacity at the resulting differential pressure, rather than at an unrelated catalogue point. Separate the body pressure and temperature limits from the differential-pressure range of the selected mechanism or orifice; these are different parts of the offered equipment description.</p>
    <p className={paragraph}>The <a className={link} href="https://www.spiraxsarco.com/learn-about-steam/condensate-removal/example-selecting-the-trap" target="_blank" rel="noopener noreferrer">worked trap-selection example from Spirax Sarco</a> evaluates the operating steam-space pressure and backpressure at different heat loads. It illustrates why a full-load selection alone can miss the relevant reduced-load condition. For an RFQ, ask the bidder to identify conditions under which the proposed drainage arrangement would cease to have the required pressure difference. Any need for another condensate-removal arrangement should be referred for system engineering review, with its scope and assumptions stated separately.</p>
    <h2 id="explain-air-removal-and-the-application-boundary" className={heading}>Explain air removal and the application boundary</h2>
    <p className={paragraph}>Tell the bidder whether the enquiry covers only the trap or also an air-venting arrangement, a connector, isolation accessories and a condensate return package. Describe known start-up delays or operating concerns as observations, with their source and date. Avoid converting an observation into an unsupported diagnosis. A request that says a heating station warms unevenly should preserve that description and ask for an assessment; it should not silently declare that a new trap will resolve the problem.</p>
    <p className={paragraph}>Require the offered trap family and discharge characteristics to be identified in the technical response, with reasons relevant to the application. If alternatives are allowed, ask for a separate description of their system implications and maintenance requirements. The buyer can then compare what changes physically and what remains dependent on the site design. A quotation for a trap should not be interpreted as a complete condensate-system design or a guarantee of heat-transfer performance across equipment outside the quoted boundary.</p>
    <h2 id="capture-the-replacement-interfaces-precisely" className={heading}>Capture the replacement interfaces precisely</h2>
    <p className={paragraph}>Provide clear photographs, the nameplate or markings, the connection standard, nominal size, installed orientation and available space. Include an approved drawing where possible. For threaded connections, distinguish the thread form and sealing arrangement using the <Link className={link} href={postUrl(getPost("npt-bspt-bspp-threaded-fitting-buyers-guide")!)}>NPT and BSP identification guide</Link>. For flanged connections, state the flange standard, rating and facing. A nominal size written without the connection specification leaves a bidder unable to confirm a direct replacement.</p>
    <p className={paragraph}>Ask for the offered dimensions, removal space, support needs and any supplied connector or adapter. Identify whether the existing strainer is retained or replaced and whether a new trap quotation includes one. The <Link className={link} href={postUrl(getPost("industrial-strainer-rfq-screen-opening-area-pressure-loss")!)}>industrial strainer enquiry guide</Link> helps separate the screening assembly from a loose mesh description. Record interface changes as exceptions to be reviewed, rather than treating adapters and pipe modifications as invisible consequences of accepting the lowest equipment price.</p>
    <h2 id="keep-material-and-documentation-requirements-tied-to-the-item" className={heading}>Keep material and documentation requirements tied to the item</h2>
    <p className={paragraph}>Specify the project material and documentation requirements that actually apply to the trap and its accessories. Ask for the body material, relevant wetted parts and a product datasheet identifying the selected variant. Where certificates or tests are requested, describe their scope and their connection to the supplied item. Do not assume that a general catalogue statement establishes a project-specific pressure rating, inspection document or manufacturing origin. Origin should describe where the product is manufactured, with supporting evidence when required.</p>
    <p className={paragraph}>Make the quotation identify quantities, included accessories, spare-part options and the commercial delivery boundary. If an item is only an indicative alternative pending duty confirmation, preserve that status in the comparison. A short technical response that clearly lists unresolved selection inputs is more useful than a generic compliant statement. The buyer needs to know which offered characteristics have been checked, which have supporting documents and which still depend on information that the project has not supplied.</p>
    <h2 id="use-a-compact-comparison-before-accepting-the-selection" className={heading}>Use a compact comparison before accepting the selection</h2>
    <p className={paragraph}>For every drainage-point tag, compare the application, selected load, inlet and return pressures, offered capacity, model limits, material, connection and included scope. Keep the bidder reference and datasheet revision beside that line. Review exceptions through the project engineer before treating the offer as technically acceptable. This is particularly useful when different bidders use different pressure assumptions: the comparison can expose the assumption directly instead of concealing it behind identical nominal sizes and very different catalogue capacities.</p>
    <p className={paragraph}>An enquiry to Oillinko can include the drainage-point schedule, existing identification, available process conditions and required records through the <Link className={link} href="/oil-and-gas/equipment/thermal-hvac-utilities/steam-traps-and-condensate-systems">steam traps and condensate systems equipment page</Link>. Oillinko coordinates the requirement for manual review and sourcing. Where the duty remains incomplete, request clarification or a separately defined assessment. A final equipment choice should follow the reviewed application data and the actual offered configuration, with commercial terms and any installation work kept identifiable.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
