import Link from "next/link";
import SiteImage from "@/components/SiteImage";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("surface-preparation-before-coating-inspection-evidence")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A coating quotation that says only “blast and paint” leaves one of the most consequential acceptance stages undefined. Before coating, a steel surface can differ in visible cleanliness, residual soluble contamination, profile and exposure to new dust or flash rust. A buyer needs to specify the approved preparation method and the evidence to be recorded before the first coat hides the substrate. The exact acceptance limits must come from the coating specification and service environment, not from a generic online checklist.</p>
    <p className={paragraph}>The <a className={link} href="https://www.ampp.org/standards/sc-05-surface-preparation" target="_blank" rel="noopener noreferrer">AMPP surface preparation standards committee</a> identifies distinct subjects: visible cleanliness grades, abrasive and waterjet methods, nonvisible contaminants and surface profile. This separation is useful when writing an enquiry. A visual blast grade alone does not document the salt level or confirm a profile compatible with the chosen coating system.</p>
    <figure className="mt-8"><SiteImage src={post.image} width={1200} height={630} sizes="(max-width: 768px) 100vw, 768px" className="h-auto w-full rounded-xl border border-line" alt="Coating surface-preparation inspection flow showing substrate condition, cleaning standard, contamination checks, profile and release to coat."/><figcaption className="mt-3 text-sm text-muted">Record the substrate condition before it becomes inaccessible under coating.</figcaption></figure>

    <h2 className={heading}>Define the substrate and coating system together</h2>
    <p className={paragraph}>State whether the work concerns new carbon steel, a previously coated structure, weld repairs, galvanized material or another substrate. Include surface area, geometry, access, environmental exposure and whether the work is in a shop or at site. Identify the approved coating system and manufacturer instructions supplied by the project. Profile and cleanliness requirements are related to that system; they cannot be selected independently from its application instructions and expected service.</p>
    <p className={paragraph}>For repair work, describe which existing coating may remain, the boundaries of removal, edge treatment and any known substrate damage. A small weld repair and a full abrasive blast of a tank exterior have different containment, access and inspection needs. Request that bidders state assumptions about access equipment, protection of nearby instruments, waste collection and temporary weather control. These exclusions can dominate the real scope even when the preparation rate per square metre looks similar.</p>

    <h2 className={heading}>Identify the preparation standard and edition</h2>
    <p className={paragraph}>Specify the exact standard, edition and required grade for the chosen method. Dry blast cleaning, wet blast cleaning, waterjetting and power-tool cleaning describe different processes and surface outcomes. An unexplained phrase such as “near white” may lead to disagreements about what was intended and how it will be judged. Include reference photographs or comparators where the specification requires them, and define who decides when a prepared area is acceptable.</p>
    <p className={paragraph}>Ask how oil, grease, weld spatter, sharp edges and visible deposits will be addressed before final inspection. These are not all resolved by the same operation. The contractor should submit its method statement and inspection plan, but the buyer must provide the approved acceptance basis. The project engineer should also identify areas that cannot be reached by the selected method and how those exceptions will be treated, rather than allowing unrecorded substitutions at site.</p>

    <h2 className={heading}>Treat nonvisible contamination as a separate question</h2>
    <p className={paragraph}>Soluble salts may remain even when a surface looks clean. If the project specifies a salt limit, state the test method, sample locations, frequency, units and acceptance value. Ask how results will be tied to the area inspected and how failed areas will be re-cleaned and retested. Do not copy a numerical threshold from another project: the substrate history, coating and exposure determine the appropriate requirement. Also state how dust or residual abrasive will be assessed before coating.</p>
    <p className={paragraph}>Environmental conditions affect whether an accepted surface can be coated. Define which ambient and steel temperatures, relative humidity and dew-point difference will be measured, how often, and how the readings will be recorded against each work area. The coating manufacturer and approved specification govern the permissible application window. If the preparation and coating teams are different parties, record the handoff time and responsibility for a surface that deteriorates before the first coat.</p>

    <h2 className={heading}>Measure profile by an agreed method</h2>
    <p className={paragraph}>Abrasive cleaning creates a profile that helps the coating system attach, but more profile is not automatically better. The requested range should reflect the coating system and its manufacturer guidance. The <a className={link} href="https://store.astm.org/standards/d4417" target="_blank" rel="noopener noreferrer">ASTM D4417 field measurement standard</a> identifies methods for measuring the profile of blast-cleaned steel. The RFQ should state the selected method, sampling frequency, acceptance range and the records to retain. A single photograph of a blasted panel does not substitute for measured profile where measurement is required.</p>
    <p className={paragraph}>Ask the contractor to identify abrasive type and quality controls, instrument checks and the inspector responsible for release. Where different geometries or repair zones need different treatment, list them separately. A flat plate test patch may not represent inaccessible corners, weld toes or bolt details. Marking the inspected zones on a drawing makes a later coating defect easier to investigate and prevents an ambiguous claim that an entire structure was accepted from a few undocumented readings.</p>

    <h2 className={heading}>Create a clear hold point before coating</h2>
    <p className={paragraph}>The inspection and test plan should show whether the buyer will witness preparation, review records, or formally release each zone before coating. Identify notice periods and what evidence must be available at the point. The <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>hold and witness point guide</Link> explains why those commitments should be agreed before work starts. If coating proceeds before an agreed hold point is released, later thickness measurements cannot recreate the hidden preparation evidence.</p>
    <p className={paragraph}>Request a package containing the area map, preparation method, standard and grade, inspection dates, environmental readings, salt and dust results where required, profile readings, nonconformances and final release. Link this package to the later <Link className={link} href={postUrl(getPost("coating-dft-inspection-reports-buyers-guide")!)}>dry-film thickness report</Link> without confusing preparation acceptance with final coating thickness. Submit the approved coating specification and scope through Oillinko&apos;s <Link className={link} href="/oil-and-gas/services/inspection-ndt-and-material-testing">inspection and material testing service page</Link> for manual routing. No service listing proves a particular inspector is already assigned.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
