import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, RelatedPosts, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("surface-roughness-inspection-reports-ra-rz-measurement-basis")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <div className="-mt-4 mb-8 text-sm text-muted">An original conceptual illustration of surface inspection records; the scene is not a validated measurement setup.</div>
    <p className={paragraph}>A surface roughness report is difficult to evaluate when it contains only a number and the word “pass”. The buyer needs to know which part and surface were measured, which drawing requirement applied, and what measurement basis produced the result. This matters when purchasing machined components, requesting inspection after repair, or comparing evidence from different bidders. A well-defined report connects the measurement to a specific requirement. It does not ask the purchasing team to infer compliance from an isolated reading or a photograph of an instrument display.</p>
    <h2 id="start-with-the-drawing-and-the-measured-surface" className={heading}>Start with the drawing and the measured surface</h2>
    <p className={paragraph}>Give the inspector the approved drawing number and revision, part identifier, relevant surface callout and any supporting specification. Identify the measured location with a sketch, annotated photograph or drawing reference. A shaft may contain several surfaces with different functions and requirements. A reading labelled only with the shaft number leaves the reviewer unable to tell whether it came from the specified journal, a shoulder or another accessible area. The same problem arises when several nominally identical parts are represented by one unlabelled measurement.</p>
    <p className={paragraph}>Define the inspection stage too. State whether the report concerns the surface after machining, after a specified finishing operation or at another agreed stage. If the work involves repair, link the report to the repair scope and approved revision. Ask the provider to explain any surface that cannot be measured as specified, before completing the work. The buyer should not discover at report review that access limitations led to a different location or that a convenient test piece was used instead of the required component.</p>
    <h2 id="preserve-the-parameter-unit-and-standard-edition" className={heading}>Preserve the parameter, unit and standard edition</h2>
    <p className={paragraph}>Copy the specified parameter and unit accurately. Do not replace a request for Ra with a result for Rz, or infer one through a general conversion factor. In its older <a className={link} href="https://www.mitutoyo.com/webfoo/wp-content/uploads/Surface_Roughness_Measurement.pdf" target="_blank" rel="noopener noreferrer">surface roughness measurement brochure</a>, Mitutoyo illustrates different profile parameters and measurement conditions. The brochure is a useful historical explanation of why a parameter label matters, but it references earlier standards and is not a current acceptance specification for a new order. Its tables should not be copied into a purchase requirement without checking the governing documents.</p>
    <p className={paragraph}>Record the standard and edition called up by the contract. The <a className={link} href="https://www.iso.org/standard/72226.html" target="_blank" rel="noopener noreferrer">ISO 21920-2:2021 catalogue entry</a> describes terminology and parameters for surface texture assessed by profile methods; its scope does not, by itself, define a particular component&#x27;s acceptance limit. If a legacy drawing cites an older standard, ask the responsible technical authority how that requirement is to be applied. Changing the edition during reporting without approval can make the evidence difficult to compare with the original requirement. Document an agreed interpretation before accepting results against it.</p>
    <h2 id="request-enough-measurement-context-to-compare-results" className={heading}>Request enough measurement context to compare results</h2>
    <p className={paragraph}>Ask the inspection provider to identify its method, instrument and the measurement settings relevant to the specified evaluation. Depending on the agreed procedure, these may include the filtering basis, evaluation length, measurement direction and probe configuration. The provider should state the actual conditions used rather than simply naming an instrument family. The purpose is to make the result understandable and reproducible within the agreed method, not to let a procurement checklist select technical settings that require qualified judgement.</p>
    <p className={paragraph}>Consider a hypothetical report that records a conforming value but does not identify the measured direction or length. The buyer has no sound basis for assuming it is directly comparable with a previous report made under documented conditions. Ask the provider to supply the missing context or explain whether a further measurement is needed. Avoid asking it to choose settings solely to obtain a passing result. Where geometry restricts the specified measurement, obtain a recorded disposition from the responsible reviewer rather than concealing the limitation in a generic remark.</p>
    <h2 id="keep-individual-evidence-linked-to-acceptance" className={heading}>Keep individual evidence linked to acceptance</h2>
    <p className={paragraph}>Agree the number of parts, surfaces and measurement locations to be inspected through the project inspection plan. Specify how part identity will remain attached to the readings. If several readings are taken, request the individual results and the reported evaluation required by the governing specification. Do not substitute an informal average for a specified acceptance rule. The report should make clear which result was assessed against which limit, including whether a value represents one location, a particular part or an agreed summary of several measurements.</p>
    <p className={paragraph}>Ask the provider to state the acceptance basis and any agreed decision rule relevant to its conformity statement. A report should distinguish the measured result from the conclusion drawn from it. If the drawing requirement is missing, contradictory or unclear, the provider should identify that gap instead of inventing a threshold. The buyer can then obtain a clarification and preserve it with the inspection record. A clear unresolved result is more useful than an unsupported pass that later becomes difficult to explain to a customer or auditor.</p>
    <h2 id="review-competence-instrument-records-and-exceptions" className={heading}>Review competence, instrument records and exceptions</h2>
    <p className={paragraph}>Request the instrument identifier and the relevant calibration or verification records required by the inspection scope. Where accredited testing or calibration is specified, check the actual scope and applicable method rather than relying only on an accreditation logo. The <Link className={link} href={postUrl(getPost("iso-17025-laboratory-accreditation-scope-test-report")!)}>laboratory accreditation scope and test-report guide</Link> explains that separate review. Accreditation, a calibration document and the individual inspection report answer different questions; the purchase file should connect the evidence needed for this particular assignment.</p>
    <p className={paragraph}>Record deviations, inaccessible areas, changed conditions and repeat measurements transparently. If a surface is reworked, preserve the earlier result and link the new report to the rework and affected part. Ask whether the new report replaces a previous revision or supplements it. This simple document-control step helps prevent a withdrawn report from remaining in the customer&#x27;s acceptance file. It also prevents a later reviewer from interpreting two different results as measurements of an unchanged surface under identical conditions.</p>
    <h2 id="define-a-useful-inspection-enquiry" className={heading}>Define a useful inspection enquiry</h2>
    <p className={paragraph}>An inspection RFQ should contain the drawing package, part quantities and identifiers, required surfaces, parameter and units, governing standard edition, acceptance basis, inspection stage and report format. Ask the bidder to state what is included in the price and what needs clarification before work can start. Include access arrangements and any witness or review requirements. A complete quotation should show the proposed scope and exclusions without implying that the service provider has already accepted every technical requirement merely by returning a commercial price.</p>
    <p className={paragraph}>This article concerns machined surface texture. For coated structures, use the separate <Link className={link} href={postUrl(getPost("surface-preparation-before-coating-inspection-evidence")!)}>surface preparation inspection guide</Link> to define the preparation evidence appropriate to that work. Submit the drawing and inspection requirement through Oillinko&#x27;s <Link className={link} href="/oil-and-gas/services/inspection-engineering">inspection and engineering service page</Link>, or start from <Link className={link} href="/">Oillinko</Link> to locate the relevant service. Requests are handled through manual review and routing. The intended outcome is a report that connects a real surface, an agreed measurement basis and a documented acceptance decision, with limitations visible to the people responsible for release.</p>
  </Prose><RelatedPosts post={post}/><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
