import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("thermowell-rfq-wake-frequency-process-data")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A thermowell RFQ should connect the process conditions, the installed geometry and the temperature sensor interface. Buying a replacement by connection size and material alone can leave the supplier quoting a part that fits the nozzle but has not been evaluated for the intended flow conditions. The useful purchasing question is which drawing and operating cases support the proposed thermowell, and what evidence will accompany the delivered component.</p>
    <p className={paragraph}>This guide concerns the enquiry and review package for a protective thermowell in process piping or equipment. It does not calculate a safe insertion length or authorize a design change. The responsible instrument and piping engineers need to establish the applicable design basis. Procurement can help by keeping their inputs, the supplier calculation and the offered dimensions linked to one controlled item reference.</p>
    <h2 id="define-the-supply-boundary" className={heading}>Define the thermowell supply boundary</h2>
    <p className={paragraph}>State whether the purchase includes only the thermowell or also the sensing element, extension, connection head, transmitter and accessories. Identify each existing component that will be retained. A thermowell drawing does not fully specify an RTD or thermocouple assembly, and a sensor model does not fully specify the process pressure boundary. Separate line items can still belong to one reviewed assembly if their interfaces are explicit.</p>
    <p className={paragraph}>For a replacement, provide the tag, available nameplate information, original drawing and known changes to the service. Include photographs as supporting identification, with dimensions taken from controlled records where available. If the old part failed, describe the observed condition without assigning an unverified cause. Ask whether the supplier is quoting an identical replacement or proposing a changed design, because those responses require different technical reviews.</p>
    <h2 id="keep-process-cases-together" className={heading}>Keep the process cases together</h2>
    <p className={paragraph}>Prepare a case table with the medium, phase, temperature, pressure and relevant flow information supplied by the process team. Record units and the source or revision of each value. Keep normal, maximum and other specified cases on separate rows. Combining a velocity from one condition with density from another can produce a calculation basis that represents none of the actual operating cases.</p>
    <p className={paragraph}>The <a className={link} href="https://blog.wika.com/us/products/temperature-products/wika-offers-web-based-thermowell-wake-frequency-calculators/" target="_blank" rel="noopener noreferrer">manufacturer overview of thermowell wake-frequency calculations</a> identifies process inputs such as pressure, density and velocity, alongside thermowell dimensions and material. Ask the supplier to return the actual input schedule with the calculation. Where only a flow rate is available, identify the piping geometry and conditions used by the engineer to establish the relevant velocity; do not silently enter the flow number as a velocity.</p>
    <h2 id="use-a-dimensioned-installation-drawing" className={heading}>Use a dimensioned installation drawing</h2>
    <p className={paragraph}>Label the reference points for insertion length, external extension and the portion shielded by the connection or nozzle. Request the bore, root and tip dimensions, tip thickness and stem profile on the offered drawing. Terms such as overall length and immersion length can refer to different distances in different catalogues. A sketch with identified datums is more useful than an unqualified request for a longer probe.</p>
    <p className={paragraph}>Confirm the process connection standard, size, facing or thread, and the sensor-side connection. For a flanged unit, retain the flange material and pressure-class information rather than treating the class number as a universal pressure rating. The <Link className={link} href={postUrl(getPost("asme-b16-5-flange-pressure-classes")!)}>flange pressure-class guide</Link> explains that separate interface check. Ask the supplier to flag any proposed dimensional change that affects the nozzle, sensor fit or removal clearance.</p>
    <h2 id="request-a-traceable-calculation" className={heading}>Request a traceable calculation</h2>
    <p className={paragraph}>Identify the calculation standard and edition required by the project. The <a className={link} href="https://www.wika.com/en-us/thermowell_calculation_software.WIKA" target="_blank" rel="noopener noreferrer">published calculation-tool description</a> identifies an implementation of ASME PTC 19.3 TW-2016. That reference should prompt a scope check, not an assumption that every thermowell construction or special geometry is covered. Ask the design provider to state whether the proposed configuration falls within the selected method and to explain any alternative evaluation.</p>
    <p className={paragraph}>Require the report to identify the item tag, drawing revision, material, input cases, calculation basis and result. Keep any qualifications and failed cases visible. The manufacturer overview distinguishes dynamic results from static stress and pressure-load results. Procurement should request the complete issued report rather than transcribing one passing frequency ratio into the bid comparison. The responsible reviewer must assess the whole required evaluation and its assumptions.</p>
    <h2 id="review-changes-as-an-assembly" className={heading}>Review proposed changes as an assembly</h2>
    <p className={paragraph}>A supplier may propose a different stem diameter, insertion length, material or profile after reviewing the enquiry. Ask for the revised drawing and the reason for the change, linked to the affected calculation. Do not approve an altered length solely because it produces a favourable report. The instrument engineer also needs to assess the measurement location and sensor arrangement, while the piping reviewer checks the installation interfaces.</p>
    <p className={paragraph}>As a procurement example, two offers may both state stainless steel and the same flange class while using different insertion lengths. Put those dimensions beside each price and record which process cases each bidder evaluated. Keep the unchanged original request available so the deviation is visible. The <Link className={link} href={postUrl(getPost("equipment-rfq-revision-control-bid-clarifications")!)}>RFQ revision-control guide</Link> supports this link between the request, clarification and final offered configuration.</p>
    <h2 id="specify-documents-and-commercial-inclusions" className={heading}>Specify documents and commercial inclusions</h2>
    <p className={paragraph}>List the required material records, dimensional inspection, identification and any project-specified tests. Ask which records are standard and which are additional. Distinguish the thermowell material certificate from sensor calibration or transmitter configuration records when the whole assembly is ordered. A calibration certificate addresses a different question from the mechanical suitability of the protective component. Record the actual manufacturing country rather than inferring origin from a distributor address.</p>
    <p className={paragraph}>Compare prices against the same supply boundary: thermowell quantity, sensors, accessories, calculations, documents and packing. Ask when the quoted lead time begins, particularly if drawing approval is a prerequisite. Separate engineering review time from manufacturing and transport assumptions. Where information remains missing, identify the offer as conditional and name the unresolved inputs. A provisional price can support planning without being described as a fully approved replacement.</p>
    <h2 id="prepare-the-release-package" className={heading}>Prepare the release package</h2>
    <p className={paragraph}>Before release, align the purchase description, accepted drawing, calculation revision and supplier deviations. Record who approved each technical change and which documents remain due with shipment. On receipt, compare the delivered identification and records with that agreed package. A report for a similar tag or an earlier drawing should trigger a controlled clarification rather than an informal substitution in the buyer file.</p>
    <p className={paragraph}>Use the <Link className={link} href="/oil-and-gas/equipment/instrumentation-control/temperature-sensors-and-thermowells">temperature-sensor and thermowell enquiry page</Link> to describe the assembly and available process data. Through <Link className={link} href="/">Oillinko equipment sourcing</Link>, enquiries are reviewed and routed manually. Include the installation drawing, case table and document requirements so suppliers can identify what they can quote and what still needs engineering resolution. The objective is a comparable, traceable offer rather than a guessed design.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
