import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost } from "@/lib/blog";
const post = getPost("ultrasonic-thickness-measurement-reports-rfq-guide")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";
export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>An ultrasonic thickness measurement report can contain hundreds of readings and still leave a buyer unable to identify what was inspected. The value of a survey depends on the locations covered, the validity of the measurements and the records connecting them to the asset. Before requesting quotations for pipes, vessels or tanks, define the inspection question and the deliverables that will answer it. A price per measurement is difficult to compare when bidders assume different access, coverage and reporting arrangements.</p>
    <p className={paragraph}>This guide explains how to prepare a thickness-survey RFQ and review the resulting evidence. It distinguishes measurement from engineering acceptance: a recorded wall thickness is an input to an integrity decision, not automatic permission to keep equipment in service. The responsible engineering and operating parties must establish the applicable assessment basis and action limits. Oillinko coordinates enquiries and clarification; a catalogue listing does not confirm an appointed inspection contractor or an approved asset assessment.</p>
    <h2 className={heading}>Define the asset and the inspection question</h2>
    <p className={paragraph}>Identify the equipment tag, piping circuit or tank, and attach the controlled drawings needed to locate the proposed work. Include the known material, nominal dimensions, relevant operating conditions and previous inspection records. State whether the objective is a baseline survey, repeat monitoring at established locations, investigation of suspected thinning, or support for a planned repair. These objectives can require different coverage. A generic request to check wall thickness does not tell a bidder which areas need attention or what historical comparison is expected.</p>
    <p className={paragraph}>Separate known facts from assumptions. An old drawing may show the original thickness rather than the currently installed component, and a photograph may not identify the material or internal condition. Record the source and revision of the information supplied. If the contractor must first verify identification or develop a location plan, make that a separate deliverable requiring review before measurement. This avoids treating an unreviewed list of convenient measurement points as the agreed inspection scope.</p>
    <h2 className={heading}>Specify coverage and repeatable locations</h2>
    <p className={paragraph}>Distinguish individual spot readings, a defined grid and a scanning or mapping assignment. They are different scopes, even if each produces a table of thickness values. Ask the responsible inspection specialist to propose and justify the coverage against the objective, then obtain the required project approval. The enquiry should identify the included surfaces, locations, access restrictions and areas excluded from inspection. A minimum value from selected points must not be described as the minimum thickness of every unmeasured part of the asset.</p>
    <p className={paragraph}>Give each measurement location a stable identifier tied to a drawing, coordinate system or documented reference. Agree how orientations, distances and accessible landmarks will be recorded so a later survey can revisit the same area. For repeat monitoring, request a clear distinction between an existing location, a replacement location and an added location. Differences between readings collected from different places should not silently become a corrosion-rate trend. Record inaccessible points and proposed substitutes rather than omit them from the final table.</p>
    <h2 className={heading}>Name the method and its application limits</h2>
    <p className={paragraph}>The <a className={link} href="https://www.iso.org/standard/87436.html" target="_blank" rel="noopener noreferrer">ISO 16809:2025 listing</a> identifies ultrasonic thickness determination using pulse travel time and contact or immersion techniques. Its published edition replaces ISO 16809:2017. Specify the edition selected by the project, including any contractually retained earlier edition and approved deviations. A standards title on a quotation does not establish a complete procedure, appropriate coverage or an engineering acceptance criterion for the inspected asset.</p>
    <p className={paragraph}>The <a className={link} href="https://store.astm.org/e0797_e0797m-21.html" target="_blank" rel="noopener noreferrer">ASTM E797/E797M-21 product page</a> describes manual ultrasonic pulse-echo contact measurement and identifies application limits, including temperature and geometry. Ask the bidder to explain how the proposed method fits the actual component, surface condition and expected thickness range. Do not assume that a procedure intended for a flat, relatively regular section automatically covers every curved, rough or heavily corroded component. The controlled procedure and applicable requirements need technical review.</p>
    <h2 className={heading}>Address coatings, corrosion and measurement validity</h2>
    <p className={paragraph}>Coatings and irregular corrosion can affect the measurement arrangement and interpretation. The <a className={link} href="https://ims.evidentscientific.com/en/applications/corrosion-gaging-dual-element-transducers" target="_blank" rel="noopener noreferrer">manufacturer guidance on corrosion thickness gauging</a> explains why probe selection and valid measurement range matter. It also describes limitations of echo-to-echo measurement for some pitted surfaces. A quotation offering measurement through paint therefore needs an application-specific explanation; it is not proof that all local thinning will be detected or that every displayed value is valid.</p>
    <p className={paragraph}>Request identification of the instrument, probe and measurement mode, together with the relevant reference checks and setup records required by the approved procedure. Explain whether coatings may be disturbed and who approves surface preparation and restoration. Require the report to flag locations where a valid result could not be obtained and to distinguish confirmed readings from estimates or unresolved indications. A number entered to fill an empty spreadsheet cell should never look equivalent to an accepted measurement.</p>
    <h2 className={heading}>Agree report contents and review responsibilities</h2>
    <p className={paragraph}>A useful report connects the asset identification, procedure revision, personnel, instrument and probe references, inspection date and location map to the individual readings. Specify the units, table format, coverage record and any required supporting signal records or photographs. Ask how corrected values, repeat measurements and rejected readings will be identified. Where temperature or other conditions affect the selected method, require the relevant conditions and approved treatment to be documented. Reporting precision should reflect the method and evidence rather than simply display extra decimal places.</p>
    <p className={paragraph}>Keep the measurement result separate from the acceptance decision. If the scope includes comparison with specified limits, identify who provides and approves those limits, their document revision and the required escalation process for adverse findings. Calculating remaining life or fitness for service is an additional engineering assignment with its own inputs and responsibilities. An instrument calibration record cannot replace this review. Likewise, a general statement that results are satisfactory is difficult to assess without the location data and governing criteria.</p>
    <h2 className={heading}>Compare access, commercial scope and final handover</h2>
    <p className={paragraph}>Ask bidders to separate inspection execution, location planning, access equipment, insulation removal, surface preparation, coating restoration and engineering interpretation. Identify site induction, permits, isolation responsibilities and the available work window. These boundaries affect price and schedule even when the number of proposed readings is unchanged. Define how additional locations, inaccessible areas and repeat work will be authorized and priced. The contractor should not assume permission to disturb insulation or coatings merely because a thickness survey has been requested.</p>
    <p className={paragraph}>Before closing the assignment, reconcile the agreed location list against completed work, exclusions and unresolved results. Request a controlled final report and the agreed editable data, with revision history and any approved changes. Retain links between the new survey and previous records without overwriting the historical observations. Send Oillinko the asset list, drawings, inspection objective, location plan and deliverable requirements through the <Link className={link} href="/oil-and-gas/services/inspection-ndt-and-material-testing">inspection and material testing enquiry page</Link> or the <Link className={link} href="/oil-and-gas/services/advanced-ndt-and-corrosion-mapping">advanced NDT and corrosion mapping enquiry page</Link>. Oillinko reviews the scope and coordinates suitable service enquiries for project-specific evaluation.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
