import Link from "next/link";
import { CtaBand } from "@/components/ui";
import { BlogPostHeader, JsonLd, Prose, articleJsonLd, breadcrumbJsonLd } from "@/components/BlogChrome";
import { getPost, postUrl } from "@/lib/blog";

const post = getPost("wps-pqr-welder-qualifications-fabrication-rfq-checklist")!;
const paragraph = "mt-4 text-sm leading-relaxed text-muted sm:text-base";
const heading = "mt-12 text-xl font-bold";
const link = "text-accent underline underline-offset-4";

export default function Article() {
  return <><BlogPostHeader post={post}/><Prose post={post}>
    <p className={paragraph}>A fabrication offer can promise qualified welding while leaving the buyer unable to tell which procedure, test record or individual welder covers the proposed work. Three documents answer different questions: a welding procedure specification (WPS) describes how production welding is to be carried out; a procedure qualification record (PQR) records a qualifying test and its results where that route is required; and a welder or welding-operator qualification record addresses the person or operator performing the work. Asking for a single “welding certificate” blurs those responsibilities.</p>
    <p className={paragraph}>This is a document-planning guide for a fabrication RFQ, not a determination that any proposed weld is code-compliant or safe to make. The governing fabrication code, contractual specification, design drawings, welding processes, materials and project edition control the actual review. State them first, then ask bidders to identify the procedures and personnel they intend to use. Oillinko can route a documented enquiry for review; a catalogue entry is not evidence of an appointed fabricator, current qualifications or an approved project method.</p>

    <h2 id="governing-basis" className={heading}>Start with the governing fabrication basis</h2>
    <p className={paragraph}>Describe the item being fabricated: assembly and drawing revision, joint types, base materials and thickness ranges, shop or field location, production quantities and the required inspection and handover package. Identify the construction or fabrication code and its edition rather than writing only “ASME welding” or “ISO welding.” ASME BPVC Section IX concerns welding, brazing and fusing qualifications; it does not by itself identify every design, fabrication, examination or acceptance requirement for a pressure item. The buyer should ask its responsible engineer which complete code set and project amendments govern the work.</p>
    <p className={paragraph}>The <a className={link} href="https://www.asme.org/codes-standards/find-codes-standards/bpvc-ix-bpvc-section-ix-welding-brazing-fusing-qualifications-(2)" target="_blank" rel="noopener noreferrer">ASME Section IX listing</a> establishes the subject of that qualification standard. Alternatively, a project may specify an ISO qualification route or a different approved scheme. Do not treat an ASME record as automatically interchangeable with an ISO record, or assume that a historical qualification remains acceptable without checking the contract and applicable rules. Put the document standard, edition, acceptance authority and submission timing in the RFQ so all offers are judged on the same basis.</p>

    <h2 id="wps-role" className={heading}>Ask what the WPS actually instructs</h2>
    <p className={paragraph}>A WPS is the controlled instruction intended for production welding. Request its identifier, revision, applicable process or process combination, material and joint scope, filler metal and other variables relevant to the selected code. The purchaser does not need to invent parameters for the fabricator, but it does need a way to confirm that the offered WPS addresses the joints in the released drawings. A generic company statement that procedures exist is weaker than a numbered WPS list linked to the joint or weld map.</p>
    <p className={paragraph}>The <a className={link} href="https://www.iso.org/standard/75556.html" target="_blank" rel="noopener noreferrer">ISO 15609-1:2019 listing</a> identifies requirements for the content of arc-welding procedure specifications, while <a className={link} href="https://www.asme.org/codes-standards/publications-information/asme-data-report-forms" target="_blank" rel="noopener noreferrer">ASME publishes a suggested QW-482 WPS form</a>. Those references show the type of record to request; neither page proves that a particular contractor procedure is qualified for this job. Ask who controls revisions, when a changed WPS is resubmitted, and how the released version will be made available at the point of work.</p>

    <h2 id="pqr-evidence" className={heading}>Separate procedure qualification evidence from instructions</h2>
    <p className={paragraph}>Where the specified code requires procedure qualification by test, a PQR supports the WPS by recording the actual variables used on a qualifying test coupon and the required test outcomes. It is evidence for a defined scope, not a replacement for the production instruction. Request the supporting PQR number and revision for every proposed WPS, together with the qualification organization, test date, material and process identification and test reports needed by the applicable scheme. Ask the technical reviewer to check the qualified ranges against the planned production joints.</p>
    <p className={paragraph}>ASME distinguishes its <a className={link} href="https://www.asme.org/codes-standards/publications-information/asme-data-report-forms" target="_blank" rel="noopener noreferrer">QW-483 suggested PQR form</a> from the QW-482 WPS form. Under another specified route, <a className={link} href="https://committee.iso.org/cms/live/live/en/sites/isoorg/contents/data/standard/05/17/51792.html?browse=tc" target="_blank" rel="noopener noreferrer">ISO 15614-1:2017</a> addresses qualification of preliminary welding procedure specifications by test for its stated materials and processes. The RFQ should not claim that every WPS must have the same kind of PQR: ask each bidder to explain the qualification route used and provide the evidence the governing project accepts, including any permitted exception.</p>

    <h2 id="welder-records" className={heading}>Check the individual welder or operator record separately</h2>
    <p className={paragraph}>A qualified procedure does not prove that every person assigned to it is qualified. Request the welder or welding-operator identification, qualification record, test process and date, recorded variables, applicable ranges and evidence of continued validity under the chosen scheme. Match that person to the proposed process and production assignment. If personnel change during the job, define how replacement records will be reviewed before the changed assignment begins. Keep names and qualification records in the controlled project dossier rather than publishing personal details on a public page.</p>
    <p className={paragraph}>ASME lists a distinct QW-484A form for welder performance qualification, and the <a className={link} href="https://www.aws.org/magazines-and-media/welding-digest/2022/september/welding-digest-welder-performance-qualification-and-welder-certification" target="_blank" rel="noopener noreferrer">American Welding Society explains the distinction between performance qualification and its record</a>. For projects using ISO rules, the <a className={link} href="https://committee.iso.org/standard/54936.html?browse=tc" target="_blank" rel="noopener noreferrer">ISO 9606-1:2012 listing</a> describes qualification testing of welders for fusion welding of steels. Terminology and validity rules can differ between schemes; ask for the actual record and have the project welding reviewer assess its scope rather than treating an old training certificate as equivalent.</p>

    <h2 id="link-records" className={heading}>Build a traceable link from joint to qualification</h2>
    <p className={paragraph}>Request a welding document index or matrix that maps the relevant drawing and weld identification to the planned WPS, supporting qualification evidence and assigned welder or operator. This can be a simple controlled table for a small fabrication order. It should identify revisions and approval status without implying that every record must be publicly shared. A list of dozens of unrelated WPS files is hard to audit if no one can show which one covers a particular joint. Resolve gaps before treating the offer as technically complete.</p>
    <p className={paragraph}>Material identity and welding qualification are related but separate evidence streams. The <Link className={link} href={postUrl(getPost("heat-number-traceability-mill-certificates")!)}>heat-number traceability guide</Link> explains how to connect delivered material with mill records; that connection does not qualify a welding procedure. Ask how the fabricator will retain material and consumable identification, weld maps, approved revisions and test reports in the final dossier. Specify a document numbering scheme and responsible approval points early enough that records can be gathered as work proceeds, not reconstructed at handover.</p>

    <h2 id="inspection-and-release" className={heading}>Define examination and release evidence alongside welding records</h2>
    <p className={paragraph}>The scope should say which fabrication stages require visual inspection, nondestructive examination or other agreed tests, who performs them, what report identifies the inspected weld and which acceptance basis applies. A PQR coupon test does not substitute for a production weld examination. A passed production examination does not by itself prove that the WPS or welder record was applicable. Keep those conclusions separate in the inspection and test plan, with the drawing and weld identifiers carried into reports.</p>
    <p className={paragraph}>Use the <Link className={link} href={postUrl(getPost("inspection-test-plans-hold-vs-witness-points")!)}>hold and witness point guide</Link> to define when work must pause for review and who can release it. If surface methods are contemplated, the <Link className={link} href={postUrl(getPost("liquid-penetrant-vs-magnetic-particle-testing-rfq")!)}>penetrant versus magnetic-particle testing guide</Link> shows why method choice follows material and inspection objective. The responsible welding and inspection specialists must set extent, technique and acceptance criteria from the actual project documents; an RFQ checklist cannot assign those limits by guesswork.</p>

    <h2 id="compare-and-send" className={heading}>Compare offers on the same documentary scope</h2>
    <p className={paragraph}>Ask bidders to return a procedure list, qualification basis, proposed personnel evidence, document index, inspection and test plan, stated subcontracted operations and a clear deviations register. Specify whether records are required with the bid, before fabrication release or at final handover. Compare whether the price includes qualification tests that are still needed, translation or review of existing records, additional examinations, retesting after nonconformance and dossier preparation. A low fabrication price may reflect an excluded qualification or reporting obligation rather than a more efficient proposal.</p>
    <p className={paragraph}>An answerable enquiry includes the drawing set and revision, materials and joint schedule, governing code and edition, required documentary outputs, witness and approval points, project location, quantity and delivery basis. Send the defined inspection and documentation requirements through Oillinko via the <Link className={link} href="/oil-and-gas/services/inspection-ndt-and-material-testing">inspection, NDT and material testing service page</Link> when an independent review or test scope is needed. Oillinko will manually assess the request and route it; acceptance of a specific WPS, PQR, welder record or completed weld remains with the responsible project authority.</p>
  </Prose><JsonLd data={[articleJsonLd(post),breadcrumbJsonLd(post)]}/><CtaBand/></>;
}
