import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { catalogue, sectors } from "@/lib/catalogue";
import { PageHeader } from "@/components/ui";
export const dynamicParams=false;
export function generateStaticParams(){return sectors.map(s=>({sector:s.id}));}
export async function generateMetadata({params}:{params:Promise<{sector:string}>}):Promise<Metadata>{const {sector}=await params;const s=sectors.find(s=>s.id===sector);return s?{title:`${s.name} Equipment & Services`,description:s.description,alternates:{canonical:`/industries/${s.id}`}}:{};}
export default async function SectorPage({params}:{params:Promise<{sector:string}>}){const {sector}=await params;const s=sectors.find(s=>s.id===sector);if(!s)notFound();const groups=catalogue.filter(g=>g.sectors.includes(s.id));return <><PageHeader title={s.name} subtitle={s.description}/><section className="mx-auto max-w-6xl px-4 py-12"><nav aria-label="Breadcrumb" className="mb-6 flex gap-3 text-sm text-muted"><Link href="/industries">Industries</Link><span>/</span><span>{s.name}</span></nav><p className="max-w-3xl text-lg text-muted">Explore the equipment and service categories relevant to this sector. Open a category for product types and the technical information to include in your request.</p><div className="mt-8 grid gap-5 md:grid-cols-2">{groups.map(g=><article key={g.slug} className="rounded-xl border border-line bg-white p-6"><h2 className="text-xl font-semibold"><Link href={`/equipment/${g.slug}`}>{g.name}</Link></h2><p className="mt-3 text-muted">{g.summary}</p><ul className="mt-4 space-y-2 text-sm">{g.types.map(t=><li key={t.id}><Link className="text-accent hover:underline" href={`/equipment/${g.slug}#${t.id}`}>{t.name}</Link></li>)}</ul></article>)}</div><div className="mt-10 rounded-xl border border-line bg-oil-800 p-6"><h2 className="text-xl font-bold">Send the complete project requirement</h2><p className="mt-3 text-muted">Include quantities, technical documents and any required manufacturing origin. Our Oillinko team reviews the inquiry and coordinates the next steps with you.</p><Link href="/rfq" className="mt-5 inline-block rounded bg-accent px-5 py-3 font-semibold text-black">Send your BOQ</Link></div></section></>;}
